# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/3d-transform-incoming.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/3d-transform-outgoing.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/active-view-transition-on-non-root.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/active-view-transition-pseudo-class-match.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/active-view-transition-type-on-non-root.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/animating-new-content-subset.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/animating-new-content.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/animation-name-ua-prefix.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/auto-name-from-id-shadow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/auto-name-from-id.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/auto-name.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/backdrop-filter-animated.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/backdrop-filter-captured.html
http://web-platform.test:8000/css/css-view-transitions/backdrop-filter-while-promise-pending.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/block-with-overflowing-text.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/break-inside-avoid-child.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/capture-old-state-error-flag-cleanup.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/capture-with-offscreen-child-translated.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/capture-with-offscreen-child.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/capture-with-opacity-zero-child.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/capture-with-visibility-hidden-child.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/capture-with-visibility-mixed-descendants.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/class-specificity.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/clip-path-larger-than-border-box-on-child-of-named-element.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/column-span-during-transition-doesnt-skip.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/content-smaller-than-box-size.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/content-visibility-auto-shared-element.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/content-with-child-with-transparent-background.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/content-with-clip-root.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/content-with-clip.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/content-with-inline-child.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/content-with-transform-new-image.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/content-with-transform-old-image.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/content-with-transparent-background.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/css-tags-paint-order-with-entry.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/css-tags-paint-order.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/css-tags-shared-element.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/dialog-in-rtl-iframe.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/dialog-in-top-layer-during-transition-new.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/dialog-in-top-layer-during-transition-old.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/element-is-grouping-during-animation.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/element-stops-grouping-after-animation.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/element-with-overflow.html
http://web-platform.test:8000/css/css-view-transitions/empty-render-target-capture.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/escaped-name.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/exit-transition-with-anonymous-layout-object.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/far-away-capture.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/fractional-box-new.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/fractional-box-old.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/fractional-box-with-overflow-children-new.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/fractional-box-with-overflow-children-old.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/fractional-box-with-shadow-new.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/fractional-box-with-shadow-old.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/fractional-translation-from-position.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/fractional-translation-from-transform.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/fragmented-at-start-ignored.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/fragmented-during-transition-skips.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/hit-test-unpainted-element.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/hit-test-unrelated-element.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/html-becomes-fixed.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/iframe-and-main-frame-transition-new-main-new-iframe.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/iframe-and-main-frame-transition-new-main-old-iframe.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/iframe-and-main-frame-transition-old-main-new-iframe.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/iframe-and-main-frame-transition-old-main-old-iframe.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/iframe-and-main-frame-transition-old-main.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/iframe-and-main-frame-transition-with-name-on-iframe.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/iframe-new-has-scrollbar.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/iframe-old-has-scrollbar.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/iframe-transition.sub.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/inline-child-with-composited-filter.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/inline-child-with-filter.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/inline-child-with-overflow-shadow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/inline-element-size.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/inline-with-offset-from-containing-block.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/japanese-tag.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-below-and-on-top-of-viewport-partially-onscreen-new.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-below-and-on-top-of-viewport-partially-onscreen-old.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-below-viewport-offscreen-new.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-below-viewport-offscreen-old.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-below-viewport-partially-onscreen-new.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-below-viewport-partially-onscreen-old.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-left-of-viewport-offscreen-new.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-left-of-viewport-offscreen-old.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-left-of-viewport-partially-onscreen-new.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-left-of-viewport-partially-onscreen-old.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-on-top-of-viewport-offscreen-new.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-on-top-of-viewport-offscreen-old.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-on-top-of-viewport-partially-onscreen-new.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-on-top-of-viewport-partially-onscreen-old.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-right-and-left-of-viewport-partially-onscreen-new.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-right-and-left-of-viewport-partially-onscreen-old.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-right-of-viewport-offscreen-new.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-right-of-viewport-offscreen-old.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-right-of-viewport-partially-onscreen-new.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/massive-element-right-of-viewport-partially-onscreen-old.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/match-element-name.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/modify-style-via-cssom.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/multiline-span-with-overflowing-text-and-box-decorations.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/named-element-with-fix-pos-child-new.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/named-element-with-fix-pos-child-old.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/names-are-tree-scoped.html
http://web-platform.test:8000/css/css-view-transitions/navigation/chromium-paint-holding-timeout.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/navigation/root-element-transition-iframe-cross-origin.sub.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/navigation/root-element-transition-iframe-with-startVT-on-main.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/navigation/root-element-transition-iframe.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/adjust-transform-with-scale.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/adjust-transform.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/compute-explicit-name-direct.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/compute-explicit-name-nested-vt-names.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/compute-explicit-name-nested.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/compute-explicit-name-non-ancestor.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/compute-explicit-name-non-existent.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/compute-explicit-name-self.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/contain-direct.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/contain-nested.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/contain-on-self.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/custom-ident-implies-contain.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/group-children-sizing-with-border-props.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/group-children-sizing-with-border.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/group-children-sizing.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/nearest-direct.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/nearest-ignores-nearest-name.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/nearest-implies-contain.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/nearest-nested.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/nested-exit.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/nested-group-display-none.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/nested-group-in-pseudo-basic.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/nested-parent-changes-transform-twice.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/nested-parent-changes-transform.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/nested-position-with-border.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/nested-root-capture-with-clip.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/normal-goes-up.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/render-element.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/rotated-container.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested/rounded-border-clipper.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nested-elements-in-overflow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-and-old-sizes-match.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-ancestor-clipped-2.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-ancestor-clipped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-captures-clip-path.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-captures-different-size.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-captures-opacity.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-captures-positioned-spans.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-captures-root.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-captures-spans.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-changes-overflow-left.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-changes-overflow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-container-writing-modes.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-element-writing-modes.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-escapes-clip-with-abspos-child.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-flat-transform-ancestor.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-from-root-display-none.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-has-scrollbars.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-inline-with-offset-from-containing-block-clipped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-intrinsic-aspect-ratio.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-is-empty-div.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-is-inline.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-object-fit-fill.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-object-fit-none.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-object-view-box-clip-path-reference.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-object-view-box-clip-path.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-object-view-box-overflow-clipped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-object-view-box-overflow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-preserve-3d-ancestor.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-root-scrollbar-with-fixed-background.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-scaling.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-transform-change-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-transform-position-fixed.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-with-object-view-box.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-with-overflow-zoomed.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-content-with-overflow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-element-on-start.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/new-root-vertical-writing-mode.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/no-named-elements.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/no-painting-while-render-blocked.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/no-root-capture.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/no-white-flash-before-activation.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/nothing-captured.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/object-view-box-new-image.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/object-view-box-old-image.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/offscreen-element-modified-before-coming-onscreen.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-captures-clip-path.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-captures-different-size.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-captures-opacity.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-captures-root.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-container-writing-modes.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-element-writing-modes.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-escapes-clip-with-abspos-child.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-has-scrollbars.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-inline-with-offset-from-containing-block-clipped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-intrinsic-aspect-ratio.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-is-empty-div.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-is-inline.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-object-fit-fill.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-object-fit-none.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-object-view-box-clip-path-reference.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-object-view-box-clip-path.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-object-view-box-overflow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-root-scrollbar-with-fixed-background.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-with-object-view-box.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-with-overflow-zoomed.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-content-with-overflow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/old-root-vertical-writing-mode.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/outer-padding-inner-background.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/paint-holding-in-iframe.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/pseudo-element-overflow-clip-with-border-radius.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/pseudo-element-overflow-hidden.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/pseudo-element-preserve-3d.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/pseudo-rendering-invalidation.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/pseudo-with-classes-entry.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/pseudo-with-classes-exit.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/pseudo-with-classes-match-ident.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/pseudo-with-classes-match-multiple-wildcard.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/pseudo-with-classes-match-multiple.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/pseudo-with-classes-match-wildcard-no-star.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/pseudo-with-classes-match-wildcard.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/pseudo-with-classes-mismatch-ident.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/pseudo-with-classes-mismatch-partial.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/pseudo-with-classes-mismatch-wildcard.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/pseudo-with-classes-multiple-vt-classes.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/pseudo-with-classes-new-with-class-old-without.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/pseudo-with-classes-old-with-class-new-without.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/pseudo-with-classes-view-transition-group.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/pseudo-with-classes-view-transition-image-pair.html
http://web-platform.test:8000/css/css-view-transitions/reset-state-after-scrolled-view-transition.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/root-captured-as-different-tag.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/root-style-change-during-animation.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/root-to-shared-animation-end.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/root-to-shared-animation-incoming.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/root-to-shared-animation-start.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/rotated-cat-off-top-edge.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/rtl-with-scrollbar.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/active-pseudo.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/ancestor-display-change.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/auto-nesting.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/box-decoration-painting.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/centered-paint-offset.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/clip-on-target-in-callback-2.html
http://web-platform.test:8000/css/css-view-transitions/scoped/clip-on-target-in-callback.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/clipper-non-containing-block.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/display-change-during-transition.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/display-change.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/fractional-border-shift.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/from-scale-zero.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/implicit-contain.html
http://web-platform.test:8000/css/css-view-transitions/scoped/ink-overflow-on-target.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/nested-scope.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/new-content.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/old-content.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/overflow-excludes-pseudo.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/paint-order.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/pause-rendering-resize.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/pause-rendering.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/rotation-on-scoped-element.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/scope-during-transition-2.html
http://web-platform.test:8000/css/css-view-transitions/scoped/scrolled-target-position-rtl.html
http://web-platform.test:8000/css/css-view-transitions/scoped/scrolled-target-position.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/scroller-with-child.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/shadow-dom.html
http://web-platform.test:8000/css/css-view-transitions/scoped/target-in-scrolled-container.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/to-scale-zero.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scoped/transform-clip.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scroller-child-abspos.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scroller-child.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/scroller.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/set-current-time-transform.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/set-current-time.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/set-universal-specificity.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/shadow-part-with-class-inside-shadow-important.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/shadow-part-with-class-inside-shadow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/shadow-part-with-class.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/shadow-part-with-name-nested.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/shadow-part-with-name-overridden-by-important.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/shadow-part-with-name.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/sibling-frames-transition.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/small-scale.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/snapshot-containing-block-absolute.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/snapshot-containing-block-includes-scrollbar-gutter.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/snapshot-containing-block-static-iframe.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/snapshot-containing-block-static.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/span-with-overflowing-text-and-box-decorations.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/span-with-overflowing-text-hidden.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/span-with-overflowing-text.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/table-caption.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/transform-origin-view-transition-group.html
http://web-platform.test:8000/css/css-view-transitions/transformed-element-scroll-transform.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/transition-in-empty-iframe.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/update-callback-called-once.html
http://web-platform.test:8000/css/css-view-transitions/view-transition-name-is-backdrop-filter-root.html
http://web-platform.test:8000/css/css-view-transitions/view-transition-name-is-grouping.html
http://web-platform.test:8000/css/css-view-transitions/view-transition-name-on-document-root.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/view-transition-name-removed-mid-transition.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/view-transition-name-stacking-context-dynamic.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/view-transition-types-match-early-mutation.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/view-transition-types-match-early.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/view-transition-types-match-late-mutation.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/view-transition-types-matches-case-sensitive.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/view-transition-types-matches.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/view-transition-types-removed.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/view-transition-types-reserved-mutation.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/view-transition-types-reserved.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/view-transition-types-stay.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/view-transition-waituntil-animation-manipulation.html
# [auto-fail:NO_REFERENCE] http://web-platform.test:8000/css/css-view-transitions/web-animations-api-parse-pseudo-argument.html?first-pseudo=::view-transition-group(      first )
# [auto-fail:NO_REFERENCE] http://web-platform.test:8000/css/css-view-transitions/web-animations-api-parse-pseudo-argument.html?first-pseudo=::view-transition-group( first
# [auto-fail:NO_REFERENCE] http://web-platform.test:8000/css/css-view-transitions/web-animations-api-parse-pseudo-argument.html?first-pseudo=::view-transition-group( first)
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/web-animations-api-parse-pseudo-argument.html?first-pseudo=::view-transition-group(first
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/web-animations-api-parse-pseudo-argument.html?first-pseudo=::view-transition-group(first )
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/web-animations-api-parse-pseudo-argument.html?first-pseudo=::view-transition-group(first)
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/web-animations-api.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-view-transitions/writing-mode-container-resize.html
