# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/abspos-static-position.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/background-image.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/basic.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/border-image-width.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/border-radius.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/border-spacing-without-border.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/border-spacing.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/border-width.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/box-shadow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/canvas.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/contain-intrinsic-height.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/contain-intrinsic-width.html
http://web-platform.test:8000/css/css-viewport/zoom/container-queries-block-size.html
http://web-platform.test:8000/css/css-viewport/zoom/container-queries-height.html
http://web-platform.test:8000/css/css-viewport/zoom/container-queries-inline-size.html
http://web-platform.test:8000/css/css-viewport/zoom/container-queries.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/explicit-inherit/border-radius.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/explicit-inherit/border.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/explicit-inherit/bottom.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/explicit-inherit/column.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/explicit-inherit/flex-basis.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/explicit-inherit/height.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/explicit-inherit/left.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/explicit-inherit/margin.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/explicit-inherit/max-height.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/explicit-inherit/max-width.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/explicit-inherit/min-height.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/explicit-inherit/min-width.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/explicit-inherit/outline.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/explicit-inherit/padding.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/explicit-inherit/right.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/explicit-inherit/top.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/explicit-inherit/webkit-border-radius.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/explicit-inherit/webkit-flex-basis.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/explicit-inherit/width.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/filters-drop-shadow.html
http://web-platform.test:8000/css/css-viewport/zoom/font-size-keyword-specified.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/font-size.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/iframe-zoom-nested.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/iframe-zoom.sub.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/image-intrinsic-size.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/inherited-length.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/inherited.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/letter-spacing.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/line-height.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/list-style-image.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/margin.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/mask-border-width.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/relative-units-from-parent.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/scroll-margin.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/scroll-padding.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/stroke.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/svg-font-relative-units.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/svg-path-simple.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/svg-path.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/svg-stroke-width.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/svg-transform.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/svg-viewBox.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/svg.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/text-decoration-thickness.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/text-indent-svg.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/text-indent.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/text-shadow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/text-stroke-width.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/text-underline-offset.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/word-spacing.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/zoom-precision.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-viewport/zoom/zoom-pseudo-image.html
