http://web-platform.test:8000/css/motion/animation/reftests/offset-distance-interpolation-001.html
http://web-platform.test:8000/css/motion/animation/reftests/offset-path-path-interpolation-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/animation/reftests/offset-path-with-transforms-001.html
http://web-platform.test:8000/css/motion/animation/reftests/offset-rotate-interpolation-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/change-offset-path.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-anchor-transform-box-fill-box-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-anchor-transform-box-fill-box-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-anchor-transform-box-fill-box-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-distance-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-distance-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-distance-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-distance-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-distance-005.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-distance-006.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-distance-007.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-distance-008.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-distance-009.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-coord-box-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-coord-box-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-coord-box-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-coord-box-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-005.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-006.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-007.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-008.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-009.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-010.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-011.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-012.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-013.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-014.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-015.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-016.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-017.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-018.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-019.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-020.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-021.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-022.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-contain-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-contain-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-contain-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-contain-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-ray-contain-005.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-circle-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-circle-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-circle-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-circle-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-circle-005.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-circle-006.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-circle-007.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-circle-008.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-ellipse-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-ellipse-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-ellipse-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-ellipse-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-ellipse-005.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-ellipse-006.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-ellipse-007.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-inset-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-inset-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-polygon-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-polygon-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-polygon-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-rect-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-rect-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-rect-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-shape-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-shape-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-shape-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-xywh-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-xywh-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-shape-xywh-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-string-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-string-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-string-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-url-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-url-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-url-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-url-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-url-005.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-url-006.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-url-007.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-url-008.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-url-009.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-url-010.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-url-011.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-path-url-012.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-rotate-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-rotate-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-rotate-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-rotate-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/motion/offset-rotate-005.html
