# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/background-image-alpha.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/background-image-multiple.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/background-image-tiled.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/background-repeat-x.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/color-custom-property-animation.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/dynamic-import.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/geometry-background-image-001.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/geometry-background-image-002.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/geometry-background-image-tiled-001.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/geometry-background-image-tiled-002.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/geometry-background-image-tiled-003.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/geometry-border-image-001.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/geometry-border-image-002.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/geometry-border-image-003.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/geometry-border-image-004.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/geometry-border-image-005.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/geometry-with-float-size.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/hidpi/canvas-reset.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/hidpi/canvas-transform.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/hidpi/device-pixel-ratio.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/invalid-image-constructor-error.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/invalid-image-paint-error.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/invalid-image-pending-script.https.html
http://web-platform.test:8000/css/css-paint-api/no-op-animation.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/non-registered-property-value.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/one-custom-property-animation-half-opaque.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/one-custom-property-animation.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/overdraw.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/paint-arguments.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/paint-function-arguments-var.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/paint-function-arguments.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/paint-function-this-value.https.html
http://web-platform.test:8000/css/css-paint-api/paint2d-canvasFilter.tentative.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/paint2d-composite.https.html
http://web-platform.test:8000/css/css-paint-api/paint2d-conicGradient.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/paint2d-filter.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/paint2d-gradient.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/paint2d-image.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/paint2d-imageSmoothingQuality.high.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/paint2d-imageSmoothingQuality.low.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/paint2d-imageSmoothingQuality.med.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/paint2d-paths.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/paint2d-rects.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/paint2d-reset.https.html
http://web-platform.test:8000/css/css-paint-api/paint2d-roundRect.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/paint2d-shadows.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/paint2d-transform.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-001.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-002.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-003.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-004.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-005.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-006.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-007.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-008.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-009.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-010.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-011.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-012.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-013.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-014.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-015.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-016.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-017.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-018.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-019.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-020.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-021.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/parse-input-arguments-022.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-interpolation-001.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-interpolation-002.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-interpolation-003.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-interpolation-004.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-interpolation-005.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-interpolation-006.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-interpolation-007.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-interpolation-008.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-interpolation-009.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-interpolation-010.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-invalidation-001.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-invalidation-002.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-stylemap.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-utf8-animation.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-value-001.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-value-002.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-value-003.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-value-004.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-value-005.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-value-006.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-value-007.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-value-008.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-value-009.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-value-010.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-value-011.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-value-012.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-value-013.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-value-014.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-value-015.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-value-016.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-value-017.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/registered-property-value-018.https.html
http://web-platform.test:8000/css/css-paint-api/roundrect.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/setTransform-001.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/setTransform-002.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/setTransform-003.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/setTransform-004.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/style-background-image.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/style-before-pseudo.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/style-first-letter-pseudo.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/top-level-await.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/two-custom-property-animation.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/two-element-custom-property-animation.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/two-element-one-custom-property-animation.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/valid-image-after-load.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-paint-api/valid-image-before-load.https.html
