# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-end-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-end-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-end-collapsed-margins.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-end-self-collapsing-and-border.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-end-self-collapsing-block-start-margin-nested.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-end-self-collapsing-block-start-margin.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-end-self-collapsing-item-has-larger-block-end.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-end-self-collapsing-item-has-larger-block-start.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-end-start-margin.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-in-inline-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-in-inline-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-in-inline-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-in-inline-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-in-inline-005.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-in-inline-006.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-in-inline-007.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-start-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-start-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-start-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-start-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-start-collapsed-margins.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-start-self-collapsing-item-has-larger-block-end.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-block-start-self-collapsing-item-larger-block-start.html
http://web-platform.test:8000/css/css-box/margin-trim/block-container-inline-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-non-adjoining-item.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-replaced-block-end.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-replaced-block-start.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/block-container-replaced-block.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-block-end-trimmed-only.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-block-start-trimmed-only.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-block-trimmed-only.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-column-block-multiline.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-column-grow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-column-inline-multiline.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-column-orthogonal-item.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-column-shrink.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-column-style-change-triggers-layout-block-end.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-column-style-change-triggers-layout-block-start.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-column-style-change-triggers-layout-block.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-inline-end-trimmed-only.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-inline-start-trimmed-only.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-inline-trimmed-only.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-row-block-multiline.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-row-grow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-row-inline-multiline.html
http://web-platform.test:8000/css/css-box/margin-trim/flex-row-orthogonal-item.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-row-shrink.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-row-style-change-triggers-layout-inline-end.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-row-style-change-triggers-layout-inline-start.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-row-style-change-triggers-layout-inline.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/flex-trim-all-margins.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/grid-block-end.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/grid-block-start.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/grid-block.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/grid-inline-end.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/grid-inline-start.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/grid-inline.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/grid-trim-ignores-collapsed-tracks.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/multicol-spanner-001.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/multicol-spanner-002.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/multicol-spanner-003.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/multicol-spanner-004.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/multicol-spanner-005.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/multicol-spanner-006.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-box/margin-trim/multicol-spanner-007.html
