# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/auto-block-size/absolute.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/auto-block-size/flex.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/auto-block-size/floats.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/auto-block-size/inflow.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/auto-block-size/negative.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/baseline/child-baseline.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/baseline/flex-baseline.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/baseline/no-baseline.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/baseline/orthogonal-baseline.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/box-tree-registered.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/box-tree-unregistered.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/available-block-size-htb-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/available-block-size-invalid.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/available-block-size-vrl-htb.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/available-inline-size-htb-htb.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/available-inline-size-invalid.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/available-inline-size-vrl-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/available-size-for-percentages-htb-htb.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/available-size-for-percentages-htb-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/available-size-for-percentages-invalid.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/available-size-for-percentages-vrl-htb.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/available-size-for-percentages-vrl-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/fixed-block-size-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/fixed-block-size.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/fixed-inline-size-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/fixed-inline-size.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/percentage-size-htb-htb.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/percentage-size-htb-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/percentage-size-invalid.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/percentage-size-quirks-mode.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/percentage-size-vrl-htb.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/child-constraints/percentage-size-vrl-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-absolute-left-right-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-absolute-none.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-absolute-top-bottom.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-block-none-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-block-none.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-fixed-max.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-fixed-min.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-fixed-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-fixed.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-flex-basis-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-flex-column-basis.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-flex-column-grow.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-flex-column-none.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-flex-column-stretch-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-flex-grow-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-flex-none.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-flex-percentage-indefinite.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-flex-stretch-max.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-flex-stretch.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-grid-none.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-grid-stretch-max.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-grid-stretch.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-grid-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-percentage-indefinite.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-percentage-quirks-mode.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-percentage-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-percentage.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-block-size-quirky-body.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-inline-size-absolute-left-right.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-inline-size-absolute-top-bottom-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-inline-size-block-auto-avoid-floats-vlr.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-inline-size-block-auto-avoid-floats.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-inline-size-block-auto-vlr.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-inline-size-block-auto.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-inline-size-fixed-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-inline-size-fixed.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-inline-size-flex-grow-column-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-inline-size-flex-grow.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-inline-size-grid.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-inline-size-percentage-vlr.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints/fixed-inline-size-percentage.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints-data-function-failure.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints-data-sab-failure.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/constraints-data.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/edges/all.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/edges/border-htb-rtl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/edges/border-htb.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/edges/border-vlr-rtl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/edges/border-vlr.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/edges/border-vrl-rtl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/edges/border-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/edges/padding-htb-rtl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/edges/padding-htb.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/edges/padding-vlr-rtl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/edges/padding-vlr.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/edges/padding-vrl-rtl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/edges/padding-vrl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/edges/scrollbar.https.html
http://web-platform.test:8000/css/css-layout-api/fallback-intrinsic-sizes/bad-return.https.html
http://web-platform.test:8000/css/css-layout-api/fallback-intrinsic-sizes/constructor-error.https.html
http://web-platform.test:8000/css/css-layout-api/fallback-intrinsic-sizes/error.https.html
http://web-platform.test:8000/css/css-layout-api/fallback-intrinsic-sizes/invalid-child.https.html
http://web-platform.test:8000/css/css-layout-api/fallback-intrinsic-sizes/no-promise.https.html
http://web-platform.test:8000/css/css-layout-api/fallback-intrinsic-sizes/unresolved-promise.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/fallback-layout/bad-return.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/fallback-layout/constructor-error.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/fallback-layout/error.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/fallback-layout/invalid-child.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/fallback-layout/invalid-fragment.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/fallback-layout/no-promise.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/fallback-layout/unresolved-promise.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/fragment-data-function-failure.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/fragment-data-immutable.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/fragment-data-sab-failure.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/fragment-data.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/intrinsic-sizes/absolute.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/intrinsic-sizes/child-replaced-percentage-01.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/intrinsic-sizes/child-replaced-percentage-02.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/intrinsic-sizes/child-size-01.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/intrinsic-sizes/child-size-02.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/intrinsic-sizes/child-size-03.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/intrinsic-sizes/child-size-contribution.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/intrinsic-sizes/content-size.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/intrinsic-sizes/floats.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/intrinsic-sizes/invalid-min-max.https.html
http://web-platform.test:8000/css/css-layout-api/intrinsic-sizes/negative-max.https.html
http://web-platform.test:8000/css/css-layout-api/intrinsic-sizes/negative-min.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/layout-child/absolute.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/layout-child/before-after.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/layout-child/fixed.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/layout-child/float.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/layout-child/inflow.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/layout-child/inlines.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/layout-child/text-01.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/layout-child/text-02.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/position-fragment/htb-ltr.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/position-fragment/htb-rtl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/position-fragment/vlr-ltr.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/position-fragment/vlr-rtl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/position-fragment/vrl-ltr.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/position-fragment/vrl-rtl.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/style-map-multi.https.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/css/css-layout-api/style-map.https.html
