# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/2_cues_overlapping_completely_move_up.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/2_cues_overlapping_partially_move_down.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/2_cues_overlapping_partially_move_up.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/2_tracks.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/3_tracks.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/align_center.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/align_center_position_50.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/align_center_position_gt_50.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/align_center_position_gt_50_size_gt_maximum_size.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/align_center_position_lt_50.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/align_center_position_lt_50_size_gt_maximum_size.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/align_center_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/align_end.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/align_end_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/align_start.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/align_start_wrapped.html
http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/audio_has_no_subtitles.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/basic.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/bidi/bidi_ruby.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/bidi/start_alignment.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/bidi/u002E_LF_u05D0.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/bidi/u002E_u2028_u05D0.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/bidi/u002E_u2029_u05D0.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/bidi/u0041_first.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/bidi/u05D0_first.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/bidi/u0628_first.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/bidi/u06E9_no_strong_dir.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/bidi/vertical_lr.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/bidi/vertical_rl.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/cue_too_long.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/decode_escaped_entities.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/disable_controls_reposition.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/dom_override_cue_align_position_line_size.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/dom_override_cue_align_position_line_size_while_paused.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/dom_override_cue_line.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/dom_override_cue_text.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/dom_override_cue_text_while_paused.html
http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/dom_override_remove_cue_while_paused.html
http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/embedded_style_cascade_priority.html
http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/embedded_style_cascade_priority_layer.html
http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/embedded_style_imports_blocked.html
http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/embedded_style_invalid_format.html
http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/embedded_style_media_queries.html
http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/embedded_style_media_queries_resized.html
http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/embedded_style_multiple_tracks.html
http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/embedded_style_selectors.html
http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/embedded_style_urls.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/evil/9_cues_overlapping_completely.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/evil/9_cues_overlapping_completely_all_cues_have_same_timestamp.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/evil/media_404_omit_subtitles.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/evil/media_height_19.html
http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/evil/non-standard-pseudo-elements.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/evil/single_quote.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/evil/size_90.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/evil/size_99.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/line_-2_wrapped_cue_grow_upwards.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/line_0_is_top.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/line_1_wrapped_cue_grow_downwards.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/line_50_percent.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/line_integer_and_percent_mixed_overlap.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/line_integer_and_percent_mixed_overlap_move_up.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/line_percent_and_integer_mixed_overlap.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/line_percent_and_integer_mixed_overlap_move_up.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/navigate_cue_position.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/one_line_cue_plus_wrapped_cue.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/portrait.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/regions/basic.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/regions/regionanchor_x_50_percent.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/regions/regionanchor_y_50_percent.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/regions/scroll_up.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/regions/single_line_top_left.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/regions/viewportanchor_x_50_percent.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/regions/viewportanchor_y_50_percent.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/regions/width_50_percent.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/repaint.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/background_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/background_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/background_shorthand_css_relative_url.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/color_hex.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/color_hsla.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/color_rgba.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/cue_selector_single_colon.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/font_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/font_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/fontsize_smaller_than_container.tentative.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/inherit_values_from_media_element.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/outline_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/outline_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/text-decoration_line-through.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/text-decoration_overline.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/text-decoration_overline_underline_line-through.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/text-decoration_underline.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/text-shadow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/vertical_ruby-position.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/vertical_text-combine-upright.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/white-space_normal_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/white-space_nowrap_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/white-space_pre-line_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/white-space_pre-wrap_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/white-space_pre.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue/white-space_pre_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue-region/font_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue-region_function/font_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/background_box.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/background_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/background_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/background_shorthand_css_relative_url.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_animation_with_timestamp.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_background_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_background_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_color.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_font_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_font_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_namespace.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_outline_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_outline_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_text-decoration_line-through.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_text-shadow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_timestamp_future.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_timestamp_past.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_transition_with_timestamp.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_white-space_normal_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_white-space_nowrap.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_white-space_pre-line_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_white-space_pre-wrap_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_white-space_pre_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_with_class.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/bold_object/bold_with_class_object_specific_selector.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_animation_with_timestamp.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_background_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_background_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_color.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_font_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_font_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_namespace.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_outline_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_outline_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_text-decoration_line-through.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_text-shadow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_timestamp_future.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_timestamp_past.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_transition_with_timestamp.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_vertical_text-combine-upright.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_white-space_normal_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_white-space_nowrap.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_white-space_pre-line_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_white-space_pre-wrap_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_white-space_pre_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_with_class.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/class_object/class_with_class_object_specific_selector.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/color_hex.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/color_hsla.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/color_rgba.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/cue_func_selector_single_colon.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/font_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/font_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/id_color.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/inherit_values_from_media_element.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_animation_with_timestamp.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_background_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_background_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_color.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_font_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_font_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_namespace.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_outline_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_outline_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_text-decoration_line-through.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_text-shadow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_timestamp_future.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_timestamp_past.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_transition_with_timestamp.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_white-space_normal_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_white-space_nowrap.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_white-space_pre-line_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_white-space_pre-wrap_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_white-space_pre_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_with_class.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/italic_object/italic_with_class_object_specific_selector.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/lang_object/lang_attribute.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/lang_object/lang_color.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/not_allowed_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/not_root_selector.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/outline_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/outline_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/root_namespace.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/root_selector.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/text-decoration_line-through.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/text-decoration_overline.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/text-decoration_overline_underline_line-through.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/text-decoration_underline.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/text-shadow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/type_selector_root.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_animation_with_timestamp.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_background_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_background_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_color.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_font_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_font_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_namespace.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_outline_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_outline_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_text-decoration_line-through.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_text-shadow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_timestamp_future.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_timestamp_past.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_transition_with_timestamp.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_white-space_normal_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_white-space_nowrap.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_white-space_pre-line_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_white-space_pre-wrap_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_white-space_pre_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_with_class.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/underline_object/underline_with_class_object_specific_selector.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_animation_with_timestamp.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_background_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_background_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_color.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_font_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_font_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_namespace.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_outline_properties.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_outline_shorthand.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_text-decoration_line-through.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_text-shadow.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_timestamp_future.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_timestamp_past.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_transition_with_timestamp.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_voice_attribute.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_white-space_normal_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_white-space_nowrap.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_white-space_pre-line_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_white-space_pre-wrap_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_white-space_pre_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_with_class.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/voice_object/voice_with_class_object_specific_selector.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/white-space_normal_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/white-space_nowrap_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/white-space_pre-line_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/white-space_pre-wrap_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/white-space_pre.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/cue_function/white-space_pre_wrapped.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/default_styles/bold_object_default_font-style.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/default_styles/inherit_as_default_value_inherits_values_from_media_element.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/default_styles/italic_object_default_font-style.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/selectors/default_styles/underline_object_default_font-style.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/size_50.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/snap-to-line.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/too_many_cues.html
# [auto-fail:IMG_MISMATCH] http://web-platform.test:8000/webvtt/rendering/cues-with-video/processing-model/too_many_cues_wrapped.html
