// https://dom.spec.whatwg.org/#interface-documentfragment

[UnimplementedConstructor,
 Exposed=Window]
interface DocumentFragment : Node {
};

// NOTE current version of Starfish does not fully support DocumentFragment
// DocumentFragment implements NonElementParentNode;
// DocumentFragment implements ParentNode;