// https://dom.spec.whatwg.org/#interface-domtokenlist

interface DOMTokenList {
  readonly attribute unsigned long length;
  getter DOMString? item(unsigned long index);
  [RaisesException] boolean contains(DOMString token);
  [Custom, RaisesException, CEReactions] void add(DOMString... tokens);
  [RaisesException, CEReactions] void remove(DOMString... tokens);
  [RaisesException, CEReactions] boolean toggle(DOMString token, optional boolean force);
  [Unimplemented, CEReactions] void replace(DOMString token, DOMString newToken);
  [Unimplemented] boolean supports(DOMString token);
  [Unimplemented] attribute DOMString value;
  stringifier;
  iterable<DOMString>;
};