// https://html.spec.whatwg.org/multipage/interaction.html#elementcontenteditable

[NoInterfaceObject]
interface ElementContentEditable {
  [Unimplemented, CEReactions] attribute DOMString contentEditable;
  [Unimplemented] readonly attribute boolean isContentEditable;
};