// https://drafts.csswg.org/cssom/#elementcssinlinestyle

[NoInterfaceObject]
interface ElementCSSInlineStyle {
  // FIXME readonly property but seems to have a Setter
  // [SameObject, PutForwards=cssText] readonly attribute CSSStyleDeclaration style;
  [Custom=(Getter, Setter)] attribute CSSStyleDeclaration style;
};