// https://html.spec.whatwg.org/multipage/webappapis.html#globaleventhandlers
[PartialInterface,
NoInterfaceObject]
interface GlobalEventHandlers {
  attribute EventHandler onabort;
  [Unimplemented] attribute EventHandler onauxclick;
  [Unimplemented] attribute EventHandler onblur;
  [Unimplemented] attribute EventHandler oncancel;
  attribute EventHandler oncanplay;
  attribute EventHandler oncanplaythrough;
  [Unimplemented] attribute EventHandler onchange;
  attribute EventHandler onclick;
  [Unimplemented] attribute EventHandler onclose;
  [Unimplemented] attribute EventHandler oncontextmenu;
  [Unimplemented] attribute EventHandler oncuechange;
  [Unimplemented] attribute EventHandler ondblclick;
  [Unimplemented] attribute EventHandler ondrag;
  [Unimplemented] attribute EventHandler ondragend;
  [Unimplemented] attribute EventHandler ondragenter;
  [Unimplemented] attribute EventHandler ondragexit;
  [Unimplemented] attribute EventHandler ondragleave;
  [Unimplemented] attribute EventHandler ondragover;
  [Unimplemented] attribute EventHandler ondragstart;
  [Unimplemented] attribute EventHandler ondrop;
  attribute EventHandler ondurationchange;
  attribute EventHandler onemptied;
  attribute EventHandler onended;
  // FIXME: onerror should be type of OnErrorEventHandler
  attribute EventHandler onerror;
  attribute EventHandler onfocus;
  [Unimplemented] attribute EventHandler oninput;
  [Unimplemented] attribute EventHandler oninvalid;
  attribute EventHandler onkeydown;
  [Unimplemented] attribute EventHandler onkeypress;
  attribute EventHandler onkeyup;
  attribute EventHandler onload;
  attribute EventHandler onloadeddata;
  attribute EventHandler onloadedmetadata;
  [Unimplemented] attribute EventHandler onloadend;
  attribute EventHandler onloadstart;
  [Unimplemented] attribute EventHandler onmousedown;
  [Unimplemented, LenientThis] attribute EventHandler onmouseenter;
  [Unimplemented, LenientThis] attribute EventHandler onmouseleave;
  [Unimplemented] attribute EventHandler onmousemove;
  [Unimplemented] attribute EventHandler onmouseout;
  attribute EventHandler onmouseover;
  [Unimplemented] attribute EventHandler onmouseup;
  [Unimplemented] attribute EventHandler onwheel;
  attribute EventHandler onpause;
  attribute EventHandler onplay;
  attribute EventHandler onplaying;
  attribute EventHandler onprogress;
  attribute EventHandler onratechange;
  [Unimplemented] attribute EventHandler onreset;
  [Unimplemented] attribute EventHandler onresize;
  [Unimplemented] attribute EventHandler onscroll;
  attribute EventHandler onseeked;
  attribute EventHandler onseeking;
  [Unimplemented] attribute EventHandler onselect;
  [Unimplemented] attribute EventHandler onshow;
  attribute EventHandler onstalled;
  [Unimplemented] attribute EventHandler onsubmit;
  attribute EventHandler onsuspend;
  attribute EventHandler ontimeupdate;
  [Unimplemented] attribute EventHandler ontoggle;
  attribute EventHandler onvolumechange;
  attribute EventHandler onwaiting;
};