// https://html.spec.whatwg.org/#htmlheadingelement

[HTMLConstructor]
interface HTMLHeadingElement : HTMLElement {
  // also has obsolete members

  [Unimplemented, CEReactions] attribute DOMString align;
};