csswg-test/css21_original/selectors/hover-selector-001.htm
csswg-test/css21_original/selectors/hover-selector-002.htm
csswg-test/css21_original/selectors/hover-selector-003.htm
csswg-test/css21_original/selectors/pseudo-003.htm
csswg-test/css21_original/selectors/pseudo-005.htm
csswg-test/css21_original/selectors/pseudo-010.htm
csswg-test/css21_original/selectors/pseudo-011.htm
csswg-test/css21_original/selectors/pseudo-012.htm
csswg-test/selectors3_original/html/css3-modsel-18.html
csswg-test/selectors3_original/html/css3-modsel-18b.html
csswg-test/selectors3_original/html/css3-modsel-19.html
csswg-test/selectors3_original/html/css3-modsel-19b.html
csswg-test/selectors3_original/html/css3-modsel-20.html
csswg-test/selectors3_original/html/css3-modsel-21.html
csswg-test/selectors3_original/html/css3-modsel-63.html
csswg-test/selectors3_original/html/css3-modsel-64.html
csswg-test/selectors3_original/html/css3-modsel-65.html
csswg-test/selectors3_original/html/css3-modsel-66.html