// https://html.spec.whatwg.org/multipage/workers.html#workerglobalscope

[
  STARFISH_WEBWORKER_HOST,
  Exposed=Worker,
  NoInterfaceObject
]
interface WorkerGlobalScope : EventTarget {
  readonly attribute WorkerGlobalScope self;
  readonly attribute WorkerLocation location;
  readonly attribute WorkerNavigator navigator;
  [RaisesException] void importScripts(USVString... urls);

  [Unimplemented] attribute EventHandler onerror;
  [Unimplemented] attribute EventHandler onlanguagechange;
  [Unimplemented] attribute EventHandler onoffline;
  [Unimplemented] attribute EventHandler ononline;
  [Unimplemented] attribute EventHandler onrejectionhandled;
  [Unimplemented] attribute EventHandler onunhandledrejection;

  // NOTE: The followings aren't the Web specification.
  readonly attribute CustomStorage workerStorage;
};

WorkerGlobalScope implements WindowOrWorkerGlobalScope;
