// https://drafts.csswg.org/resize-observer/#ref-for-resizeobserverentry 
[Exposed=Window]
interface ResizeObserverEntry {
    readonly attribute Element target;
    readonly attribute DOMRectReadOnly contentRect;
    // [Unimplemented] readonly attribute FrozenArray<ResizeObserverSize> borderBoxSize;
    // [Unimplemented] readonly attribute FrozenArray<ResizeObserverSize> contentBoxSize;
    // [Unimplemented] readonly attribute FrozenArray<ResizeObserverSize> devicePixelContentBoxSize;
};
