# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-exit-fullscreen-active-document.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-exit-fullscreen-nested-in-iframe.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-exit-fullscreen-nested-shadow-dom.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-exit-fullscreen-nested.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-exit-fullscreen-timing.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-exit-fullscreen-twice.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-exit-fullscreen.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-fullscreen-element.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-fullscreen-enabled-active-document.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-fullscreen-enabled-cross-origin.sub.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-fullscreen-enabled-removing-allowfullscreen.sub.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-fullscreen-enabled-setting-allowfullscreen-timing.sub.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-fullscreen-enabled-setting-allowfullscreen.sub.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-fullscreen-enabled.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-fullscreen-keyboard-lock-change.window.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-fullscreen-keyboard-lock-escape.window.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-fullscreen-keyboard-lock-multiple-elements.window.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-fullscreen-keyboard-lock-shadowdom.window.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-onfullscreenchange.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/document-onfullscreenerror.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-ready-allowed.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-ready-check-allowed-cross-origin.sub.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-ready-check-containing-iframe.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-ready-check-fullscreen-element-sibling.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-ready-check-fullscreen-iframe-child.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-ready-check-iframe-child.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-ready-check-not-allowed-cross-origin.sub.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-ready-check-not-in-document.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-active-document.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-after-error.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-and-exit-iframe.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-and-move-to-iframe.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-and-move.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-and-remove-iframe.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-and-remove.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-consume-user-activation.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-cross-origin.sub.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-dialog.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-namespaces.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-non-top.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-not-allowed.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-options.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-same-element.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-svg-rect.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-svg-svg.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-svg-text.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-timing.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-top.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-twice.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen-two-elements.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/element-request-fullscreen.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/fullscreen-display-contents.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/fullscreen-reordering.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/historical.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/keyboard-lock-cross-origin-iframe.sub.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/navigate-iframe.sub.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/promises-reject.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/promises-resolve.html
# [auto-fail] http://web-platform.test:8000/fullscreen/api/shadowroot-fullscreen-element.html
# [auto-fail] http://web-platform.test:8000/fullscreen/idlharness.window.html
# [auto-fail] http://web-platform.test:8000/fullscreen/model/move-fullscreen-element.html
# [auto-fail] http://web-platform.test:8000/fullscreen/model/move-to-fullscreen-iframe.html
# [auto-fail] http://web-platform.test:8000/fullscreen/model/move-to-iframe.html
# [auto-fail] http://web-platform.test:8000/fullscreen/model/move-to-inactive-document.html
# [auto-fail] http://web-platform.test:8000/fullscreen/model/remove-child.html
# [auto-fail] http://web-platform.test:8000/fullscreen/model/remove-first-sibling.html
# [auto-fail] http://web-platform.test:8000/fullscreen/model/remove-first.html
# [auto-fail] http://web-platform.test:8000/fullscreen/model/remove-last-sibling.html
# [auto-fail] http://web-platform.test:8000/fullscreen/model/remove-last.html
# [auto-fail] http://web-platform.test:8000/fullscreen/model/remove-parent.html
# [auto-fail] http://web-platform.test:8000/fullscreen/model/remove-single.html
# [auto-fail] http://web-platform.test:8000/fullscreen/rendering/fullscreen-css-invalidation.html
# [auto-fail] http://web-platform.test:8000/fullscreen/rendering/fullscreen-css-transition.html
http://web-platform.test:8000/fullscreen/rendering/fullscreen-pseudo-class-support.html
# [auto-fail] http://web-platform.test:8000/fullscreen/rendering/fullscreen-pseudo-class.html
# [auto-fail] http://web-platform.test:8000/fullscreen/rendering/fullscreen-root-block-scroll.html
# [auto-fail] http://web-platform.test:8000/fullscreen/rendering/fullscreen-root-block-size.html
# [auto-fail] http://web-platform.test:8000/fullscreen/rendering/ua-style-iframe.html
# [auto-fail] https://web-platform.test:8443/fullscreen/api/element-request-fullscreen-options.tentative.https.html
# [auto-fail] https://web-platform.test:8443/fullscreen/api/element-request-fullscreen-screen-size.https.html
# [auto-fail] https://web-platform.test:8443/fullscreen/api/element-request-fullscreen-without-user-activation.tentative.https.html
# [auto-fail] https://web-platform.test:8443/fullscreen/api/permission.tentative.https.html
