http://web-platform.test:8000/html/webappapis/timers/evil-spec-example.any.html
http://web-platform.test:8000/html/webappapis/system-state-and-capabilities/the-navigator-object/navigator-indexed.html
# [auto-fail] http://web-platform.test:8000/html/webappapis/scripting/processing-model-2/window-onerror-runtime-error-throw.html
http://web-platform.test:8000/html/webappapis/scripting/processing-model-2/runtime-error-same-origin-with-hash.html
http://web-platform.test:8000/html/webappapis/scripting/processing-model-2/runtime-error-same-origin.html
http://web-platform.test:8000/html/webappapis/scripting/processing-model-2/runtime-error-data-url.html
http://web-platform.test:8000/html/webappapis/scripting/processing-model-2/compile-error-in-body-onerror.html
http://web-platform.test:8000/html/webappapis/scripting/processing-model-2/addEventListener.html
http://web-platform.test:8000/html/webappapis/scripting/events/invalid-uncompiled-raw-handler-compiled-once.window.html
http://web-platform.test:8000/html/webappapis/scripting/events/invalid-uncompiled-raw-handler-compiled-late.window.html
http://web-platform.test:8000/html/webappapis/scripting/events/event-handler-onresize.html
http://web-platform.test:8000/html/webappapis/scripting/events/event-handler-javascript.html
http://web-platform.test:8000/html/webappapis/scripting/events/body-onload.html
# [auto-fail] http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-same-origin-domain.sub.html
# [auto-fail] http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-basic.html
http://web-platform.test:8000/html/webappapis/animation-frames/same-dispatch-time.html
http://web-platform.test:8000/html/webappapis/animation-frames/cancel-invoked.html
http://web-platform.test:8000/html/webappapis/animation-frames/callback-multicalls.html
http://web-platform.test:8000/html/webappapis/animation-frames/callback-invoked.html
http://web-platform.test:8000/html/webappapis/animation-frames/callback-exception.html
http://web-platform.test:8000/html/syntax/serializing-html-fragments/initial-linefeed-pre.html
http://web-platform.test:8000/html/semantics/text-level-semantics/the-a-element/a.text-setter-01.html
http://web-platform.test:8000/html/semantics/text-level-semantics/the-a-element/a.text-getter-01.html
http://web-platform.test:8000/html/semantics/text-level-semantics/historical.html
http://web-platform.test:8000/html/semantics/tabular-data/the-tr-element/rowIndex.html
http://web-platform.test:8000/html/semantics/tabular-data/the-tr-element/deleteCell.html
http://web-platform.test:8000/html/semantics/tabular-data/the-tbody-element/insertRow.html
http://web-platform.test:8000/html/semantics/tabular-data/the-tbody-element/deleteRow.html
http://web-platform.test:8000/html/semantics/tabular-data/the-table-element/insertRow-method-03.html
http://web-platform.test:8000/html/semantics/tabular-data/the-table-element/insertRow-method-02.html
http://web-platform.test:8000/html/semantics/tabular-data/the-table-element/insertRow-method-01.html
http://web-platform.test:8000/html/semantics/tabular-data/the-table-element/delete-caption.html
http://web-platform.test:8000/html/semantics/tabular-data/historical.html
http://web-platform.test:8000/html/semantics/selectors/pseudo-classes/indeterminate-radio.html
http://web-platform.test:8000/html/semantics/selectors/pseudo-classes/focus-autofocus.html
http://web-platform.test:8000/html/semantics/selectors/pseudo-classes/dir01.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/script-onload-string.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/script-crossorigin.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/script-charset-03.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/fetch-src/alpha/base.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/137.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/129.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/125.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/121.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/120.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/115.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/114.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/113.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/112.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/111.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/110.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/107-noimport.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/107-import.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/104.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/095.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/092.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/090.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/089.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/088.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/087.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/086.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/085.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/082.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/081.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/078.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/077.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/076.html
# [auto-fail] http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/075.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/069.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/067.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/066.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/065.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/064.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/063.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/062.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/061.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/060.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/059.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/058.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/057.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/053.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/052.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/051.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/049.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/048.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/047.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/046.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/038.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/037.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/036.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/034.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/033.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/032.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/031.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/025.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/024.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/023.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/022.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/021.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/020.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/019.html
# [auto-fail] http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/018.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/017.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/016.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/015a.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/015.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/014.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/013.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/006.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/005.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/004.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/003.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/002.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/execution-timing/001.html
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/async_006.htm
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/async_005.htm
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/async_004.htm
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/async_003.htm
http://web-platform.test:8000/html/semantics/scripting-1/the-script-element/async_002.htm
http://web-platform.test:8000/html/semantics/links/links-created-by-a-and-area-elements/htmlanchorelement_getter.html
http://web-platform.test:8000/html/semantics/links/links-created-by-a-and-area-elements/htmlanchorelement_attribute-getter-setter.html
http://web-platform.test:8000/html/semantics/grouping-content/the-ul-element/grouping-ul.html
http://web-platform.test:8000/html/semantics/grouping-content/the-pre-element/grouping-pre.html
http://web-platform.test:8000/html/semantics/grouping-content/the-p-element/grouping-p.html
http://web-platform.test:8000/html/semantics/grouping-content/the-ol-element/ol.start-reflection-2.html
http://web-platform.test:8000/html/semantics/grouping-content/the-ol-element/ol.start-reflection-1.html
http://web-platform.test:8000/html/semantics/grouping-content/the-li-element/grouping-li.html
http://web-platform.test:8000/html/semantics/grouping-content/the-hr-element/grouping-hr.html
http://web-platform.test:8000/html/semantics/grouping-content/the-dt-element/grouping-dt.html
http://web-platform.test:8000/html/semantics/grouping-content/the-dl-element/grouping-dl.html
http://web-platform.test:8000/html/semantics/grouping-content/the-div-element/grouping-div.html
http://web-platform.test:8000/html/semantics/grouping-content/the-dd-element/grouping-dd.html
http://web-platform.test:8000/html/semantics/forms/the-textarea-element/textarea-type.html
http://web-platform.test:8000/html/semantics/forms/the-select-element/select-named-getter.html
# [auto-fail] http://web-platform.test:8000/html/semantics/forms/the-select-element/common-HTMLOptionsCollection-namedItem.html
# [auto-fail] http://web-platform.test:8000/html/semantics/forms/the-select-element/common-HTMLOptionsCollection-add.html
http://web-platform.test:8000/html/semantics/forms/the-option-element/option-text-label.html
http://web-platform.test:8000/html/semantics/forms/the-option-element/option-text-backslash.html
http://web-platform.test:8000/html/semantics/forms/the-option-element/option-selected.html
http://web-platform.test:8000/html/semantics/forms/the-option-element/option-form.html
http://web-platform.test:8000/html/semantics/forms/the-input-element/search_input.html
http://web-platform.test:8000/html/semantics/forms/the-input-element/required_attribute.html
# [auto-fail] http://web-platform.test:8000/html/semantics/forms/the-input-element/pattern_attribute.html
http://web-platform.test:8000/html/semantics/forms/the-input-element/input-width.html
http://web-platform.test:8000/html/semantics/forms/the-input-element/input-type-button.html
http://web-platform.test:8000/html/semantics/forms/the-input-element/input-labels.html
http://web-platform.test:8000/html/semantics/forms/the-input-element/input-height.html
http://web-platform.test:8000/html/semantics/forms/the-form-element/form-length.html
http://web-platform.test:8000/html/semantics/forms/the-form-element/form-elements-sameobject.html
http://web-platform.test:8000/html/semantics/forms/the-form-element/form-elements-nameditem-02.html
http://web-platform.test:8000/html/semantics/forms/the-form-element/form-elements-matches.html
http://web-platform.test:8000/html/semantics/forms/the-form-element/form-elements-interfaces-01.html
http://web-platform.test:8000/html/semantics/forms/the-form-element/form-action.html
http://web-platform.test:8000/html/semantics/forms/the-button-element/button-labels.html
http://web-platform.test:8000/html/interaction/focus/the-autofocus-attribute/not-on-first-task.html
# [auto-fail] http://web-platform.test:8000/html/semantics/embedded-content/the-area-element/area-shape.html
http://web-platform.test:8000/html/semantics/embedded-content/the-area-element/area-coords.html
http://web-platform.test:8000/html/semantics/embedded-content/the-video-element/video-tabindex.html
http://web-platform.test:8000/html/semantics/embedded-content/the-object-element/object-ignored-in-media-element.html
# [auto-fail] http://web-platform.test:8000/html/semantics/embedded-content/the-object-element/historical.html
http://web-platform.test:8000/html/semantics/embedded-content/the-img-element/not-rendered-dimension-getter.html
http://web-platform.test:8000/html/semantics/embedded-content/the-img-element/nonexistent-image.html
# [auto-fail] http://web-platform.test:8000/html/semantics/embedded-content/the-iframe-element/same_origin_parentage.html
http://web-platform.test:8000/html/semantics/embedded-content/the-iframe-element/move_iframe_in_dom_04.html
http://web-platform.test:8000/html/semantics/embedded-content/the-iframe-element/move_iframe_in_dom_03.html
http://web-platform.test:8000/html/semantics/embedded-content/the-iframe-element/move_iframe_in_dom_02.html
http://web-platform.test:8000/html/semantics/embedded-content/the-iframe-element/move_iframe_in_dom_01.html
http://web-platform.test:8000/html/semantics/embedded-content/the-iframe-element/historical.html
# [auto-fail] http://web-platform.test:8000/html/semantics/embedded-content/the-iframe-element/cross_origin_parentage.sub.html
http://web-platform.test:8000/html/semantics/embedded-content/the-iframe-element/change_parentage.html
http://web-platform.test:8000/html/semantics/embedded-content/the-embed-element/historical.html
http://web-platform.test:8000/html/semantics/embedded-content/the-embed-element/embed-ignored-in-media-element.html
http://web-platform.test:8000/html/semantics/embedded-content/the-canvas-element/type.exists.html
http://web-platform.test:8000/html/semantics/embedded-content/the-canvas-element/toDataURL.png.html
http://web-platform.test:8000/html/semantics/embedded-content/the-canvas-element/toDataURL.nocontext.html
http://web-platform.test:8000/html/semantics/embedded-content/the-canvas-element/toDataURL.default.html
http://web-platform.test:8000/html/semantics/embedded-content/the-canvas-element/toDataURL.arguments.3.html
http://web-platform.test:8000/html/semantics/embedded-content/the-canvas-element/toDataURL.arguments.2.html
http://web-platform.test:8000/html/semantics/embedded-content/the-canvas-element/toDataURL.arguments.1.html
http://web-platform.test:8000/html/semantics/embedded-content/the-canvas-element/size.attributes.style.html
http://web-platform.test:8000/html/semantics/embedded-content/the-canvas-element/fallback.nested.html
http://web-platform.test:8000/html/semantics/embedded-content/the-canvas-element/fallback.multiple.html
http://web-platform.test:8000/html/semantics/embedded-content/the-canvas-element/fallback.basic.html
http://web-platform.test:8000/html/semantics/embedded-content/the-canvas-element/context.unrecognised.unicode.html
http://web-platform.test:8000/html/semantics/embedded-content/the-canvas-element/context.unrecognised.nullsuffix.html
http://web-platform.test:8000/html/semantics/embedded-content/the-canvas-element/context.unrecognised.badsuffix.html
http://web-platform.test:8000/html/semantics/embedded-content/the-canvas-element/context.unrecognised.badname.html
http://web-platform.test:8000/html/semantics/embedded-content/the-canvas-element/context.emptystring.html
http://web-platform.test:8000/html/semantics/embedded-content/the-canvas-element/context.casesensitive.html
http://web-platform.test:8000/html/semantics/embedded-content/the-canvas-element/context.arguments.missing.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/volume_nonfinite.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/video_volume_check.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/track/track-element/vtt-cue-float-precision.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/track/track-element/track-node-add-remove.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/track/track-element/track-load-from-src-readyState.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/track/track-element/track-load-from-element-readyState.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/track/track-element/track-id.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/track/track-element/track-cue-inline.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/track/track-element/track-api-texttracks.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/track/track-element/src-clear-cues.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/src_reflects_attribute_not_source_elements.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/readyState_initial.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/preload_reflects_none_autoplay.html
# [auto-fail] http://web-platform.test:8000/html/semantics/embedded-content/media-elements/playing-the-media-resource/playbackRate.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/offsets-into-the-media-resource/duration.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/networkState_initial.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/loading-the-media-resource/resource-selection-invoke-set-src-in-namespace.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/loading-the-media-resource/resource-selection-invoke-insert-source-in-namespace.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/loading-the-media-resource/resource-selection-invoke-insert-source-in-div.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/loading-the-media-resource/resource-selection-invoke-insert-into-document.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/loading-the-media-resource/resource-selection-invoke-insert-fragment-into-document.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/loading-the-media-resource/resource-selection-invoke-audio-constructor-no-src.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/loading-the-media-resource/resource-selection-candidate-remove-no-listener.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/interfaces/TextTrackList/length.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/interfaces/TextTrackList/getTrackById.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/interfaces/TextTrackCue/track.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/interfaces/TextTrackCue/startTime.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/interfaces/TextTrackCue/onexit.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/interfaces/TextTrackCue/onenter.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/interfaces/TextTrackCue/id.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/interfaces/TextTrackCue/constructor.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/interfaces/TextTrack/oncuechange.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/interfaces/TextTrack/mode.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/interfaces/TextTrack/language.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/interfaces/TextTrack/label.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/interfaces/TextTrack/constants.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/interfaces/HTMLElement/HTMLTrackElement/track.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/interfaces/HTMLElement/HTMLTrackElement/srclang.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/interfaces/HTMLElement/HTMLTrackElement/readyState.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/interfaces/HTMLElement/HTMLTrackElement/label.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/interfaces/HTMLElement/HTMLTrackElement/default.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/interfaces/HTMLElement/HTMLMediaElement/textTracks.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/historical.html
http://web-platform.test:8000/html/semantics/embedded-content/media-elements/audio_volume_check.html
http://web-platform.test:8000/html/semantics/edits/the-ins-element/ins_effect.html
http://web-platform.test:8000/html/semantics/edits/the-del-element/del_effect.html
http://web-platform.test:8000/html/semantics/document-metadata/the-title-element/title.text-03.html
http://web-platform.test:8000/html/semantics/document-metadata/the-style-element/style_non_matching_media.html
http://web-platform.test:8000/html/semantics/document-metadata/the-style-element/style_load_async.html
# [auto-fail] http://web-platform.test:8000/html/semantics/document-metadata/the-style-element/style_events.html
http://web-platform.test:8000/html/semantics/document-metadata/the-style-element/style_disabled.html
http://web-platform.test:8000/html/semantics/document-metadata/the-meta-element/the-lang-attribute-012.html
http://web-platform.test:8000/html/semantics/document-metadata/the-link-element/link-rellist.html
http://web-platform.test:8000/html/semantics/document-metadata/the-link-element/link-load-event.html
http://web-platform.test:8000/html/semantics/document-metadata/the-base-element/base_href_unspecified.html
http://web-platform.test:8000/html/semantics/document-metadata/the-base-element/base_href_empty.html
http://web-platform.test:8000/html/rendering/non-replaced-elements/tables/table-vspace-hspace-s.html
http://web-platform.test:8000/html/rendering/non-replaced-elements/tables/table-vspace-hspace.html
http://web-platform.test:8000/html/rendering/non-replaced-elements/margin-collapsing-quirks/multicol-standards-mode.html
http://web-platform.test:8000/html/rendering/non-replaced-elements/margin-collapsing-quirks/multicol-quirks-mode.html
http://web-platform.test:8000/html/obsolete/requirements-for-implementations/other-elements-attributes-and-apis/script-IDL-event-htmlfor.html
http://web-platform.test:8000/html/obsolete/requirements-for-implementations/other-elements-attributes-and-apis/heading-obsolete-attributes-01.html
http://web-platform.test:8000/html/obsolete/requirements-for-implementations/other-elements-attributes-and-apis/document-color-04.html
http://web-platform.test:8000/html/obsolete/requirements-for-implementations/other-elements-attributes-and-apis/document-color-02.html
http://web-platform.test:8000/html/infrastructure/conformance-requirements/extensibility/foreign.html
http://web-platform.test:8000/html/interaction/focus/focus-management/focus-event-targets-simple.html
# [auto-fail] http://web-platform.test:8000/html/interaction/focus/focus-management/focus-events.html
# [auto-fail] http://web-platform.test:8000/html/editing/editing-0/making-entire-documents-editable-the-designmode-idl-attribute/user-interaction-editing-designMode.html
http://web-platform.test:8000/html/editing/activation/click.html
http://web-platform.test:8000/html/dom/elements/global-attributes/the-lang-attribute-007.html
http://web-platform.test:8000/html/dom/elements/global-attributes/the-lang-attribute-006.html
http://web-platform.test:8000/html/dom/elements/global-attributes/the-lang-attribute-005.html
http://web-platform.test:8000/html/dom/elements/global-attributes/the-lang-attribute-004.html
http://web-platform.test:8000/html/dom/elements/global-attributes/the-lang-attribute-003.html
http://web-platform.test:8000/html/dom/elements/global-attributes/the-lang-attribute-002.html
http://web-platform.test:8000/html/dom/elements/global-attributes/the-lang-attribute-001.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/global-attributes/id-name-specialcase.html
http://web-platform.test:8000/html/dom/elements/global-attributes/id-name.html
http://web-platform.test:8000/html/dom/elements/global-attributes/id-attribute.html
http://web-platform.test:8000/html/dom/elements/global-attributes/dataset-prototype.html
http://web-platform.test:8000/html/dom/elements/global-attributes/dataset-enumeration.html
http://web-platform.test:8000/html/dom/elements/global-attributes/data_unicode_attr.html
http://web-platform.test:8000/html/dom/elements/global-attributes/classlist-nonstring.html
http://web-platform.test:8000/html/dom/elements/elements-in-the-dom/historical.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/014.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/013.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/012.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/011.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/002.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/script_008.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/script_007.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/script_003.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/script_001.html
# [auto-fail] http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/iframe_009.html
# [auto-fail] http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/iframe_008.html
# [auto-fail] http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/iframe_007.html
# [auto-fail] http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/iframe_006.html
# [auto-fail] http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/iframe_004.html
# [auto-fail] http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/iframe_003.html
# [auto-fail] http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/iframe_002.html
# [auto-fail] http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/iframe_001.html
# [auto-fail] http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/document.write-02.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/051.html
# [auto-fail] http://web-platform.test:8000/html/editing/dnd/selection/048.xhtml
# [auto-fail] http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/047.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/044.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/043.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/042.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/040.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/032.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/031.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/030.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/029.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/028.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/027.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/026.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/025.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/024.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/023.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/022.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/021.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/020.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/019.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/006.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/002.html
http://web-platform.test:8000/html/webappapis/dynamic-markup-insertion/document-write/001.html
# [auto-fail] http://web-platform.test:8000/html/dom/documents/resource-metadata-management/document-readyState.html
http://web-platform.test:8000/html/dom/documents/resource-metadata-management/document-compatmode-03.html
http://web-platform.test:8000/html/dom/documents/resource-metadata-management/document-compatmode-02.html
http://web-platform.test:8000/html/dom/documents/resource-metadata-management/document-compatmode-01.html
http://web-platform.test:8000/html/dom/documents/dom-tree-accessors/nameditem-03.html
# [auto-fail] http://web-platform.test:8000/html/dom/documents/dom-tree-accessors/nameditem-01.html
http://web-platform.test:8000/html/dom/documents/dom-tree-accessors/Element.getElementsByClassName-null-undef.html
http://web-platform.test:8000/html/dom/documents/dom-tree-accessors/document.title-08.html
http://web-platform.test:8000/html/dom/documents/dom-tree-accessors/document.title-01.html
http://web-platform.test:8000/html/dom/documents/dom-tree-accessors/document.scripts.html
http://web-platform.test:8000/html/dom/documents/dom-tree-accessors/document.head-01.html
http://web-platform.test:8000/html/dom/documents/dom-tree-accessors/document.getElementsByName/document.getElementsByName-same.html
http://web-platform.test:8000/html/dom/documents/dom-tree-accessors/document.getElementsByName/document.getElementsByName-liveness.html
http://web-platform.test:8000/html/dom/documents/dom-tree-accessors/document.getElementsByName/document.getElementsByName-interface.html
http://web-platform.test:8000/html/dom/documents/dom-tree-accessors/document.getElementsByClassName-same.html
http://web-platform.test:8000/html/dom/documents/dom-tree-accessors/Document.getElementsByClassName-null-undef.html
http://web-platform.test:8000/html/browsers/windows/nested-browsing-contexts/window-top.html
http://web-platform.test:8000/html/browsers/the-window-object/window-aliases.html
http://web-platform.test:8000/html/browsers/the-window-object/accessing-other-browsing-contexts/iterator.html
http://web-platform.test:8000/html/browsers/offline/browser-state/navigator_online_online.https.html
http://web-platform.test:8000/html/browsers/history/the-location-interface/security_location_0.htm
# [auto-fail] http://web-platform.test:8000/html/browsers/history/the-location-interface/location-protocol-setter-with-colon.sub.html
# [auto-fail] http://web-platform.test:8000/html/browsers/history/the-location-interface/location_replace.html
http://web-platform.test:8000/html/browsers/history/the-location-interface/location_reload.html
http://web-platform.test:8000/html/browsers/history/the-location-interface/location_protocol.html
http://web-platform.test:8000/html/browsers/history/the-location-interface/location_port.html
http://web-platform.test:8000/html/browsers/history/the-location-interface/location_pathname.html
http://web-platform.test:8000/html/browsers/history/the-location-interface/location_href.html
http://web-platform.test:8000/html/browsers/history/the-location-interface/location_hostname.html
http://web-platform.test:8000/html/browsers/history/the-location-interface/location_host.html
http://web-platform.test:8000/html/browsers/history/the-location-interface/location_assign_about_blank.html
http://web-platform.test:8000/html/browsers/history/the-history-interface/history_state.html
http://web-platform.test:8000/html/browsers/history/the-history-interface/history_replacestate_nooptionalparam.html
http://web-platform.test:8000/html/browsers/history/the-history-interface/history_replacestate_err.html
http://web-platform.test:8000/html/browsers/history/the-history-interface/history_replacestate.html
http://web-platform.test:8000/html/browsers/history/the-history-interface/history_pushstate_nooptionalparam.html
http://web-platform.test:8000/html/browsers/history/the-history-interface/history_pushstate_err.html
http://web-platform.test:8000/html/browsers/history/the-history-interface/history_pushstate.html
http://web-platform.test:8000/html/browsers/history/the-history-interface/history_go_plus.html
http://web-platform.test:8000/html/browsers/history/the-history-interface/history_go_minus.html
http://web-platform.test:8000/html/browsers/history/the-history-interface/history_forward.html
http://web-platform.test:8000/html/browsers/history/the-history-interface/history_back.html
http://web-platform.test:8000/html/browsers/history/the-history-interface/combination_history_007.html
http://web-platform.test:8000/html/browsers/history/the-history-interface/combination_history_006.html
http://web-platform.test:8000/html/browsers/history/the-history-interface/combination_history_005.html
http://web-platform.test:8000/html/browsers/history/the-history-interface/combination_history_004.html
http://web-platform.test:8000/html/browsers/history/the-history-interface/combination_history_003.html
http://web-platform.test:8000/html/browsers/history/the-history-interface/combination_history_002.html
http://web-platform.test:8000/html/browsers/history/the-history-interface/combination_history_001.html
http://web-platform.test:8000/html/browsers/history/the-history-interface/006.html
http://web-platform.test:8000/html/browsers/browsing-the-web/unloading-documents/unload/003.html
http://web-platform.test:8000/html/browsers/browsing-the-web/unloading-documents/unload/002.html
http://web-platform.test:8000/html/browsers/browsing-the-web/unloading-documents/prompt/003.html
http://web-platform.test:8000/html/browsers/browsing-the-web/unloading-documents/prompt/002.html
http://web-platform.test:8000/html/browsers/browsing-the-web/scroll-to-fragid/scroll-position.html
http://web-platform.test:8000/html/browsers/browsing-the-web/scroll-to-fragid/003.html
http://web-platform.test:8000/html/browsers/browsing-the-web/scroll-to-fragid/002.html
http://web-platform.test:8000/html/browsers/browsing-the-web/scroll-to-fragid/001.html
# [auto-fail] http://web-platform.test:8000/html/browsers/browsing-the-web/navigating-across-documents/source/navigate-child-src-about-blank.html
http://web-platform.test:8000/html/browsers/browsing-the-web/navigating-across-documents/source/navigate-child-function-src.html
http://web-platform.test:8000/html/browsers/browsing-the-web/navigating-across-documents/source/navigate-child-function.html
http://web-platform.test:8000/html/browsers/browsing-the-web/navigating-across-documents/navigation-unload-same-origin-fragment.html
http://web-platform.test:8000/html/browsers/browsing-the-web/navigating-across-documents/empty_fragment.html
# [auto-fail] http://web-platform.test:8000/websockets/binary/002.html
# [auto-fail] http://web-platform.test:8000/websockets/binary/001.html
http://web-platform.test:8000/html/browsers/browsing-the-web/history-traversal/window-name-after-same-origin-sub-frame-navigation.sub.html
http://web-platform.test:8000/html/browsers/browsing-the-web/history-traversal/window-name-after-cross-origin-sub-frame-navigation.sub.html
