// https://notifications.spec.whatwg.org/#service-worker-api

[STARFISH_ENABLE_SERVICE_WORKER, Unimplemented]
dictionary GetNotificationOptions {
  DOMString tag = "";
};

partial interface ServiceWorkerRegistration {
  Promise<void> showNotification(DOMString title, optional NotificationOptions options);
  [Unimplemented] Promise<sequence<Notification>> getNotifications(optional GetNotificationOptions filter);
};

//partial interface ServiceWorkerGlobalScope {
//  attribute EventHandler onnotificationclick;
//  attribute EventHandler onnotificationclose;
//};
