[
  Constructor(ReadableStream stream),
  Exposed=(Window,Worker),
  ConstructorCallWith=ExecutionContext
] interface ReadableStreamDefaultReader {
  Promise<any> read();
  Promise<any> cancel();
  void releaseLock();
  readonly attribute Promise<boolean> closed;
};
