# [auto-fail] http://web-platform.test:8000/html/syntax/parsing/foreign_content_013.html
# [auto-fail] http://web-platform.test:8000/html/syntax/parsing/foreign_content_011.html
# [auto-fail] http://web-platform.test:8000/html/syntax/parsing/foreign_content_010.html
# [auto-fail] http://web-platform.test:8000/html/syntax/parsing/foreign_content_009.html
# [auto-fail] http://web-platform.test:8000/html/syntax/parsing/foreign_content_008.html
# [auto-fail] http://web-platform.test:8000/html/syntax/parsing/foreign_content_006.html
# [auto-fail] http://web-platform.test:8000/html/syntax/parsing/foreign_content_005.html
# [auto-fail] http://web-platform.test:8000/html/semantics/text-level-semantics/the-br-element/br-bidi.html
# [auto-fail] http://web-platform.test:8000/html/semantics/text-level-semantics/the-b-element/b-usage.html
# [auto-fail] http://web-platform.test:8000/html/semantics/text-level-semantics/the-bdo-element/bdo-override.html
# [auto-fail] http://web-platform.test:8000/html/semantics/text-level-semantics/the-bdo-element/bdo-ltr.html
# [auto-fail] http://web-platform.test:8000/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-to-number-following-2.html
# [auto-fail] http://web-platform.test:8000/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-to-letter-preceding-2.html
# [auto-fail] http://web-platform.test:8000/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-to-letter-following-2.html
# [auto-fail] http://web-platform.test:8000/html/semantics/text-level-semantics/the-bdi-element/bdi-neutral-to-another-bdi-2.html
# [auto-fail] http://web-platform.test:8000/html/semantics/grouping-content/the-pre-element/pre-newline-bidi.html
# [auto-fail] http://web-platform.test:8000/html/semantics/grouping-content/the-ol-element/reversed-2.html
# [auto-fail] http://web-platform.test:8000/html/semantics/grouping-content/the-ol-element/reversed-1d.html
# [auto-fail] http://web-platform.test:8000/html/semantics/grouping-content/the-ol-element/reversed-1c.html
# [auto-fail] http://web-platform.test:8000/html/semantics/grouping-content/the-ol-element/reversed-1b.html
# [auto-fail] http://web-platform.test:8000/html/semantics/grouping-content/the-ol-element/reversed-1a.html
# [auto-fail] http://web-platform.test:8000/html/semantics/grouping-content/the-ol-element/grouping-ol-type-reftest-003.html
# [auto-fail] http://web-platform.test:8000/html/semantics/grouping-content/the-ol-element/grouping-ol-type-reftest-002.html
# [auto-fail] http://web-platform.test:8000/html/semantics/grouping-content/the-ol-element/grouping-ol-type-reftest-001.html
# [auto-fail] http://web-platform.test:8000/html/semantics/grouping-content/the-ol-element/grouping-ol-start-reftest-002.html
# [auto-fail] http://web-platform.test:8000/html/semantics/grouping-content/the-ol-element/grouping-ol-start-reftest-001.html
# [auto-fail] http://web-platform.test:8000/html/semantics/forms/the-label-element/iframe-label-attributes.html
# [auto-fail] http://web-platform.test:8000/html/semantics/embedded-content/the-video-element/video_content_text.htm
# [auto-fail] http://web-platform.test:8000/html/semantics/embedded-content/the-img-element/document-base-url.html
# [auto-fail] http://web-platform.test:8000/html/semantics/embedded-content/the-img-element/document-adopt-base-url.html
# [auto-fail] http://web-platform.test:8000/html/semantics/embedded-content/the-embed-element/embed-represent-nothing-03.html
# [auto-fail] http://web-platform.test:8000/html/semantics/embedded-content/the-embed-element/embed-represent-nothing-01.html
# [auto-fail] http://web-platform.test:8000/html/semantics/embedded-content/the-embed-element/embed-iframe.html
# [auto-fail] http://web-platform.test:8000/html/semantics/document-metadata/the-link-element/stylesheet-with-base.html
# [auto-fail] http://web-platform.test:8000/html/semantics/document-metadata/the-link-element/stylesheet-media.html
# [auto-fail] http://web-platform.test:8000/html/semantics/document-metadata/the-link-element/stylesheet-empty-href.html
# [auto-fail] http://web-platform.test:8000/html/semantics/document-metadata/the-link-element/stylesheet-change-href.html
# [auto-fail] http://web-platform.test:8000/html/semantics/document-metadata/the-base-element/example2.html
# [auto-fail] http://web-platform.test:8000/html/rendering/the-css-user-agent-style-sheet-and-presentational-hints/body-bgcolor-attribute-change.html
# [auto-fail] http://web-platform.test:8000/html/rendering/replaced-elements/embedded-content-rendering-rules/canvas_without_context_a.html
# [auto-fail] http://web-platform.test:8000/html/rendering/replaced-elements/attributes-for-embedded-content-and-images/img-dim.html
# [auto-fail] http://web-platform.test:8000/html/rendering/non-replaced-elements/lists/ol-type-unsupported-upper-roman.html
# [auto-fail] http://web-platform.test:8000/html/rendering/non-replaced-elements/lists/ol-type-unsupported-upper-alpha.html
# [auto-fail] http://web-platform.test:8000/html/rendering/non-replaced-elements/lists/ol-type-unsupported-square.html
# [auto-fail] http://web-platform.test:8000/html/rendering/non-replaced-elements/lists/ol-type-unsupported-round.html
# [auto-fail] http://web-platform.test:8000/html/rendering/non-replaced-elements/lists/ol-type-unsupported-none.html
# [auto-fail] http://web-platform.test:8000/html/rendering/non-replaced-elements/lists/ol-type-unsupported-lower-roman.html
# [auto-fail] http://web-platform.test:8000/html/rendering/non-replaced-elements/lists/ol-type-unsupported-lower-alpha.html
# [auto-fail] http://web-platform.test:8000/html/rendering/non-replaced-elements/lists/ol-type-unsupported-invalid.html
# [auto-fail] http://web-platform.test:8000/html/rendering/non-replaced-elements/lists/ol-type-unsupported-disc.html
# [auto-fail] http://web-platform.test:8000/html/rendering/non-replaced-elements/lists/ol-type-unsupported-circle.html
# [auto-fail] http://web-platform.test:8000/html/rendering/non-replaced-elements/lists/ol-type-supported.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/requirements-relating-to-bidirectional-algorithm-formatting-characters/dir-isolation-008c.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/requirements-relating-to-bidirectional-algorithm-formatting-characters/dir-isolation-008a.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/requirements-relating-to-bidirectional-algorithm-formatting-characters/dir-isolation-007c.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/requirements-relating-to-bidirectional-algorithm-formatting-characters/dir-isolation-007a.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/requirements-relating-to-bidirectional-algorithm-formatting-characters/dir-isolation-003c.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/requirements-relating-to-bidirectional-algorithm-formatting-characters/dir-isolation-003a.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/global-attributes/lang-xyzzy.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/global-attributes/dir_auto-pre-N-EN.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/global-attributes/dir_auto-N-L.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/global-attributes/dir_auto-N-EN-L.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/global-attributes/dir_auto-N-EN.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/global-attributes/dir_auto-L.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/global-attributes/dir_auto-isolate.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/global-attributes/dir_auto-EN-L.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/global-attributes/dir_auto-contained-style-L.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/global-attributes/dir_auto-contained-script-L.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/global-attributes/dir_auto-contained-L.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/global-attributes/dir_auto-contained-dir-L.html
# [auto-fail] http://web-platform.test:8000/html/dom/elements/global-attributes/dir_auto-contained-bdi-L.html
