# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/about-blank-replacement.https.html
# [auto-fail:HARNESS_STATUS_2] https://web-platform.test:8443/service-workers/service-worker/activate-event-after-install-state-change.https.html
# [auto-fail:HARNESS_STATUS_2] https://web-platform.test:8443/service-workers/service-worker/activation-after-registration.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/activation.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/active.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/claim-affect-other-registration.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/claim-fetch.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/claim-not-using-registration.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/claim-shared-worker-fetch.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/claim-using-registration.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/claim-with-redirect.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/claim-worker-fetch.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/client-id.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/client-navigate.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/clients-get-client-types.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/clients-get-cross-origin.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/clients-get.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/clients-matchall-client-types.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/clients-matchall-exact-controller.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/clients-matchall.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/clients-matchall-include-uncontrolled.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/clients-matchall-on-evaluation.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/clients-matchall-order.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/controller-on-disconnect.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/controller-on-load.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/controller-on-reload.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/dedicated-worker-service-worker-interception.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/detached-context.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/embed-and-object-are-not-intercepted.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/extendable-event-async-waituntil.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/extendable-event-waituntil.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-canvas-tainting-image-cache.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-canvas-tainting-image.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-canvas-tainting-video-cache.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-canvas-tainting-video.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-canvas-tainting-video-with-range-request.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-cors-exposed-header-names.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-cors-xhr.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-csp.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event-after-navigation-within-page.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event-async-respond-with.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event-is-history-backward-navigation-manual.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event-is-history-forward-navigation-manual.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event-is-reload-iframe-navigation-manual.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event-is-reload-navigation-manual.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event-network-error.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event-redirect.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event-referrer-policy.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event-respond-with-argument.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event-respond-with-body-loaded-in-chunk.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event-respond-with-custom-response.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event-respond-with-partial-stream.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event-respond-with-readable-stream-chunk.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event-respond-with-readable-stream.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event-respond-with-response-body-with-invalid-chunk.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event-respond-with-stops-propagation.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event-throws-after-respond-with.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-event-within-sw.https.html
# [auto-fail:SUBTESTS_FAILED] https://web-platform.test:8443/service-workers/service-worker/fetch-event-within-sw-manual.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-frame-resource.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-header-visibility.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-mixed-content-to-inscope.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-mixed-content-to-outscope.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-request-css-base-url.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-request-css-cross-origin.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-request-css-images.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-request-fallback.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-request-no-freshness-headers.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-request-redirect.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-request-resources.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-request-xhr.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-request-xhr-sync.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-request-xhr-sync-on-worker.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-response-taint.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-response-xhr.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/fetch-waits-for-activate.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/getregistration.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/getregistrations.https.html
# [auto-fail:SUBTESTS_FAILED] https://web-platform.test:8443/service-workers/service-worker/http-to-https-redirect-and-register.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/immutable-prototype-serviceworker.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/import-scripts-redirect.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/import-scripts-resource-map.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/import-scripts-updated-flag.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/indexeddb.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/install-event-type.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/installing.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/invalid-blobtype.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/invalid-header.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/iso-latin1-header.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/local-url-inherit-controller.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/mime-sniffing.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/multi-globals/current/current.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/multi-globals/incumbent/incumbent.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/multi-globals/relevant/relevant.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/multi-globals/url-parsing.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/multipart-image.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/multiple-register.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/multiple-update.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/navigate-window.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/navigation-preload/broken-chunked-encoding.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/navigation-preload/chunked-encoding.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/navigation-preload/empty-preload-response-body.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/navigation-preload/get-state.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/navigation-preload/redirect.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/navigation-preload/request-headers.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/navigation-preload/resource-timing.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/navigation-redirect-body.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/navigation-redirect.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/navigation-redirect-to-http.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/navigation-timing.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/onactivate-script-error.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/oninstall-script-error.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/opaque-response-preloaded.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/performance-timeline.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/postmessage-blob-url.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/postmessage-from-waiting-serviceworker.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/postmessage.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/postmessage-msgport-to-client.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/postmessage-to-client.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/ready.https.window.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/redirected-response.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/referer.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/referrer-policy-header.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/register-closed-window.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/register-default-scope.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/register-same-scope-different-script-url.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/register-wait-forever-in-install-worker.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/registration-basic.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/registration-end-to-end.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/registration-events.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/registration-iframe.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/registration-mime-types.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/registration-scope.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/registration-script.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/registration-script-url.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/registration-security-error.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/registration-service-worker-attributes.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/registration-updateviacache.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/rejections.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/request-end-to-end.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/resource-timing-cross-origin.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/respond-with-body-accessed-response.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/sandboxed-iframe-fetch-event.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/sandboxed-iframe-navigator-serviceworker.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/Service-Worker-Allowed-header.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/service-worker-csp-connect.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/service-worker-csp-default.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/service-worker-csp-script.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/ServiceWorkerGlobalScope/close.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/ServiceWorkerGlobalScope/extendable-message-event-constructor.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/ServiceWorkerGlobalScope/extendable-message-event.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/ServiceWorkerGlobalScope/postmessage.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/ServiceWorkerGlobalScope/registration-attribute.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/ServiceWorkerGlobalScope/service-worker-error-event.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/ServiceWorkerGlobalScope/unregister.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/ServiceWorkerGlobalScope/update.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/service-worker-header.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/serviceworker-message-event-historical.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/serviceworkerobject-scripturl.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/skip-waiting.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/skip-waiting-installed.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/skip-waiting-using-registration.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/skip-waiting-without-client.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/skip-waiting-without-using-registration.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/state.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/svg-target-reftest.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/synced-state.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/uncontrolled-page.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/unregister-controller.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/unregister.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/unregister-then-register.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/unregister-then-register-new-script.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/update-after-navigation-fetch-event.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/update-after-oneday.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/update-bytecheck.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/update.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/update-recovery.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/update-result.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/waiting.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/websocket.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/websocket-in-service-worker.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/webvtt-cross-origin.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/windowclient-navigate.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/worker-client-id.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/worker-in-sandboxed-iframe-by-csp-fetch-event.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/worker-interception.https.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/service-worker/worker-interception-redirect.https.html
# [auto-fail:SUBTESTS_FAILED] https://web-platform.test:8443/service-workers/cache-storage/common.https.window.html
# [auto-fail:HARNESS_STATUS_1] https://web-platform.test:8443/service-workers/cache-storage/cache-abort.https.any.html
# [auto-fail:HARNESS_STATUS_1] https://web-platform.test:8443/service-workers/cache-storage/cache-add.https.any.html
# [auto-fail:HARNESS_STATUS_1] https://web-platform.test:8443/service-workers/cache-storage/cache-delete.https.any.html
# [auto-fail:TIMEOUT] https://web-platform.test:8443/service-workers/cache-storage/cache-keys-attributes-for-service-worker.https.html
# [auto-fail:HARNESS_STATUS_1] https://web-platform.test:8443/service-workers/cache-storage/cache-keys.https.any.html
# [auto-fail:HARNESS_STATUS_1] https://web-platform.test:8443/service-workers/cache-storage/cache-matchAll.https.any.html
# [auto-fail:HARNESS_STATUS_1] https://web-platform.test:8443/service-workers/cache-storage/cache-match.https.any.html
# [auto-fail:HARNESS_STATUS_1] https://web-platform.test:8443/service-workers/cache-storage/cache-put.https.any.html
# [auto-fail:SUBTESTS_FAILED] https://web-platform.test:8443/service-workers/cache-storage/cache-storage-keys.https.any.html
# [auto-fail:HARNESS_STATUS_1] https://web-platform.test:8443/service-workers/cache-storage/cache-storage-match.https.any.html
# [auto-fail:SUBTESTS_FAILED] https://web-platform.test:8443/service-workers/cache-storage/credentials.https.html
# [auto-fail:SUBTESTS_FAILED] https://web-platform.test:8443/service-workers/cache-storage/sandboxed-iframes.https.html
