// https://w3c.github.io/media-source/#mediasource

enum ReadyState {
    "closed",
    "open",
    "ended"
};

enum EndOfStreamError {
    "network",
    "decode"
};

[STARFISH_ENABLE_MULTIMEDIA,
 Constructor,
 ConstructorCallWith=Document]
interface MediaSource : EventTarget {
  readonly attribute SourceBufferList sourceBuffers;
  readonly attribute SourceBufferList activeSourceBuffers;
  readonly attribute ReadyState readyState;
  [RaisesException=Setter] attribute unrestricted double duration;
  [Unimplemented] attribute EventHandler onsourceopen;
  [Unimplemented] attribute EventHandler onsourceended;
  [Unimplemented] attribute EventHandler onsourceclose;
  [RaisesException] SourceBuffer addSourceBuffer(DOMString type);
  [RaisesException] void removeSourceBuffer(SourceBuffer sourceBuffer);
  [RaisesException] void endOfStream(optional EndOfStreamError error);
  [Unimplemented, RaisesException] void setLiveSeekableRange(double start, double end);
  [Unimplemented, RaisesException] void clearLiveSeekableRange();
  static boolean isTypeSupported(DOMString type);
};