// https://w3c.github.io/ServiceWorker/#serviceworkercontainer
[STARFISH_ENABLE_SERVICE_WORKER, Exposed=(Window,Worker)]
dictionary RegistrationOptions {
  USVString scope;
  WorkerType type = "classic";
  ServiceWorkerUpdateViaCache updateViaCache = "imports";
};
