/*
 * Copyright (c) 2019-present Samsung Electronics Co., Ltd
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
 *  USA
 */

// https://w3c.github.io/webrtc-pc/#rtcpeerconnection-interface

[STARFISH_ENABLE_WEBRTC]
enum RTCSignalingState {
  "stable",
  "have-local-offer",
  "have-remote-offer",
  "have-local-pranswer",
  "have-remote-pranswer",
  "closed"
};

[STARFISH_ENABLE_WEBRTC]
enum RTCIceGatheringState {
  "new",
  "gathering",
  "complete"
};

[STARFISH_ENABLE_WEBRTC]
enum RTCPeerConnectionState {
  "closed",
  "failed",
  "disconnected",
  "new",
  "connecting",
  "connected"
};

[STARFISH_ENABLE_WEBRTC]
enum RTCIceConnectionState {
  "closed",
  "failed",
  "disconnected",
  "new",
  "checking",
  "completed",
  "connected"
};

[STARFISH_ENABLE_WEBRTC]
dictionary RTCOfferAnswerOptions {
  boolean voiceActivityDetection = true;
};

[STARFISH_ENABLE_WEBRTC]
dictionary RTCOfferOptions : RTCOfferAnswerOptions {
  boolean iceRestart = false;
};

[STARFISH_ENABLE_WEBRTC]
dictionary RTCAnswerOptions : RTCOfferAnswerOptions {
};

[STARFISH_ENABLE_WEBRTC]
partial dictionary RTCOfferOptions {
  boolean offerToReceiveAudio;
  boolean offerToReceiveVideo;
};

[ STARFISH_ENABLE_WEBRTC,
  Constructor (optional RTCConfiguration configuration),
  ConstructorCallWith=ExecutionContext,
  RaisesException=Constructor,
  Exposed=Window ]
interface RTCPeerConnection : EventTarget {
  [RaisesException] Promise<RTCSessionDescriptionInit> createOffer (optional RTCOfferOptions options);
  [RaisesException] Promise<RTCSessionDescriptionInit> createAnswer (optional RTCAnswerOptions options);
  [RaisesException] Promise<void> setLocalDescription (RTCSessionDescriptionInit description);
  readonly attribute RTCSessionDescription? localDescription;
  readonly attribute RTCSessionDescription? currentLocalDescription;
  readonly attribute RTCSessionDescription? pendingLocalDescription;
  [RaisesException] Promise<void> setRemoteDescription (RTCSessionDescriptionInit description);
  readonly attribute RTCSessionDescription? remoteDescription;
  readonly attribute RTCSessionDescription? currentRemoteDescription;
  readonly attribute RTCSessionDescription? pendingRemoteDescription;
  [RaisesException] Promise<void> addIceCandidate (optional RTCIceCandidateInit candidate);
  readonly attribute RTCSignalingState signalingState;
  readonly attribute RTCIceGatheringState iceGatheringState;
  readonly attribute RTCIceConnectionState iceConnectionState;
  readonly attribute RTCPeerConnectionState connectionState;
  // readonly attribute boolean? canTrickleIceCandidates; // Not supported by WebRTC
  static sequence<RTCIceServer> getDefaultIceServers ();
  RTCConfiguration getConfiguration ();
  [RaisesException] void setConfiguration (RTCConfiguration configuration);
  void close ();
  attribute EventHandler onnegotiationneeded;
  attribute EventHandler onicecandidate;
  attribute EventHandler onicecandidateerror;
  attribute EventHandler onsignalingstatechange;
  attribute EventHandler oniceconnectionstatechange;
  attribute EventHandler onicegatheringstatechange;
  attribute EventHandler onconnectionstatechange;
};

[STARFISH_ENABLE_WEBRTC]
partial interface RTCPeerConnection {
  [Unimplemented] Promise<void> createOffer (RTCSessionDescriptionCallback successCallback, RTCPeerConnectionErrorCallback failureCallback, optional RTCOfferOptions options);
  [Unimplemented] Promise<void> setLocalDescription (RTCSessionDescriptionInit description, VoidFunction successCallback, RTCPeerConnectionErrorCallback failureCallback);
  [Unimplemented] Promise<void> createAnswer (RTCSessionDescriptionCallback successCallback, RTCPeerConnectionErrorCallback failureCallback);
  [Unimplemented] Promise<void> setRemoteDescription (RTCSessionDescriptionInit description, VoidFunction successCallback, RTCPeerConnectionErrorCallback failureCallback);
  [Unimplemented] Promise<void> addIceCandidate (RTCIceCandidateInit candidate, VoidFunction successCallback, RTCPeerConnectionErrorCallback failureCallback);
};

[STARFISH_ENABLE_WEBRTC]
partial interface RTCPeerConnection {
  readonly attribute RTCSctpTransport? sctp;
  // USVString -> DOMString
  [RaisesException] RTCDataChannel createDataChannel (DOMString label, optional RTCDataChannelInit dataChannelDict);
  attribute EventHandler ondatachannel;
};

[STARFISH_ENABLE_WEBRTC]
partial interface RTCPeerConnection {
  [Unimplemented] static Promise<RTCCertificate> generateCertificate (AlgorithmIdentifier keygenAlgorithm);
};

[STARFISH_ENABLE_WEBRTC]
partial interface RTCPeerConnection {
  sequence<RTCRtpSender> getSenders ();
  sequence<RTCRtpReceiver> getReceivers ();
  sequence<RTCRtpTransceiver> getTransceivers ();
  [RaisesException] RTCRtpSender addTrack (MediaStreamTrack track, MediaStream... streams);
  [RaisesException] void removeTrack (RTCRtpSender sender);
  // Change (MediaStreamTrack or DOMString) -> (DOMString or MediaStreamTrack) to workaround the binding generator bugs
  [RaisesException] RTCRtpTransceiver addTransceiver ((DOMString or MediaStreamTrack) trackOrKind, optional RTCRtpTransceiverInit init);
  attribute EventHandler ontrack;
};

[STARFISH_ENABLE_WEBRTC]
partial interface RTCPeerConnection {
  Promise<RTCStatsReport> getStats(optional MediaStreamTrack? selector = null);
//  attribute EventHandler onstatsended;
};
