/*
 * Copyright (c) 2019-present Samsung Electronics Co., Ltd
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
 *  USA
 */

// https://w3c.github.io/webrtc-pc/#dom-rtcrtpparameters
[ STARFISH_ENABLE_WEBRTC ]
dictionary RTCRtpParameters {
  //required sequence<RTCRtpHeaderExtensionParameters> headerExtensions;
  //required RTCRtcpParameters rtcp;
  //required sequence<RTCRtpCodecParameters> codecs;
};

// https://w3c.github.io/webrtc-pc/#dom-rtcrtpsendparameters
[ STARFISH_ENABLE_WEBRTC ]
dictionary RTCRtpSendParameters : RTCRtpParameters {
  required DOMString transactionId;
  //required sequence<RTCRtpEncodingParameters> encodings;
  //RTCDegradationPreference degradationPreference = "balanced";
  //RTCPriorityType priority = "low";
};

[ STARFISH_ENABLE_WEBRTC,
  ConstructorCallWith=ExecutionContext,
  Exposed=Window ]
interface RTCRtpSender {
  readonly attribute MediaStreamTrack? track;
  //readonly attribute RTCDtlsTransport? transport;
  //readonly attribute RTCDtlsTransport? rtcpTransport; // Not supported by WebRTC
  //static RTCRtpCapabilities? getCapabilities(DOMString kind); // Not supported by WebRTC
  //Promise<void> setParameters(RTCRtpSendParameters parameters);
  //RTCRtpSendParameters getParameters();
  [RaisesException] Promise<void> replaceTrack(MediaStreamTrack? withTrack);
  //void setStreams(MediaStream... streams);
  //Promise<RTCStatsReport> getStats(); // Not supported by WebRTC
};
