name: Build Starfish

on:
  pull_request:

jobs:

  build_tizen_50:
    runs-on: [ self-hosted,code-2xlarge ]
    container:
      image: art.sec.samsung.net/circleci-docker/docker-gbs-base:actions
      options: --user root --privileged
    strategy:
      matrix:
        mode: [wearable, tv, mobile]

    # Set reasonable timeout value.
    timeout-minutes: 60

    steps:
      - name: Checkout source..
        uses: CODE-Actions/checkout@v2
        with:
          submodules: false

      - name: Reset Submodule
        run: git submodule foreach --recursive git reset --hard

      - name: Download a gbs.conf
        run: wget http://10.113.113.204:7000/gbs_confs/gbs.conf

      - name: Build wearable
        if: matrix.mode == 'wearable'
        run: gbs -c ./gbs.conf build -A armv7l -P profile.50std --define 'build_profile wearable'

      - name: Build tv
        if: matrix.mode == 'tv'
        run: gbs -c ./gbs.conf build -A armv7l -P profile.50std --define 'build_profile tv'

      - name: Build mobile
        if: matrix.mode == 'mobile'
        run: gbs -c ./gbs.conf build -A armv7l -P profile.50std --define 'build_profile mobile'

      - name: Build headless
        if: matrix.mode == 'headless'
        run: gbs -c ./gbs.conf build -A x86_64 -P profile.50tizenheadless  

