image: 10.113.64.54:5000/starfish/starfish:170103
build:
  stage: build
  tags:
    - main_build
  before_script:
    - git submodule deinit -f .
    - git submodule init
    - git submodule update
    - ./build_third_party.sh
  script:
    - make x64.exe.release -j
  artifacts:
    paths:
      - StarFish
      - out/x64/exe/release/StarFish
      - third_party/libav/out/linux/x64/release/libavformat/libavformat.so.56
      - third_party/libav/out/linux/x64/release/libavcodec/libavcodec.so.56
      - third_party/libav/out/linux/x64/release/libavutil/libavutil.so.54
      #- out/

# run tests using the binary built before

test_internal_test_fast1:
  stage: test
  before_script:
    - git submodule deinit -f .
    - git submodule init
    - git submodule update
    - make install_pixel_test_dep
    - make internal_test_gitlab_prerequisite div=4
  script:
    - xvfb-run -s "-screen 0 1920x1080x24" -a make internal_test_fast | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
    - xvfb-run -s "-screen 0 1920x1080x24" -a make internal_test_part1 | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
  dependencies:
  - build

test_internal_test2:
  stage: test
  before_script:
    - git submodule deinit -f .
    - git submodule init
    - git submodule update
    - make install_pixel_test_dep
    - make internal_test_gitlab_prerequisite div=4
  script:
    - xvfb-run -s "-screen 0 1920x1080x24" -a make internal_test_part2 | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
  dependencies:
  - build

test_internal_test3:
  stage: test
  before_script:
    - git submodule deinit -f .
    - git submodule init
    - git submodule update
    - make install_pixel_test_dep
    - make internal_test_gitlab_prerequisite div=4
  script:
    - xvfb-run -s "-screen 0 1920x1080x24" -a make internal_test_part3 | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
  dependencies:
  - build

test_internal_test4:
  stage: test
  before_script:
    - git submodule deinit -f .
    - git submodule init
    - git submodule update
    - make install_pixel_test_dep
    - make internal_test_gitlab_prerequisite div=4
  script:
    - xvfb-run -s "-screen 0 1920x1080x24" -a make internal_test_part4 | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
  dependencies:
  - build

test_regression_test_blink:
  stage: test
  before_script:
    - git submodule deinit -f .
    - git submodule init
    - git submodule update
    - make install_pixel_test_dep
  script:
    - xvfb-run -s "-screen 0 1920x1080x24" -a make regression_test_blink_fast_html | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
    - xvfb-run -s "-screen 0 1920x1080x24" -a make regression_test_blink_fast_css | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
    - xvfb-run -s "-screen 0 1920x1080x24" -a make regression_test_blink_fast_etc | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
  dependencies:
  - build

test_regression_test_webkit:
  stage: test
  before_script:
    - git submodule deinit -f .
    - git submodule init
    - git submodule update
    - make install_pixel_test_dep
  script:
    - xvfb-run -s "-screen 0 1920x1080x24" -a make regression_test_webkit_fast_html | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
    - xvfb-run -s "-screen 0 1920x1080x24" -a make regression_test_webkit_fast_css | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
    - xvfb-run -s "-screen 0 1920x1080x24" -a make regression_test_webkit_fast_etc | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
    - xvfb-run -s "-screen 0 1920x1080x24" -a make regression_test_webkit_fast_dom | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
  dependencies:
  - build

test_regression_test_wpt:
  stage: test
  before_script:
    - git submodule deinit -f .
    - git submodule init
    - git submodule update
    - make install_pixel_test_dep
  script:
    - xvfb-run -s "-screen 0 1920x1080x24" -a make regression_test_wpt_dom | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
    - xvfb-run -s "-screen 0 1920x1080x24" -a make regression_test_wpt_html | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
    - xvfb-run -s "-screen 0 1920x1080x24" -a make regression_test_wpt_dom_events | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
    - xvfb-run -s "-screen 0 1920x1080x24" -a make regression_test_wpt_progress_events | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
    - xvfb-run -s "-screen 0 1920x1080x24" -a make regression_test_wpt_page_visibility | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
    - xvfb-run -s "-screen 0 1920x1080x24" -a make regression_test_wpt_xhr | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
  dependencies:
  - build

test_regression_test_dom:
  stage: test
  before_script:
    - git submodule deinit -f .
    - git submodule init
    - git submodule update
  script:
    - xvfb-run -s "-screen 0 1920x1080x24" -a make regression_test_dom_conformance_test | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
    - xvfb-run -s "-screen 0 1920x1080x24" -a make regression_test_webkit_dom_conformance_test | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
    - xvfb-run -s "-screen 0 1920x1080x24" -a make regression_test_blink_dom_conformance_test | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
    - xvfb-run -s "-screen 0 1920x1080x24" -a make regression_test_gecko_dom_conformance_test | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
  dependencies:
  - build

test_regression_test_css:
  stage: test
  before_script:
    - git submodule deinit -f .
    - git submodule init
    - git submodule update
    - make install_pixel_test_dep
  script:
    - xvfb-run -s "-screen 0 1920x1080x24" -a make pixel_test_css_all | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
  dependencies:
  - build

test_regression_test_font:
  stage: test
  before_script:
    - git submodule deinit -f .
    - git submodule init
    - git submodule update
    - make install_pixel_test_dep
  script:
    - xvfb-run -s "-screen 0 1920x1080x24" -a make font_dependent_test_css | tee prepush_test_result; if cat prepush_test_result |grep 'FAIL' > /dev/null; then  exit 1; fi
  dependencies:
  - build
