[STARFISH_WEBWORKER_HOST, Global=(ServiceWorker)]
interface Internal {
  // https://w3c.github.io/ServiceWorker/#cache-interface
  [NewObject] Promise<undefined> put(any self, Request request, Response response);
  [NewObject] Promise<undefined> put(Request request, Response response);

  // https://w3c.github.io/ServiceWorker/#cachestorage-interface
  [NewObject] Promise<any> open(DOMString cacheName);
  [NewObject] Promise<sequence<DOMString>> cache_storage_keys();
};
