[general]
profile = profile.t70amber
 
[profile.t70amber]
repos = repo.70amber-base, repo.70amber
 
[repo.70amber-base]
url=http://download.tizen.org/snapshots/TIZEN/Tizen-7.0/Tizen-7.0-Base/latest/repos/standard/packages/
 
[repo.70amber]
url=http://10.198.76.11:8080/snapshots/ROBOT/Tizen-7.0/MAIN2023-Amber-Unified/latest/repos/eng/packages/
