[general]
profile = profile.botfit

[profile.botfit]
repos = repo.65base, repo.65pro
buildroot = ~/GBS-ROOT/t65pro

[repo.65base]
url=http://10.198.76.11:8080/tizen_base/tizen-6.5-base_20240329.041322/repos/standard/packages/

[repo.65pro]
url=http://10.198.76.11:8080/snapshots/ROBOT/Tizen-6.5/Tizen-6.5-EX1-PRO/latest/repos/eng/packages/
