[general]
# Default profile is profile.t65gems
# Use latest snapshots. It does not guarantee the success of the build.
# But in most areas, there will be no problem
profile = profile.t65gems

# Build success is guaranteed with the repo set by the project manager.
# profile = profile.t65gems_ref

# Global config user/passwd
# If authentication is required, fill in the values below (user/passwd).
# Be careful not to expose the created value to git or to the outside.
# user =
# passwd =

############## Tizen 6.5 GEMS ##############
[profile.t65gems]
repos = repo.65base, repo.65gems
buildroot = ~/GBS-ROOT/t65gems

[profile.t65gems_ref]
repos = repo.65base, repo.65gems_ref
buildroot = ~/GBS-ROOT/t65gems_ref

[repo.65base]
#url=http://10.113.245.23/download/public_mirror/tizen/6.5-base/latest/repos/standard/packages/
# url=http://download.tizen.org/snapshots/TIZEN/Tizen-6.5/Tizen-6.5-Base/latest/repos/standard/packages/
url=http://10.198.76.11:8080/tizen_base/tizen-6.5-base_20240329.041322/repos/standard/packages/
# http://10.113.245.23/download is aka SPIN download server
# need SPIN account
# fill in the values below (user/passwd). or fill in the Global user/passwd
# Be careful not to expose the created value to git or to the outside.
# user =
# passwd =

[repo.65gems]
# latest repo
# It does not guarantee the success of the build.
# But in most areas, there will be no problem.
#url=http://10.198.76.11:8080/snapshots/ROBOT/Tizen-6.5/Tizen-6.5-EX1/latest/repos/standard/packages/
url=http://10.198.76.11:8080/snapshots/ROBOT/Tizen-6.5/Tizen-6.5-EX1/latest/repos/eng/packages/

[repo.65gems_ref]
# Build success is guaranteed with the repo set by the project manager.
#url=http://10.198.76.11:8080/snapshots/ROBOT/Tizen-6.5/Tizen-6.5-EX1/reference/repos/standard/packages/
url=http://10.198.76.11:8080/snapshots/ROBOT/Tizen-6.5/Tizen-6.5-EX1/reference/repos/eng/packages/
