// https://url.spec.whatwg.org/#url
// NOTE Using DOMString instead of USVString

[Constructor(DOMString url, optional DOMString base),
 ConstructorCallWith=Window,
 Exposed=(Window,Worker)]
interface URL {
  stringifier attribute DOMString href;
  readonly attribute DOMString origin;
  attribute DOMString protocol;
  attribute DOMString username;
  attribute DOMString password;
  attribute DOMString host;
  attribute DOMString hostname;
  attribute DOMString port;
  attribute DOMString pathname;
  attribute DOMString search;
  [Unimplemented, SameObject] readonly attribute URLSearchParams searchParams;
  attribute DOMString hash;
  [Unimplemented] DOMString toJSON();


  // partial
  // https://w3c.github.io/FileAPI/#creating-revoking
  static DOMString createObjectURL(Blob blob);
  [STARFISH_ENABLE_MULTIMEDIA] static DOMString createObjectURL(MediaSource mediaSource);
  [CallWith=Document] static void revokeObjectURL(DOMString url);
};
