// https://w3c.github.io/performance-timeline/#dom-performanceentry
[Exposed=(Window,Worker)]
interface PerformanceEntry {
    [Unimplemented] readonly attribute unsigned long long id;
    [Unimplemented] readonly attribute DOMString name;
    [Unimplemented] readonly attribute DOMString entryType;
    [Unimplemented] readonly attribute DOMHighResTimeStamp startTime;
    [Unimplemented] readonly attribute DOMHighResTimeStamp duration;
    [Unimplemented] readonly attribute unsigned long long navigationId;
    // [Default] object toJSON();
};
