// https://dom.spec.whatwg.org/#interface-characterdata

[Exposed=Window]
interface CharacterData : Node {
  [TreatNullAs=EmptyString] attribute DOMString data;
  [Custom=Getter] readonly attribute unsigned long length;
  [RaisesException] DOMString substringData(unsigned long offset, unsigned long count);
  [RaisesException] void appendData(DOMString data);
  [RaisesException] void insertData(unsigned long offset, DOMString data);
  [RaisesException] void deleteData(unsigned long offset, unsigned long count);
  [RaisesException] void replaceData(unsigned long offset, unsigned long count, DOMString data);
};


CharacterData implements ChildNode;
CharacterData implements NonDocumentTypeChildNode;
