// https://html.spec.whatwg.org/multipage/webappapis.html#documentandelementeventhandlers

[PartialInterface,
 NoInterfaceObject]
interface DocumentAndElementEventHandlers {
  [Unimplemented] attribute EventHandler oncopy;
  [Unimplemented] attribute EventHandler oncut;
  [Unimplemented] attribute EventHandler onpaste;
};