// https://html.spec.whatwg.org/multipage/interaction.html#elementcontenteditable

[PartialInterface,
 NoInterfaceObject]
interface ElementContentEditable {
  [RaisesException, CEReactions] attribute DOMString contentEditable;
  [Unimplemented] readonly attribute boolean isContentEditable;
};