// https://drafts.csswg.org/cssom/#elementcssinlinestyle

[PartialInterface,
 NoInterfaceObject]
interface ElementCSSInlineStyle {
  [Rename=inlineStyle, PutForwards=cssText, SameObject] attribute CSSStyleDeclaration style;
};