// REF1. https://dom.spec.whatwg.org/#interface-element
// REF2. https://dom.spec.whatwg.org/#parentnode
// REF3. https://dom.spec.whatwg.org/#nondocumenttypechildnode
// REF4. https://dom.spec.whatwg.org/#childnode
// REF5. https://dom.spec.whatwg.org/#slotable
// REF6. https://w3c.github.io/DOM-Parsing/#extensions-to-the-element-interface
// REF7. https://drafts.csswg.org/cssom-view/#extension-to-the-element-interface


[Exposed=Window]
interface Element : Node {
  // [REF1]--------------------------------------------------------------
  readonly attribute DOMString? namespaceURI;
  readonly attribute DOMString? prefix;
  readonly attribute DOMString localName;
  readonly attribute DOMString tagName;

  [CEReactions] attribute DOMString id;
  [CEReactions] attribute DOMString className;
  [CEReactions, SameObject, PutForwards=value] readonly attribute DOMTokenList classList;
  [Unimplemented, CEReactions, Unscopable] attribute DOMString slot;

  boolean hasAttributes();
  [SameObject] readonly attribute NamedNodeMap attributes;
  sequence<DOMString> getAttributeNames();
  DOMString? getAttribute(DOMString qualifiedName);
  DOMString? getAttributeNS(DOMString? namespace, DOMString localName);
  [CEReactions, RaisesException] void setAttribute(DOMString qualifiedName, DOMString value);
  [CEReactions, RaisesException] void setAttributeNS(DOMString? namespace, DOMString qualifiedName, DOMString value);
  [CEReactions] void removeAttribute(DOMString qualifiedName);
  [CEReactions] void removeAttributeNS(DOMString? namespace, DOMString localName);
  boolean hasAttribute(DOMString qualifiedName);
  boolean hasAttributeNS(DOMString? namespace, DOMString localName);

  Attr? getAttributeNode(DOMString qualifiedName);
  Attr? getAttributeNodeNS(DOMString? namespace, DOMString localName);
  [CEReactions, RaisesException] Attr? setAttributeNode(Attr attr);
  [CEReactions, RaisesException] Attr? setAttributeNodeNS(Attr attr);
  [CEReactions, RaisesException] Attr removeAttributeNode(Attr attr);

  [Unimplemented] ShadowRoot attachShadow(ShadowRootInit init);
  [Unimplemented] readonly attribute ShadowRoot? shadowRoot;

  [Unimplemented] Element? closest(DOMString selectors);
  [RaisesException] boolean matches(DOMString selectors);

  HTMLCollection getElementsByTagName(DOMString qualifiedName);
  HTMLCollection getElementsByTagNameNS(DOMString? namespace, DOMString localName);
  HTMLCollection getElementsByClassName(DOMString classNames);

  [CEReactions, RaisesException] Node? insertAdjacentElement(DOMString where, Element element); // historical
  [RaisesException] void insertAdjacentText(DOMString where, DOMString data); // historical


  // [REF6]--------------------------------------------------------------
  [CEReactions, TreatNullAs=EmptyString] attribute DOMString innerHTML;
  [CEReactions, RaisesException, TreatNullAs=EmptyString] attribute DOMString outerHTML;
  [CEReactions, RaisesException] void insertAdjacentHTML(DOMString position, DOMString text);


  // [REF7]--------------------------------------------------------------
  // NOTE using DOMRectList instead of sequence<DOMRect>
  // sequence<DOMRect> getClientRects();
  DOMRectList getClientRects();
  [NewObject] DOMRect getBoundingClientRect();
  void scrollIntoView();
  // void scrollIntoView((boolean or object) arg);
  // TODO implement options version of scrollIntoView
  void scrollIntoView(boolean arg);
  [Unimplemented] void scroll(optional ScrollToOptions options);
  [Unimplemented] void scroll(unrestricted double x, unrestricted double y);
  [Unimplemented] void scrollTo(optional ScrollToOptions options);
  [Unimplemented] void scrollTo(unrestricted double x, unrestricted double y);
  [Unimplemented] void scrollBy(optional ScrollToOptions options);
  [Unimplemented] void scrollBy(unrestricted double x, unrestricted double y);
  attribute unrestricted double scrollTop;
  attribute unrestricted double scrollLeft;
  readonly attribute long scrollWidth;
  readonly attribute long scrollHeight;
  readonly attribute long clientTop;
  readonly attribute long clientLeft;
  readonly attribute long clientWidth;
  readonly attribute long clientHeight;
};

Element implements ParentNode;
Element implements NonDocumentTypeChildNode;
Element implements ChildNode;
Element implements Slotable;
