// https://drafts.csswg.org/cssom/#elementcssinlinestyle

[PartialInterface,
 NoInterfaceObject]
interface ElementCSSInlineStyle {
  // FIXME cssText is not implemented so we implement here using Custom extended attribute
  // [SameObject, PutForwards=cssText] readonly attribute CSSStyleDeclaration style;
  [Custom=(Getter, Setter)] attribute CSSStyleDeclaration style;
};