// https://html.spec.whatwg.org/multipage/webappapis.html#globaleventhandlers
[PartialInterface,
 NoInterfaceObject]
interface GlobalEventHandlers {
  attribute EventHandler onabort;
  [Unimplemented] attribute EventHandler onauxclick;
  attribute EventHandler onblur;
  [Unimplemented] attribute EventHandler oncancel;
  [STARFISH_ENABLE_MULTIMEDIA] attribute EventHandler oncanplay;
  [STARFISH_ENABLE_MULTIMEDIA] attribute EventHandler oncanplaythrough;
  attribute EventHandler onchange;
  attribute EventHandler onclick;
  [Unimplemented] attribute EventHandler onclose;
  [Unimplemented] attribute EventHandler oncontextmenu;
  [Unimplemented] attribute EventHandler oncuechange;
  [Unimplemented] attribute EventHandler ondblclick;
  [Unimplemented] attribute EventHandler ondrag;
  [Unimplemented] attribute EventHandler ondragend;
  [Unimplemented] attribute EventHandler ondragenter;
  [Unimplemented] attribute EventHandler ondragexit;
  [Unimplemented] attribute EventHandler ondragleave;
  [Unimplemented] attribute EventHandler ondragover;
  [Unimplemented] attribute EventHandler ondragstart;
  [Unimplemented] attribute EventHandler ondrop;
  [STARFISH_ENABLE_MULTIMEDIA] attribute EventHandler ondurationchange;
  [STARFISH_ENABLE_MULTIMEDIA] attribute EventHandler onemptied;
  [STARFISH_ENABLE_MULTIMEDIA] attribute EventHandler onended;
  // FIXME: onerror should be type of OnErrorEventHandler
  attribute EventHandler onerror;
  attribute EventHandler onfocus;
  attribute EventHandler oninput;
  [Unimplemented] attribute EventHandler oninvalid;
  attribute EventHandler onkeydown;
  attribute EventHandler onkeypress;
  attribute EventHandler onkeyup;
  attribute EventHandler onload;
  [STARFISH_ENABLE_MULTIMEDIA] attribute EventHandler onloadeddata;
  [STARFISH_ENABLE_MULTIMEDIA] attribute EventHandler onloadedmetadata;
  [Unimplemented] attribute EventHandler onloadend;
  attribute EventHandler onloadstart;
  attribute EventHandler onmousedown;
  [Unimplemented, LenientThis] attribute EventHandler onmouseenter;
  [Unimplemented, LenientThis] attribute EventHandler onmouseleave;
  attribute EventHandler onmousemove;
  attribute EventHandler onmouseout;
  attribute EventHandler onmouseover;
  attribute EventHandler onmouseup;
  [Unimplemented] attribute EventHandler onwheel;
  [STARFISH_ENABLE_MULTIMEDIA] attribute EventHandler onpause;
  [STARFISH_ENABLE_MULTIMEDIA] attribute EventHandler onplay;
  [STARFISH_ENABLE_MULTIMEDIA] attribute EventHandler onplaying;
  attribute EventHandler onprogress;
  [STARFISH_ENABLE_MULTIMEDIA] attribute EventHandler onratechange;
  [Unimplemented] attribute EventHandler onreset;
  attribute EventHandler onresize;
  [Unimplemented] attribute EventHandler onscroll;
  [STARFISH_ENABLE_MULTIMEDIA] attribute EventHandler onseeked;
  [STARFISH_ENABLE_MULTIMEDIA] attribute EventHandler onseeking;
  [Unimplemented] attribute EventHandler onselect;
  [Unimplemented] attribute EventHandler onshow;
  [STARFISH_ENABLE_MULTIMEDIA] attribute EventHandler onstalled;
  attribute EventHandler onsubmit;
  [STARFISH_ENABLE_MULTIMEDIA] attribute EventHandler onsuspend;
  [STARFISH_ENABLE_MULTIMEDIA] attribute EventHandler ontimeupdate;
  [Unimplemented] attribute EventHandler ontoggle;
  [STARFISH_ENABLE_MULTIMEDIA] attribute EventHandler onvolumechange;
  [STARFISH_ENABLE_MULTIMEDIA] attribute EventHandler onwaiting;
};
