
[HTMLConstructor]
interface HTMLElement : Element {
  // https://html.spec.whatwg.org/multipage/dom.html#htmlelement
  // metadata attributes
  [Unimplemented, CEReactions] attribute DOMString title;
  [Unimplemented, CEReactions] attribute DOMString lang;
  [Unimplemented, CEReactions] attribute boolean translate;
  [CEReactions] attribute DOMString dir;
  [Unimplemented, SameObject] readonly attribute DOMStringMap dataset;

  // user interaction
  [Unimplemented, CEReactions] attribute boolean hidden;
  void click();
  [Unimplemented, CEReactions] attribute long tabIndex;
  void focus();
  [Unimplemented] void blur();
  [Unimplemented, CEReactions] attribute DOMString accessKey;
  [Unimplemented] readonly attribute DOMString accessKeyLabel;
  [Unimplemented, CEReactions] attribute boolean draggable;
  [Unimplemented, CEReactions] attribute HTMLMenuElement? contextMenu;
  [Unimplemented, CEReactions] attribute boolean spellcheck;
  [Unimplemented] void forceSpellCheck();

  [CEReactions, TreatNullAs=EmptyString] attribute DOMString innerText;

  // https://drafts.csswg.org/cssom-view/#extensions-to-the-htmlelement-interface
  [Unimplemented] readonly attribute Element? offsetParent;
  [Unimplemented] readonly attribute long offsetTop;
  [Unimplemented] readonly attribute long offsetLeft;
  readonly attribute long offsetWidth;
  readonly attribute long offsetHeight;
};

HTMLElement implements GlobalEventHandlers;
HTMLElement implements DocumentAndElementEventHandlers;
HTMLElement implements ElementContentEditable;
HTMLElement implements ElementCSSInlineStyle;
