// https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element
// NOTE Using DOMString instead of USVString

[
  HTMLConstructor,
  ConstructorCallWith=Document,
  NamedConstructor=Image(optional unsigned long width, optional unsigned long height)]
interface HTMLImageElement : HTMLElement {
  [Unimplemented, CEReactions] attribute DOMString alt;
  [CEReactions] attribute DOMString src;
  [Unimplemented, CEReactions] attribute DOMString srcset;
  [Unimplemented, CEReactions] attribute DOMString sizes;
  [Unimplemented, CEReactions] attribute DOMString? crossOrigin;
  [CEReactions, Reflect] attribute DOMString useMap;
  [Unimplemented, CEReactions] attribute boolean isMap;
  [CEReactions] attribute unsigned long width;
  [CEReactions] attribute unsigned long height;
  [Unimplemented] readonly attribute unsigned long naturalWidth;
  [Unimplemented] readonly attribute unsigned long naturalHeight;
  [Unimplemented] readonly attribute boolean complete;
  [Unimplemented] readonly attribute DOMString currentSrc;
  [CEReactions] attribute DOMString referrerPolicy;

  // https://www.w3.org/TR/REC-DOM-Level-1/level-one-html.html#ID-17701901
  // Initial definition
  [Unimplemented] attribute DOMString lowSrc;
  [Rename=nameAttr] attribute DOMString name;
  [Unimplemented] attribute DOMString align;
  [Unimplemented] attribute DOMString hspace;
  [Unimplemented] attribute DOMString longDesc;
  [Unimplemented] attribute DOMString vspace;
};
