// https://html.spec.whatwg.org/multipage/semantics.html#meta
[HTMLConstructor]
interface HTMLMetaElement : HTMLElement {
  [CEReactions, Rename=domName] attribute DOMString name;
  [CEReactions] attribute DOMString httpEquiv;
  [CEReactions] attribute DOMString content;
};