// https://html.spec.whatwg.org/#the-textarea-element

[HTMLConstructor]
interface HTMLTextAreaElement : HTMLElement {
    [Unimplemented, CEReactions] attribute DOMString autocomplete;
    [CEReactions, Reflect] attribute boolean autofocus;
    [Unimplemented, CEReactions] attribute unsigned long cols;
    [Unimplemented, CEReactions] attribute DOMString dirName;
    [Unimplemented, CEReactions] attribute boolean disabled;
    readonly attribute HTMLFormElement? form;
    [Unimplemented, CEReactions] attribute DOMString inputMode;
    [Unimplemented, CEReactions] attribute long maxLength;
    [Unimplemented, CEReactions] attribute long minLength;
    [Unimplemented, CEReactions] attribute DOMString name;
    [Unimplemented, CEReactions] attribute DOMString placeholder;
    [Unimplemented, CEReactions] attribute boolean readOnly;
    [Unimplemented, CEReactions] attribute boolean required;
    [Unimplemented, CEReactions] attribute unsigned long rows;
    [Unimplemented, CEReactions] attribute DOMString wrap;

    [Unimplemented] readonly attribute DOMString type;
    [Unimplemented, CEReactions] attribute DOMString defaultValue;
    [TreatNullAs=EmptyString, CEReactions] attribute DOMString value;
    [Unimplemented] readonly attribute unsigned long textLength;

    [Unimplemented] readonly attribute boolean willValidate;
    [Unimplemented] readonly attribute ValidityState validity;
    [Unimplemented] readonly attribute DOMString validationMessage;
    [Unimplemented] boolean checkValidity();
    [Unimplemented] boolean reportValidity();
    [Unimplemented] void setCustomValidity(DOMString error);

    [Unimplemented] readonly attribute NodeList labels;

    [Unimplemented] void select();
    [Unimplemented] attribute unsigned long selectionStart;
    [Unimplemented] attribute unsigned long selectionEnd;
    [Unimplemented] attribute DOMString selectionDirection;
    [Unimplemented] void setRangeText(DOMString replacement);
    [Unimplemented] void setRangeText(DOMString replacement, unsigned long start, unsigned long end, optional SelectionMode selectionMode = "preserve");
    [Unimplemented] void setSelectionRange(unsigned long start, unsigned long end, optional DOMString direction);
};
