// https://html.spec.whatwg.org/#forms

[HTMLConstructor]
interface HTMLInputElement : HTMLElement {
    [Unimplemented, CEReactions] attribute DOMString accept;
    [Unimplemented, CEReactions] attribute DOMString alt;
    [Unimplemented, CEReactions] attribute DOMString autocomplete;
    [CEReactions] attribute boolean autofocus;
    [CEReactions] attribute boolean defaultChecked;
    attribute boolean checked;
    [Unimplemented, CEReactions] attribute DOMString dirName;
    [CEReactions] attribute boolean disabled;
    readonly attribute HTMLFormElement? form;
    [Unimplemented] readonly attribute FileList? files;
    [CEReactions] attribute USVString formAction;
    [CEReactions] attribute DOMString formEnctype;
    [CEReactions] attribute DOMString formMethod;
    [Unimplemented, CEReactions] attribute boolean formNoValidate;
    [CEReactions] attribute DOMString formTarget;
    [Unimplemented, CEReactions] attribute unsigned long height;
    [Unimplemented] attribute boolean indeterminate;
    [Unimplemented, CEReactions] attribute DOMString inputMode;
    [Unimplemented] readonly attribute HTMLElement? list;
    [CEReactions] attribute DOMString max;
    [RaisesException=Setter, CEReactions] attribute long maxLength;
    [CEReactions] attribute DOMString min;
    [Unimplemented, CEReactions] attribute long minLength;
    [CEReactions] attribute boolean multiple;
    [CEReactions, Rename=domName] attribute DOMString name;
    [Unimplemented, CEReactions] attribute DOMString pattern;
    [CEReactions] attribute DOMString placeholder;
    [Unimplemented, CEReactions] attribute boolean readOnly;
    [CEReactions] attribute boolean required;
    // FIXME: later size should be implemented RaisesException=Setter
    [CEReactions, Custom=Setter] attribute unsigned long size;
    [Unimplemented, CEReactions] attribute USVString src;
    [CEReactions] attribute DOMString step;
    [CEReactions] attribute DOMString type;
    [CEReactions] attribute DOMString defaultValue;
    [TreatNullAs=EmptyString, CEReactions] attribute DOMString value;
    [Unimplemented] attribute object? valueAsDate;
    [Unimplemented] attribute unrestricted double valueAsNumber;
    [Unimplemented, CEReactions] attribute unsigned long width;

    [Unimplemented] void stepUp(optional long n = 1);
    [Unimplemented] void stepDown(optional long n = 1);

    [Unimplemented] readonly attribute boolean willValidate;
    [Unimplemented] readonly attribute ValidityState validity;
    [Unimplemented] readonly attribute DOMString validationMessage;
    [Unimplemented] boolean checkValidity();
    [Unimplemented] boolean reportValidity();
    [Unimplemented] void setCustomValidity(DOMString error);

    [Unimplemented] readonly attribute NodeList? labels;

    [Unimplemented] void select();
    [Unimplemented] attribute unsigned long? selectionStart;
    [Unimplemented] attribute unsigned long? selectionEnd;
    [Unimplemented] attribute DOMString? selectionDirection;
    [Unimplemented] void setRangeText(DOMString replacement);
    [Unimplemented] void setRangeText(DOMString replacement, unsigned long start, unsigned long end, optional SelectionMode selectionMode = "preserve");
    [Unimplemented] void setSelectionRange(unsigned long start, unsigned long end, optional DOMString direction);

    // also has obsolete members
};
