// https://html.spec.whatwg.org/multipage/semantics.html#the-body-element

[HTMLConstructor]
interface HTMLBodyElement : HTMLElement {
  // The onblur, onerror, onfocus, onload, onresize, and onscroll event handlers of the Window object, exposed on the body element, replace the generic event handlers with the same names normally supported by HTML elements.
  [Unimplemented] attribute EventHandler onblur;
  [Unimplemented] attribute EventHandler onerror;
  [Unimplemented] attribute EventHandler onfocus;
  attribute EventHandler onload;
  [Unimplemented] attribute EventHandler onresize;
  [Unimplemented] attribute EventHandler onscroll;
};

HTMLBodyElement implements WindowEventHandlers;

