// https://html.spec.whatwg.org/#the-iframe-element

interface HTMLIFrameElement : HTMLElement {
    [CEReactions, Reflect, URL] attribute DOMString src;
    [Unimplemented, CEReactions, Reflect] attribute DOMString srcdoc;
    [Unimplemented, CEReactions, Reflect] attribute DOMString name;
    [Unimplemented, CEReactions, PutForwards=value] readonly attribute DOMTokenList sandbox;
    // Note: The seamless attribute was once supported, but was removed.
    [Unimplemented, CEReactions, Reflect] attribute boolean allowFullscreen;
    [CEReactions, Reflect] attribute DOMString width;
    [CEReactions, Reflect] attribute DOMString height;

    [Unimplemented, CheckSecurity=ReturnValue] readonly attribute Document? contentDocument;
    readonly attribute Window? contentWindow;
//    [Unimplemented, CheckSecurity=ReturnValue, RaisesException] Document? getSVGDocument();
//    [Unimplemented, CEReactions, Reflect, ReflectOnly=("","no-referrer","origin","no-referrer-when-downgrade","origin-when-cross-origin","unsafe-url"), ReflectMissing="", ReflectInvalid=""] attribute DOMString referrerPolicy;
    // https://w3c.github.io/webappsec-csp/embedded/#dom-htmliframeelement-csp
    [Unimplemented, RuntimeEnabled=EmbedderCSPEnforcement, CEReactions, Reflect] attribute DOMString csp;

    // Feature Policy allow attribute
    // https://wicg.github.io/feature-policy/
    [Unimplemented, RuntimeEnabled=FeaturePolicy, CEReactions, PutForwards=value] readonly attribute DOMTokenList allow;
    // obsolete members
    // https://html.spec.whatwg.org/#HTMLIFrameElement-partial
    [Unimplemented, CEReactions, Reflect] attribute DOMString align;
    [Unimplemented, CEReactions, Reflect] attribute DOMString scrolling;
    [Unimplemented, CEReactions, Reflect] attribute DOMString frameBorder;
    [Unimplemented, CEReactions, Reflect, URL] attribute DOMString longDesc;

    [Unimplemented, CEReactions, Reflect, TreatNullAs=EmptyString] attribute DOMString marginHeight;
    [Unimplemented, CEReactions, Reflect, TreatNullAs=EmptyString] attribute DOMString marginWidth;
};
