// https://html.spec.whatwg.org/#htmltablesectionelement

[HTMLConstructor]
interface HTMLTableSectionElement : HTMLElement {
  [SameObject] readonly attribute HTMLCollection rows;
  [CEReactions, RaisesException] HTMLElement insertRow(optional long index = -1);
  [CEReactions, RaisesException] void deleteRow(long index);

  // also has obsolete members
  // https://html.spec.whatwg.org/#HTMLTableSectionElement-partial
  [CEReactions, Reflect] attribute DOMString align;
  [CEReactions] attribute DOMString ch;
  [CEReactions, Reflect=charoff] attribute DOMString chOff;
  [CEReactions, Reflect] attribute DOMString vAlign;
};
