// https://html.spec.whatwg.org/#the-select-element

[HTMLConstructor]
interface HTMLSelectElement : HTMLElement {
    [Unimplemented, CEReactions] attribute DOMString autocomplete;
    [Unimplemented, CEReactions] attribute boolean autofocus;
    [CEReactions] attribute boolean disabled;
    readonly attribute HTMLFormElement? form;
    [Unimplemented, CEReactions] attribute boolean multiple;
    [CEReactions,Rename=domName] attribute DOMString name;
    [Unimplemented, CEReactions] attribute boolean required;
    [Unimplemented, CEReactions] attribute unsigned long size;

    readonly attribute DOMString type;

    [SameObject] readonly attribute HTMLOptionsCollection options;
    [Unimplemented, CEReactions] attribute unsigned long length;
    [Unimplemented] getter Element? item(unsigned long index);
    [Unimplemented] HTMLOptionElement? namedItem(DOMString name);
    [Unimplemented, CEReactions] void add((HTMLOptionElement or HTMLOptGroupElement) element, optional (HTMLElement or long)? before = null);
    [Unimplemented, CEReactions] void remove(); // ChildNode overload
    [Unimplemented, CEReactions] void remove(long index);
    [Unimplemented, CEReactions] setter void (unsigned long index, HTMLOptionElement? option);

    [SameObject] readonly attribute HTMLCollection selectedOptions;
    attribute long selectedIndex;
    attribute DOMString value;

    [Unimplemented] readonly attribute boolean willValidate;
    [Unimplemented] readonly attribute ValidityState validity;
    [Unimplemented] readonly attribute DOMString validationMessage;
    [Unimplemented] boolean checkValidity();
    [Unimplemented] boolean reportValidity();
    [Unimplemented] void setCustomValidity(DOMString error);

    [Unimplemented] readonly attribute NodeList labels;
};
