// https://html.spec.whatwg.org/multipage/semantics.html#the-a-element
// NOTE Using DOMString instead of USVString

[HTMLConstructor]
interface HTMLAnchorElement : HTMLElement {
  [CEReactions] attribute DOMString target;
  [Unimplemented, CEReactions] attribute DOMString download;
  [Unimplemented, CEReactions] attribute DOMString ping;
  [CEReactions, Reflect] attribute DOMString rel;
  [SameObject, PutForwards=value] readonly attribute DOMTokenList relList;
  [CEReactions, Reflect] attribute DOMString hreflang;
  [CEReactions, Reflect] attribute DOMString type;

  [CEReactions, Rename=textContent] attribute DOMString? text;

  [CEReactions] attribute DOMString referrerPolicy;

  // obsolete members
  // https://html.spec.whatwg.org/#HTMLAnchorElement-partial
  [CEReactions, Reflect] attribute DOMString coords;
  [CEReactions, Reflect] attribute DOMString charset;
  [CEReactions, Reflect] attribute DOMString name;
  [CEReactions, Reflect] attribute DOMString rev;
  [CEReactions, Reflect] attribute DOMString shape;
};

HTMLAnchorElement implements HTMLHyperlinkElementUtils;
