// https://html.spec.whatwg.org/multipage/semantics.html#the-html-element
[HTMLConstructor]
interface HTMLHtmlElement : HTMLElement {
  // https://html.spec.whatwg.org/#HTMLHtmlElement-partial
  [CEReactions, Reflect] attribute DOMString version;
};