// https://html.spec.whatwg.org/#the-select-element

[HTMLConstructor]
interface HTMLSelectElement : HTMLElement {
    /*
    [Unimplemented, CEReactions] attribute DOMString autocomplete;
    [Unimplemented, CEReactions] attribute boolean autofocus;
    [Unimplemented, CEReactions] attribute boolean disabled;
    [Unimplemented] readonly attribute HTMLFormElement? form;
    [Unimplemented, CEReactions] attribute boolean multiple;
    [Unimplemented, CEReactions] attribute DOMString name;
    [Unimplemented, CEReactions] attribute boolean required;
    [Unimplemented, CEReactions] attribute unsigned long size;

    [Unimplemented] readonly attribute DOMString type;

    [Unimplemented, SameObject] readonly attribute HTMLOptionsCollection options;
    [Unimplemented, CEReactions] attribute unsigned long length;
    [Unimplemented] getter Element? item(unsigned long index);
    [Unimplemented] HTMLOptionElement? namedItem(DOMString name);
    [Unimplemented, CEReactions] void add((HTMLOptionElement or HTMLOptGroupElement) element, optional (HTMLElement or long)? before = null);
    [Unimplemented, CEReactions] void remove(); // ChildNode overload
    [Unimplemented, CEReactions] void remove(long index);
    [Unimplemented, CEReactions] setter void (unsigned long index, HTMLOptionElement? option);

    [Unimplemented, SameObject] readonly attribute HTMLCollection selectedOptions;
    [Unimplemented] attribute long selectedIndex;
    [Unimplemented] attribute DOMString value;

    [Unimplemented] readonly attribute boolean willValidate;
    [Unimplemented] readonly attribute ValidityState validity;
    [Unimplemented] readonly attribute DOMString validationMessage;
    [Unimplemented] boolean checkValidity();
    [Unimplemented] boolean reportValidity();
    [Unimplemented] void setCustomValidity(DOMString error);

    [Unimplemented] readonly attribute NodeList labels;
    */
};
