// https://html.spec.whatwg.org/multipage/semantics.html#the-pre-element
[HTMLConstructor]
interface HTMLPreElement : HTMLElement {
    // https://html.spec.whatwg.org/#HTMLPreElement-partial
    // [CEReactions, Reflect] attribute long width;
};