// https://html.spec.whatwg.org/#htmlolistelement

[HTMLConstructor]
interface HTMLOListElement : HTMLElement {
  // also has obsolete members
  [CEReactions, Reflect] attribute boolean compact;

  // https://html.spec.whatwg.org/#HTMLOListElement-partial
  [CEReactions] attribute boolean reversed;
  [CEReactions] attribute long start;
  [CEReactions] attribute DOMString type;
};
