// https://html.spec.whatwg.org/#htmllielement

[HTMLConstructor]
interface HTMLLIElement : HTMLElement {
  [CEReactions] attribute long value;

  // also has obsolete members
  [Unimplemented, CEReactions] attribute DOMString type;
};
