// https://html.spec.whatwg.org/#forms

[HTMLConstructor]
interface HTMLLabelElement : HTMLElement {
    readonly attribute HTMLFormElement? form;
    [CEReactions, Rename=forAttr] attribute DOMString htmlFor;
    readonly attribute HTMLElement? control;
};

