// https://html.spec.whatwg.org/#htmlfontelement

[HTMLConstructor]
interface HTMLFontElement : HTMLElement {
    [CEReactions] attribute DOMString color;
    [Unimplemented, CEReactions] attribute DOMString face;
    [Unimplemented, CEReactions] attribute DOMString size; 
};
