// https://html.spec.whatwg.org/multipage/semantics.html#the-link-element
// NOTE Using DOMString instead of USVString

[HTMLConstructor]
interface HTMLLinkElement : HTMLElement {
  [CEReactions] attribute DOMString href;
  [Unimplemented, CEReactions] attribute DOMString? crossOrigin;
  [CEReactions, Reflect] attribute DOMString rel;
  [Unimplemented, CEReactions] attribute RequestDestination as; // (default "")
  [SameObject, PutForwards=value] readonly attribute DOMTokenList relList;
  [CEReactions] attribute DOMString media;
  [Unimplemented, CEReactions] attribute DOMString integrity;
  [CEReactions, Reflect] attribute DOMString hreflang;
  [CEReactions] attribute DOMString type;
  [Unimplemented, SameObject, PutForwards=value] readonly attribute DOMTokenList sizes;
  [CEReactions] attribute DOMString referrerPolicy;
  [Unimplemented, CEReactions] attribute DOMString scope;
  [Unimplemented, CEReactions] attribute WorkerType workerType;
  [Unimplemented, CEReactions] attribute boolean useCache;

  // https://html.spec.whatwg.org/#HTMLLinkElement-partial
  [CEReactions, Reflect] attribute DOMString charset;
  [CEReactions, Reflect] attribute DOMString rev;
  [CEReactions, Reflect] attribute DOMString target;
};

HTMLLinkElement implements LinkStyle;
