// https://html.spec.whatwg.org/multipage/semantics.html#the-br-element

[HTMLConstructor]
interface HTMLBRElement : HTMLElement {
    // https://html.spec.whatwg.org/#HTMLBRElement-partial
    [CEReactions, Reflect] attribute DOMString clear;
};
