// https://html.spec.whatwg.org/multipage/scripting.html#the-script-element
// NOTE Using DOMString instead of USVString

[HTMLConstructor]
interface HTMLScriptElement : HTMLElement {
  [CEReactions] attribute DOMString src;
  [CEReactions] attribute DOMString type;
  [CEReactions, Reflect] attribute boolean noModule;
  [CEReactions] attribute DOMString charset;
  [CEReactions] attribute boolean async;
  [CEReactions] attribute boolean defer;
  [Unimplemented, CEReactions] attribute DOMString? crossOrigin;
  [CEReactions] attribute DOMString text;

  // obsolete members
  // https://html.spec.whatwg.org/#HTMLScriptElement-partial
  [CEReactions, Reflect] attribute DOMString event;
  [CEReactions, Reflect=for] attribute DOMString htmlFor;

  // Subresource Integrity
  // https://w3c.github.io/webappsec-subresource-integrity/#HTMLScriptElement
  [Unimplemented, CEReactions, Reflect] attribute DOMString integrity;
};
