// https://html.spec.whatwg.org/#htmltablerowelement

[HTMLConstructor]
interface HTMLTableRowElement : HTMLElement {
  readonly attribute long rowIndex;
  readonly attribute long sectionRowIndex;
  [SameObject] readonly attribute HTMLCollection cells;
  [CEReactions, RaisesException] HTMLTableCellElement insertCell(optional long index = -1);
  [CEReactions, RaisesException] void deleteCell(long index);

  // also has obsolete members
  // https://html.spec.whatwg.org/#HTMLTableRowElement-partial
  [CEReactions, Reflect] attribute DOMString align;
  [CEReactions] attribute DOMString ch;
  [CEReactions, Reflect=charoff] attribute DOMString chOff;
  [CEReactions, Reflect] attribute DOMString vAlign;

  [CEReactions, TreatNullAs=EmptyString, Reflect] attribute DOMString bgColor;
};
