// https://html.spec.whatwg.org/multipage/semantics.html#the-style-element

[HTMLConstructor]
interface HTMLStyleElement : HTMLElement {
  [Measure] attribute boolean disabled;
  [CEReactions, Reflect] attribute DOMString media;
  [CEReactions, Reflect] attribute DOMString type;

};

HTMLStyleElement implements LinkStyle;
