// https://html.spec.whatwg.org/#htmlvideoelement

[STARFISH_ENABLE_MULTIMEDIA, HTMLConstructor]
interface HTMLVideoElement : HTMLMediaElement {
  [CEReactions] attribute unsigned long width;
  [CEReactions] attribute unsigned long height;
  readonly attribute unsigned long videoWidth;
  readonly attribute unsigned long videoHeight;
  [CEReactions] attribute USVString poster;
  [Unimplemented, CEReactions] attribute boolean playsInline;
};