// https://html.spec.whatwg.org/#htmltablecaptionelement

interface HTMLTableCaptionElement : HTMLElement {
  // also has obsolete members
  // https://html.spec.whatwg.org/#HTMLTableCaptionElement-partial
  [CEReactions, Reflect] attribute DOMString align;
};
