// https://www.w3.org/TR/DOM-Level-2-HTML/html.html#ID-26809268
interface HTMLDocument : Document {
  // NOTE Disable `Document` inheritable properties
  // attribute DOMString title;
  // readonly attribute DOMString referrer;
  // readonly attribute DOMString domain;
  // readonly attribute DOMString URL;
  // attribute HTMLElement body;
  // readonly attribute HTMLCollection images;
  [Unimplemented] readonly attribute HTMLCollection applets;
  // readonly attribute HTMLCollection links;
  // readonly attribute HTMLCollection forms;
  [Unimplemented] readonly attribute HTMLCollection anchors;
  // attribute DOMString cookie;
                                        // raises(DOMException) on setting

  // void open();
  // void close();
  // void write(DOMString text);
  // void writeln(DOMString text);
  // NodeList getElementsByName(DOMString elementName);
};