// https://html.spec.whatwg.org/#the-iframe-element

interface HTMLIFrameElement : HTMLElement {
    [CEReactions] attribute DOMString src;
    [Unimplemented, CEReactions] attribute DOMString srcdoc;
    [CEReactions, Rename=nameAttr] attribute DOMString name;
    [Unimplemented, CEReactions, PutForwards=value] readonly attribute DOMTokenList sandbox;
    // Note: The seamless attribute was once supported, but was removed.
    [Unimplemented, CEReactions] attribute boolean allowFullscreen;
    [CEReactions] attribute DOMString width;
    [CEReactions] attribute DOMString height;

    readonly attribute Document? contentDocument;
    readonly attribute Window? contentWindow;
//    [Unimplemented, RaisesException] Document? getSVGDocument();
//    [Unimplemented, CEReactions] attribute DOMString referrerPolicy;
    // https://w3c.github.io/webappsec-csp/embedded/#dom-htmliframeelement-csp
    [Unimplemented, RuntimeEnabled=EmbedderCSPEnforcement, CEReactions, Reflect] attribute DOMString csp;

    // Feature Policy allow attribute
    // https://wicg.github.io/feature-policy/
    [Unimplemented, RuntimeEnabled=FeaturePolicy, CEReactions, PutForwards=value] readonly attribute DOMTokenList allow;
    // obsolete members
    // https://html.spec.whatwg.org/#HTMLIFrameElement-partial
    [Unimplemented, CEReactions] attribute DOMString align;
    [CEReactions] attribute DOMString scrolling;
    [Unimplemented, CEReactions] attribute DOMString frameBorder;
    [Unimplemented, CEReactions] attribute DOMString longDesc;

    [Unimplemented, CEReactions, TreatNullAs=EmptyString] attribute DOMString marginHeight;
    [Unimplemented, CEReactions, TreatNullAs=EmptyString] attribute DOMString marginWidth;
};
