// https://html.spec.whatwg.org/#htmlulistelement

[HTMLConstructor]
interface HTMLUListElement : HTMLElement {
  // also has obsolete members

  // https://html.spec.whatwg.org/#HTMLUListElement-partial
  [CEReactions, Reflect] attribute boolean compact;
  [CEReactions] attribute DOMString type;
};
