// https://html.spec.whatwg.org/#forms
// NOTE Using NotEnumerable at getter instead of LegacyUnenumerableNamedProperties at interface

[OverrideBuiltins, LegacyUnenumerableNamedProperties, HTMLConstructor]
interface HTMLFormElement : HTMLElement {
    [Unimplemented, CEReactions] attribute DOMString acceptCharset;
    [CEReactions] attribute USVString action;
    [Unimplemented, CEReactions] attribute DOMString autocomplete;
    [CEReactions] attribute DOMString enctype;
    [Unimplemented, CEReactions] attribute DOMString encoding;
    [CEReactions] attribute DOMString method;
    [CEReactions, Rename=domName] attribute DOMString name;
    [Unimplemented, CEReactions] attribute boolean noValidate;
    [CEReactions] attribute DOMString target;

    [SameObject] readonly attribute HTMLFormControlsCollection elements;
    readonly attribute unsigned long length;
    getter Element (unsigned long index);
    // [Unimplemented] getter (RadioNodeList or Element) (DOMString name);
    [NotEnumerable] getter Element (DOMString name);

    void submit();
    [Unimplemented, CEReactions] void reset();
    [Unimplemented] boolean checkValidity();
    [Unimplemented] boolean reportValidity();
};

