// https://html.spec.whatwg.org/#htmltablecellelement

[HTMLConstructor]
interface HTMLTableCellElement : HTMLElement {
  [CEReactions] attribute unsigned long colSpan;
  [CEReactions] attribute unsigned long rowSpan;
  [Unimplemented, CEReactions] attribute DOMString headers;
  [Unimplemented] readonly attribute long cellIndex;

  [Unimplemented, CEReactions] attribute DOMString scope; // only conforming for th elements
  [Unimplemented, CEReactions] attribute DOMString abbr;  // only conforming for th elements

  // also has obsolete members
  // https://html.spec.whatwg.org/#HTMLTableCellElement-partial
  [CEReactions, Reflect] attribute DOMString align;
  [CEReactions] attribute DOMString ch;
  [CEReactions, Reflect=charoff] attribute DOMString chOff;
  [CEReactions, Reflect] attribute DOMString vAlign;

  [CEReactions, TreatNullAs=EmptyString, Reflect] attribute DOMString bgColor;
};
