// https://html.spec.whatwg.org/#the-table-element

[HTMLConstructor]
interface HTMLTableElement : HTMLElement {
  [CEReactions, RaisesException=Setter] attribute HTMLTableCaptionElement? caption;
  [CEReactions] HTMLTableCaptionElement createCaption();
  [CEReactions] void deleteCaption();

  [CEReactions, RaisesException=Setter] attribute HTMLTableSectionElement? tHead;
  [CEReactions] HTMLTableSectionElement createTHead();
  [CEReactions] void deleteTHead();

  [CEReactions, RaisesException=Setter] attribute HTMLTableSectionElement? tFoot;
  [CEReactions] HTMLTableSectionElement createTFoot();
  [CEReactions] void deleteTFoot();

  [SameObject] readonly attribute HTMLCollection tBodies;
  [CEReactions] HTMLTableSectionElement createTBody();

  [SameObject] readonly attribute HTMLCollection rows;
  [CEReactions, RaisesException] HTMLTableRowElement insertRow(optional long index = -1);
  [CEReactions, RaisesException] void deleteRow(long index);

  // also has obsolete members
  // https://html.spec.whatwg.org/#HTMLTableElement-partial
  [CEReactions, Reflect] attribute DOMString align;
  [Unimplemented, CEReactions, Reflect] attribute DOMString border;
  [Unimplemented, CEReactions] attribute DOMString frame;
  [Unimplemented, CEReactions] attribute DOMString rules;
  [Unimplemented, CEReactions] attribute DOMString summary;
  [CEReactions, Reflect] attribute DOMString width;

  [CEReactions, TreatNullAs=EmptyString, Reflect] attribute DOMString bgColor;
  [Unimplemented, CEReactions, TreatNullAs=EmptyString] attribute DOMString cellPadding;
  [Unimplemented, CEReactions, TreatNullAs=EmptyString] attribute DOMString cellSpacing;
};
