// https://html.spec.whatwg.org/#htmloptgroupelement

[Exposed=Window,
 HTMLConstructor]
 interface HTMLOptGroupElement : HTMLElement {
     [CEReactions] attribute boolean disabled;
     [Unimplemented, CEReactions] attribute DOMString label;
 };

