// https://html.spec.whatwg.org/#htmltablecolelement

[HTMLConstructor]
interface HTMLTableColElement : HTMLElement {
  [CEReactions] attribute unsigned long span;

  // also has obsolete members
  [CEReactions, Reflect] attribute DOMString align;
  [CEReactions] attribute DOMString ch;
  [CEReactions, Reflect=charoff] attribute DOMString chOff;
  [CEReactions, Reflect] attribute DOMString vAlign;
  [CEReactions, Reflect] attribute DOMString width;
};
