// https://html.spec.whatwg.org/multipage/links.html#api-for-a-and-area-elements

[PartialInterface,
 NoInterfaceObject]
interface HTMLHyperlinkElementUtils {
  [CEReactions] attribute USVString href;
  [Unimplemented] readonly attribute USVString origin;
  [CEReactions] attribute USVString protocol;
  [Unimplemented, CEReactions] attribute USVString username;
  [Unimplemented, CEReactions] attribute USVString password;
  [CEReactions] attribute USVString host;
  [Unimplemented, CEReactions] attribute USVString hostname;
  [Unimplemented, CEReactions] attribute USVString port;
  [Unimplemented, CEReactions] attribute USVString pathname;
  [Unimplemented, CEReactions] attribute USVString search;
  [Unimplemented, CEReactions] attribute USVString hash;
};
