
// https://www.w3.org/TR/html5/grouping-content.html#the-div-element

[HTMLConstructor]
interface HTMLDivElement : HTMLElement {
    // https://html.spec.whatwg.org/#HTMLDivElement-partial
    [CEReactions, Reflect] attribute DOMString align;
};