[HTMLConstructor]
interface HTMLTemplateElement : HTMLElement {
  readonly attribute DocumentFragment content;
  [CEReactions, RaisesException] attribute DOMString shadowRootMode;
  [Unimplemented, CEReactions, RaisesException] attribute boolean shadowRootDelegatesFocus;
  [Unimplemented, CEReactions, RaisesException] attribute boolean shadowRootClonable;
  [Unimplemented, CEReactions, RaisesException] attribute boolean shadowRootSerializable;
};
