// https://w3c.github.io/uievents/#idl-mouseeventinit
dictionary MouseEventInit : EventModifierInit {
  double screenX = 0;
  double screenY = 0;
  double clientX = 0;
  double clientY = 0;

  [Unimplemented] short button = 0;
  [Unimplemented] unsigned short buttons = 0;
  [Unimplemented] EventTarget? relatedTarget = null;
};

// https://w3c.github.io/uievents/#idl-mouseevent
[Constructor(DOMString type, optional MouseEventInit eventInitDict), ConstructorCallWith=Document]
interface MouseEvent : UIEvent {
  readonly attribute long screenX;
  readonly attribute long screenY;
  readonly attribute long clientX;
  readonly attribute long clientY;

  [Unimplemented] readonly attribute boolean ctrlKey;
  [Unimplemented] readonly attribute boolean shiftKey;
  [Unimplemented] readonly attribute boolean altKey;
  [Unimplemented] readonly attribute boolean metaKey;

  readonly attribute short button;
  readonly attribute unsigned short buttons;

  [Unimplemented] readonly attribute EventTarget? relatedTarget;

  [Unimplemented] boolean getModifierState(DOMString keyArg);
};
