// https://dom.spec.whatwg.org/#mutationobserver

callback MutationCallback = undefined (sequence<MutationRecord> mutations, MutationObserver observer);

[Exposed=Window,Constructor(MutationCallback callback),ConstructorCallWith=ExecutionContext]
interface MutationObserver {
  // constructor(MutationCallback callback);

  [RaisesException] undefined observe(Node target, optional MutationObserverInit options);

  undefined disconnect();

  sequence<MutationRecord> takeRecords();
};

dictionary MutationObserverInit {
  boolean childList = false;
  boolean attributes;
  boolean characterData;
  boolean subtree = false;
  boolean attributeOldValue;
  boolean characterDataOldValue;
  sequence<DOMString> attributeFilter;
};
