// https://dom.spec.whatwg.org/#interface-namednodemap
// NOTE Using NotEnumerable at getter instead of LegacyUnenumerableNamedProperties at interface

[Exposed=Window]
interface NamedNodeMap {
  readonly attribute unsigned long length;
  getter Attr? item(unsigned long index);
  [NotEnumerable] getter Attr? getNamedItem(DOMString qualifiedName);
  Attr? getNamedItemNS(DOMString? namespace, DOMString localName);
  [CEReactions, RaisesException] Attr? setNamedItem(Attr attr);
  [CEReactions, RaisesException] Attr? setNamedItemNS(Attr attr);
  [CEReactions, RaisesException] Attr removeNamedItem(DOMString qualifiedName);
  [CEReactions, RaisesException] Attr removeNamedItemNS(DOMString? namespace, DOMString localName);
};
