// https://dom.spec.whatwg.org/#nodelist

[Exposed=Window, ObjectType=Exposable]
interface NodeList {
  getter Node? item(unsigned long index);
  readonly attribute unsigned long length;
  iterable<Node>;
};
