"'use strict';\n"
"/*\n"
" * Copyright (C) 2012 Google Inc. All rights reserved.\n"
" * Copyright (c) 2014 The Chromium Authors. All rights reserved.\n"
" *\n"
" * Redistribution and use in source and binary forms, with or without\n"
" * modification, are permitted provided that the following conditions\n"
" * are met:\n"
" * 1. Redistributions of source code must retain the above copyright\n"
" *    notice, this list of conditions and the following disclaimer.\n"
" * 2. Redistributions in binary form must reproduce the above copyright\n"
" *    notice, this list of conditions and the following disclaimer in the\n"
" *    documentation and/or other materials provided with the distribution.\n"
" *\n"
" * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS'' AND\n"
" * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n"
" * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\n"
" * ARE DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS BE LIABLE\n"
" * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\n"
" * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR\n"
" * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n"
" * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n"
" * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY\n"
" * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH\n"
" * DAMAGE.\n"
" */\n"
"function openListPicker(args) {\n"
"    var frame = document.getElementById(iframeId);\n"
"\n"
"    var pagePopupController = {\n"
"        setValue: function(stringValue) {\n"
"        },\n"
"        setValueAndClosePopup: function(numValue, stringValue) {\n"
"            var frame = document.getElementById(iframeId);\n"
"            if (numValue == 0)\n"
"                frame.contentWindow.picker.value = stringValue;\n"
"            document.body.removeChild(frame);\n"
"        },\n"
"        closePopup : function() {\n"
"            var frame = document.getElementById(iframeId);\n"
"            if (numValue == 0)\n"
"                frame.contentWindow.picker.value = stringValue;\n"
"            document.body.removeChild(frame);\n"
"        }\n"
"    }\n"
"    \n"
"    setTimeout(function() {\n"
"        frame.contentWindow.postMessage(JSON.stringify(args), '*');\n"
"        frame.contentWindow.pagePopupController = pagePopupController;\n"
"    }, 100);\n"
"    \n"
"}\n"
"\n"
"(function(){\n"
"    var iframe = document.getElementById(iframeId);\n"
"    if (iframe == undefined || iframe == null)\n"
"        iframe = document.createElement('iframe');\n"
"\n"
"    iframe.id = iframeId;\n"
"    iframe.style = 'position:absolute;left:'+rect.x+'px; top:'+(rect.y + rect.height)+'px; width:'+rect.width+'px;border:0;';\n"
"    var srcdoc= '<!DOCTYPE html><head><style>';\n"
"    srcdoc += 'body {margin: 0; overflow: hidden;} .rtl {direction: rtl;} select {display: block; overflow-y: auto;} select hr {border-style: none; border-bottom: 1px solid black; margin: 0 0.5em;} .wrap option { white-space: pre-wrap;}';\n"
"    srcdoc += optionStyle;\n"
"    srcdoc += '</style>';\n"
"    srcdoc += '<script>';\n"
"    srcdoc += 'function $(id) {'\n"
"    srcdoc += '  return document.getElementById(id);'\n"
"    srcdoc += '}'\n"
"    srcdoc += ''\n"
"    srcdoc += 'function createElement(tagName, opt_class, opt_text) {'\n"
"    srcdoc += '  var element = document.createElement(tagName);'\n"
"    srcdoc += '  if (opt_class)'\n"
"    srcdoc += '    element.setAttribute(\"class\", opt_class);'\n"
"    srcdoc += '  if (opt_text)'\n"
"    srcdoc += '    element.appendChild(document.createTextNode(opt_text));'\n"
"    srcdoc += '  return element;'\n"
"    srcdoc += '}'\n"
"    srcdoc += ''\n"
"    srcdoc += 'function Rectangle(xOrRect, y, width, height) {'\n"
"    srcdoc += '  if (typeof xOrRect === \"object\") {'\n"
"    srcdoc += '    y = xOrRect.y;'\n"
"    srcdoc += '    width = xOrRect.width;'\n"
"    srcdoc += '    height = xOrRect.height;'\n"
"    srcdoc += '    xOrRect = xOrRect.x;'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '  this.x = xOrRect;'\n"
"    srcdoc += '  this.y = y;'\n"
"    srcdoc += '  this.width = width;'\n"
"    srcdoc += '  this.height = height;'\n"
"    srcdoc += '}'\n"
"    srcdoc += ''\n"
"    srcdoc += 'Rectangle.prototype = {'\n"
"    srcdoc += '  get maxX() {'\n"
"    srcdoc += '    return this.x + this.width;'\n"
"    srcdoc += '  },'\n"
"    srcdoc += '  get maxY() {'\n"
"    srcdoc += '    return this.y + this.height;'\n"
"    srcdoc += '  },'\n"
"    srcdoc += '  toString: function() {'\n"
"    srcdoc += '    return \"Rectangle(\" + this.x + \",\" + this.y + \",\" + this.width + \",\" + this.height + \")\";'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'Rectangle.intersection = function(rect1, rect2) {'\n"
"    srcdoc += '  var x = Math.max(rect1.x, rect2.x);'\n"
"    srcdoc += '  var maxX = Math.min(rect1.maxX, rect2.maxX);'\n"
"    srcdoc += '  var y = Math.max(rect1.y, rect2.y);'\n"
"    srcdoc += '  var maxY = Math.min(rect1.maxY, rect2.maxY);'\n"
"    srcdoc += '  var width = maxX - x;'\n"
"    srcdoc += '  var height = maxY - y;'\n"
"    srcdoc += '  if (width < 0 || height < 0)'\n"
"    srcdoc += '    return null;'\n"
"    srcdoc += '  return new Rectangle(x, y, width, height);'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'function resizeWindow(width, height) {'\n"
"    srcdoc += '  var zoom = global.params.zoomFactor ? global.params.zoomFactor : 1;'\n"
"    srcdoc += '  setWindowRect(adjustWindowRect(width * zoom, height * zoom, width * zoom, height * zoom));'\n"
"    srcdoc += '}'\n"
"    srcdoc += ''\n"
"    srcdoc += 'function adjustWindowRect(width, height, minWidth, minHeight) {'\n"
"    srcdoc += '  if (typeof minWidth !== \"number\")'\n"
"    srcdoc += '    minWidth = 0;'\n"
"    srcdoc += '  if (typeof minHeight !== \"number\")'\n"
"    srcdoc += '    minHeight = 0;'\n"
"    srcdoc += ''\n"
"    srcdoc += '  var windowRect = new Rectangle(0, 0, Math.ceil(width), Math.ceil(height));'\n"
"    srcdoc += ''\n"
"    srcdoc += '  if (!global.params.anchorRectInScreen)'\n"
"    srcdoc += '    return windowRect;'\n"
"    srcdoc += ''\n"
"    srcdoc += '  var anchorRect = new Rectangle(global.params.anchorRectInScreen);'\n"
"    srcdoc += '  var availRect = new Rectangle('\n"
"    srcdoc += '      window.screen.availLeft, window.screen.availTop, window.screen.availWidth, window.screen.availHeight);'\n"
"    srcdoc += ''\n"
"    srcdoc += '  _adjustWindowRectVertically(windowRect, availRect, anchorRect, minHeight);'\n"
"    srcdoc += '  _adjustWindowRectHorizontally(windowRect, availRect, anchorRect, minWidth);'\n"
"    srcdoc += ''\n"
"    srcdoc += '  return windowRect;'\n"
"    srcdoc += '}'\n"
"    srcdoc += ''\n"
"    srcdoc += 'function _adjustWindowRectVertically(windowRect, availRect, anchorRect, minHeight) {'\n"
"    srcdoc += '  var availableSpaceAbove = anchorRect.y - availRect.y;'\n"
"    srcdoc += '  availableSpaceAbove = Math.max(0, Math.min(availRect.height, availableSpaceAbove));'\n"
"    srcdoc += ''\n"
"    srcdoc += '  var availableSpaceBelow = availRect.maxY - anchorRect.maxY;'\n"
"    srcdoc += '  availableSpaceBelow = Math.max(0, Math.min(availRect.height, availableSpaceBelow));'\n"
"    srcdoc += ''\n"
"    srcdoc += '  if (availableSpaceAbove == 0 && availableSpaceBelow == 0) {'\n"
"    srcdoc += '    windowRect.height = Math.max(minHeight, windowRect.height);'\n"
"    srcdoc += '    windowRect.y = anchorRect.maxY;'\n"
"    srcdoc += '  } else if (windowRect.height > availableSpaceBelow && availableSpaceBelow < availableSpaceAbove) {'\n"
"    srcdoc += '    windowRect.height = Math.min(windowRect.height, availableSpaceAbove);'\n"
"    srcdoc += '    windowRect.height = Math.max(windowRect.height, minHeight);'\n"
"    srcdoc += '    windowRect.y = anchorRect.y - windowRect.height;'\n"
"    srcdoc += '  } else {'\n"
"    srcdoc += '    windowRect.height = Math.min(windowRect.height, availableSpaceBelow);'\n"
"    srcdoc += '    windowRect.height = Math.max(windowRect.height, minHeight);'\n"
"    srcdoc += '    windowRect.y = anchorRect.maxY;'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '}'\n"
"    srcdoc += ''\n"
"    srcdoc += 'function _adjustWindowRectHorizontally(windowRect, availRect, anchorRect, minWidth) {'\n"
"    srcdoc += '  if (anchorRect.maxX <= availRect.x || availRect.maxX <= anchorRect.x) {'\n"
"    srcdoc += '    windowRect.width = Math.max(minWidth, windowRect.width);'\n"
"    srcdoc += '    windowRect.x = anchorRect.x;'\n"
"    srcdoc += '    return;'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '  windowRect.width = Math.min(windowRect.width, availRect.width);'\n"
"    srcdoc += '  windowRect.width = Math.max(windowRect.width, minWidth);'\n"
"    srcdoc += '  windowRect.x = anchorRect.x;'\n"
"    srcdoc += '  var rightAlignedX = windowRect.x + anchorRect.width - windowRect.width;'\n"
"    srcdoc += '  if (rightAlignedX >= availRect.x && (windowRect.maxX > availRect.maxX || global.params.isRTL))'\n"
"    srcdoc += '    windowRect.x = rightAlignedX;'\n"
"    srcdoc += '}'\n"
"    srcdoc += ''\n"
"    srcdoc += 'function setWindowRect(rect) {'\n"
"    srcdoc += '  if (window.frameElement) {'\n"
"    srcdoc += '    window.frameElement.style.width = rect.width + \"px\";'\n"
"    srcdoc += '    window.frameElement.style.height = rect.height + \"px\";'\n"
"    srcdoc += '  } else {'\n"
"    srcdoc += '    window.pagePopupController.setWindowRect(rect.x, rect.y, rect.width, rect.height);'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '}'\n"
"    srcdoc += ''\n"
"    srcdoc += 'function hideWindow() {'\n"
"    srcdoc += '  setWindowRect(adjustWindowRect(1, 1, 1, 1));'\n"
"    srcdoc += '}'\n"
"    srcdoc += ''\n"
"    srcdoc += 'function isWindowHidden() {'\n"
"    srcdoc += '  return window.innerWidth <= 1 && window.innerHeight <= 1;'\n"
"    srcdoc += '}'\n"
"    srcdoc += ''\n"
"    srcdoc += 'window.addEventListener(\"resize\", function() {'\n"
"    srcdoc += '  if (isWindowHidden())'\n"
"    srcdoc += '    window.dispatchEvent(new CustomEvent(\"didHide\"));'\n"
"    srcdoc += '  else'\n"
"    srcdoc += '    window.dispatchEvent(new CustomEvent(\"didOpenPicker\"));'\n"
"    srcdoc += '}, false);'\n"
"    srcdoc += ''\n"
"    srcdoc += 'function getScrollbarWidth() {'\n"
"    srcdoc += '  if (typeof window.scrollbarWidth === \"undefined\") {'\n"
"    srcdoc += '    var scrollDiv = document.createElement(\"div\");'\n"
"    srcdoc += '    scrollDiv.style.opacity = \"0\";'\n"
"    srcdoc += '    scrollDiv.style.overflow = \"scroll\";'\n"
"    srcdoc += '    scrollDiv.style.width = \"50px\";'\n"
"    srcdoc += '    scrollDiv.style.height = \"50px\";'\n"
"    srcdoc += '    document.body.appendChild(scrollDiv);'\n"
"    srcdoc += '    window.scrollbarWidth = scrollDiv.offsetWidth - scrollDiv.clientWidth;'\n"
"    srcdoc += '    scrollDiv.parentNode.removeChild(scrollDiv);'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '  return window.scrollbarWidth;'\n"
"    srcdoc += '}'\n"
"    srcdoc += ''\n"
"    srcdoc += 'function enclosingNodeOrSelfWithClass(selfNode, className) {'\n"
"    srcdoc += '  for (var node = selfNode; node && node !== selfNode.ownerDocument; node = node.parentNode) {'\n"
"    srcdoc += '    if (node.nodeType === Node.ELEMENT_NODE && node.classList.contains(className))'\n"
"    srcdoc += '      return node;'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '  return null;'\n"
"    srcdoc += '}'\n"
"    srcdoc += ''\n"
"    srcdoc += 'function EventEmitter(){};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'EventEmitter.prototype.on = function(type, callback) {'\n"
"    srcdoc += '  console.assert(callback instanceof Function);'\n"
"    srcdoc += '  if (!this._callbacks)'\n"
"    srcdoc += '    this._callbacks = {};'\n"
"    srcdoc += '  if (!this._callbacks[type])'\n"
"    srcdoc += '    this._callbacks[type] = [];'\n"
"    srcdoc += '  this._callbacks[type].push(callback);'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'EventEmitter.prototype.hasListener = function(type) {'\n"
"    srcdoc += '  if (!this._callbacks)'\n"
"    srcdoc += '    return false;'\n"
"    srcdoc += '  var callbacksForType = this._callbacks[type];'\n"
"    srcdoc += '  if (!callbacksForType)'\n"
"    srcdoc += '    return false;'\n"
"    srcdoc += '  return callbacksForType.length > 0;'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'EventEmitter.prototype.removeListener = function(type, callback) {'\n"
"    srcdoc += '  if (!this._callbacks)'\n"
"    srcdoc += '    return;'\n"
"    srcdoc += '  var callbacksForType = this._callbacks[type];'\n"
"    srcdoc += '  if (!callbacksForType)'\n"
"    srcdoc += '    return;'\n"
"    srcdoc += '  callbacksForType.splice(callbacksForType.indexOf(callback), 1);'\n"
"    srcdoc += '  if (callbacksForType.length === 0)'\n"
"    srcdoc += '    delete this._callbacks[type];'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'EventEmitter.prototype.dispatchEvent = function(type) {'\n"
"    srcdoc += '  if (!this._callbacks)'\n"
"    srcdoc += '    return;'\n"
"    srcdoc += '  var callbacksForType = this._callbacks[type];'\n"
"    srcdoc += '  if (!callbacksForType)'\n"
"    srcdoc += '    return;'\n"
"    srcdoc += '  callbacksForType = callbacksForType.slice(0);'\n"
"    srcdoc += '  for (var i = 0; i < callbacksForType.length; ++i) {'\n"
"    srcdoc += '    callbacksForType[i].apply(this, Array.prototype.slice.call(arguments, 1));'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'function Picker(element, config) {'\n"
"    srcdoc += '  this._element = element;'\n"
"    srcdoc += '  this._config = config;'\n"
"    srcdoc += '}'\n"
"    srcdoc += ''\n"
"    srcdoc += 'Picker.prototype = Object.create(EventEmitter.prototype);'\n"
"    srcdoc += ''\n"
"    srcdoc += 'Picker.Actions = {'\n"
"    srcdoc += '  SetValue: 0,'\n"
"    srcdoc += '  Cancel: -1,'\n"
"    srcdoc += '  ChooseOtherColor: -2'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'Picker.prototype.submitValue = function(value) {'\n"
"    srcdoc += '  window.pagePopupController.setValue(value);'\n"
"    srcdoc += '  window.pagePopupController.closePopup();'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'Picker.prototype.handleCancel = function() {'\n"
"    srcdoc += '  window.pagePopupController.closePopup();'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'Picker.prototype.chooseOtherColor = function() {'\n"
"    srcdoc += '  window.pagePopupController.setValueAndClosePopup(Picker.Actions.ChooseOtherColor, \"\");'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'Picker.prototype.cleanup = function() {};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'window.addEventListener(\"keyup\", function(event) {'\n"
"    srcdoc += '  if (event.key === \"Alt\")'\n"
"    srcdoc += '    event.preventDefault();'\n"
"    srcdoc += '}, true);'\n"
"    srcdoc += ''\n"
"    srcdoc += 'var global = {argumentsReceived: false, params: null, picker: null};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'function handleMessage(event) {'\n"
"    srcdoc += '  window.removeEventListener(\"message\", handleMessage, false);'\n"
"    srcdoc += '  initialize(JSON.parse(event.data));'\n"
"    srcdoc += '  global.argumentsReceived = true;'\n"
"    srcdoc += '}'\n"
"    srcdoc += ''\n"
"    srcdoc += 'function initialize(args) {'\n"
"    srcdoc += '  global.params = args;'\n"
"    srcdoc += '  var main = $(\"main\");'\n"
"    srcdoc += '  main.innerHTML = \"\";'\n"
"    srcdoc += '  global.picker = new ListPicker(main, args);'\n"
"    srcdoc += '}'\n"
"    srcdoc += ''\n"
"    srcdoc += 'function handleArgumentsTimeout() {'\n"
"    srcdoc += '  if (global.argumentsReceived)'\n"
"    srcdoc += '    return;'\n"
"    srcdoc += '  initialize({});'\n"
"    srcdoc += '}'\n"
"    srcdoc += ''\n"
"    srcdoc += 'function ListPicker(element, config) {'\n"
"    srcdoc += '  Picker.call(this, element, config);'\n"
"    srcdoc += '  this._selectElement = createElement(\"select\");'\n"
"    srcdoc += '  this._selectElement.id = \"s1\";'\n"
"    srcdoc += '  this._selectElement.size = 20/*config.children.length*/;'\n"
"    srcdoc += '  this._element.appendChild(this._selectElement);'\n"
"    srcdoc += '  this._delayedChildrenConfig = null;'\n"
"    srcdoc += '  this._delayedChildrenConfigIndex = 0;'\n"
"    srcdoc += '  this._layout();'\n"
"    srcdoc += '  this._selectElement.addEventListener(\"mouseup\", this._handleMouseUp.bind(this), false);'\n"
"    srcdoc += '  this._selectElement.addEventListener(\"touchstart\", this._handleTouchStart.bind(this), false);'\n"
"    srcdoc += '  this._selectElement.addEventListener(\"keydown\", this._handleKeyDown.bind(this), false);'\n"
"    srcdoc += '  window.addEventListener(\"message\", this._handleWindowMessage.bind(this), false);'\n"
"    srcdoc += '  window.addEventListener(\"mousemove\", this._handleWindowMouseMove.bind(this), false);'\n"
"    srcdoc += '  window.addEventListener(\"mouseover\", this._handleWindowMouseOver.bind(this), false);'\n"
"    srcdoc += '  this._handleWindowTouchMoveBound = this._handleWindowTouchMove.bind(this);'\n"
"    srcdoc += '  this._handleWindowTouchEndBound = this._handleWindowTouchEnd.bind(this);'\n"
"    srcdoc += '  this._handleTouchSelectModeScrollBound = this._handleTouchSelectModeScroll.bind(this);'\n"
"    srcdoc += '  this.lastMousePositionX = Infinity;'\n"
"    srcdoc += '  this.lastMousePositionY = Infinity;'\n"
"    srcdoc += '  this._selectionSetByMouseHover = false;'\n"
"    srcdoc += ''\n"
"    srcdoc += '  this._trackingTouchId = null;'\n"
"    srcdoc += ''\n"
"    srcdoc += '  this._handleWindowDidHide();'\n"
"    srcdoc += '  this._selectElement.focus();'\n"
"    srcdoc += '  this._selectElement.value = this._config.selectedIndex;'\n"
"    srcdoc += '}'\n"
"    srcdoc += 'ListPicker.prototype = Object.create(Picker.prototype);'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._handleWindowDidHide = function() {'\n"
"    srcdoc += '  this._fixWindowSize();'\n"
"    srcdoc += '  var selectedOption = this._selectElement.options[this._selectElement.selectedIndex];'\n"
"    srcdoc += '  if (selectedOption)'\n"
"    srcdoc += '    selectedOption.scrollIntoView(false);'\n"
"    srcdoc += '  window.removeEventListener(\"didHide\", this._handleWindowDidHideBound, false);'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._handleWindowMessage = function(event) {'\n"
"    srcdoc += '  eval(event.data);'\n"
"    srcdoc += '  if (window.updateData.type === \"update\") {'\n"
"    srcdoc += '    this._config.baseStyle = window.updateData.baseStyle;'\n"
"    srcdoc += '    this._config.children = window.updateData.children;'\n"
"    srcdoc += '    this._update();'\n"
"    srcdoc += '    if (this._config.anchorRectInScreen.x !== window.updateData.anchorRectInScreen.x ||'\n"
"    srcdoc += '        this._config.anchorRectInScreen.y !== window.updateData.anchorRectInScreen.y ||'\n"
"    srcdoc += '        this._config.anchorRectInScreen.width !== window.updateData.anchorRectInScreen.width ||'\n"
"    srcdoc += '        this._config.anchorRectInScreen.height !== window.updateData.anchorRectInScreen.height) {'\n"
"    srcdoc += '      if (!navigator.platform.startsWith(\"Win\")) {'\n"
"    srcdoc += '        this._config.anchorRectInScreen = window.updateData.anchorRectInScreen;'\n"
"    srcdoc += '        this._fixWindowSize();'\n"
"    srcdoc += '      }'\n"
"    srcdoc += '    }'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '  delete window.updateData;'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.ListboxSelectBorder = 1;'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._handleWindowMouseMove = function(event) {'\n"
"    srcdoc += '  var visibleTop = ListPicker.ListboxSelectBorder;'\n"
"    srcdoc += '  var visibleBottom = this._selectElement.offsetHeight - ListPicker.ListboxSelectBorder;'\n"
"    srcdoc += '  if (event.target instanceof HTMLDocument)'\n"
"    srcdoc += '    return;'\n"
"    srcdoc += '  var optionBounds = event.target.getBoundingClientRect();'\n"
"    srcdoc += '  if (optionBounds.height >= 1.0) {'\n"
"    srcdoc += '    if (optionBounds.top < visibleTop) {'\n"
"    srcdoc += '      if (optionBounds.bottom - visibleTop < 1.0)'\n"
"    srcdoc += '        return;'\n"
"    srcdoc += '    } else if (optionBounds.bottom > visibleBottom) {'\n"
"    srcdoc += '      if (visibleBottom - optionBounds.top < 1.0)'\n"
"    srcdoc += '        return;'\n"
"    srcdoc += '    }'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '  this.lastMousePositionX = event.clientX;'\n"
"    srcdoc += '  this.lastMousePositionY = event.clientY;'\n"
"    srcdoc += '  this._selectionSetByMouseHover = true;'\n"
"    srcdoc += '  event.preventDefault();'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._handleWindowMouseOver = function(event) {'\n"
"    srcdoc += '  this._highlightOption(event.target);'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._handleMouseUp = function(event) {'\n"
"    srcdoc += '  if (event.target.tagName !== \"OPTION\")'\n"
"    srcdoc += '    return;'\n"
"    srcdoc += '  window.pagePopupController.setValueAndClosePopup(0, this._selectElement.value);'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._handleTouchStart = function(event) {'\n"
"    srcdoc += '  if (this._trackingTouchId !== null)'\n"
"    srcdoc += '    return;'\n"
"    srcdoc += '  var touch = event.touches[0];'\n"
"    srcdoc += '  this._trackingTouchId = touch.identifier;'\n"
"    srcdoc += '  this._highlightOption(touch.target);'\n"
"    srcdoc += '  this._selectionSetByMouseHover = false;'\n"
"    srcdoc += '  this._selectElement.addEventListener(\"scroll\", this._handleTouchSelectModeScrollBound, false);'\n"
"    srcdoc += '  window.addEventListener(\"touchmove\", this._handleWindowTouchMoveBound, false);'\n"
"    srcdoc += '  window.addEventListener(\"touchend\", this._handleWindowTouchEndBound, false);'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._handleTouchSelectModeScroll = function(event) {'\n"
"    srcdoc += '  this._exitTouchSelectMode();'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._exitTouchSelectMode = function(event) {'\n"
"    srcdoc += '  this._trackingTouchId = null;'\n"
"    srcdoc += '  this._selectElement.removeEventListener(\"scroll\", this._handleTouchSelectModeScrollBound, false);'\n"
"    srcdoc += '  window.removeEventListener(\"touchmove\", this._handleWindowTouchMoveBound, false);'\n"
"    srcdoc += '  window.removeEventListener(\"touchend\", this._handleWindowTouchEndBound, false);'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._handleWindowTouchMove = function(event) {'\n"
"    srcdoc += '  if (this._trackingTouchId === null)'\n"
"    srcdoc += '    return;'\n"
"    srcdoc += '  var touch = this._getTouchForId(event.touches, this._trackingTouchId);'\n"
"    srcdoc += '  if (!touch)'\n"
"    srcdoc += '    return;'\n"
"    srcdoc += '  this._highlightOption(document.elementFromPoint(touch.clientX, touch.clientY));'\n"
"    srcdoc += '  this._selectionSetByMouseHover = false;'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._handleWindowTouchEnd = function(event) {'\n"
"    srcdoc += '  if (this._trackingTouchId === null)'\n"
"    srcdoc += '    return;'\n"
"    srcdoc += '  var touch = this._getTouchForId(event.changedTouches, this._trackingTouchId);'\n"
"    srcdoc += '  if (!touch)'\n"
"    srcdoc += '    return;'\n"
"    srcdoc += '  var target = document.elementFromPoint(touch.clientX, touch.clientY);'\n"
"    srcdoc += '  if (target.tagName === \"OPTION\" && !target.disabled)'\n"
"    srcdoc += '    window.pagePopupController.setValueAndClosePopup(0, this._selectElement.value);'\n"
"    srcdoc += '  this._exitTouchSelectMode();'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._getTouchForId = function(touchList, id) {'\n"
"    srcdoc += '  for (var i = 0; i < touchList.length; i++) {'\n"
"    srcdoc += '    if (touchList[i].identifier === id)'\n"
"    srcdoc += '      return touchList[i];'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '  return null;'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._highlightOption = function(target) {'\n"
"    srcdoc += '  if (target.tagName !== \"OPTION\" || target.selected || target.disabled)'\n"
"    srcdoc += '    return;'\n"
"    srcdoc += '  var savedScrollTop = this._selectElement.scrollTop;'\n"
"    srcdoc += '  target.selected = true;'\n"
"    srcdoc += '  this._selectElement.scrollTop = savedScrollTop;'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._handleChange = function(event) {'\n"
"    srcdoc += '  window.pagePopupController.setValue(this._selectElement.value);'\n"
"    srcdoc += '  this._selectionSetByMouseHover = false;'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._handleKeyDown = function(event) {'\n"
"    srcdoc += '  var key = event.key;'\n"
"    srcdoc += '  if (key === \"Escape\") {'\n"
"    srcdoc += '    window.pagePopupController.closePopup();'\n"
"    srcdoc += '    event.preventDefault();'\n"
"    srcdoc += '  } else if (key === \"Tab\" || key === \"Enter\") {'\n"
"    srcdoc += '    window.pagePopupController.setValueAndClosePopup(0, this._selectElement.value);'\n"
"    srcdoc += '    event.preventDefault();'\n"
"    srcdoc += '  } else if (event.altKey && (key === \"ArrowDown\" || key === \"ArrowUp\")) {'\n"
"    srcdoc += '    setTimeout(function() {'\n"
"    srcdoc += '      window.pagePopupController.closePopup();'\n"
"    srcdoc += '    }, 0);'\n"
"    srcdoc += '    event.preventDefault();'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._fixWindowSize = function() {'\n"
"    srcdoc += '  this._selectElement.style.height = \"\";'\n"
"    srcdoc += '  var scale = this._config.scaleFactor;'\n"
"    srcdoc += '  var maxHeight = this._selectElement.offsetHeight;'\n"
"    srcdoc += '  var noScrollHeight = (this._calculateScrollHeight() + ListPicker.ListboxSelectBorder * 2);'\n"
"    srcdoc += '  var scrollbarWidth = getScrollbarWidth();'\n"
"    srcdoc += '  var elementOffsetWidth = this._selectElement.offsetWidth;'\n"
"    srcdoc += '  var desiredWindowHeight = noScrollHeight;'\n"
"    srcdoc += '  var desiredWindowWidth = elementOffsetWidth;'\n"
"    srcdoc += '  if (this._selectElement.scrollHeight > this._selectElement.clientHeight)'\n"
"    srcdoc += '    desiredWindowWidth -= scrollbarWidth;'\n"
"    srcdoc += '  var expectingScrollbar = false;'\n"
"    srcdoc += '  if (desiredWindowHeight > maxHeight) {'\n"
"    srcdoc += '    desiredWindowHeight = maxHeight;'\n"
"    srcdoc += '    desiredWindowWidth += scrollbarWidth;'\n"
"    srcdoc += '    expectingScrollbar = true;'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '  desiredWindowWidth = Math.max(this._config.anchorRectInScreen.width * scale, desiredWindowWidth);'\n"
"    srcdoc += '  var windowRect ='\n"
"    srcdoc += '      adjustWindowRect(desiredWindowWidth / scale, desiredWindowHeight / scale, elementOffsetWidth / scale, 0);'\n"
"    srcdoc += '  if (!expectingScrollbar && windowRect.height < noScrollHeight / scale) {'\n"
"    srcdoc += '    desiredWindowWidth = windowRect.width * scale + scrollbarWidth;'\n"
"    srcdoc += '    windowRect = adjustWindowRect(desiredWindowWidth / scale, windowRect.height, windowRect.width, windowRect.height);'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '  this._selectElement.style.width = (windowRect.width * scale) + \"px\";'\n"
"    srcdoc += '  this._selectElement.style.height = (windowRect.height * scale) + \"px\";'\n"
"    srcdoc += '  this._element.style.height = (windowRect.height * scale) + \"px\";'\n"
"    srcdoc += '  setWindowRect(windowRect);'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._calculateScrollHeight = function() {'\n"
"    srcdoc += '  var top = Infinity;'\n"
"    srcdoc += '  var bottom = -Infinity;'\n"
"    srcdoc += '  for (var i = 0; i < this._selectElement.children.length; i++) {'\n"
"    srcdoc += '    var rect = this._selectElement.children[i].getBoundingClientRect();'\n"
"    srcdoc += '    if (rect.width === 0 && rect.height === 0)'\n"
"    srcdoc += '      continue;'\n"
"    srcdoc += '    top = Math.min(top, rect.top);'\n"
"    srcdoc += '    bottom = Math.max(bottom, rect.bottom);'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '  return Math.max(bottom - top, 0);'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._listItemCount = function() {'\n"
"    srcdoc += '  return this._selectElement.querySelectorAll(\"option,optgroup,hr\").length;'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._layout = function() {'\n"
"    srcdoc += '  if (this._config.isRTL)'\n"
"    srcdoc += '    this._element.classList.add(\"rtl\");'\n"
"    srcdoc += '  if (this._config.baseStyle != undefined) {'\n"
"    srcdoc += '    this._selectElement.style.backgroundColor = this._config.baseStyle.backgroundColor;'\n"
"    srcdoc += '    this._selectElement.style.color = this._config.baseStyle.color;'\n"
"    srcdoc += '    this._selectElement.style.textTransform = this._config.baseStyle.textTransform;'\n"
"    srcdoc += '    this._selectElement.style.fontStyle = this._config.baseStyle.fontStyle;'\n"
"    srcdoc += '    this._selectElement.style.fontVariant = this._config.baseStyle.fontVariant;'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '  this._updateChildren(this._selectElement, this._config);'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._update = function() {'\n"
"    srcdoc += '  var scrollPosition = this._selectElement.scrollTop;'\n"
"    srcdoc += '  var oldValue = this._selectElement.value;'\n"
"    srcdoc += '  this._layout();'\n"
"    srcdoc += '  this._selectElement.value = this._config.selectedIndex;'\n"
"    srcdoc += '  this._selectElement.scrollTop = scrollPosition;'\n"
"    srcdoc += '  var optionUnderMouse = null;'\n"
"    srcdoc += '  if (this._selectionSetByMouseHover) {'\n"
"    srcdoc += '    var elementUnderMouse = document.elementFromPoint(this.lastMousePositionX, this.lastMousePositionY);'\n"
"    srcdoc += '    optionUnderMouse = elementUnderMouse && elementUnderMouse.closest(\"option\");'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '  if (optionUnderMouse)'\n"
"    srcdoc += '    optionUnderMouse.selected = true;'\n"
"    srcdoc += '  else'\n"
"    srcdoc += '    this._selectElement.value = oldValue;'\n"
"    srcdoc += '  this._selectElement.scrollTop = scrollPosition;'\n"
"    srcdoc += '  this.dispatchEvent(\"didUpdate\");'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.DelayedLayoutThreshold = 1000;'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._updateChildren = function(parent, config) {'\n"
"    srcdoc += '  var outOfDateIndex = 0;'\n"
"    srcdoc += '  var fragment = null;'\n"
"    srcdoc += '  var inGroup = parent.tagName === \"OPTGROUP\";'\n"
"    srcdoc += '  var lastListIndex = -1;'\n"
"    srcdoc += '  var limit = Math.max(this._config.selectedIndex, ListPicker.DelayedLayoutThreshold);'\n"
"    srcdoc += '  var i;'\n"
"    srcdoc += '  for (i = 0; i < config.children.length; ++i) {'\n"
"    srcdoc += '    if (!inGroup && lastListIndex >= limit)'\n"
"    srcdoc += '      break;'\n"
"    srcdoc += '    var childConfig = config.children[i];'\n"
"    srcdoc += '    var item = this._findReusableItem(parent, childConfig, outOfDateIndex) || this._createItemElement(childConfig);'\n"
"    srcdoc += '    this._configureItem(item, childConfig, inGroup);'\n"
"    srcdoc += '    lastListIndex = item.value ? Number(item.value) : -1;'\n"
"    srcdoc += '    if (outOfDateIndex < parent.children.length) {'\n"
"    srcdoc += '      parent.insertBefore(item, parent.children[outOfDateIndex]);'\n"
"    srcdoc += '    } else {'\n"
"    srcdoc += '      if (!fragment)'\n"
"    srcdoc += '        fragment = document.createDocumentFragment();'\n"
"    srcdoc += '      fragment.appendChild(item);'\n"
"    srcdoc += '    }'\n"
"    srcdoc += '    outOfDateIndex++;'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '  if (fragment) {'\n"
"    srcdoc += '    parent.appendChild(fragment);'\n"
"    srcdoc += '  } else {'\n"
"    srcdoc += '    var unused = parent.children.length - outOfDateIndex;'\n"
"    srcdoc += '    for (var j = 0; j < unused; j++) {'\n"
"    srcdoc += '      parent.removeChild(parent.lastElementChild);'\n"
"    srcdoc += '    }'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '  if (i < config.children.length) {'\n"
"    srcdoc += '    this._delayedChildrenConfig = config.children;'\n"
"    srcdoc += '    this._delayedChildrenConfigIndex = i;'\n"
"    srcdoc += '    setTimeout(this._updateChildrenLater.bind(this), 100);'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._updateChildrenLater = function(timeStamp) {'\n"
"    srcdoc += '  if (!this._delayedChildrenConfig)'\n"
"    srcdoc += '    return;'\n"
"    srcdoc += '  var fragment = document.createDocumentFragment();'\n"
"    srcdoc += '  var startIndex = this._delayedChildrenConfigIndex;'\n"
"    srcdoc += '  for (; this._delayedChildrenConfigIndex < this._delayedChildrenConfig.length; ++this._delayedChildrenConfigIndex) {'\n"
"    srcdoc += '    var childConfig = this._delayedChildrenConfig[this._delayedChildrenConfigIndex];'\n"
"    srcdoc += '    var item = this._createItemElement(childConfig);'\n"
"    srcdoc += '    this._configureItem(item, childConfig, false);'\n"
"    srcdoc += '    fragment.appendChild(item);'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '  this._selectElement.appendChild(fragment);'\n"
"    srcdoc += '  this._selectElement.classList.add(\"wrap\");'\n"
"    srcdoc += '  this._delayedChildrenConfig = null;'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._findReusableItem = function(parent, config, startIndex) {'\n"
"    srcdoc += '  if (startIndex >= parent.children.length)'\n"
"    srcdoc += '    return null;'\n"
"    srcdoc += '  var tagName = \"OPTION\";'\n"
"    srcdoc += '  if (config.type === \"optgroup\")'\n"
"    srcdoc += '    tagName = \"OPTGROUP\";'\n"
"    srcdoc += '  else if (config.type === \"separator\")'\n"
"    srcdoc += '    tagName = \"HR\";'\n"
"    srcdoc += '  for (var i = startIndex; i < parent.children.length; i++) {'\n"
"    srcdoc += '    var child = parent.children[i];'\n"
"    srcdoc += '    if (tagName === child.tagName) {'\n"
"    srcdoc += '      return child;'\n"
"    srcdoc += '    }'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '  return null;'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._createItemElement = function(config) {'\n"
"    srcdoc += '  var element;'\n"
"    srcdoc += '  if (!config.type || config.type === \"option\")'\n"
"    srcdoc += '    element = createElement(\"option\");'\n"
"    srcdoc += '  else if (config.type === \"optgroup\")'\n"
"    srcdoc += '    element = createElement(\"optgroup\");'\n"
"    srcdoc += '  else if (config.type === \"separator\")'\n"
"    srcdoc += '    element = createElement(\"hr\");'\n"
"    srcdoc += '  return element;'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._applyItemStyle = function(element, styleConfig) {'\n"
"    srcdoc += '  if (!styleConfig)'\n"
"    srcdoc += '    return;'\n"
"    srcdoc += '  var style = element.style;'\n"
"    srcdoc += '  style.visibility = styleConfig.visibility ? styleConfig.visibility : \"\";'\n"
"    srcdoc += '  style.display = styleConfig.display ? styleConfig.display : \"\";'\n"
"    srcdoc += '  style.direction = styleConfig.direction ? styleConfig.direction : \"\";'\n"
"    srcdoc += '  style.unicodeBidi = styleConfig.unicodeBidi ? styleConfig.unicodeBidi : \"\";'\n"
"    srcdoc += '  style.color = styleConfig.color ? styleConfig.color : \"\";'\n"
"    srcdoc += '  style.backgroundColor = styleConfig.backgroundColor ? styleConfig.backgroundColor : \"\";'\n"
"    srcdoc += '  style.fontSize = styleConfig.fontSize ? styleConfig.fontSize + \"px\" : \"\";'\n"
"    srcdoc += '  style.fontWeight = styleConfig.fontWeight ? styleConfig.fontWeight : \"\";'\n"
"    srcdoc += '  style.fontStyle = styleConfig.fontStyle ? styleConfig.fontStyle : \"\";'\n"
"    srcdoc += '  style.fontVariant = styleConfig.fontVariant ? styleConfig.fontVariant : \"\";'\n"
"    srcdoc += '  style.textTransform = styleConfig.textTransform ? styleConfig.textTransform : \"\";'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'ListPicker.prototype._configureItem = function(element, config, inGroup) {'\n"
"    srcdoc += '  if (!config.type || config.type === \"option\") {'\n"
"    srcdoc += '    element.label = config.label;'\n"
"    srcdoc += '    element.value = config.value;'\n"
"    srcdoc += '    if (config.title)'\n"
"    srcdoc += '      element.title = config.title;'\n"
"    srcdoc += '    else'\n"
"    srcdoc += '      element.removeAttribute(\"title\");'\n"
"    srcdoc += '    element.disabled = !!config.disabled;'\n"
"    srcdoc += '    if (config.ariaLabel)'\n"
"    srcdoc += '    element.setAttribute(\"aria-label\", config.ariaLabel);'\n"
"    srcdoc += '    else element.removeAttribute(\"aria-label\");'\n"
"    srcdoc += '    element.style.paddingLeft = this._config.paddingStart + \"px\";'\n"
"    srcdoc += '    if (inGroup) {'\n"
"    srcdoc += '      element.style.marginLeft = (-this._config.paddingStart) + \"px\";'\n"
"    srcdoc += '      element.style.marginRight = \"-2px\";'\n"
"    srcdoc += '    }'\n"
"    srcdoc += '  } else if (config.type === \"optgroup\") {'\n"
"    srcdoc += '    element.label = config.label;'\n"
"    srcdoc += '    element.title = config.title;'\n"
"    srcdoc += '    element.disabled = config.disabled;'\n"
"    srcdoc += '    element.setAttribute(\"aria-label\", config.ariaLabel);'\n"
"    srcdoc += '    this._updateChildren(element, config);'\n"
"    srcdoc += '    element.style.paddingLeft = this._config.paddingStart + \"px\";'\n"
"    srcdoc += '  } else if (config.type === \"separator\") {'\n"
"    srcdoc += '    element.title = config.title;'\n"
"    srcdoc += '    element.disabled = config.disabled;'\n"
"    srcdoc += '    element.setAttribute(\"aria-label\", config.ariaLabel);'\n"
"    srcdoc += '    if (inGroup) {'\n"
"    srcdoc += '      element.style.marginLeft = (-this._config.paddingStart) + \"px\";'\n"
"    srcdoc += '      element.style.marginRight = \"-2px\";'\n"
"    srcdoc += '    }'\n"
"    srcdoc += '  }'\n"
"    srcdoc += '  this._applyItemStyle(element, config.style);'\n"
"    srcdoc += '};'\n"
"    srcdoc += ''\n"
"    srcdoc += 'if (window.dialogArguments) {  '\n"
"    srcdoc += '  initialize(dialogArguments);  '\n"
"    srcdoc += '} else {'\n"
"    srcdoc += '  window.addEventListener(\"message\", handleMessage, false);'\n"
"    srcdoc += '  window.setTimeout(handleArgumentsTimeout, 1000);'\n"
"    srcdoc += '}'\n"
"    srcdoc += ''\n"
"    srcdoc += '</script></head>';\n"
"    srcdoc += '<body><div id=main></div></body>';\n"
"    iframe.srcdoc = srcdoc;\n"
"    document.body.appendChild(iframe);\n"
"    iframe.onload = function() {\n"
"        openListPicker(window.dialogArguments);\n"
"    }\n"
"})()\n"