// https://w3c.github.io/webcomponents/spec/shadow/#shadowrootinit-dictionary
dictionary ShadowRootInit {
  required ShadowRootMode mode;
  boolean delegatesFocus = false;
  SlotAssignmentMode slotAssignment = "named";
  boolean clonable = false;
  boolean serializable = false;
};
