// https://dom.spec.whatwg.org/#interface-shadowroot
[Exposed=Window]
interface ShadowRoot : DocumentFragment {
  readonly attribute ShadowRootMode mode;
  readonly attribute boolean delegatesFocus;
  readonly attribute SlotAssignmentMode slotAssignment;
  readonly attribute boolean clonable;
  readonly attribute boolean serializable;
  readonly attribute Element host;
  attribute EventHandler onslotchange;

  // The HTML spec exposes innerHTML through the `InnerHTML` mixin, which both
  // Element and ShadowRoot include:
  // https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#dom-innerhtml
  [CEReactions, TreatNullAs=EmptyString] attribute DOMString innerHTML;
};

enum ShadowRootMode { "open", "closed" };
enum SlotAssignmentMode { "manual", "named" };

ShadowRoot implements DocumentOrShadowRoot; // https://drafts.csswg.org/cssom/
