// https://dom.spec.whatwg.org/#text

[Constructor(optional DOMString data = ""),
 ConstructorCallWith=Document,
 Exposed=Window]
interface Text : CharacterData {
  [RaisesException, NewObject] Text splitText(unsigned long offset);
  readonly attribute DOMString wholeText;
};