// https://w3c.github.io/uievents/#interface-UIEvent

[Constructor(DOMString type, optional UIEventInit eventInitDict), ConstructorCallWith=Document]
interface UIEvent : Event {
  [Unimplemented] readonly attribute Window? view;
  [Unimplemented] readonly attribute long detail;
};

// https://w3c.github.io/uievents/#dictdef-uieventinit
dictionary UIEventInit : EventInit {
  Window? view = null;
  long detail = 0;
};

// https://w3c.github.io/uievents/#dictdef-eventmodifierinit
dictionary EventModifierInit : UIEventInit {
  boolean ctrlKey = false;
  boolean shiftKey = false;
  boolean altKey = false;
  boolean metaKey = false;

  boolean modifierAltGraph = false;
  boolean modifierCapsLock = false;
  boolean modifierFn = false;
  boolean modifierFnLock = false;
  boolean modifierHyper = false;
  boolean modifierNumLock = false;
  boolean modifierScrollLock = false;
  boolean modifierSuper = false;
  boolean modifierSymbol = false;
  boolean modifierSymbolLock = false;
};
