// https://w3c.github.io/uievents/#interface-UIEvent

[
  Constructor(DOMString type, optional UIEventInit eventInitDict),
  ConstructorCallWith=ExecutionContext
]
interface UIEvent : Event {
  readonly attribute Window? view;
  readonly attribute long detail;
  // https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which
  // The following support legacy user agents
  readonly attribute unsigned long which;
};

// https://w3c.github.io/uievents/#dictdef-uieventinit
dictionary UIEventInit : EventInit {
  Window? view = null;
  long detail = 0;
  // The following support legacy user agents
  unsigned long which = 0;
};

// https://w3c.github.io/uievents/#dictdef-eventmodifierinit
dictionary EventModifierInit : UIEventInit {
  boolean ctrlKey = false;
  boolean shiftKey = false;
  boolean altKey = false;
  boolean metaKey = false;

  [Unimplemented] boolean modifierAltGraph = false;
  [Unimplemented] boolean modifierCapsLock = false;
  [Unimplemented] boolean modifierFn = false;
  [Unimplemented] boolean modifierFnLock = false;
  [Unimplemented] boolean modifierHyper = false;
  [Unimplemented] boolean modifierNumLock = false;
  [Unimplemented] boolean modifierScrollLock = false;
  [Unimplemented] boolean modifierSuper = false;
  [Unimplemented] boolean modifierSymbol = false;
  [Unimplemented] boolean modifierSymbolLock = false;
};
