[general]
profile = profile.fhub4_kantm
work_dir=~/tizen/spin/product/da/scm/meta/gbs-build-config

[profile.fhub4_kantm]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos=repo.fhub4_kantm, repo.base_arm
buildconf=${work_dir}/TIZEN_4.0_DA_FHUB4_BUILD_KANTM.conf
buildroot=~/gbs-root/tizen_4.0_spin/da-fhub/kantm/ad/

[profile.fhub4_kantm_asan]
user = juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.fhub4_kantm_asan, repo.base_arm
buildconf=${work_dir}/TIZEN_4.0_DA_FHUB4_BUILD_KANTM_ASAN.conf
buildroot=~/gbs-root/tizen_4.0_spin/da-fhub/kantm/ad/

[profile.fhub4_emulator32]
user = juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.fhub4_emulator, repo.base_emulator32
buildconf=${work_dir}/TIZEN_4.0_DA_FHUB4_BUILD_EMULATOR.conf
buildroot=~/gbs-root/tizen_4.0_spin/da-fhub/emulator/32/ad/

[profile.fhub4_emulator64]
user = juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.fhub4_emulator, repo.base_emulator64
buildconf=${work_dir}/TIZEN_4.0_DA_FHUB4_BUILD_EMULATOR.conf
buildroot=~/gbs-root/tizen_4.0_spin/da-fhub/emulator/64/ad/

#Family Hub 4 KANT-M
[repo.fhub4_kantm]
url = http://165.213.149.200/download/snapshots/tizen/4.0-da-fhub4/latest/repos/KANTM/packages/

#Family Hub 4 KANT-M ASAN
[repo.fhub4_kantm_asan]
url = http://165.213.149.200/download/snapshots/tizen/4.0-da-fhub4/latest/repos/KM_ASAN/packages/

#Family Hub 4 Emulator
[repo.fhub4_emulator]
url=http://165.213.149.200/download/snapshots/tizen/4.0-da-fhub4/latest/repos/emulator/packages/

#Tizen 4.0 Base ARM
[repo.base_arm]
url=http://165.213.149.200/download/public_mirror/tizen/4.0-base/latest/repos/arm/packages/

#Tizen 4.0 Base Emulator 32
[repo.base_emulator32]
url=http://165.213.149.200/download/public_mirror/tizen/4.0-base/latest/repos/emulator32/packages/

#Tizen 4.0 Base Emulator 64
[repo.base_emulator64]
url=http://165.213.149.200/download/public_mirror/tizen/4.0-base/latest/repos/emulator64/packages/

