[general]
profile = profile.fhub5_kantm_arm
work_dir=~/gbs-configuration

[profile.fhub5_kantm_arm]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.fhub5_kantm, repo.base
buildconf=${work_dir}/TIZEN_5.5_DA_FHUB5_KANTM_BUILD.conf
buildroot=~/gbs-root/tizen_5.5/fhub5/kantm/arm/ad/

[profile.fhub5_meson64_arm]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.fhub5_meson64, repo.base
buildconf=${work_dir}/TIZEN_5.5_DA_FHUB5_MESON64_BUILD.conf
buildroot=~/gbs-root/tizen_5.5/fhub5/meson64/arm/ad/

[profile.fhub5_meson64_aarch64]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.fhub5_meson64, repo.base
buildconf=${work_dir}/TIZEN_5.5_DA_FHUB5_MESON64_BUILD.conf
buildroot=~/gbs-root/tizen_5.5/fhub5/meson64/aarch64/ad/

#DA Family Hub 5.0 kantm
[repo.fhub5_kantm]
url = http://10.113.138.205/snapshots/DA/Tizen-5.5/Tizen-5.5-DA-FHUB5/reference/repos/KANTM/packages/

#DA Family Hub 5.0 meson64
[repo.fhub5_meson64]
url = http://10.113.138.205/snapshots/DA/Tizen-5.5/Tizen-5.5-DA-FHUB5/reference/repos/MESON64/packages/

#Tizen 5.5 Base
[repo.base]
url=http://download.tizen.org/snapshots/tizen/5.5-base/latest/repos/standard/packages/

