[general]
profile = profile.fhub_kantm_arm
work_dir=~/gbs-configuration

[profile.fhub_kantm_arm]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.fhub_kantm, repo.base
buildconf=${work_dir}/TIZEN_6.0_DA_FHUB_KANTM_BUILD.conf
buildroot=~/gbs-root/tizen_6.0/fhub/kantm/arm/ad/

[profile.fhub_meson64_arm]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.fhub_meson64, repo.base
buildconf=${work_dir}/TIZEN_6.0_DA_FHUB_MESON64_BUILD.conf
buildroot=~/gbs-root/tizen_6.0/fhub/meson64/arm/ad/

[profile.fhub_meson64_aarch64]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.fhub_meson64, repo.base
buildconf=${work_dir}/TIZEN_6.0_DA_FHUB_MESON64_BUILD.conf
buildroot=~/gbs-root/tizen_6.0/fhub/meson64/aarch64/ad/

#DA Family Hub KantM
[repo.fhub_kantm]
url = http://10.113.138.205/snapshots/DA/Tizen-6.0/Tizen-6.0-DA-FHUB/reference/repos/KANTM/packages/

#DA Family Hub Meson64
[repo.fhub_meson64]
url = http://10.113.138.205/snapshots/DA/Tizen-6.0/Tizen-6.0-DA-FHUB/reference/repos/MESON64/packages/

#Tizen 6.0 Base
[repo.base]
url=http://download.tizen.org/snapshots/tizen/base/latest/repos/standard/packages/

