[general]
profile = profile.da_unified_meson64_arm
work_dir=~/gbs-configuration

[profile.da_unified_meson64_arm]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_unified_meson64, repo.base
buildconf=${work_dir}/TIZEN_6.0_DA_UNIFIED_MESON64_BUILD.conf
buildroot=~/gbs-root/tizen_6.0/da-unified/meson64/arm/ad/

[profile.da_unified_meson64_aarch64]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_unified_meson64, repo.base
buildconf=${work_dir}/TIZEN_6.0_DA_UNIFIED_MESON64_BUILD.conf
buildroot=~/gbs-root/tizen_6.0/da-unified/meson64/aarch64/ad/


#DA Unified Meson64
[repo.da_unified_meson64]
url = http://10.113.138.205/snapshots/DA/Tizen-6.0/Tizen-6.0-DA-Unified/reference/repos/MESON64/packages/

#Tizen 6.0 Base
[repo.base]
url=http://download.tizen.org/snapshots/tizen/base/latest/repos/standard/packages/

