[general]
profile = profile.da_unified_meson64_aarch64
work_dir=~/da/gbs-configuration

[profile.da_unified_meson64_aarch64]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_unified_meson64, repo.base
buildconf=${work_dir}/TIZEN_6.0_DA_UNIFIED_MESON64_BUILD.conf
buildroot=~/gbs-root/tizen_6.0/da-unified/meson64/aarch64/ad/

[profile.da_unified_r18_aarch64]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_unified_r18, repo.base
buildconf=${work_dir}/TIZEN_6.0_DA_UNIFIED_R18_BUILD.conf
buildroot=~/gbs-root/tizen_6.0/da-unified/r18/aarch64/ad/


#DA Unified Meson64
[repo.da_unified_meson64]
url = http://10.113.138.205/snapshots/DA/Tizen-6.0/Tizen-6.0-DA-Unified/reference/repos/MESON64/packages/

#DA Unified R18
[repo.da_unified_r18]
url = http://10.113.138.205/snapshots/DA/Tizen-6.0/Tizen-6.0-DA-Unified/reference/repos/R18/packages/

#Tizen 6.0 Base
[repo.base]
url=http://10.91.252.21/product-mp-tizen-6.0-da-base/latest/repos/standard/packages/

