[general]
profile = profile.ad_fhub_kantm_arm
work_dir=~/da/gbs-configuration

######################################## AD ############################################################################
[profile.ad_fhub_kantm_arm]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.ad_fhub_kantm, repo.ad_base
buildconf=${work_dir}/TIZEN_6.0_DA_FHUB_KANTM_BUILD.conf
buildroot=~/gbs-root/tizen_6.0/fhub/kantm/arm/ad/

[profile.ad_fhub_meson64_arm]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.ad_fhub_meson64, repo.ad_base
buildconf=${work_dir}/TIZEN_6.0_DA_FHUB_MESON64_BUILD.conf
buildroot=~/gbs-root/tizen_6.0/fhub/meson64/arm/ad/

[profile.ad_fhub_meson64_aarch64]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.ad_fhub_meson64, repo.ad_base
buildconf=${work_dir}/TIZEN_6.0_DA_FHUB_MESON64_BUILD.conf
buildroot=~/gbs-root/tizen_6.0/fhub/meson64/aarch64/ad/

#DA Family Hub KantM
[repo.ad_fhub_kantm]
url = http://10.113.138.205/snapshots/DA/Tizen-6.0/Tizen-6.0-DA-FHUB/reference/repos/KANTM/packages/

#DA Family Hub Meson64
[repo.ad_fhub_meson64]
url = http://10.113.138.205/snapshots/DA/Tizen-6.0/Tizen-6.0-DA-FHUB/reference/repos/MESON64/packages/

#Tizen 6.0 Base
[repo.ad_base]
url=http://10.91.252.21/product-mp-tizen-6.0-da-base/latest/repos/standard/packages/

######################################## DV ############################################################################
[profile.dv_fhub9_kantm_arm]
repos = repo.dv_fhub9_kantm, repo.dv_base
buildconf=${work_dir}/TIZEN_6.0_DA_FHUB_KANTM_BUILD.conf
buildroot=~/gbs-root/tizen_6.0/fhub9/kantm/arm/dv/

[profile.dv_fhub9_meson64_arm]
repos = repo.dv_fhub9_meson64, repo.dv_base
buildconf=${work_dir}/TIZEN_6.0_DA_FHUB_MESON64_BUILD.conf
buildroot=~/gbs-root/tizen_6.0/fhub9/meson64/arm/dv/

[profile.dv_fhub9_meson64_aarch64]
repos = repo.dv_fhub9_meson64, repo.dv_base
buildconf=${work_dir}/TIZEN_6.0_DA_FHUB_MESON64_BUILD.conf
buildroot=~/gbs-root/tizen_6.0/fhub9/meson64/aarch64/dv/

[profile.dv_fhub8_kantm_arm]
repos = repo.dv_fhub8_kantm, repo.dv_base
buildconf=${work_dir}/TIZEN_6.0_DA_FHUB_KANTM_BUILD.conf
buildroot=~/gbs-root/tizen_6.0/fhub8/kantm/arm/dv/

[profile.dv_fhub8_meson64_arm]
repos = repo.dv_fhub8_meson64, repo.dv_base
buildconf=${work_dir}/TIZEN_6.0_DA_FHUB_MESON64_BUILD.conf
buildroot=~/gbs-root/tizen_6.0/fhub8/meson64/arm/dv/

[profile.dv_fhub8_meson64_aarch64]
repos = repo.dv_fhub8_meson64, repo.dv_base
buildconf=${work_dir}/TIZEN_6.0_DA_FHUB_MESON64_BUILD.conf
buildroot=~/gbs-root/tizen_6.0/fhub8/meson64/aarch64/dv/

#DA Family Hub KantM
[repo.dv_fhub9_kantm]
url = http://10.91.252.21/snapshots/DA/Tizen-6.0/Prod-DV-Tizen-6.0-DA-FHUB9/reference/repos/KANTM/packages/

#DA Family Hub Meson64
[repo.dv_fhub9_meson64]
url = http://10.91.252.21/snapshots/DA/Tizen-6.0/Prod-DV-Tizen-6.0-DA-FHUB9/reference/repos/MESON64/packages/

#DA Family Hub KantM
[repo.dv_fhub8_kantm]
url = http://10.91.252.21/snapshots/DA/Tizen-6.0/Prod-DV-Tizen-6.0-DA-FHUB8/reference/repos/KANTM/packages/

#DA Family Hub Meson64
[repo.dv_fhub8_meson64]
url = http://10.91.252.21/snapshots/DA/Tizen-6.0/Prod-DV-Tizen-6.0-DA-FHUB8/reference/repos/MESON64/packages/

#Tizen 6.0 Base
[repo.dv_base]
url=http://10.91.255.30/download/snapshots/product/da/6.0/product-mp-tizen-6.0-da-base/latest/repos/standard/packages/
