[general]
profile = profile.da_unified_meson64_aarch64
work_dir=~/da/gbs-configuration

[profile.da_unified_qrb4210_aarch64]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_unified_qrb4210, repo.da_base
buildconf=${work_dir}/TIZEN_7.0_DA_UNIFIED_BUILD_QRB4210.conf
buildroot=~/gbs-root/tizen-7.0/da-unified/ad/qrb4210/aarch64/

[profile.da_unified_kantm_armv7l]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_unified_kantm, repo.da_base
buildconf=${work_dir}/TIZEN_7.0_DA_UNIFIED_BUILD_KANTM.conf
buildroot=~/gbs-root/tizen-7.0/da-unified/ad/kantm/armv7l/

[profile.da_unified_meson64_aarch64]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_unified_meson64, repo.da_base
buildconf=${work_dir}/TIZEN_7.0_DA_UNIFIED_BUILD_MESON64.conf
buildroot=~/gbs-root/tizen-7.0/da-unified/ad/meson64/aarch64/

[profile.da_unified_meson64_armv7l]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_unified_meson64, repo.da_base
buildconf=${work_dir}/TIZEN_7.0_DA_UNIFIED_BUILD_MESON64.conf
buildroot=~/gbs-root/tizen-7.0/da-unified/ad/meson64/armv7l/

[profile.da_unified_emulator_aarch64]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_unified_emulator, repo.da_base
buildconf=${work_dir}/TIZEN_7.0_DA_UNIFIED_BUILD_EMULATOR.conf
buildroot=~/gbs-root/tizen-7.0/da-unified/ad/emulator/aarch64/

[profile.da_unified_emulator_armv7l]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_unified_emulator, repo.da_base
buildconf=${work_dir}/TIZEN_7.0_DA_UNIFIED_BUILD_EMULATOR.conf
buildroot=~/gbs-root/tizen-7.0/da-unified/ad/emulator/armv7l/

#DA Unified QRB4210
[repo.da_unified_qrb4210]
url = http://10.113.138.205/snapshots/DA/Tizen-7.0/Tizen-7.0-DA-Unified/reference/repos/QRB4210/packages/

#DA Unified KANTM
[repo.da_unified_kantm]
url = http://10.113.138.205/snapshots/DA/Tizen-7.0/Tizen-7.0-DA-Unified/reference/repos/KANTM/packages/

#DA Unified MESON64
[repo.da_unified_meson64]
url = http://10.113.138.205/snapshots/DA/Tizen-7.0/Tizen-7.0-DA-Unified/reference/repos/MESON64/packages/

#DA Unified Emulator
[repo.da_unified_emulator]
url = http://10.113.138.205/snapshots/DA/Tizen-7.0/Tizen-7.0-DA-Unified/reference/repos/emulator/packages/

#DA Base
[repo.da_base]
url=http://10.113.138.205/snapshots/DA/Tizen-7.0/Tizen-7.0-DA-Base/reference/repos/standard/packages/
