[general]
profile = profile.da_platform
work_dir=~/da/gbs-configuration

[profile.da_platform]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_platform, repo.da_base
buildconf=${work_dir}/TIZEN_NEXT_DA_PLATFORM_BUILD.conf

[profile.da_hal_qrb4210]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_hal_qrb4210, repo.da_platform, repo.da_base
buildconf=${work_dir}/TIZEN_NEXT_DA_HAL_BUILD_QRB4210.conf

[profile.da_hal_kodiak]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_hal_kodiak, repo.da_platform, repo.da_base
buildconf=${work_dir}/TIZEN_NEXT_DA_HAL_BUILD_KODIAK.conf

[profile.da_hal_meson64]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_hal_meson64, repo.da_platform, repo.da_base
buildconf=${work_dir}/TIZEN_NEXT_DA_HAL_BUILD_MESON64.conf

[profile.da_hal_pontusml]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_hal_pontusml, repo.da_platform, repo.da_base
buildconf=${work_dir}/TIZEN_NEXT_DA_HAL_BUILD_PONTUSML.conf

[profile.da_hal_emulator]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_hal_emulator, repo.da_platform, repo.da_base
buildconf=${work_dir}/TIZEN_NEXT_DA_HAL_BUILD_EMULATOR.conf

#DA HAL KODIAK
[repo.da_hal_kodiak]
url = http://10.113.138.205/snapshots/DA/Tizen-Next/Tizen-DA-HAL/reference/repos/KODIAK/packages/

#DA HAL QRB4210
[repo.da_hal_qrb4210]
url = http://10.113.138.205/snapshots/DA/Tizen-Next/Tizen-DA-HAL/reference/repos/QRB4210/packages/

#DA HAL MESON64
[repo.da_hal_meson64]
url = http://10.113.138.205/snapshots/DA/Tizen-Next/Tizen-DA-HAL/reference/repos/MESON64/packages/

#DA HAL PONTUSML
[repo.da_hal_pontusml]
url = http://10.113.138.205/snapshots/DA/Tizen-Next/Tizen-DA-HAL/reference/repos/PONTUSML/packages/

#DA HAL Emulator
[repo.da_hal_emulator]
url = http://10.113.138.205/snapshots/DA/Tizen-Next/Tizen-DA-HAL/reference/repos/emulator/packages/

#DA Platform
[repo.da_platform]
url = http://10.113.138.205/snapshots/DA/Tizen-Next/Tizen-DA-Platform/reference/repos/standard/packages/

#DA Base
[repo.da_base]
url = http://10.113.138.205/snapshots/DA/Tizen-Next/Tizen-DA-Base/reference/repos/standard/packages/

