[general]
profile = profile.fhub4_kantm
work_dir=~/tizen/spin/product/da/scm/meta/gbs-build-config

#------------------------ FHUB4/5 KANTM AD BUILD -------------------------------

[profile.fhub4_kantm]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.fhub4_kantm, repo.base_arm
buildconf=${work_dir}/TIZEN_4.0_DA_FHUB_BUILD_KANTM.conf
buildroot=~/gbs-root/tizen_4.0_spin/fhub4/kantm/ad/

#Family Hub 4 KANT-M
[repo.fhub4_kantm]
url = http://165.213.149.200/download/snapshots/tizen/4.0-da-fhub4/latest/repos/KANTM/packages/

#Tizen 4.0 Base ARM
[repo.base_arm]
url=http://165.213.149.200/download/public_mirror/tizen/4.0-base/latest/repos/arm/packages/

#------------------------ KANTM4/5 DV/MP BUILD ---------------------------------
[profile.dv_fhub4_kantm]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.dv_fhub4_kantm, repo.mp_da_base_arm32
buildconf=${work_dir}/TIZEN_4.0_DA_FHUB_BUILD_KANTM.conf
buildroot=~/gbs-root/tizen_4.0_spin/fhub4/kantm/dv/

[profile.mp_fhub4_kantm]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.mp_fhub4_kantm, repo.mp_da_base_arm32
buildconf=${work_dir}/TIZEN_4.0_DA_FHUB_BUILD_KANTM.conf
buildroot=~/gbs-root/tizen_4.0_spin/fhub4/kantm/mp/

[profile.dv_fhub5_kantm]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.dv_fhub5_kantm, repo.mp_da_base_arm32
buildconf=${work_dir}/TIZEN_4.0_DA_FHUB_BUILD_KANTM.conf
buildroot=~/gbs-root/tizen_4.0_spin/fhub4/kantm/dv/

[profile.mp_fhub5_kantm]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.mp_fhub5_kantm, repo.mp_da_base_arm32
buildconf=${work_dir}/TIZEN_4.0_DA_FHUB_BUILD_KANTM.conf
buildroot=~/gbs-root/tizen_4.0_spin/fhub5/kantm/mp/

#DV Family Hub 5 KANTM
[repo.dv_fhub5_kantm]
url = http://10.91.255.30/download/snapshots/product/da/4.0/product-dv-tizen-4.0-da-fhub5/latest/repos/KANTM/packages/

#MP Family Hub 5 KANTM
[repo.mp_fhub5_kantm]
url = http://10.91.255.30/download/snapshots/product/da/4.0/product-mp-tizen-4.0-da-fhub5/latest/repos/KANTM/packages/

#DV Family Hub 4 KANTM
[repo.dv_fhub4_kantm]
url = http://10.91.255.30/download/snapshots/product/da/4.0/product-dv-tizen-4.0-da-fhub4/latest/repos/KANTM/packages/

#MP Family Hub 4 KANTM
[repo.mp_fhub4_kantm]
url = http://10.91.255.30/download/snapshots/product/da/4.0/product-mp-tizen-4.0-da-fhub4/latest/repos/KANTM/packages/

#MP Tizen 4.0 Base ARM 32-bit
[repo.mp_da_base_arm32]
url=http://10.91.255.30/download/snapshots/product/da/4.0/product-mp-tizen-4.0-da-base/latest/repos/arm/packages/

#------------------------- Emulator Build --------------------------------------
[profile.fhub4_emulator32]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.fhub4_emulator, repo.base_emulator32
buildconf=${work_dir}/TIZEN_4.0_DA_FHUB_BUILD_EMULATOR.conf
buildroot=~/gbs-root/tizen_4.0_spin/fhub4/emulator/32/ad/

[profile.fhub4_emulator64]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.fhub4_emulator, repo.base_emulator64
buildconf=${work_dir}/TIZEN_4.0_DA_FHUB_BUILD_EMULATOR.conf
buildroot=~/gbs-root/tizen_4.0_spin/fhub4/emulator/64/ad/

#Family Hub 4 Emulator
[repo.fhub4_emulator]
url=http://165.213.149.200/download/snapshots/tizen/4.0-da-fhub4/latest/repos/emulator/packages/

#Tizen 4.0 Base Emulator 32
[repo.base_emulator32]
url=http://165.213.149.200/download/public_mirror/tizen/4.0-base/latest/repos/emulator32/packages/

#Tizen 4.0 Base Emulator 64
[repo.base_emulator64]
url=http://165.213.149.200/download/public_mirror/tizen/4.0-base/latest/repos/emulator64/packages/

