[general]
profile = profile.da_robot_r18_aarch64
work_dir=~/da/gbs-configuration

[profile.da_robot_qrb4210_aarch64]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_robot_qrb4210, repo.base
buildconf=${work_dir}/TIZEN_6.5_DA_ROBOT_QRB4210_BUILD.conf
buildroot=~/gbs-root/tizen_6.5/da-robot/qrb4210/aarch64/ad/

[profile.da_robot_r18_aarch64]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_robot_r18, repo.base
buildconf=${work_dir}/TIZEN_6.5_DA_ROBOT_R18_BUILD.conf
buildroot=~/gbs-root/tizen_6.5/da-robot/r18/aarch64/ad/


#DA Robot QRB4210
[repo.da_robot_qrb4210]
url = http://10.113.138.205/snapshots/DA/Tizen-6.5/Tizen-6.5-DA-Robot/reference/repos/QRB4210/packages/

#DA Robot R18
[repo.da_robot_r18]
url = http://10.113.138.205/snapshots/DA/Tizen-6.5/Tizen-6.5-DA-Robot/reference/repos/R18/packages/

#Tizen 6.5 Base
[repo.base]
url=http://10.113.136.32/download_trbs/public_mirror/tizen/6.5-base/latest/repos/standard/packages/

