// https://www.w3.org/TR/webstorage/#the-storage-interface

interface Storage {
    [RaisesException] readonly attribute unsigned long length;
    [RaisesException] DOMString? key(unsigned long index);
    [RaisesException] getter DOMString? getItem(DOMString key);
    [RaisesException] setter void setItem(DOMString key, DOMString data);
    [RaisesException] void removeItem(DOMString key);
    [RaisesException] void clear();
    [RaisesException] deleter void (DOMString name);
};
