version: 2
jobs:
  build_android:
    docker:
      - image: circleci/android:api-28-ndk-r17b
    environment:
      JVM_OPTS: -Xmx3200m
      resource_class: medium+
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b6:c9:79:20:89:ac:5d:2d:8e:6f:3f:12:0d:b3:45:cf"
      - run:
          name: Set proxy enviroment
          command: curl -sL https://art.sec.samsung.net/artifactory/tools/CircleCI/scripts/set_proxy_setting.sh | sh
      - run:
          name: Update cmake
          command: (while sleep 3; do echo "y"; done) | /opt/android/sdk/tools/bin/sdkmanager "cmake;3.10.2.4988404" --proxy=http --proxy_host=${proxyHost} --proxy_port=${proxyPort} || true
      - run:
          name: Update SDK
          command: /opt/android/sdk/tools/bin/sdkmanager --update --proxy=http --proxy_host=${proxyHost} --proxy_port=${proxyPort} || true
      - run:
          name: Accpect SDK license
          command: /opt/android/sdk/tools/bin/sdkmanager --licenses --proxy=http --proxy_host=${proxyHost} --proxy_port=${proxyPort} || true
      - checkout
      - run:
          name: Prepare submodule
          command: git submodule update --init
      - run:
          name: Install ninja
          command: sudo apt-get install ninja-build
      - run:
          name: Install Jinja2
          command: sudo pip install Jinja2
      - run:
          name: Prepare escargot submodule
          working_directory: third_party/escargot/
          command: git submodule update --init third_party
      - run:
          name: Make escargot header directory
          working_directory: third_party/escargot/
          command: mkdir -p include
      - run:
          name: Prepare binding
          command: python binding_generator/scripts/starfish_code_generator.py src/ src/binding/
      - run:
          name: Build Debug Apk
          working_directory: build/android/shell_standalone/
          command: ./gradlew :app:assembleDebug
      - run:
          name: Build Release Apk
          working_directory: build/android/shell_standalone/
          command: ./gradlew :app:assembleRelease
  build_x64_glfw_debug:
    docker:
      - image: art.sec.samsung.net/ci-docker/lws/starfish:latest
    working_directory: ~/starfish-workflows
    environment:
    resource_class: xlarge
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b6:c9:79:20:89:ac:5d:2d:8e:6f:3f:12:0d:b3:45:cf"
      - run: curl -sL https://art.sec.samsung.net/artifactory/tools/CircleCI/scripts/set_proxy_setting.sh | sh
      - run:
            name: Restart network
            command: /etc/init.d/networking restart
      - checkout
      - run:
            name : Check tidy
            command: ./tool/check_tidy.py
      - run:
            name : Run build script
            no_output_timeout: 20m
            command: /root/workspace/build.sh x64_glfw_debug
      - run:
            name : Install test dep
            command: ninja install_pixel_test_dep
      - run:
            no_output_timeout: 10m
            name : Run test
            command: /root/workspace/run_test.sh
  build_x64_glfw_debug_wasm:
    docker:
      - image: art.sec.samsung.net/ci-docker/lws/starfish:latest
    working_directory: ~/starfish-workflows
    environment:
    resource_class: xlarge
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b6:c9:79:20:89:ac:5d:2d:8e:6f:3f:12:0d:b3:45:cf"
      - run: curl -sL https://art.sec.samsung.net/artifactory/tools/CircleCI/scripts/set_proxy_setting.sh | sh
      - checkout
      - run:
            name : Run build script
            no_output_timeout: 20m
            command: /root/workspace/build.sh x64_glfw_debug_wasm
      - run:
            name : Run simple demo app
            no_output_timeout: 10m
            command: xvfb-run -s '-screen 0 1920x1080x24' -a ./Starfish https://liona24.github.io/wasm-tetris/ --crash-test || exit 1
  build_x64_glfw_release:
    docker:
      - image: art.sec.samsung.net/ci-docker/lws/starfish:latest
    working_directory: ~/starfish-workflows
    environment:
    resource_class: xlarge
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b6:c9:79:20:89:ac:5d:2d:8e:6f:3f:12:0d:b3:45:cf"
      - run: curl -sL https://art.sec.samsung.net/artifactory/tools/CircleCI/scripts/set_proxy_setting.sh | sh
      - checkout
      - run:
            name : Run build script
            no_output_timeout: 20m
            command: /root/workspace/build.sh x64_glfw_release
  build_x64_efl_headless_debug:
    docker:
      - image: art.sec.samsung.net/ci-docker/lws/starfish:latest
    working_directory: ~/starfish-workflows
    environment:
    resource_class: xlarge
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b6:c9:79:20:89:ac:5d:2d:8e:6f:3f:12:0d:b3:45:cf"
      - run: curl -sL https://art.sec.samsung.net/artifactory/tools/CircleCI/scripts/set_proxy_setting.sh | sh
      - checkout
      - run:
            name : Run build script
            no_output_timeout: 20m
            command: /root/workspace/build.sh x64_efl_headless
workflows:
  version: 2
  build_All:
    jobs:
      - build_x64_glfw_debug
      - build_x64_glfw_debug_wasm
      - build_x64_glfw_release
      - build_x64_efl_headless_debug
