[general]
profile = profile.tizen_standard

[profile.tizen_standard]
repos = repo.base-standard, repo.unified-standard
[profile.tizen_emulator]
repos = repo.base-standard, repo.unified-emulator

[repo.base-standard]
url=http://download.tizen.org/snapshots/TIZEN/Tizen/Tizen-Base/reference/repos/standard/packages/
[repo.unified-standard]
url=http://download.tizen.org/snapshots/TIZEN/Tizen/Tizen-Unified/reference/repos/standard/packages/
[repo.unified-emulator]
url=http://download.tizen.org/snapshots/TIZEN/Tizen/Tizen-Unified/reference/repos/emulator/packages/
