[general]
profile = profile.aitt_latest
user =
passwdx =

[profile.aitt_latest]
repos = repo.addition, repo.latest_base, repo.latest_std
buildroot = ~/GBS-ROOT/latest

[repo.latest_base]
url=http://download.tizen.org/snapshots/TIZEN/Tizen/Tizen-Base/latest/repos/standard/packages/

[repo.latest_std]
url=http://download.tizen.org/snapshots/TIZEN/Tizen/Tizen-Unified/latest/repos/standard/packages/

[repo.addition]
url=https://art.sec.samsung.net/artifactory/beyond_generic/aitt/latest/packages/


[profile.aitt_t65]
repos = repo.t65_base, repo.t65_std, repo.addition
buildroot = ~/GBS-ROOT/t65std

[repo.t65_base]
url=http://download.tizen.org/snapshots/tizen/6.5-base/latest/repos/standard/packages/

[repo.t65_std]
url=http://download.tizen.org/snapshots/tizen/6.5-unified/latest/repos/standard/packages/

