[general]
profile = profile.tizen_5.5_standard


[profile.tizen_5.5_standard]
repos = repo.5.5-base-standard, repo.5.5-unified-standard
[profile.tizen_5.5_emulator]
repos = repo.5.5-base-standard, repo.5.5-unified-emulator

[repo.5.5-base-standard]
url=http://download.tizen.org/snapshots/TIZEN/Tizen-5.5/Tizen-5.5-Base/reference/repos/standard/packages/
[repo.5.5-unified-standard]
url=http://download.tizen.org/snapshots/TIZEN/Tizen-5.5/Tizen-5.5-Unified/reference/repos/standard/packages/
[repo.5.5-unified-emulator]
url=http://download.tizen.org/snapshots/TIZEN/Tizen-5.5/Tizen-5.5-Unified/reference/repos/emulator/packages/
