[general]
profile = profile.tizen_robot_unified
user = obs_viewer
passwdx = QlpoOTFBWSZTWWV18UwAAAKDgAAAkiCZgCAAMQZMQQDJ6jQwAvxdyRThQkGV18Uw

[profile.tizen_robot_unified]
repos = repo.9.0-base-standard, repo.9.0-robot-unified-standard

[profile.tizen_robot_movable]
repos = repo.X-base-standard, repo.9.0-robot-movable

[obs.tizen]
url = https://api.tizen.org

[repo.9.0-base-standard]
url = http://download.tizen.org/snapshots/TIZEN/Tizen/Tizen-Base/reference/repos/standard/packages/

[repo.X-base-standard]
url = http://download.tizen.org/snapshots/TIZEN/Tizen/Tizen-Base-X/reference/repos/standard/packages/

[repo.9.0-robot-unified-standard]
url = http://10.113.138.205/snapshots/SR/Tizen-9.0/Tizen-9.0-Robot-Unified/reference/repos/standard/packages/

[repo.9.0-robot-movable]
url = http://10.113.138.205/snapshots/VD/Tizen-9.0/Tizen-9.0-VD-Movable-C8550/reference/repos/standard/packages/
