[general]
profile = profile.tizen_9.0_standard

[profile.tizen_9.0_standard]
repos = repo.9.0-base-standard, repo.9.0-unified-standard
[profile.tizen_9.0_emulator]
repos = repo.9.0-base-standard, repo.9.0-unified-emulator

[repo.9.0-base-standard]
url=http://download.tizen.org/snapshots/TIZEN/Tizen-9.0/Tizen-9.0-Base/reference/repos/standard/packages/
[repo.9.0-unified-standard]
url=http://download.tizen.org/snapshots/TIZEN/Tizen-9.0/Tizen-9.0-Unified/reference/repos/standard/packages/
[repo.9.0-unified-emulator]
url=http://download.tizen.org/snapshots/TIZEN/Tizen-9.0/Tizen-9.0-Unified/reference/repos/emulator/packages/
