[general]
profile = profile.tizen_robot_serving_standard
user = obs_viewer
passwdx = QlpoOTFBWSZTWWV18UwAAAKDgAAAkiCZgCAAMQZMQQDJ6jQwAvxdyRThQkGV18Uw

[profile.tizen_robot_serving_standard]
repos = repo.public_base_6.5_arm, repo.tizen_serving_robot

[profile.tizen_robot_gems_standard]
repos = repo.public_base_arm, repo.tizen_gems_robot

[obs.tizen]
url = https://api.tizen.org

[repo.public_base_arm]
url = http://download.tizen.org/snapshots/tizen/6.5-base/latest/repos/standard/packages/

[repo.public_base_6.5_arm]
url = http://download.tizen.org/releases/milestone/tizen/base/latest/repos/standard/packages/

[repo.tizen_serving_robot]
url = http://10.113.136.26/snapshots/SR/Tizen-6.5/Tizen-6.5-Robot-Unified/latest/repos/standard/packages/

[repo.tizen_gems_robot]
url = http://10.113.136.26/snapshots/ROBOT/Tizen-6.5/Tizen-6.5-Robot-Gems/latest/repos/standard/packages/
