[general]
profile = profile.tizen

[profile.tizen]
repos = repo.base, repo.unified, repo.unified-aot

#
# For android on tizen
#
[repo.base]
url = http://download.tizen.org/snapshots/TIZEN/Tizen/Tizen-Base/reference/repos/standard/packages/

[repo.unified]
url = http://download.tizen.org/snapshots/TIZEN/Tizen/Tizen-Unified/reference/repos/standard/packages/

[repo.unified-aot]
url = http://10.113.138.205/snapshots/SR/Tizen-9.0/Tizen-9.0-Unified-AOT/reference/repos/standard/packages/
