[general]
profile = profile.tizen

[profile.tizen]
repos = repo.base, repo.unified

#
# For hybris
#
[repo.base]
url = https://bart.sec.samsung.net/artifactory/download-tizen-generic-remote/snapshots/TIZEN/Tizen/Tizen-Base/reference/repos/standard/packages/

[repo.unified]
url = http://10.113.138.205/snapshots/SR/Tizen-10.0/Tizen-10.0-Unified-GBM/reference/repos/standard/packages/
