[general]
profile = profile.tizen_6.0_standard

[profile.tizen_6.0_standard]
repos = repo.6.0-base-standard, repo.6.0-unified-standard
[profile.tizen_6.0_emulator]
repos = repo.6.0-base-standard, repo.6.0-unified-emulator

[repo.6.0-base-standard]
url=http://download.tizen.org/snapshots/TIZEN/Tizen-6.0/Tizen-6.0-Base/reference/repos/standard/packages/
[repo.6.0-unified-standard]
url=http://download.tizen.org/snapshots/TIZEN/Tizen-6.0/Tizen-6.0-Unified/reference/repos/standard/packages/
[repo.6.0-unified-emulator]
url=http://download.tizen.org/snapshots/TIZEN/Tizen-6.0/Tizen-6.0-Unified/reference/repos/emulator/packages/
