[general]
profile = profile.tizen_5.5_speaker

[profile.tizen_5.5_speaker]
obs = obs.tizen
repos = repo.tizen_speaker_5.5_base, repo.tizen_5.5_speaker

[profile.tizen_6.0_speaker]
obs = obs.tizen
repos = repo.tizen_speaker_6.0_base, repo.tizen_6.0_speaker

[profile.tizen_6.5_speaker]
obs = obs.tizen
repos = repo.tizen_speaker_6.5_base, repo.tizen_6.5_speaker

[obs.tizen]
url = https://api.tizen.org

[repo.tizen_speaker_5.5_base]
url = http://download.tizen.org/snapshots/tizen/5.5-base/latest/repos/standard/packages/
[repo.tizen_5.5_speaker]
url = http://10.113.136.26/snapshots/SR/Tizen-5.5/Tizen-5.5-Speaker/reference/repos/standard/packages/
[repo.tizen_speaker_6.0_base]
url = http://download.tizen.org/snapshots/tizen/6.0-base/latest/repos/standard/packages/
[repo.tizen_6.0_speaker]
url = http://10.113.136.26/snapshots/SR/Tizen-6.0/Tizen-6.0-Speaker/reference/repos/standard/packages/
[repo.tizen_speaker_6.5_base]
url = http://download.tizen.org/snapshots/tizen/base/latest/repos/standard/packages/
[repo.tizen_6.5_speaker]
url = http://10.113.136.26/snapshots/SR/Tizen-6.0/Tizen-6.0-Speaker/reference/repos/standard/packages/
