[general]
profile = profile.tizen_6.5_standard

[profile.tizen_6.5_standard]
repos = repo.6.5-base-standard, repo.6.5-unified-standard
[profile.tizen_6.5_emulator]
repos = repo.6.5-base-standard, repo.6.5-unified-emulator

[repo.6.5-base-standard]
url=http://download.tizen.org/snapshots/TIZEN/Tizen-6.5/Tizen-6.5-Base/reference/repos/standard/packages/
[repo.6.5-unified-standard]
url=http://download.tizen.org/snapshots/TIZEN/Tizen-6.5/Tizen-6.5-Unified/reference/repos/standard/packages/
[repo.6.5-unified-emulator]
url=http://download.tizen.org/snapshots/TIZEN/Tizen-6.5/Tizen-6.5-Unified/reference/repos/emulator/packages/
