[general]
profile = profile.tizen_robot_unified
user = obs_viewer
passwdx = QlpoOTFBWSZTWWV18UwAAAKDgAAAkiCZgCAAMQZMQQDJ6jQwAvxdyRThQkGV18Uw

[profile.tizen_robot_unified]
repos = repo.7.0-base-standard, repo.7.0-robot-unified-standard

[obs.tizen]
url = https://api.tizen.org

[repo.7.0-base-standard]
url = http://download.tizen.org/snapshots/TIZEN/Tizen-7.0/Tizen-7.0-Base/latest/repos/standard/packages/

[repo.7.0-robot-unified-standard]
url = http://10.113.138.205/snapshots/SR/Tizen-7.0/Tizen-7.0-Robot-Unified/latest/repos/standard/packages/

