[general]
profile = profile.tizen_5.0_standard


[profile.tizen_5.0_standard]
repos = repo.5.0-base-standard, repo.5.0-unified-standard
[profile.tizen_5.0_emulator]
repos = repo.5.0-base-standard, repo.5.0-unified-emulator

[repo.5.0-base-standard]
url=http://download.tizen.org/snapshots/TIZEN/Tizen-5.0/Tizen-5.0-Base/reference/repos/standard/packages/
[repo.5.0-unified-standard]
url=http://download.tizen.org/snapshots/TIZEN/Tizen-5.0/Tizen-5.0-Unified/reference/repos/standard/packages/
[repo.5.0-unified-emulator]
url=http://download.tizen.org/snapshots/TIZEN/Tizen-5.0/Tizen-5.0-Unified/reference/repos/emulator/packages/
