[general]
profile = profile.tizen_robot_unified
user = obs_viewer
passwdx = QlpoOTFBWSZTWWV18UwAAAKDgAAAkiCZgCAAMQZMQQDJ6jQwAvxdyRThQkGV18Uw

[profile.tizen_robot_unified]
repos = repo.8.0-base-standard, repo.8.0-robot-unified-standard

[profile.tizen_robot_unified_rel]
repos = repo.8.0-base-standard, repo.8.0-robot-unified-standard-rel

[profile.tizen_robot_unified_gtr]
repos = repo.8.0-base-standard, repo.8.0-robot-unified-standard-gtr

[obs.tizen]
url = https://api.tizen.org

[repo.8.0-base-standard]
url = http://download.tizen.org/snapshots/TIZEN/Tizen-8.0/Tizen-8.0-Base/latest/repos/standard/packages/

[repo.8.0-robot-unified-standard]
url = http://10.113.138.205/snapshots/SR/Tizen-8.0/Tizen-8.0-Robot-Unified/latest/repos/standard/packages/

[repo.8.0-robot-unified-standard-rel]
url = http://10.113.138.205/snapshots/SR/Tizen-8.0/Tizen-8.0-Robot-Unified-REL/latest/repos/standard/packages/

[repo.8.0-robot-unified-standard-gtr]
url = http://10.113.138.205/snapshots/GTR/Tizen-8.0/Tizen-8.0-RobotGTR-Unified/latest/repos/standard/packages/
