[general]
profile = profile.tizen_4.0_standard

[profile.tizen_4.0_standard]
repos = repo.4.0-base-standard, repo.4.0-unified-standard
[profile.tizen_4.0_emulator]
repos = repo.4.0-base-standard, repo.4.0-unified-emulator

[repo.4.0-base-standard]
url=http://download.tizen.org/snapshots/TIZEN/Tizen-4.0/Tizen-4.0-Base/reference/repos/standard/packages/
[repo.4.0-unified-standard]
url=http://download.tizen.org/snapshots/TIZEN/Tizen-4.0/Tizen-4.0-Unified/reference/repos/standard/packages/
[repo.4.0-unified-emulator]
url=http://download.tizen.org/snapshots/TIZEN/Tizen-4.0/Tizen-4.0-Unified/reference/repos/emulator/packages/
