[general]
profile = profile.tizen

[profile.tizen]
repos = repo.base, repo.unified

#
# For hybris
#
[repo.base]
url = http://10.113.138.205/snapshots/SR/Tizen-9.0/Tizen-9.0-Base/latest/repos/standard/packages/

[repo.unified]
url = http://10.113.138.205/snapshots/SR/Tizen-9.0/Tizen-9.0-Unified-GBM/latest/repos/standard/packages/
