[general]
profile = profile.da_sac_cmcr_standard_armv7l_dev
work_dir=~/da/gbs-configuration/da/sac/cmcr

#dvmai
[profile.da_sac_cmcr_standard_armv7l_dev]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_sac_cmcr_standard_dev, repo.da_base, repo.da_platform_y26_dev_standard
buildconf=${work_dir}/TIZEN_10.0_DA_SAC_STANDARD_BUILD.conf
buildroot=~/gbs-root/tizen-10.0/da-sac-cmcr/standard/armv7l/dev/

[profile.da_sac_cmcr_standard_armv7l_stg]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_sac_cmcr_standard_stg, repo.da_base, repo.da_platform_y26_dev_standard
buildconf=${work_dir}/TIZEN_10.0_DA_SAC_STANDARD_BUILD.conf
buildroot=~/gbs-root/tizen-10.0/da-sac-cmcr/standard/armv7l/stg/

[repo.da_sac_cmcr_standard_dev]
url = http://10.91.252.21/snapshots/DA/Tizen-10.0/Prod-MP-Tizen-10.0-DA-SAC-CMCR-26-Dev/reference/repos/standard/packages/

[repo.da_sac_cmcr_standard_stg]
url = http://10.91.252.21/snapshots/DA/Tizen-10.0/Prod-MP-Tizen-10.0-DA-SAC-CMCR-26-Stg/reference/repos/standard/packages/

#DA Base
[repo.da_base]
url=http://10.113.138.205/snapshots/DA/Tizen-Next/Tizen-DA-Base/reference/repos/standard/packages/

#DA Platform Y26 Dev Standard
[repo.da_platform_y26_dev_standard]
url = http://10.113.138.205/snapshots/DA/Tizen-Next/Tizen-DA-Platform/reference/repos/standard/packages/

#DA Platform Y26 Stg Standard
[repo.da_platform_y26_stg_standard]
url = http://10.113.138.205/snapshots/DA/Tizen-Next/Tizen-DA-Platform/reference/repos/standard/packages/