http://web-platform.test:8000/2dcontext/drawing-paths-to-the-canvas/canvas_complexshapes_ispointInpath_001.htm
#http://web-platform.test:8000/2dcontext/drawing-paths-to-the-canvas/canvas_focus_drawFocusIfNeeded_AAPI_001-manual.html
#
#
#http://web-platform.test:8000/2dcontext/building-paths/canvas_complexshapes_arcto_001-ref.htm
#http://web-platform.test:8000/2dcontext/building-paths/canvas_complexshapes_beziercurveto_001-ref.htm
#http://web-platform.test:8000/2dcontext/building-paths/canvas_complexshapes_arcto_001.htm
#http://web-platform.test:8000/2dcontext/building-paths/canvas_complexshapes_beziercurveto_001.htm
#
#
#http://web-platform.test:8000/2dcontext/tools/current-work-canvas.xhtml
#
#
#http://web-platform.test:8000/2dcontext/line-styles/canvas_linestyles_linecap_001-ref.htm
#http://web-platform.test:8000/2dcontext/line-styles/canvas_linestyles_linecap_001.htm
#
#
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.globalAlpha.canvascopy.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.source-in.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.copy.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.source-out.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.source-atop.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.destination-in.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.lighter.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.destination-over.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.destination-out.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.globalAlpha.canvas.html
#http://web-platform.test:8000/2dcontext/compositing/canvas_compositing_globalcompositeoperation_001.htm
http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.xor.html
#http://web-platform.test:8000/2dcontext/compositing/canvas_compositing_globalcompositeoperation_001-ref.htm
http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.destination-atop.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.source-over.html
#
#
#http://web-platform.test:8000/2dcontext/text-styles/canvas_text_font_001.htm
#http://web-platform.test:8000/2dcontext/text-styles/canvas_text_font_001-ref.htm
#
#
#http://web-platform.test:8000/2dcontext/transformations/canvas_transformations_reset_001-ref.html
#http://web-platform.test:8000/2dcontext/transformations/canvas_transformations_reset_001.html
#http://web-platform.test:8000/2dcontext/transformations/canvas_transformations_scale_001-ref.htm
#http://web-platform.test:8000/2dcontext/transformations/canvas_transformations_scale_001.htm
#
#
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.default.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.get.semitransparent.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.get.solid.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.get.transparent.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.invalidstring.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.invalidtype.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-hsl-1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-hsl-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-hsl-3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-hsl-4.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-hsl-5.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-hsl-6.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-hsl-7.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-hsl-8.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-hsl-9.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-hsla-1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-hsla-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-hsla-3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-hsla-4.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-hsla-5.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-hsla-6.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-hsla-7.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-hsla-8.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-hsla-9.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-rgb-1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-rgb-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-rgb-3.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-rgb-4.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-rgb-5.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-rgb-6.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-rgba-1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-rgba-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-rgba-3.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-rgba-4.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-rgba-5.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-rgba-6.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.current.basic.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.current.changed.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.current.notrendered.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.current.removed.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hex3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hex4.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hex6.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hex8.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hsl-1.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hsl-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hsl-3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hsl-4.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hsl-5.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hsl-6.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hsl-clamp-1.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hsl-clamp-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hsl-clamp-3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hsl-clamp-4.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hsla-1.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hsla-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hsla-clamp-1.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hsla-clamp-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hsla-clamp-3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hsla-clamp-4.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hsla-clamp-5.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.hsla-clamp-6.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.html4.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.css-color-4-hsl-1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.css-color-4-hsl-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.css-color-4-hsl-3.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.css-color-4-hsl-4.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.css-color-4-hsl-5.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.css-color-4-hsla-1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.css-color-4-hsla-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.css-color-4-hsla-3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.css-color-4-rgb-1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.css-color-4-rgb-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.css-color-4-rgb-3.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.css-color-4-rgb-4.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.css-color-4-rgb-5.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.css-color-4-rgba-1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.css-color-4-rgba-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.css-color-4-rgba-3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.hex1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.hex2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.hex3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.hex4.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.hex5.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.hex6.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.hex7.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.hex8.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.hsl-1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.hsl-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.hsl-3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.hsl-4.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.hsl-5.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.hsl-6.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.hsla-1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.hsla-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.hsla-3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.name-1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.name-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.name-3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.name-4.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.name-5.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.rgb-1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.rgb-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.rgb-3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.rgba-1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.rgba-2.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.rgba-3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.rgba-4.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.invalid.rgba-5.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgb-clamp-1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgb-clamp-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgb-clamp-3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgb-clamp-4.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgb-clamp-5.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgb-eof.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgb-num.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgb-percent.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgba-clamp-1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgba-clamp-2.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgba-eof.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgba-num-1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgba-num-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgba-percent.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgba-solid-1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgba-solid-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgba-solid-3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.rgba-solid-4.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.svg-1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.svg-2.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.system.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.transparent-1.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.transparent-2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.empty.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.interpolate.alpha.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.interpolate.colour.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.interpolate.colouralpha.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.interpolate.multiple.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.interpolate.outside.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.interpolate.overlap.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.interpolate.overlap2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.interpolate.solid.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.interpolate.vertical.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.interpolate.zerosize.fill.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.interpolate.zerosize.fillRect.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.interpolate.zerosize.fillText.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.interpolate.zerosize.stroke.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.interpolate.zerosize.strokeRect.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.interpolate.zerosize.strokeText.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.linear.nonfinite.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.linear.transform.1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.linear.transform.2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.linear.transform.3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.object.compare.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.object.crosscanvas.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.object.current.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.object.invalidcolour.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.object.invalidoffset.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.object.return.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.object.type.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.object.update.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.cone.behind.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.cone.beside.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.cone.bottom.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.cone.cylinder.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.cone.front.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.cone.shape1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.cone.shape2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.cone.top.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.equal.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.inside1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.inside2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.inside3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.negative.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.nonfinite.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.outside1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.outside2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.outside3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.touch1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.touch2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.touch3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.transform.1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.transform.2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.radial.transform.3.html
# http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.animated.gif.html // starfish/issues/3485
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.basic.canvas.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.basic.image.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.basic.nocontext.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.basic.type.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.basic.zerocanvas.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.crosscanvas.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.image.broken.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.image.incomplete.emptysrc.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.image.incomplete.immediate.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.image.incomplete.nosrc.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.image.incomplete.reload.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.image.incomplete.removedsrc.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.image.null.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.image.string.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.image.undefined.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.modify.canvas1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.modify.canvas2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.modify.image1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.modify.image2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.norepeat.basic.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.norepeat.coord1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.norepeat.coord2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.norepeat.coord3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.norepeat.outside.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.orientation.canvas.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.orientation.image.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeat.basic.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeat.coord1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeat.coord2.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeat.coord3.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeat.outside.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeatx.basic.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeatx.coord1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeatx.outside.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeaty.basic.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeaty.coord1.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.repeaty.outside.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.repeat.case.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.repeat.empty.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.repeat.null.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.repeat.nullsuffix.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.repeat.undefined.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.repeat.unrecognised.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.repeat.unrecognisednull.html
http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.strokeStyle.default.html
#
#
#http://web-platform.test:8000/2dcontext/the-canvas-state/canvas_state_restore_001.htm
#http://web-platform.test:8000/2dcontext/the-canvas-state/canvas_state_restore_001-ref.htm
#
#
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.order.html
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.rotate.direction.html
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.rotate.nonfinite.html
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.rotate.radians.html
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.rotate.wrapnegative.html
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.rotate.zero.html
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.scale.basic.html
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.scale.large.html
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.scale.multiple.html
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.scale.negative.html
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.scale.nonfinite.html
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.scale.zero.html
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.setTransform.multiple.html
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.setTransform.nonfinite.html
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.setTransform.skewed.html
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.transform.identity.html
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.transform.multiply.html
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.transform.nonfinite.html
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.translate.basic.html
http://web-platform.test:8000/2dcontext/transformations/2d.transformation.translate.nonfinite.html
#
#
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.angle.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.angle.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.angle.3.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.angle.4.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.angle.5.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.angle.6.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.default.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.empty.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.end.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.negative.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.nonempty.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.nonfinite.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.scale.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.scale.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.selfintersect.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.selfintersect.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.shape.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.shape.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.shape.3.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.shape.4.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.shape.5.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.twopie.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.twopie.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.twopie.3.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.twopie.4.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.zero.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.zero.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arc.zeroradius.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arcTo.coincide.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arcTo.coincide.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arcTo.collinear.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arcTo.collinear.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arcTo.collinear.3.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arcTo.ensuresubpath.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arcTo.ensuresubpath.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arcTo.negative.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arcTo.nonfinite.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arcTo.scale.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arcTo.shape.curve1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arcTo.shape.curve2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arcTo.shape.end.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arcTo.shape.start.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arcTo.transformation.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arcTo.zero.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.arcTo.zero.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.beginPath.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.bezierCurveTo.basic.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.bezierCurveTo.ensuresubpath.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.bezierCurveTo.ensuresubpath.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.bezierCurveTo.nonfinite.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.bezierCurveTo.scaled.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.bezierCurveTo.shape.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.clip.basic.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.clip.basic.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.clip.intersect.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.clip.unaffected.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.clip.winding.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.clip.winding.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.closePath.empty.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.closePath.newline.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.closePath.nextpoint.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.fill.closed.basic.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.fill.closed.unaffected.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.fill.overlap.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.fill.winding.add.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.fill.winding.subtract.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.fill.winding.subtract.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.fill.winding.subtract.3.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.initial.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.isPointInPath.arc.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.isPointInPath.basic.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.isPointInPath.basic.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.isPointInPath.bezier.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.isPointInPath.bigarc.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.isPointInPath.edge.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.isPointInPath.empty.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.isPointInPath.nonfinite.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.isPointInPath.outside.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.isPointInPath.subpath.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.isPointInPath.transform.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.isPointInPath.transform.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.isPointInPath.transform.3.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.isPointInPath.transform.4.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.isPointInPath.unclosed.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.isPointInPath.winding.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.lineTo.basic.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.lineTo.ensuresubpath.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.lineTo.ensuresubpath.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.lineTo.nextpoint.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.lineTo.nonfinite.details.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.lineTo.nonfinite.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.moveTo.basic.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.moveTo.multiple.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.moveTo.newsubpath.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.moveTo.nonfinite.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.quadraticCurveTo.basic.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.quadraticCurveTo.ensuresubpath.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.quadraticCurveTo.ensuresubpath.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.quadraticCurveTo.nonfinite.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.quadraticCurveTo.scaled.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.quadraticCurveTo.shape.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.rect.basic.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.rect.closed.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.rect.end.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.rect.end.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.rect.negative.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.rect.newsubpath.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.rect.nonfinite.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.rect.selfintersect.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.rect.winding.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.rect.zero.1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.rect.zero.2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.rect.zero.3.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.rect.zero.4.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.rect.zero.5.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.rect.zero.6.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.stroke.empty.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.stroke.overlap.html
#http://web-platform.test:8000/2dcontext/path-objects/2d.path.stroke.prune.arc.html
#http://web-platform.test:8000/2dcontext/path-objects/2d.path.stroke.prune.closed.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.stroke.prune.corner.html
#http://web-platform.test:8000/2dcontext/path-objects/2d.path.stroke.prune.curve.html
#http://web-platform.test:8000/2dcontext/path-objects/2d.path.stroke.prune.line.html
#http://web-platform.test:8000/2dcontext/path-objects/2d.path.stroke.prune.rect.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.stroke.scale1.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.stroke.scale2.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.stroke.skew.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.stroke.unaffected.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.stroke.union.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.transformation.basic.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.transformation.changing.html
http://web-platform.test:8000/2dcontext/path-objects/2d.path.transformation.multiple.html
#
#
http://web-platform.test:8000/2dcontext/line-styles/2d.line.cap.butt.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.cap.closed.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.cap.invalid.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.cap.open.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.cap.round.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.cap.square.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.cap.valid.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.cross.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.defaults.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.join.bevel.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.join.closed.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.join.invalid.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.join.miter.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.join.open.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.join.parallel.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.join.round.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.join.valid.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.miter.acute.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.miter.exceeded.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.miter.invalid.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.miter.lineedge.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.miter.obtuse.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.miter.rightangle.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.miter.valid.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.miter.within.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.union.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.width.basic.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.width.invalid.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.width.scaledefault.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.width.transformed.html
http://web-platform.test:8000/2dcontext/line-styles/2d.line.width.valid.html
#http://web-platform.test:8000/2dcontext/line-styles/lineto_a.html // lineto_ref.html
http://web-platform.test:8000/2dcontext/line-styles/setLineDash.html
#
#
http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.bitmap.html
http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.clip.html
http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.fillStyle.html
http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.font.html
http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.globalAlpha.html
http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.globalCompositeOperation.html
http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.imageSmoothingEnabled.html
http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.lineCap.html
http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.lineJoin.html
http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.lineWidth.html
http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.miterLimit.html
http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.path.html
#http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.shadowBlur.html
#http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.shadowColor.html
#http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.shadowOffsetX.html
#http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.shadowOffsetY.html
http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.stack.html
http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.stackdepth.html
http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.strokeStyle.html
http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.textAlign.html
http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.textBaseline.html
http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.transformation.html
#http://web-platform.test:8000/2dcontext/the-canvas-state/2d.state.saverestore.underflow.html
#
#
http://web-platform.test:8000/2dcontext/compositing/2d.composite.clip.copy.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.clip.destination-atop.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.clip.destination-in.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.clip.destination-out.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.clip.destination-over.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.clip.lighter.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.clip.source-atop.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.clip.source-in.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.clip.source-out.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.clip.source-over.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.clip.xor.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.globalAlpha.canvas.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.globalAlpha.canvascopy.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.globalAlpha.canvaspattern.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.globalAlpha.default.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.globalAlpha.fill.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.globalAlpha.image.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.globalAlpha.imagepattern.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.globalAlpha.invalid.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.globalAlpha.range.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.image.copy.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.image.destination-atop.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.image.destination-in.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.image.destination-out.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.image.destination-over.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.image.lighter.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.image.source-atop.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.image.source-in.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.image.source-out.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.image.source-over.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.image.xor.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.operation.casesensitive.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.operation.clear.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.operation.darker.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.operation.default.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.operation.get.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.operation.highlight.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.operation.nullsuffix.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.operation.over.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.operation.unrecognised.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.solid.copy.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.solid.destination-atop.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.solid.destination-in.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.solid.destination-out.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.solid.destination-over.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.solid.lighter.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.solid.source-atop.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.solid.source-in.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.solid.source-out.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.solid.source-over.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.solid.xor.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.transparent.copy.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.transparent.destination-atop.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.transparent.destination-in.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.transparent.destination-out.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.transparent.destination-over.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.transparent.lighter.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.transparent.source-atop.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.transparent.source-in.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.transparent.source-out.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.transparent.source-over.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.transparent.xor.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.fill.copy.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.fill.destination-atop.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.fill.destination-in.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.fill.source-in.html
http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.fill.source-out.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.image.copy.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.image.destination-atop.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.image.destination-in.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.image.source-in.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.image.source-out.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.nocontext.copy.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.nocontext.destination-atop.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.nocontext.destination-in.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.nocontext.source-in.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.nocontext.source-out.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.pattern.copy.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.pattern.destination-atop.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.pattern.destination-in.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.pattern.source-in.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.uncovered.pattern.source-out.html
#
#
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.create1.basic.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.create1.initial.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.create1.this.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.create1.type.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.create1.zero.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.create2.basic.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.create2.double.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.create2.initial.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.create2.large.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.create2.negative.html
#http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.create2.nonfinite.html // Failed, equally with major browsers.
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.create2.this.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.create2.type.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.create2.zero.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.get.basic.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.get.clamp.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.get.double.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.get.length.html
#http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.get.nonfinite.html // Failed, equally with major browsers.
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.get.nonpremul.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.get.order.alpha.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.get.order.cols.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.get.order.rgb.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.get.order.rows.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.get.range.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.get.source.negative.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.get.source.outside.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.get.source.size.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.get.type.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.get.unaffected.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.get.zero.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.object.clamp.html
#http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.object.ctor.array.bounds.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.object.ctor.array.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.object.ctor.size.bounds.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.object.ctor.size.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.object.nan.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.object.properties.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.object.readonly.html
#http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.object.round.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.object.set.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.object.string.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.object.undefined.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.put.alpha.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.put.basic.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.put.clip.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.put.created.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.put.cross.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.put.dirty.negative.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.put.dirty.outside.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.put.dirty.rect1.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.put.dirty.rect2.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.put.dirty.zero.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.put.modified.html
#http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.put.nonfinite.html // Failed equally with major browsers.
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.put.null.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.put.path.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.put.unaffected.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.put.unchanged.html
http://web-platform.test:8000/2dcontext/pixel-manipulation/2d.imageData.put.wrongtype.html
#
#
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.clearRect.basic.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.clearRect.clip.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.clearRect.globalalpha.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.clearRect.globalcomposite.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.clearRect.negative.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.clearRect.nonfinite.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.clearRect.path.html
#http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.clearRect.shadow.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.clearRect.transform.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.clearRect.zero.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.fillRect.basic.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.fillRect.clip.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.fillRect.negative.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.fillRect.nonfinite.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.fillRect.path.html
#http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.fillRect.shadow.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.fillRect.transform.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.fillRect.zero.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.strokeRect.basic.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.strokeRect.clip.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.strokeRect.globalalpha.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.strokeRect.globalcomposite.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.strokeRect.negative.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.strokeRect.nonfinite.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.strokeRect.path.html
#http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.strokeRect.shadow.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.strokeRect.transform.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.strokeRect.zero.1.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.strokeRect.zero.2.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.strokeRect.zero.3.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.strokeRect.zero.4.html
http://web-platform.test:8000/2dcontext/drawing-rectangles-to-the-canvas/2d.strokeRect.zero.5.html
#
#
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.3arg.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.5arg.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.9arg.basic.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.9arg.destpos.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.9arg.destsize.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.9arg.sourcepos.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.9arg.sourcesize.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.alpha.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.animated.apng.html
# http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.animated.gif.html // starfish/issues/3485
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.animated.poster.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.broken.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.canvas.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.clip.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.composite.html
#http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.floatsource.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.incomplete.emptysrc.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.incomplete.immediate.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.incomplete.nosrc.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.incomplete.reload.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.incomplete.removedsrc.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.negativedest.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.negativedir.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.negativesource.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.nonfinite.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.nowrap.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.null.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.path.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.self.1.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.self.2.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.svg.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.transform.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.wrongtype.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.zerocanvas.html
#http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.zerosource.html
#http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.zerosource.image.html
#http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/drawimage_canvas.html // FIXME: (150 pass, 1 fail) I guess one failure is because of image smoothing.
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/drawimage_html_image.html
http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/drawimage_svg_image_1.html
#
#
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.align.center.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.align.end.ltr.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.align.end.rtl.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.align.left.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.align.right.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.align.start.ltr.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.align.start.rtl.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.fill.basic-manual.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.fill.maxWidth.NaN.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.fill.maxWidth.bound.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.fill.maxWidth.fontface.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.fill.maxWidth.large-manual.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.fill.maxWidth.negative.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.fill.maxWidth.small.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.fill.maxWidth.zero.html
#http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.fill.rtl-manual.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.fill.unaffected.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.fontface.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.fontface.repeat.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.kern.consistent-manual.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.space.basic.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.space.collapse.nonspace.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.stroke.basic-manual.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.draw.stroke.unaffected.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.measure.width.basic.html
http://web-platform.test:8000/2dcontext/drawing-text-to-the-canvas/2d.text.measure.width.empty.html
#
#
http://web-platform.test:8000/2dcontext/image-smoothing/imagesmoothing.html
#
#
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.alpha.1.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.alpha.2.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.alpha.3.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.alpha.4.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.alpha.5.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.attributes.shadowBlur.initial.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.attributes.shadowBlur.invalid.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.attributes.shadowBlur.valid.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.attributes.shadowColor.initial.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.attributes.shadowColor.invalid.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.attributes.shadowColor.valid.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.attributes.shadowOffset.initial.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.attributes.shadowOffset.invalid.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.attributes.shadowOffset.valid.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.blur.high-manual.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.blur.low-manual.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.canvas.alpha.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.canvas.basic.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.canvas.transparent.1.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.canvas.transparent.2.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.clip.1.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.clip.2.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.clip.3.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.composite.1.html
#http://web-platform.test:8000/2dcontext/shadows/2d.shadow.composite.2.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.composite.3.html
#http://web-platform.test:8000/2dcontext/shadows/2d.shadow.enable.blur.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.enable.off.1.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.enable.off.2.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.enable.x.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.enable.y.html
#http://web-platform.test:8000/2dcontext/shadows/2d.shadow.gradient.alpha.html
#http://web-platform.test:8000/2dcontext/shadows/2d.shadow.gradient.basic.html
#http://web-platform.test:8000/2dcontext/shadows/2d.shadow.gradient.transparent.1.html
#http://web-platform.test:8000/2dcontext/shadows/2d.shadow.gradient.transparent.2.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.image.alpha.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.image.basic.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.image.scale.html
#http://web-platform.test:8000/2dcontext/shadows/2d.shadow.image.section.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.image.transparent.1.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.image.transparent.2.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.offset.negativeX.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.offset.negativeY.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.offset.positiveX.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.offset.positiveY.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.outside.html
#http://web-platform.test:8000/2dcontext/shadows/2d.shadow.pattern.alpha.html
#http://web-platform.test:8000/2dcontext/shadows/2d.shadow.pattern.basic.html
#http://web-platform.test:8000/2dcontext/shadows/2d.shadow.pattern.transparent.1.html
#http://web-platform.test:8000/2dcontext/shadows/2d.shadow.pattern.transparent.2.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.stroke.basic.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.stroke.cap.1.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.stroke.cap.2.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.stroke.join.1.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.stroke.join.2.html
http://web-platform.test:8000/2dcontext/shadows/2d.shadow.stroke.join.3.html
#http://web-platform.test:8000/2dcontext/shadows/2d.shadow.transform.1.html
#http://web-platform.test:8000/2dcontext/shadows/2d.shadow.transform.2.html
