#http://web-platform.test:8000/2dcontext/drawing-paths-to-the-canvas/canvas_complexshapes_ispointInpath_001.htm
#http://web-platform.test:8000/2dcontext/drawing-paths-to-the-canvas/canvas_focus_drawFocusIfNeeded_AAPI_001-manual.html
#
#
#http://web-platform.test:8000/2dcontext/building-paths/canvas_complexshapes_arcto_001-ref.htm
#http://web-platform.test:8000/2dcontext/building-paths/canvas_complexshapes_beziercurveto_001-ref.htm
#http://web-platform.test:8000/2dcontext/building-paths/canvas_complexshapes_arcto_001.htm
#http://web-platform.test:8000/2dcontext/building-paths/canvas_complexshapes_beziercurveto_001.htm
#
#
#http://web-platform.test:8000/2dcontext/tools/current-work-canvas.xhtml
#
#
#http://web-platform.test:8000/2dcontext/line-styles/canvas_linestyles_linecap_001-ref.htm
#http://web-platform.test:8000/2dcontext/line-styles/canvas_linestyles_linecap_001.htm
#
#
#http://web-platform.test:8000/2dcontext/shadows/canvas_shadows_002.htm
#http://web-platform.test:8000/2dcontext/shadows/2d.shadow.canvas.transparent.2.html
#http://web-platform.test:8000/2dcontext/shadows/2d.shadow.canvas.alpha.html
#http://web-platform.test:8000/2dcontext/shadows/2d.shadow.canvas.transparent.1.html
#http://web-platform.test:8000/2dcontext/shadows/canvas_shadows_001.htm
#http://web-platform.test:8000/2dcontext/shadows/2d.shadow.canvas.basic.html
#http://web-platform.test:8000/2dcontext/shadows/canvas_shadows_002-ref.htm
#
#
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.globalAlpha.canvascopy.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.source-in.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.copy.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.source-out.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.source-atop.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.destination-in.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.lighter.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.destination-over.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.destination-out.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.globalAlpha.canvas.html
#http://web-platform.test:8000/2dcontext/compositing/canvas_compositing_globalcompositeoperation_001.htm
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.xor.html
#http://web-platform.test:8000/2dcontext/compositing/canvas_compositing_globalcompositeoperation_001-ref.htm
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.destination-atop.html
#http://web-platform.test:8000/2dcontext/compositing/2d.composite.canvas.source-over.html
#
#
#http://web-platform.test:8000/2dcontext/text-styles/canvas_text_font_001.htm
#http://web-platform.test:8000/2dcontext/text-styles/canvas_text_font_001-ref.htm
#
#
#http://web-platform.test:8000/2dcontext/transformations/canvas_transformations_reset_001-ref.html
#http://web-platform.test:8000/2dcontext/transformations/canvas_transformations_reset_001.html
#http://web-platform.test:8000/2dcontext/transformations/canvas_transformations_scale_001-ref.htm
#http://web-platform.test:8000/2dcontext/transformations/canvas_transformations_scale_001.htm
#
#
#http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.zerocanvas.html
#http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/2d.drawImage.canvas.html
#http://web-platform.test:8000/2dcontext/drawing-images-to-the-canvas/drawimage_canvas.html
#
#
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.crosscanvas.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/canvas_colorsandstyles_createlineargradient_001.htm
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.modify.canvas1.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.gradient.object.crosscanvas.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.basic.zerocanvas.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.modify.canvas2.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.paint.orientation.canvas.html
#http://web-platform.test:8000/2dcontext/fill-and-stroke-styles/2d.pattern.basic.canvas.html
#
#
#http://web-platform.test:8000/2dcontext/the-canvas-state/canvas_state_restore_001.htm
#http://web-platform.test:8000/2dcontext/the-canvas-state/canvas_state_restore_001-ref.htm
