http://web-platform.test:8000/content-security-policy/base-uri/base-uri-allow.sub.html
http://web-platform.test:8000/content-security-policy/base-uri/base-uri-deny.sub.html
#http://web-platform.test:8000/content-security-policy/base-uri/base-uri_iframe_sandbox.sub.html # inheritance
#http://web-platform.test:8000/content-security-policy/base-uri/report-uri-does-not-respect-base-uri.sub.html # Response Header
#
#
http://web-platform.test:8000/content-security-policy/blob/blob-urls-do-not-match-self.sub.html
http://web-platform.test:8000/content-security-policy/blob/blob-urls-match-blob.sub.html
#http://web-platform.test:8000/content-security-policy/blob/self-doesnt-match-blob.sub.html # Worker
#http://web-platform.test:8000/content-security-policy/blob/star-doesnt-match-blob.sub.html # Worker
#
#
http://web-platform.test:8000/content-security-policy/child-src/child-src-about-blank-allowed-by-default.sub.html
http://web-platform.test:8000/content-security-policy/child-src/child-src-about-blank-allowed-by-scheme.sub.html
http://web-platform.test:8000/content-security-policy/child-src/child-src-allowed.sub.html
http://web-platform.test:8000/content-security-policy/child-src/child-src-blocked.sub.html
http://web-platform.test:8000/content-security-policy/child-src/child-src-conflicting-frame-src.sub.html
http://web-platform.test:8000/content-security-policy/child-src/child-src-cross-origin-load.sub.html
http://web-platform.test:8000/content-security-policy/child-src/child-src-redirect-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/child-src/child-src-worker-allowed.sub.html
#http://web-platform.test:8000/content-security-policy/child-src/child-src-worker-blocked.sub.html
#
#
#http://web-platform.test:8000/content-security-policy/connect-src/connect-src-beacon-allowed.sub.html
#http://web-platform.test:8000/content-security-policy/connect-src/connect-src-beacon-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/connect-src/connect-src-beacon-redirect-to-blocked.sub.html
http://web-platform.test:8000/content-security-policy/connect-src/connect-src-eventsource-allowed.sub.html
http://web-platform.test:8000/content-security-policy/connect-src/connect-src-eventsource-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/connect-src/connect-src-eventsource-redirect-to-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/connect-src/connect-src-websocket-allowed.sub.html
#http://web-platform.test:8000/content-security-policy/connect-src/connect-src-websocket-blocked.sub.html
http://web-platform.test:8000/content-security-policy/connect-src/connect-src-xmlhttprequest-allowed.sub.html
http://web-platform.test:8000/content-security-policy/connect-src/connect-src-xmlhttprequest-blocked.sub.html
http://web-platform.test:8000/content-security-policy/connect-src/connect-src-xmlhttprequest-redirect-to-blocked.sub.html
#
#
#http://web-platform.test:8000/content-security-policy/connect-src/shared-worker-connect-src-allowed.sub.html
#http://web-platform.test:8000/content-security-policy/connect-src/shared-worker-connect-src-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/connect-src/worker-connect-src-allowed.sub.html
#http://web-platform.test:8000/content-security-policy/connect-src/worker-connect-src-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/connect-src/worker-from-guid.sub.html
#
#
http://web-platform.test:8000/content-security-policy/default-src/default-src-inline-allowed.sub.html
http://web-platform.test:8000/content-security-policy/default-src/default-src-inline-blocked.sub.html
#
#
#http://web-platform.test:8000/content-security-policy/embedded-enforcement/allow_csp_from-header.html
#http://web-platform.test:8000/content-security-policy/embedded-enforcement/iframe-csp-attribute.html
#http://web-platform.test:8000/content-security-policy/embedded-enforcement/required-csp-header-cascade.html
#http://web-platform.test:8000/content-security-policy/embedded-enforcement/required_csp-header-crlf.html
#http://web-platform.test:8000/content-security-policy/embedded-enforcement/required_csp-header.html
#http://web-platform.test:8000/content-security-policy/embedded-enforcement/subsumption_algorithm-general.html
#http://web-platform.test:8000/content-security-policy/embedded-enforcement/subsumption_algorithm-hashes.html
#http://web-platform.test:8000/content-security-policy/embedded-enforcement/subsumption_algorithm-host_sources-hosts.html
#http://web-platform.test:8000/content-security-policy/embedded-enforcement/subsumption_algorithm-host_sources-paths.html
#http://web-platform.test:8000/content-security-policy/embedded-enforcement/subsumption_algorithm-host_sources-ports.html
#http://web-platform.test:8000/content-security-policy/embedded-enforcement/subsumption_algorithm-host_sources-protocols.html
#http://web-platform.test:8000/content-security-policy/embedded-enforcement/subsumption_algorithm-nonces.html
#http://web-platform.test:8000/content-security-policy/embedded-enforcement/subsumption_algorithm-none.html
#http://web-platform.test:8000/content-security-policy/embedded-enforcement/subsumption_algorithm-self.html
#http://web-platform.test:8000/content-security-policy/embedded-enforcement/subsumption_algorithm-strict_dynamic.html
#http://web-platform.test:8000/content-security-policy/embedded-enforcement/subsumption_algorithm-unsafe_eval.html
#http://web-platform.test:8000/content-security-policy/embedded-enforcement/subsumption_algorithm-unsafe_hashed_attributes.html
#http://web-platform.test:8000/content-security-policy/embedded-enforcement/subsumption_algorithm-unsafe_inline.html
#
#
#http://web-platform.test:8000/content-security-policy/font-src/font-match-allowed.sub.html
#http://web-platform.test:8000/content-security-policy/font-src/font-mismatch-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/font-src/font-none-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/font-src/font-self-allowed.html
#http://web-platform.test:8000/content-security-policy/font-src/font-stylesheet-font-blocked.sub.html
#
#
#http://web-platform.test:8000/content-security-policy/form-action/form-action-self-allowed-target-blank.html
#http://web-platform.test:8000/content-security-policy/form-action/form-action-src-allowed.sub.html
#http://web-platform.test:8000/content-security-policy/form-action/form-action-src-allowed-target-blank.sub.html
#http://web-platform.test:8000/content-security-policy/form-action/form-action-src-allowed-target-frame.sub.html
#http://web-platform.test:8000/content-security-policy/form-action/form-action-src-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/form-action/form-action-src-default-ignored.sub.html
#http://web-platform.test:8000/content-security-policy/form-action/form-action-src-get-allowed.sub.html
#http://web-platform.test:8000/content-security-policy/form-action/form-action-src-get-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/form-action/form-action-src-javascript-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/form-action/form-action-src-redirect-allowed-target-blank.sub.html
#http://web-platform.test:8000/content-security-policy/form-action/form-action-src-redirect-allowed-target-frame.sub.html
#http://web-platform.test:8000/content-security-policy/form-action/form-action-src-redirect-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/form-action/support/post-message-to-opener.sub.html
#http://web-platform.test:8000/content-security-policy/form-action/support/post-message-to-parent.sub.html
#
#
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-cross-in-cross-none-block.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-cross-in-cross-self-block.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-cross-in-cross-star-allow.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-cross-in-cross-url-allow.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-cross-in-cross-url-block.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-cross-in-same-none-block.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-cross-in-same-self-block.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-cross-in-same-star-allow.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-cross-in-same-url-allow.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-cross-in-same-url-block.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-cross-in-sandboxed-cross-url-block.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-same-in-cross-none-block.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-same-in-cross-self-block.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-same-in-cross-star-allow.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-same-in-cross-url-allow.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-same-in-cross-url-block.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-same-in-same-none-block.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-same-in-same-self-allow.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-same-in-same-star-allow.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-same-in-same-url-allow.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-nested-same-in-same-url-block.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-none-block.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-overrides-xfo.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-self-allow.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-self-block.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-star-allow-crossorigin.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-star-allow-sameorigin.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-url-allow.sub.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/frame-ancestors-url-block.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/support/frame-ancestors-and-x-frame-options.sub.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/support/frame-ancestors.sub.html
#http://web-platform.test:8000/content-security-policy/frame-ancestors/support/frame-in-frame.sub.html
#
#
http://web-platform.test:8000/content-security-policy/frame-src/frame-src-about-blank-allowed-by-default.sub.html
http://web-platform.test:8000/content-security-policy/frame-src/frame-src-about-blank-allowed-by-scheme.sub.html
http://web-platform.test:8000/content-security-policy/frame-src/frame-src-allowed.sub.html
http://web-platform.test:8000/content-security-policy/frame-src/frame-src-blocked.sub.html
http://web-platform.test:8000/content-security-policy/frame-src/frame-src-cross-origin-load.sub.html
#http://web-platform.test:8000/content-security-policy/frame-src/frame-src-redirect.html
#http://web-platform.test:8000/content-security-policy/frame-src/frame-src-self-unique-origin.html
#http://web-platform.test:8000/content-security-policy/frame-src/support/frame.html
#
#
http://web-platform.test:8000/content-security-policy/generic/duplicate-directive.sub.html
#http://web-platform.test:8000/content-security-policy/generic/filesystem-urls-do-not-match-self.sub.html
#http://web-platform.test:8000/content-security-policy/generic/filesystem-urls-match-filesystem.sub.html
http://web-platform.test:8000/content-security-policy/generic/generic-0_10_1.sub.html
http://web-platform.test:8000/content-security-policy/generic/generic-0_10.html
http://web-platform.test:8000/content-security-policy/generic/generic-0_1-img-src.html
#http://web-platform.test:8000/content-security-policy/generic/generic-0_1-script-src.html
http://web-platform.test:8000/content-security-policy/generic/generic-0_2_2.sub.html
http://web-platform.test:8000/content-security-policy/generic/generic-0_2_3.html
#http://web-platform.test:8000/content-security-policy/generic/generic-0_2.html
#http://web-platform.test:8000/content-security-policy/generic/generic-0_8_1.sub.html
#http://web-platform.test:8000/content-security-policy/generic/generic-0_8.sub.html
#http://web-platform.test:8000/content-security-policy/generic/generic-0_9.sub.html
#http://web-platform.test:8000/content-security-policy/generic/no-default-src.sub.html
#http://web-platform.test:8000/content-security-policy/generic/policy-does-not-affect-child.sub.html
#http://web-platform.test:8000/content-security-policy/generic/policy-inherited-correctly-by-plznavigate.html
#http://web-platform.test:8000/content-security-policy/generic/support/log-pass.html
#http://web-platform.test:8000/content-security-policy/generic/support/sandboxed-eval.sub.html
#
#
#http://web-platform.test:8000/content-security-policy/img-src/icon-allowed.sub.html
#http://web-platform.test:8000/content-security-policy/img-src/icon-blocked.sub.html
http://web-platform.test:8000/content-security-policy/img-src/img-src-4_1.sub.html
http://web-platform.test:8000/content-security-policy/img-src/img-src-full-host-wildcard-blocked.sub.html
http://web-platform.test:8000/content-security-policy/img-src/img-src-host-partial-wildcard-allowed.sub.html
http://web-platform.test:8000/content-security-policy/img-src/img-src-none-blocks.html
http://web-platform.test:8000/content-security-policy/img-src/img-src-port-wildcard-allowed.sub.html
#http://web-platform.test:8000/content-security-policy/img-src/img-src-self-unique-origin.html
#http://web-platform.test:8000/content-security-policy/img-src/img-src-wildcard-allowed.html
http://web-platform.test:8000/content-security-policy/img-src/report-blocked-data-uri.sub.html
#
#
#http://web-platform.test:8000/content-security-policy/inheritance/iframe.html
#http://web-platform.test:8000/content-security-policy/inheritance/inherited-csp-list-modifications-are-local.html
#http://web-platform.test:8000/content-security-policy/inheritance/window.html
#
#
#http://web-platform.test:8000/content-security-policy/inside-worker/dedicated-inheritance.html
#http://web-platform.test:8000/content-security-policy/inside-worker/dedicated-script.html
#http://web-platform.test:8000/content-security-policy/inside-worker/shared-inheritance.html
#http://web-platform.test:8000/content-security-policy/inside-worker/shared-script.html
#
#
#http://web-platform.test:8000/content-security-policy/media-src/media-src-7_1_2.sub.html
#http://web-platform.test:8000/content-security-policy/media-src/media-src-7_1.html
#http://web-platform.test:8000/content-security-policy/media-src/media-src-7_2_2.sub.html
#http://web-platform.test:8000/content-security-policy/media-src/media-src-7_2.html
#http://web-platform.test:8000/content-security-policy/media-src/media-src-7_3_2.sub.html
#http://web-platform.test:8000/content-security-policy/media-src/media-src-7_3.sub.html
#http://web-platform.test:8000/content-security-policy/media-src/media-src-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/media-src/media-src-redir-bug.sub.html
#
#
http://web-platform.test:8000/content-security-policy/media-src/media-src-7_1_2.sub.mp4.html
http://web-platform.test:8000/content-security-policy/media-src/media-src-7_1.mp4.html
http://web-platform.test:8000/content-security-policy/media-src/media-src-7_2_2.sub.mp4.html
http://web-platform.test:8000/content-security-policy/media-src/media-src-7_2.mp4.html
http://web-platform.test:8000/content-security-policy/media-src/media-src-7_3_2.sub.mp4.html
http://web-platform.test:8000/content-security-policy/media-src/media-src-7_3.sub.mp4.html
http://web-platform.test:8000/content-security-policy/media-src/media-src-blocked.sub.mp4.html
http://web-platform.test:8000/content-security-policy/media-src/media-src-redir-bug.sub.mp4.html
#
#
#http://web-platform.test:8000/content-security-policy/meta/combine-header-and-meta-policies.sub.html
http://web-platform.test:8000/content-security-policy/meta/meta-img-src.html
#http://web-platform.test:8000/content-security-policy/meta/meta-modified.html
#http://web-platform.test:8000/content-security-policy/meta/meta-outside-head.sub.html
#
#
#http://web-platform.test:8000/content-security-policy/navigate-to/anchor-navigation-always-allowed.html
#http://web-platform.test:8000/content-security-policy/navigate-to/child-navigates-parent-allowed.html
#http://web-platform.test:8000/content-security-policy/navigate-to/child-navigates-parent-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/form-action/form-action-allows-navigate-to-allows.html
#http://web-platform.test:8000/content-security-policy/navigate-to/form-action/form-action-allows-navigate-to-blocks.html
#http://web-platform.test:8000/content-security-policy/navigate-to/form-action/form-action-blocks-navigate-to-allows.html
#http://web-platform.test:8000/content-security-policy/navigate-to/form-action/form-action-blocks-navigate-to-blocks.html
#http://web-platform.test:8000/content-security-policy/navigate-to/form-allowed.html
#http://web-platform.test:8000/content-security-policy/navigate-to/form-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/form-cross-origin-allowed.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/form-cross-origin-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/form-redirected-allowed.html
#http://web-platform.test:8000/content-security-policy/navigate-to/form-redirected-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/href-location-allowed.html
#http://web-platform.test:8000/content-security-policy/navigate-to/href-location-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/href-location-cross-origin-allowed.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/href-location-cross-origin-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/href-location-redirected-allowed.html
#http://web-platform.test:8000/content-security-policy/navigate-to/href-location-redirected-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/link-click-allowed.html
#http://web-platform.test:8000/content-security-policy/navigate-to/link-click-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/link-click-cross-origin-allowed.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/link-click-cross-origin-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/link-click-redirected-allowed.html
#http://web-platform.test:8000/content-security-policy/navigate-to/link-click-redirected-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/meta-refresh-allowed.html
#http://web-platform.test:8000/content-security-policy/navigate-to/meta-refresh-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/meta-refresh-cross-origin-allowed.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/meta-refresh-cross-origin-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/meta-refresh-redirected-allowed.html
#http://web-platform.test:8000/content-security-policy/navigate-to/meta-refresh-redirected-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/parent-navigates-child-allowed.html
#http://web-platform.test:8000/content-security-policy/navigate-to/parent-navigates-child-blocked.html
#http://web-platform.test:8000/content-security-policy/navigate-to/support/form_action_navigation.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/support/href_location_navigation.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/support/link_click_navigation.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/support/meta_refresh_navigation.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/support/navigate_parent.sub.html
#http://web-platform.test:8000/content-security-policy/navigate-to/support/post_message_to_frame_owner.html
#http://web-platform.test:8000/content-security-policy/navigate-to/support/wait_for_navigation.html
#
#
#http://web-platform.test:8000/content-security-policy/navigation/javascript-url-navigation-inherits-csp.html
#http://web-platform.test:8000/content-security-policy/navigation/support/test_csp_self_window.sub.html
#http://web-platform.test:8000/content-security-policy/navigation/to-javascript-url-frame-src.html
#http://web-platform.test:8000/content-security-policy/navigation/to-javascript-url-script-src.html
#
#
http://web-platform.test:8000/content-security-policy/nonce-hiding/script-nonces-hidden-meta.tentative.sub.html
#http://web-platform.test:8000/content-security-policy/nonce-hiding/script-nonces-hidden.tentative.html
#http://web-platform.test:8000/content-security-policy/nonce-hiding/svgscript-nonces-hidden-meta.tentative.sub.html
#http://web-platform.test:8000/content-security-policy/nonce-hiding/svgscript-nonces-hidden.tentative.html
#
#
#http://web-platform.test:8000/content-security-policy/object-src/object-src-2_1.html
#http://web-platform.test:8000/content-security-policy/object-src/object-src-2_2.html
#http://web-platform.test:8000/content-security-policy/object-src/object-src-no-url-allowed.sub.html
#http://web-platform.test:8000/content-security-policy/object-src/object-src-no-url-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/object-src/object-src-url-allowed.sub.html
#http://web-platform.test:8000/content-security-policy/object-src/object-src-url-blocked.sub.html
#
#
#http://web-platform.test:8000/content-security-policy/plugin-types/plugintypes-mismatched-data.sub.html
#http://web-platform.test:8000/content-security-policy/plugin-types/plugintypes-mismatched-url.sub.html
#http://web-platform.test:8000/content-security-policy/plugin-types/plugintypes-notype-data.sub.html
#http://web-platform.test:8000/content-security-policy/plugin-types/plugintypes-notype-url.sub.html
#http://web-platform.test:8000/content-security-policy/plugin-types/plugintypes-nourl-allowed.sub.html
#http://web-platform.test:8000/content-security-policy/plugin-types/plugintypes-nourl-blocked.sub.html
#
#
#http://web-platform.test:8000/content-security-policy/prefetch-src/prefetch-allowed.html
#http://web-platform.test:8000/content-security-policy/prefetch-src/prefetch-blocked.html
#http://web-platform.test:8000/content-security-policy/prefetch-src/prefetch-header-allowed.html
#http://web-platform.test:8000/content-security-policy/prefetch-src/prefetch-header-blocked.html
#
#
#http://web-platform.test:8000/content-security-policy/reporting-api/reporting-api-doesnt-send-reports-without-violation.https.sub.html
#http://web-platform.test:8000/content-security-policy/reporting-api/reporting-api-report-only-sends-reports-on-violation.https.sub.html
#http://web-platform.test:8000/content-security-policy/reporting-api/reporting-api-report-to-overrides-report-uri-1.https.sub.html
#http://web-platform.test:8000/content-security-policy/reporting-api/reporting-api-report-to-overrides-report-uri-2.https.sub.html
#http://web-platform.test:8000/content-security-policy/reporting-api/reporting-api-sends-reports-on-violation.https.sub.html
#http://web-platform.test:8000/content-security-policy/reporting-api/reporting-api-works-on-frame-src.https.sub.html
#http://web-platform.test:8000/content-security-policy/reporting/multiple-report-policies.html
#http://web-platform.test:8000/content-security-policy/reporting/report-and-enforce.html
#http://web-platform.test:8000/content-security-policy/reporting/report-blocked-data-uri.html
#http://web-platform.test:8000/content-security-policy/reporting/report-blocked-uri-cross-origin.sub.html
#http://web-platform.test:8000/content-security-policy/reporting/report-blocked-uri.html
#http://web-platform.test:8000/content-security-policy/reporting/report-cross-origin-no-cookies.sub.html
#http://web-platform.test:8000/content-security-policy/reporting/report-multiple-violations-01.html
#http://web-platform.test:8000/content-security-policy/reporting/report-multiple-violations-02.html
#http://web-platform.test:8000/content-security-policy/reporting/report-only-in-meta.sub.html
#http://web-platform.test:8000/content-security-policy/reporting/report-original-url.sub.html
#http://web-platform.test:8000/content-security-policy/reporting/report-same-origin-with-cookies.html
#http://web-platform.test:8000/content-security-policy/reporting/report-strips-fragment.html
#http://web-platform.test:8000/content-security-policy/reporting/report-uri-effective-directive.html
#http://web-platform.test:8000/content-security-policy/reporting/report-uri-from-child-frame.html
#http://web-platform.test:8000/content-security-policy/reporting/report-uri-from-inline-javascript.html
#http://web-platform.test:8000/content-security-policy/reporting/report-uri-from-javascript.html
#http://web-platform.test:8000/content-security-policy/reporting/report-uri-multiple.html
#http://web-platform.test:8000/content-security-policy/reporting/report-uri-multiple-reversed.html
#http://web-platform.test:8000/content-security-policy/reporting/report-uri-scheme-relative.html
#http://web-platform.test:8000/content-security-policy/reporting/support/generate-csp-report.html
#
#
#http://web-platform.test:8000/content-security-policy/sandbox/iframe-inside-csp.sub.html
#http://web-platform.test:8000/content-security-policy/sandbox/sandbox-allow-scripts-subframe.sub.html
#http://web-platform.test:8000/content-security-policy/sandbox/sandbox-allow-scripts.sub.html
#http://web-platform.test:8000/content-security-policy/sandbox/sandbox-empty-subframe.sub.html
#http://web-platform.test:8000/content-security-policy/sandbox/sandbox-empty.sub.html
#http://web-platform.test:8000/content-security-policy/sandbox/support/sandboxed-data-iframe.sub.html
#http://web-platform.test:8000/content-security-policy/sandbox/support/sandboxed-eval.sub.html
#http://web-platform.test:8000/content-security-policy/sandbox/support/sandboxed-post-message-to-parent.html
#http://web-platform.test:8000/content-security-policy/sandbox/support/sandboxed-post-property-to-opener.html
#http://web-platform.test:8000/content-security-policy/sandbox/support/unsandboxed-post-property-to-opener.html
#http://web-platform.test:8000/content-security-policy/sandbox/window-reuse-sandboxed.html
#http://web-platform.test:8000/content-security-policy/sandbox/window-reuse-unsandboxed.html
#
#
http://web-platform.test:8000/content-security-policy/script-src/injected-inline-script-allowed.sub.html
http://web-platform.test:8000/content-security-policy/script-src/injected-inline-script-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/script-src/javascript-window-open-blocked.html
#http://web-platform.test:8000/content-security-policy/script-src/nonce-enforce-blocked.html
http://web-platform.test:8000/content-security-policy/script-src/scripthash-allowed.sub.html
http://web-platform.test:8000/content-security-policy/script-src/scripthash-basic-blocked.sub.html
http://web-platform.test:8000/content-security-policy/script-src/scripthash-default-src.sub.html
http://web-platform.test:8000/content-security-policy/script-src/scripthash-ignore-unsafeinline.sub.html
http://web-platform.test:8000/content-security-policy/script-src/scripthash-unicode-normalization.sub.html
http://web-platform.test:8000/content-security-policy/script-src/scriptnonce-allowed.sub.html
http://web-platform.test:8000/content-security-policy/script-src/scriptnonce-and-scripthash.sub.html
http://web-platform.test:8000/content-security-policy/script-src/scriptnonce-basic-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/script-src/scriptnonce-ignore-unsafeinline.sub.html
http://web-platform.test:8000/content-security-policy/script-src/scriptnonce-redirect.sub.html
http://web-platform.test:8000/content-security-policy/script-src/script-src-1_10_1.html
http://web-platform.test:8000/content-security-policy/script-src/script-src-1_10.html
http://web-platform.test:8000/content-security-policy/script-src/script-src-1_1.html
http://web-platform.test:8000/content-security-policy/script-src/script-src-1_2_1.html
http://web-platform.test:8000/content-security-policy/script-src/script-src-1_2.html
http://web-platform.test:8000/content-security-policy/script-src/script-src-1_3.html
http://web-platform.test:8000/content-security-policy/script-src/script-src-1_4_1.html
http://web-platform.test:8000/content-security-policy/script-src/script-src-1_4_2.html
http://web-platform.test:8000/content-security-policy/script-src/script-src-1_4.html
http://web-platform.test:8000/content-security-policy/script-src/script-src-multiple-policies-multiple-hashing-algorithms.html
http://web-platform.test:8000/content-security-policy/script-src/script-src-multiple-policies-one-using-hashing-algorithms.html
http://web-platform.test:8000/content-security-policy/script-src/script-src-overrides-default-src.sub.html
#http://web-platform.test:8000/content-security-policy/script-src/script-src-report-only-policy-works-with-external-hash-policy.html
#http://web-platform.test:8000/content-security-policy/script-src/script-src-report-only-policy-works-with-hash-policy.html
#http://web-platform.test:8000/content-security-policy/script-src/script-src-sri_hash.sub.html
http://web-platform.test:8000/content-security-policy/script-src/script-src-strict_dynamic_and_unsafe_eval_eval.html
http://web-platform.test:8000/content-security-policy/script-src/script-src-strict_dynamic_and_unsafe_eval_new_function.html
#http://web-platform.test:8000/content-security-policy/script-src/script-src-strict_dynamic_discard_whitelist.html
#http://web-platform.test:8000/content-security-policy/script-src/script-src-strict_dynamic_double_policy_different_nonce.html
#http://web-platform.test:8000/content-security-policy/script-src/script-src-strict_dynamic_double_policy_honor_whitelist.sub.html
#http://web-platform.test:8000/content-security-policy/script-src/script-src-strict_dynamic_double_policy_report_only.html
#http://web-platform.test:8000/content-security-policy/script-src/script-src-strict_dynamic_eval.html
http://web-platform.test:8000/content-security-policy/script-src/script-src-strict_dynamic_hashes.html
http://web-platform.test:8000/content-security-policy/script-src/script-src-strict_dynamic_in_img-src.html
#http://web-platform.test:8000/content-security-policy/script-src/script-src-strict_dynamic_javascript_uri.html
#http://web-platform.test:8000/content-security-policy/script-src/script-src-strict_dynamic_meta_tag.html
#http://web-platform.test:8000/content-security-policy/script-src/script-src-strict_dynamic_new_function.html
#http://web-platform.test:8000/content-security-policy/script-src/script-src-strict_dynamic_non_parser_inserted.html
#http://web-platform.test:8000/content-security-policy/script-src/script-src-strict_dynamic_non_parser_inserted_incorrect_nonce.html
#http://web-platform.test:8000/content-security-policy/script-src/script-src-strict_dynamic_parser_inserted_correct_nonce.html
#http://web-platform.test:8000/content-security-policy/script-src/script-src-strict_dynamic_parser_inserted.html
#http://web-platform.test:8000/content-security-policy/script-src/script-src-strict_dynamic_worker.https.html
#http://web-platform.test:8000/content-security-policy/script-src/script-src-strict_dynamic_worker-importScripts.https.html
http://web-platform.test:8000/content-security-policy/script-src/script-src-wildcards-disallowed.html
#http://web-platform.test:8000/content-security-policy/script-src/srcdoc-doesnt-bypass-script-src.sub.html
#http://web-platform.test:8000/content-security-policy/script-src/worker-eval-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/script-src/worker-function-function-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/script-src/worker-importscripts-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/script-src/worker-script-src.sub.html
#http://web-platform.test:8000/content-security-policy/script-src/worker-set-timeout-blocked.sub.html
#
#
#http://web-platform.test:8000/content-security-policy/securitypolicyviolation/blockeduri-eval.html
#http://web-platform.test:8000/content-security-policy/securitypolicyviolation/blockeduri-inline.html
#http://web-platform.test:8000/content-security-policy/securitypolicyviolation/idl.html
#http://web-platform.test:8000/content-security-policy/securitypolicyviolation/img-src-redirect-upgrade-reporting.https.html
#http://web-platform.test:8000/content-security-policy/securitypolicyviolation/inside-dedicated-worker.html
#http://web-platform.test:8000/content-security-policy/securitypolicyviolation/inside-service-worker.https.html
#http://web-platform.test:8000/content-security-policy/securitypolicyviolation/inside-shared-worker.html
#http://web-platform.test:8000/content-security-policy/securitypolicyviolation/script-sample.html
#http://web-platform.test:8000/content-security-policy/securitypolicyviolation/script-sample-no-opt-in.html
#http://web-platform.test:8000/content-security-policy/securitypolicyviolation/securitypolicyviolation-block-cross-origin-image-from-script.sub.html
#http://web-platform.test:8000/content-security-policy/securitypolicyviolation/securitypolicyviolation-block-cross-origin-image.sub.html
#http://web-platform.test:8000/content-security-policy/securitypolicyviolation/securitypolicyviolation-block-image-from-script.sub.html
#http://web-platform.test:8000/content-security-policy/securitypolicyviolation/securitypolicyviolation-block-image.sub.html
#http://web-platform.test:8000/content-security-policy/securitypolicyviolation/style-sample.html
#http://web-platform.test:8000/content-security-policy/securitypolicyviolation/style-sample-no-opt-in.html
#http://web-platform.test:8000/content-security-policy/securitypolicyviolation/targeting.html
#http://web-platform.test:8000/content-security-policy/securitypolicyviolation/upgrade-insecure-requests-reporting.https.html
#
#
#http://web-platform.test:8000/content-security-policy/style-src/injected-inline-style-allowed.sub.html # document.styleSheets.length
http://web-platform.test:8000/content-security-policy/style-src/injected-inline-style-blocked.sub.html
http://web-platform.test:8000/content-security-policy/style-src/inline-style-allowed.sub.html
#http://web-platform.test:8000/content-security-policy/style-src/inline-style-allowed-while-cloning-objects.sub.html
http://web-platform.test:8000/content-security-policy/style-src/inline-style-attribute-allowed.sub.html
http://web-platform.test:8000/content-security-policy/style-src/inline-style-attribute-blocked.sub.html
http://web-platform.test:8000/content-security-policy/style-src/inline-style-attribute-on-html.sub.html
http://web-platform.test:8000/content-security-policy/style-src/inline-style-blocked.sub.html
#http://web-platform.test:8000/content-security-policy/style-src/style-allowed.sub.html # document.styleSheets.length
http://web-platform.test:8000/content-security-policy/style-src/style-blocked.sub.html
http://web-platform.test:8000/content-security-policy/style-src/stylehash-allowed.sub.html
http://web-platform.test:8000/content-security-policy/style-src/stylehash-basic-blocked.sub.html
http://web-platform.test:8000/content-security-policy/style-src/stylehash-default-src.sub.html
http://web-platform.test:8000/content-security-policy/style-src/stylenonce-allowed.sub.html
#http://web-platform.test:8000/content-security-policy/style-src/stylenonce-blocked.sub.html # window.getComputedStyle(el).color
http://web-platform.test:8000/content-security-policy/style-src/style-src-error-event-fires.html
http://web-platform.test:8000/content-security-policy/style-src/style-src-hash-allowed.html
http://web-platform.test:8000/content-security-policy/style-src/style-src-hash-blocked.html
http://web-platform.test:8000/content-security-policy/style-src/style-src-hash-default-src-allowed.html
http://web-platform.test:8000/content-security-policy/style-src/style-src-imported-style-allowed.sub.html
http://web-platform.test:8000/content-security-policy/style-src/style-src-imported-style-blocked.html
http://web-platform.test:8000/content-security-policy/style-src/style-src-injected-inline-style-allowed.html
http://web-platform.test:8000/content-security-policy/style-src/style-src-injected-inline-style-blocked.html
http://web-platform.test:8000/content-security-policy/style-src/style-src-injected-stylesheet-allowed.sub.html
http://web-platform.test:8000/content-security-policy/style-src/style-src-injected-stylesheet-blocked.sub.html
http://web-platform.test:8000/content-security-policy/style-src/style-src-inline-style-allowed.html
http://web-platform.test:8000/content-security-policy/style-src/style-src-inline-style-attribute-allowed.html
http://web-platform.test:8000/content-security-policy/style-src/style-src-inline-style-attribute-blocked.html
http://web-platform.test:8000/content-security-policy/style-src/style-src-inline-style-blocked.html
http://web-platform.test:8000/content-security-policy/style-src/style-src-inline-style-nonce-allowed.html
http://web-platform.test:8000/content-security-policy/style-src/style-src-inline-style-nonce-blocked-error-event.html
http://web-platform.test:8000/content-security-policy/style-src/style-src-inline-style-nonce-blocked.html
#http://web-platform.test:8000/content-security-policy/style-src/style-src-multiple-policies-multiple-hashing-algorithms.html
http://web-platform.test:8000/content-security-policy/style-src/style-src-none-blocked.html
#http://web-platform.test:8000/content-security-policy/style-src/style-src-star-allowed.html # window.getComputedStyle(el).getPropertyValue('margin-left')
#http://web-platform.test:8000/content-security-policy/style-src/style-src-stylesheet-nonce-allowed.html # window.getComputedStyle(el).getPropertyValue('margin-left')
http://web-platform.test:8000/content-security-policy/style-src/style-src-stylesheet-nonce-blocked.html
#
#
#http://web-platform.test:8000/content-security-policy/svg/object-in-svg-foreignobject.sub.html
#http://web-platform.test:8000/content-security-policy/svg/svg-from-guid.html
#http://web-platform.test:8000/content-security-policy/svg/svg-inline.sub.html
#http://web-platform.test:8000/content-security-policy/svg/svg-policy-resource-doc-includes.html
#http://web-platform.test:8000/content-security-policy/svg/svg-policy-with-resource.html
#
#
http://web-platform.test:8000/content-security-policy/unsafe-eval/eval-allowed.sub.html
http://web-platform.test:8000/content-security-policy/unsafe-eval/eval-blocked-and-sends-report.sub.html
#http://web-platform.test:8000/content-security-policy/unsafe-eval/eval-blocked-in-about-blank-iframe.sub.html
http://web-platform.test:8000/content-security-policy/unsafe-eval/eval-blocked.sub.html
http://web-platform.test:8000/content-security-policy/unsafe-eval/eval-scripts-setInterval-allowed.sub.html
http://web-platform.test:8000/content-security-policy/unsafe-eval/eval-scripts-setInterval-blocked.sub.html
http://web-platform.test:8000/content-security-policy/unsafe-eval/eval-scripts-setTimeout-allowed.sub.html
http://web-platform.test:8000/content-security-policy/unsafe-eval/eval-scripts-setTimeout-blocked.sub.html
http://web-platform.test:8000/content-security-policy/unsafe-eval/function-constructor-allowed.sub.html
http://web-platform.test:8000/content-security-policy/unsafe-eval/function-constructor-blocked.sub.html
#
#
#http://web-platform.test:8000/content-security-policy/unsafe-hashed-attributes/script_event_handlers_allowed.html
#http://web-platform.test:8000/content-security-policy/unsafe-hashed-attributes/script_event_handlers_denied_matching_hash_no_unsafe_inline_attribute.html
#http://web-platform.test:8000/content-security-policy/unsafe-hashed-attributes/script_event_handlers_denied_not_matching_hash.html
#
#
#http://web-platform.test:8000/content-security-policy/worker-src/dedicated-child.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/dedicated-fallback.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/dedicated-list.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/dedicated-none.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/dedicated-self.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/dedicated-worker-src-child-fallback.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/dedicated-worker-src-default-fallback.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/dedicated-worker-src-script-fallback.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/dedicated-worker-src-self-fallback.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/service-child.https.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/service-fallback.https.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/service-list.https.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/service-none.https.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/service-self.https.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/service-worker-src-child-fallback.https.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/service-worker-src-default-fallback.https.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/service-worker-src-script-fallback.https.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/service-worker-src-self-fallback.https.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/shared-child.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/shared-fallback.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/shared-list.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/shared-none.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/shared-self.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/shared-worker-src-child-fallback.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/shared-worker-src-default-fallback.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/shared-worker-src-script-fallback.sub.html
#http://web-platform.test:8000/content-security-policy/worker-src/shared-worker-src-self-fallback.sub.html
