#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/test_variable_legal_values.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-animation-from-to.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-animation-over-transition.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-animation-substitute-into-keyframe.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-animation-substitute-into-keyframe-shorthand.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-animation-substitute-into-keyframe-transform.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-animation-substitute-within-keyframe-fallback.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-animation-substitute-within-keyframe.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-animation-substitute-within-keyframe-multiple.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-animation-to-only.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-created-document.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-created-element.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-cssText.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-definition-border-shorthand-serialize.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-definition-cascading.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-definition.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-definition-keywords.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-first-letter.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-first-line.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-invalidation.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-presentation-attribute.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-pseudo-element.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-reference-cssom.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-reference.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-reference-refresh.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-reference-shorthands-cssom.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-reference-shorthands.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-reference-variable.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-substitution-background-properties.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-substitution-basic.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-substitution-filters.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-substitution-plus-box-shadow.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-substitution-replaced-size.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-substitution-shadow-properties.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-substitution-shorthands.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-substitution-variable-declaration.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-transitions-from-no-value.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-transitions-to-no-value.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-transitions-transition-property-all-before-value.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-transitions-transition-property-variable-before-value.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-transitions-value-before-transition-property-all.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/variable-transitions-value-before-transition-property-variable.htm
#http://web-platform.test:8000/css/dist/css-variables-1_dev/html/vars-border-shorthand-serialize.htm
