#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/css-vars-custom-property-case-sensitive-001.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/css-vars-custom-property-inheritance.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-01.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-02.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-03.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-04.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-05.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-06.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-07.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-08.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-09.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-10.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-11.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-12.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-13.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-14.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-15.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-16.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-17.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-18.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-19.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-20.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-21.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-22.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-23.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-24.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-25.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-26.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-28.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-29.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-30.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-31.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-32.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-33.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-34.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-35.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-36.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-37.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-38.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-39.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-40.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-41.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-42.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-43.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-44.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-45.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-46.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-47.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-48.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-49.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-50.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-51.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-52.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-53.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-54.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-55.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-56.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-57.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-58.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-59.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-declaration-60.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-external-declaration-01.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-external-font-face-01.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-external-reference-01.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-external-supports-01.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-font-face-01.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-font-face-02.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-01.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-02.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-03.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-04.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-05.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-06.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-07.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-08.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-09.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-10.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-11.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-12.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-13.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-14.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-15.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-16.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-17.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-18.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-19.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-20.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-21.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-22.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-23.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-24.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-25.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-26.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-27.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-28.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-29.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-30.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-31.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-32.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-33.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-34.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-35.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-36.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-37.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-38.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-39.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-40.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-refresh-iframe.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-reference-without-whitespace.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-01.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-02.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-03.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-04.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-05.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-06.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-07.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-08.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-09.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-10.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-11.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-12.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-13.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-14.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-15.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-16.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-17.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-18.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-19.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-20.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-21.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-22.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-23.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-24.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-25.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-26.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-27.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-28.htm
test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-29.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-30.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-31.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-32.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-33.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-34.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-35.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-36.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-37.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-38.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-39.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-40.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-41.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-42.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-43.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-44.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-45.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-46.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-47.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-48.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-49.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-50.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-51.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-52.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-53.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-54.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-55.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-56.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-57.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-58.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-59.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-60.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-61.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-62.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-63.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-64.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-65.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-66.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/variable-supports-67.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/vars-background-shorthand-001.htm
#test/cairo/reftest/web_platform_test/css/dist/css-variables-1_dev/html/vars-font-shorthand-001.htm
