#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/background-color-hsl-001.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/background-color-hsl-002.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/background-color-hsl-003.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/background-color-hsl-004.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/background-color-rgb-001.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/background-color-rgb-002.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/background-color-rgb-003.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/border-bottom-color.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/border-left-color.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/border-right-color.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/border-top-color.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/caret-color-007.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/color-001.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/color-002.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/color-003.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/currentcolor-001.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/currentcolor-002.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hex-001.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hex-002.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hex-003.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hex-004.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hsl-001.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hsl-002.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hsl-003.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hsl-004.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hsl-005.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hsl-006.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hsl-007.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hsl-008.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hsla-001.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hsla-002.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hsla-003.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hsla-004.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hsla-005.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hsla-006.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hsla-007.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/hsla-008.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/lab-001.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/lab-002.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/lab-003.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/lab-004.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/lab-005.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/lab-006.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/lab-007.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/lch-001.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/lch-002.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/lch-003.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/lch-004.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/lch-005.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/lch-006.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/lch-007.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/multicol-rule-color-inherit-002.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/named-001.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/outline-019.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/rgb-001.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/rgb-002.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/rgb-003.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/rgb-004.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/rgb-005.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/rgb-006.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/rgb-007.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/rgb-008.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/rgba-001.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/rgba-002.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/rgba-003.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/rgba-004.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/rgba-005.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/rgba-006.htm
test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/rgba-007.htm
#test/cairo/reftest/web_platform_test/css/dist/css-color-4_dev/html/rgba-008.htm
