#http://web-platform.test:8000/fetch/nosniff/parsing-nosniff.html
#http://web-platform.test:8000/fetch/nosniff/worker.html
#http://web-platform.test:8000/fetch/nosniff/importscripts.html
#http://web-platform.test:8000/fetch/nosniff/script.html
#http://web-platform.test:8000/fetch/nosniff/stylesheet.html
#http://web-platform.test:8000/fetch/nosniff/image.html
#http://web-platform.test:8000/fetch/api/basic/conditional-get.html
#http://web-platform.test:8000/fetch/api/basic/text-utf8.html
#http://web-platform.test:8000/fetch/api/basic/keepalive.html
#http://web-platform.test:8000/fetch/api/basic/request-referrer-redirected-worker.html
#http://web-platform.test:8000/fetch/api/basic/error-after-response.html
#http://web-platform.test:8000/fetch/api/basic/block-mime-as-script.html
#http://web-platform.test:8000/fetch/api/resources/keepalive-iframe.html
#http://web-platform.test:8000/fetch/api/resources/basic.html
#http://web-platform.test:8000/fetch/api/request/request-cache-no-cache.html
#http://web-platform.test:8000/fetch/api/request/request-cache-force-cache.html
#http://web-platform.test:8000/fetch/api/request/request-bad-port.html
#http://web-platform.test:8000/fetch/api/request/request-init-002.html
#http://web-platform.test:8000/fetch/api/request/request-cache-only-if-cached.html
#http://web-platform.test:8000/fetch/api/request/request-consume-empty.html
#http://web-platform.test:8000/fetch/api/request/url-encoding.html
#http://web-platform.test:8000/fetch/api/request/request-error.html
#http://web-platform.test:8000/fetch/api/request/multi-globals/url-parsing.html
#http://web-platform.test:8000/fetch/api/request/multi-globals/current/current.html
#http://web-platform.test:8000/fetch/api/request/multi-globals/incumbent/incumbent.html
#http://web-platform.test:8000/fetch/api/request/request-clone.sub.html
#http://web-platform.test:8000/fetch/api/request/request-type-attribute-historical.html
#http://web-platform.test:8000/fetch/api/request/request-disturbed.html
#http://web-platform.test:8000/fetch/api/request/request-reset-attributes.https.html
#http://web-platform.test:8000/fetch/api/request/request-headers.html
#http://web-platform.test:8000/fetch/api/request/request-cache-no-store.html
#http://web-platform.test:8000/fetch/api/request/destination/fetch-destination-no-load-event.https.html
#http://web-platform.test:8000/fetch/api/request/destination/fetch-destination-worker.https.html
#http://web-platform.test:8000/fetch/api/request/destination/resources/empty.https.html
#http://web-platform.test:8000/fetch/api/request/destination/resources/dummy.html
#http://web-platform.test:8000/fetch/api/request/destination/fetch-destination.https.html
#http://web-platform.test:8000/fetch/api/request/destination/fetch-destination-iframe.https.html
#http://web-platform.test:8000/fetch/api/request/request-consume.html
#http://web-platform.test:8000/fetch/api/request/request-cache-default.html
#http://web-platform.test:8000/fetch/api/request/request-cache-reload.html
http://web-platform.test:8000/fetch/api/request/request-init-001.sub.html
#http://web-platform.test:8000/fetch/api/request/request-init-003.sub.html
#http://web-platform.test:8000/fetch/api/request/request-cache-default-conditional.html
#http://web-platform.test:8000/fetch/api/request/request-keepalive-quota.html
#http://web-platform.test:8000/fetch/api/request/request-structure.html
#http://web-platform.test:8000/fetch/api/request/request-keepalive.html
http://web-platform.test:8000/fetch/api/headers/headers-errors.html
#http://web-platform.test:8000/fetch/api/headers/headers-basic.html
#http://web-platform.test:8000/fetch/api/headers/headers-record.html
#http://web-platform.test:8000/fetch/api/headers/header-values-normalize.html
#http://web-platform.test:8000/fetch/api/headers/header-values.html
http://web-platform.test:8000/fetch/api/headers/headers-normalize.html
#http://web-platform.test:8000/fetch/api/headers/headers-combine.html
http://web-platform.test:8000/fetch/api/headers/headers-structure.html
http://web-platform.test:8000/fetch/api/headers/headers-casing.html
#http://web-platform.test:8000/fetch/api/policies/referrer-no-referrer-service-worker.https.html
#http://web-platform.test:8000/fetch/api/policies/referrer-unsafe-url-service-worker.https.html
#http://web-platform.test:8000/fetch/api/policies/csp-blocked.html
#http://web-platform.test:8000/fetch/api/policies/referrer-origin-when-cross-origin-service-worker.https.html
#http://web-platform.test:8000/fetch/api/policies/referrer-unsafe-url-worker.html
#http://web-platform.test:8000/fetch/api/policies/referrer-origin-when-cross-origin-worker.html
#http://web-platform.test:8000/fetch/api/policies/referrer-origin.html
#http://web-platform.test:8000/fetch/api/policies/csp-blocked-worker.html
#http://web-platform.test:8000/fetch/api/policies/referrer-unsafe-url.html
#http://web-platform.test:8000/fetch/api/policies/referrer-no-referrer-worker.html
#http://web-platform.test:8000/fetch/api/policies/referrer-no-referrer.html
#http://web-platform.test:8000/fetch/api/policies/referrer-origin-service-worker.https.html
#http://web-platform.test:8000/fetch/api/policies/referrer-origin-when-cross-origin.html
#http://web-platform.test:8000/fetch/api/policies/referrer-origin-worker.html
#http://web-platform.test:8000/fetch/api/abort/cache.https.html
#http://web-platform.test:8000/fetch/api/abort/serviceworker-intercepted.https.html
#http://web-platform.test:8000/fetch/api/redirect/redirect-schemes.html
#http://web-platform.test:8000/fetch/api/response/response-stream-disturbed-2.html
#http://web-platform.test:8000/fetch/api/response/response-consume-stream.html
#http://web-platform.test:8000/fetch/api/response/response-init-002.html
#http://web-platform.test:8000/fetch/api/response/response-consume.html
#http://web-platform.test:8000/fetch/api/response/response-error-from-stream.html
#http://web-platform.test:8000/fetch/api/response/response-stream-disturbed-4.html
#http://web-platform.test:8000/fetch/api/response/multi-globals/url-parsing.html
#http://web-platform.test:8000/fetch/api/response/multi-globals/relevant/relevant.html
#http://web-platform.test:8000/fetch/api/response/multi-globals/current/current.html
#http://web-platform.test:8000/fetch/api/response/multi-globals/incumbent/incumbent.html
#http://web-platform.test:8000/fetch/api/response/response-trailer.html
#http://web-platform.test:8000/fetch/api/response/response-stream-disturbed-5.html
#http://web-platform.test:8000/fetch/api/response/response-consume-empty.html
#http://web-platform.test:8000/fetch/api/response/response-stream-disturbed-1.html
#http://web-platform.test:8000/fetch/api/response/response-cancel-stream.html
#http://web-platform.test:8000/fetch/api/response/response-init-001.html
#http://web-platform.test:8000/fetch/api/response/response-stream-disturbed-3.html
#http://web-platform.test:8000/fetch/api/response/response-static-redirect.html
#http://web-platform.test:8000/fetch/api/response/response-static-error.html
#http://web-platform.test:8000/fetch/api/response/response-stream-disturbed-6.html
#http://web-platform.test:8000/fetch/api/response/response-clone.html
#http://web-platform.test:8000/fetch/api/response/response-error.html
#http://web-platform.test:8000/fetch/content-length/content-length.html
#http://web-platform.test:8000/fetch/security/dangling-markup-mitigation-data-url.tentative.sub.html
#http://web-platform.test:8000/fetch/security/support/embedded-credential-window.sub.html
#http://web-platform.test:8000/fetch/security/redirect-to-url-with-credentials.https.html
#http://web-platform.test:8000/fetch/security/embedded-credentials.tentative.sub.html
#http://web-platform.test:8000/fetch/security/dangling-markup-mitigation.tentative.html
#http://web-platform.test:8000/fetch/http-cache/partial.html
#http://web-platform.test:8000/fetch/http-cache/heuristic.html
#http://web-platform.test:8000/fetch/http-cache/304-update.html
#http://web-platform.test:8000/fetch/http-cache/status.html
#http://web-platform.test:8000/fetch/http-cache/basic-auth-cache-test-ref.html
#http://web-platform.test:8000/fetch/http-cache/basic-auth-cache-test.html
#http://web-platform.test:8000/fetch/http-cache/cc-request.html
#http://web-platform.test:8000/fetch/http-cache/invalidate.html
#http://web-platform.test:8000/fetch/http-cache/vary.html
#http://web-platform.test:8000/fetch/http-cache/freshness.html
#http://web-platform.test:8000/fetch/range/resources/basic.html
#http://web-platform.test:8000/fetch/corb/img-png-mislabeled-as-html.sub.html
#http://web-platform.test:8000/fetch/corb/img-png-mislabeled-as-html.sub-ref.html
#http://web-platform.test:8000/fetch/corb/img-html-correctly-labeled.sub.html
#http://web-platform.test:8000/fetch/corb/img-png-mislabeled-as-html-nosniff.tentative.sub-ref.html
#http://web-platform.test:8000/fetch/corb/style-css-with-json-parser-breaker.sub.html
#http://web-platform.test:8000/fetch/corb/style-css-mislabeled-as-html.sub.html
#http://web-platform.test:8000/fetch/corb/style-css-mislabeled-as-html-nosniff.sub.html
#http://web-platform.test:8000/fetch/corb/script-html-js-polyglot.sub.html
#http://web-platform.test:8000/fetch/corb/img-html-correctly-labeled.sub-ref.html
#http://web-platform.test:8000/fetch/corb/script-js-mislabeled-as-html-nosniff.sub.html
#http://web-platform.test:8000/fetch/corb/resources/subframe-that-posts-html-containing-blob-url-to-parent.html
#http://web-platform.test:8000/fetch/corb/resources/html-correctly-labeled.html
#http://web-platform.test:8000/fetch/corb/style-html-correctly-labeled.sub.html
#http://web-platform.test:8000/fetch/corb/img-png-mislabeled-as-html-nosniff.tentative.sub.html
#http://web-platform.test:8000/fetch/corb/script-html-correctly-labeled.tentative.sub.html
#http://web-platform.test:8000/fetch/corb/script-js-mislabeled-as-html.sub.html
#http://web-platform.test:8000/fetch/corb/script-html-via-cross-origin-blob-url.sub.html
#http://web-platform.test:8000/fetch/corb/preload-image-png-mislabeled-as-html-nosniff.tentative.sub.html
#http://web-platform.test:8000/fetch/corb/img-mime-types-coverage.tentative.sub.html
#http://web-platform.test:8000/fetch/sec-metadata/img.tentative.https.sub.html
#http://web-platform.test:8000/fetch/sec-metadata/iframe.tentative.https.sub.html
#http://web-platform.test:8000/fetch/sec-metadata/script.tentative.https.sub.html
#http://web-platform.test:8000/fetch/sec-metadata/window-open.tentative.https.sub.html
#http://web-platform.test:8000/fetch/sec-metadata/fetch.tentative.https.sub.html
