#http://www.web-platform.test:8000/FileAPI/historical.https.html
#http://www.web-platform.test:8000/FileAPI/filelist-section/filelist_selected_file-manual.html
#http://www.web-platform.test:8000/FileAPI/filelist-section/filelist_multiple_selected_files-manual.html
#http://www.web-platform.test:8000/FileAPI/filelist-section/filelist.html
#http://www.web-platform.test:8000/FileAPI/unicode.html
#http://www.web-platform.test:8000/FileAPI/blob/Blob-constructor.html
#http://www.web-platform.test:8000/FileAPI/blob/Blob-constructor-endings.html
#http://www.web-platform.test:8000/FileAPI/blob/Blob-slice-overflow.html
#http://www.web-platform.test:8000/FileAPI/blob/Blob-slice.html
#http://www.web-platform.test:8000/FileAPI/idlharness-manual.html
#http://www.web-platform.test:8000/FileAPI/BlobURL/test2-manual.html
http://www.web-platform.test:8000/FileAPI/reading-data-section/filereader_readAsText.html
#http://www.web-platform.test:8000/FileAPI/reading-data-section/FileReader-multiple-reads.html
#http://www.web-platform.test:8000/FileAPI/reading-data-section/test2.html
#http://www.web-platform.test:8000/FileAPI/reading-data-section/filereader_error.html
#http://www.web-platform.test:8000/FileAPI/reading-data-section/test.html
#http://www.web-platform.test:8000/FileAPI/reading-data-section/FileReader-event-handler-attributes.html
http://www.web-platform.test:8000/FileAPI/reading-data-section/filereader_readAsArrayBuffer.html
#http://www.web-platform.test:8000/FileAPI/reading-data-section/filereader_file-manual.html
#http://www.web-platform.test:8000/FileAPI/reading-data-section/filereader_readAsDataURL.html
#http://www.web-platform.test:8000/FileAPI/reading-data-section/filereader_abort.html
#http://www.web-platform.test:8000/FileAPI/reading-data-section/filereader_file_img-manual.html
#http://www.web-platform.test:8000/FileAPI/reading-data-section/Determining-Encoding.html
#http://www.web-platform.test:8000/FileAPI/reading-data-section/filereader_readystate.html
#http://www.web-platform.test:8000/FileAPI/reading-data-section/filereader_readAsBinaryString.html
#http://www.web-platform.test:8000/FileAPI/reading-data-section/filereader_result.html
#http://www.web-platform.test:8000/FileAPI/file/File-constructor.html
#http://www.web-platform.test:8000/FileAPI/file/File-constructor-endings.html
#http://www.web-platform.test:8000/FileAPI/file/send-file-form.html
#http://www.web-platform.test:8000/FileAPI/file/send-file-form-iso-2022-jp.tentative.html
#http://www.web-platform.test:8000/FileAPI/file/send-file-form-utf-8.html
#http://www.web-platform.test:8000/FileAPI/file/send-file-form-windows-1252.tentative.html
#http://www.web-platform.test:8000/FileAPI/file/send-file-form-x-user-defined.tentative.html
#http://www.web-platform.test:8000/FileAPI/FileReader/workers.html
#http://www.web-platform.test:8000/FileAPI/FileReader/test_notreadableerrors-manual.html
#http://www.web-platform.test:8000/FileAPI/FileReader/Progress_event_bubbles_cancelable.html
#http://www.web-platform.test:8000/FileAPI/FileReader/test_errors-manual.html
#http://www.web-platform.test:8000/FileAPI/FileReader/test_securityerrors-manual.html
#http://www.web-platform.test:8000/FileAPI/url/url_xmlhttprequest_img.html
#http://www.web-platform.test:8000/FileAPI/url/url_createobjecturl_file_img-manual.html
#http://www.web-platform.test:8000/FileAPI/url/resources/create-helper.html
#http://www.web-platform.test:8000/FileAPI/url/resources/revoke-helper.html
#http://www.web-platform.test:8000/FileAPI/url/sandboxed-iframe.html
#http://www.web-platform.test:8000/FileAPI/url/url_xmlhttprequest_img-ref.html
#http://www.web-platform.test:8000/FileAPI/url/cross-global-revoke.sub.html
#http://www.web-platform.test:8000/FileAPI/url/unicode-origin.sub.html
#http://www.web-platform.test:8000/FileAPI/url/url-lifetime.html
#http://www.web-platform.test:8000/FileAPI/url/multi-global-origin-serialization.sub.html
#http://www.web-platform.test:8000/FileAPI/url/url_createobjecturl_file-manual.html
#http://www.web-platform.test:8000/FileAPI/idlharness.html
#http://www.web-platform.test:8000/FileAPI/support/document-domain-setter.sub.html
#http://www.web-platform.test:8000/FileAPI/support/incumbent.sub.html
#http://www.web-platform.test:8000/FileAPI/support/url-origin.html
#http://www.web-platform.test:8000/FileAPI/fileReader.html
#http://www.web-platform.test:8000/FileAPI/progress-manual.html
