#https://web-platform.test:8443/service-workers/service-worker/about-blank-replacement.https.html
#https://web-platform.test:8443/service-workers/service-worker/activate-event-after-install-state-change.https.html
#https://web-platform.test:8443/service-workers/service-worker/activation-after-registration.https.html
#https://web-platform.test:8443/service-workers/service-worker/activation.https.html
#https://web-platform.test:8443/service-workers/service-worker/active.https.html
#https://web-platform.test:8443/service-workers/service-worker/appcache-ordering-main.https.html
#https://web-platform.test:8443/service-workers/service-worker/claim-affect-other-registration.https.html
#https://web-platform.test:8443/service-workers/service-worker/claim-fetch.https.html
#https://web-platform.test:8443/service-workers/service-worker/claim-not-using-registration.https.html
#https://web-platform.test:8443/service-workers/service-worker/claim-shared-worker-fetch.https.html
#https://web-platform.test:8443/service-workers/service-worker/claim-using-registration.https.html
#https://web-platform.test:8443/service-workers/service-worker/claim-with-redirect.https.html
#https://web-platform.test:8443/service-workers/service-worker/claim-worker-fetch.https.html
#https://web-platform.test:8443/service-workers/service-worker/client-id.https.html
#https://web-platform.test:8443/service-workers/service-worker/client-navigate.https.html
#https://web-platform.test:8443/service-workers/service-worker/clients-get-client-types.https.html
#https://web-platform.test:8443/service-workers/service-worker/clients-get-cross-origin.https.html
#https://web-platform.test:8443/service-workers/service-worker/clients-get.https.html
#https://web-platform.test:8443/service-workers/service-worker/clients-matchall-client-types.https.html
#https://web-platform.test:8443/service-workers/service-worker/clients-matchall-exact-controller.https.html
#https://web-platform.test:8443/service-workers/service-worker/clients-matchall.https.html
#https://web-platform.test:8443/service-workers/service-worker/clients-matchall-include-uncontrolled.https.html
#https://web-platform.test:8443/service-workers/service-worker/clients-matchall-on-evaluation.https.html
#https://web-platform.test:8443/service-workers/service-worker/clients-matchall-order.https.html
#https://web-platform.test:8443/service-workers/service-worker/controller-on-disconnect.https.html
#https://web-platform.test:8443/service-workers/service-worker/controller-on-load.https.html
#https://web-platform.test:8443/service-workers/service-worker/controller-on-reload.https.html
#https://web-platform.test:8443/service-workers/service-worker/dedicated-worker-service-worker-interception.https.html
#https://web-platform.test:8443/service-workers/service-worker/detached-context.https.html
#https://web-platform.test:8443/service-workers/service-worker/embed-and-object-are-not-intercepted.https.html
#https://web-platform.test:8443/service-workers/service-worker/extendable-event-async-waituntil.https.html
#https://web-platform.test:8443/service-workers/service-worker/extendable-event-waituntil.https.html
#
#
#https://web-platform.test:8443/service-workers/service-worker/fetch-canvas-tainting-image-cache.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-canvas-tainting-image.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-canvas-tainting-video-cache.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-canvas-tainting-video.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-canvas-tainting-video-with-range-request.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-cors-exposed-header-names.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-cors-xhr.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-csp.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-after-navigation-within-page.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-async-respond-with.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-is-history-backward-navigation-manual.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-is-history-forward-navigation-manual.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-is-reload-iframe-navigation-manual.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-is-reload-navigation-manual.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-network-error.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-redirect.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-referrer-policy.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-respond-with-argument.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-respond-with-body-loaded-in-chunk.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-respond-with-custom-response.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-respond-with-partial-stream.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-respond-with-readable-stream-chunk.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-respond-with-readable-stream.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-respond-with-response-body-with-invalid-chunk.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-respond-with-stops-propagation.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-throws-after-respond-with.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-within-sw.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-event-within-sw-manual.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-frame-resource.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-header-visibility.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-mixed-content-to-inscope.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-mixed-content-to-outscope.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-request-css-base-url.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-request-css-cross-origin.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-request-css-images.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-request-fallback.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-request-html-imports.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-request-no-freshness-headers.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-request-redirect.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-request-resources.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-request-xhr.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-request-xhr-sync.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-request-xhr-sync-on-worker.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-response-taint.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-response-xhr.https.html
#https://web-platform.test:8443/service-workers/service-worker/fetch-waits-for-activate.https.html
#
#
#https://web-platform.test:8443/service-workers/service-worker/getregistration.https.html
#https://web-platform.test:8443/service-workers/service-worker/getregistrations.https.html
#https://web-platform.test:8443/service-workers/service-worker/http-to-https-redirect-and-register.https.html
#https://web-platform.test:8443/service-workers/service-worker/immutable-prototype-serviceworker.https.html
#https://web-platform.test:8443/service-workers/service-worker/import-scripts-redirect.https.html
#https://web-platform.test:8443/service-workers/service-worker/import-scripts-resource-map.https.html
#https://web-platform.test:8443/service-workers/service-worker/import-scripts-updated-flag.https.html
#https://web-platform.test:8443/service-workers/service-worker/indexeddb.https.html
#https://web-platform.test:8443/service-workers/service-worker/install-event-type.https.html
#https://web-platform.test:8443/service-workers/service-worker/installing.https.html
#https://web-platform.test:8443/service-workers/service-worker/interfaces-sw.https.html
#https://web-platform.test:8443/service-workers/service-worker/interfaces-window.https.html
#https://web-platform.test:8443/service-workers/service-worker/invalid-blobtype.https.html
#https://web-platform.test:8443/service-workers/service-worker/invalid-header.https.html
#https://web-platform.test:8443/service-workers/service-worker/iso-latin1-header.https.html
#https://web-platform.test:8443/service-workers/service-worker/local-url-inherit-controller.https.html
#https://web-platform.test:8443/service-workers/service-worker/mime-sniffing.https.html
#https://web-platform.test:8443/service-workers/service-worker/multi-globals/current/current.https.html
#https://web-platform.test:8443/service-workers/service-worker/multi-globals/incumbent/incumbent.https.html
#https://web-platform.test:8443/service-workers/service-worker/multi-globals/relevant/relevant.https.html
#https://web-platform.test:8443/service-workers/service-worker/multi-globals/url-parsing.https.html
#https://web-platform.test:8443/service-workers/service-worker/multipart-image.https.html
#https://web-platform.test:8443/service-workers/service-worker/multiple-register.https.html
#https://web-platform.test:8443/service-workers/service-worker/multiple-update.https.html
#https://web-platform.test:8443/service-workers/service-worker/navigate-window.https.html
#https://web-platform.test:8443/service-workers/service-worker/navigation-preload/broken-chunked-encoding.https.html
#https://web-platform.test:8443/service-workers/service-worker/navigation-preload/chunked-encoding.https.html
#https://web-platform.test:8443/service-workers/service-worker/navigation-preload/empty-preload-response-body.https.html
#https://web-platform.test:8443/service-workers/service-worker/navigation-preload/get-state.https.html
#https://web-platform.test:8443/service-workers/service-worker/navigation-preload/redirect.https.html
#https://web-platform.test:8443/service-workers/service-worker/navigation-preload/request-headers.https.html
#https://web-platform.test:8443/service-workers/service-worker/navigation-preload/resource-timing.https.html
#https://web-platform.test:8443/service-workers/service-worker/navigation-redirect-body.https.html
#https://web-platform.test:8443/service-workers/service-worker/navigation-redirect.https.html
#https://web-platform.test:8443/service-workers/service-worker/navigation-redirect-to-http.https.html
#https://web-platform.test:8443/service-workers/service-worker/navigation-timing.https.html
#https://web-platform.test:8443/service-workers/service-worker/onactivate-script-error.https.html
#https://web-platform.test:8443/service-workers/service-worker/oninstall-script-error.https.html
#https://web-platform.test:8443/service-workers/service-worker/opaque-response-preloaded.https.html
#https://web-platform.test:8443/service-workers/service-worker/performance-timeline.https.html
#https://web-platform.test:8443/service-workers/service-worker/postmessage-blob-url.https.html
#https://web-platform.test:8443/service-workers/service-worker/postmessage-from-waiting-serviceworker.https.html
#https://web-platform.test:8443/service-workers/service-worker/postmessage.https.html
#https://web-platform.test:8443/service-workers/service-worker/postmessage-msgport-to-client.https.html
#https://web-platform.test:8443/service-workers/service-worker/postmessage-to-client.https.html
#https://web-platform.test:8443/service-workers/service-worker/ready.https.html
#https://web-platform.test:8443/service-workers/service-worker/redirected-response.https.html
#https://web-platform.test:8443/service-workers/service-worker/referer.https.html
#https://web-platform.test:8443/service-workers/service-worker/referrer-policy-header.https.html
#
#
#https://web-platform.test:8443/service-workers/service-worker/register-closed-window.https.html
#https://web-platform.test:8443/service-workers/service-worker/register-default-scope.https.html
#https://web-platform.test:8443/service-workers/service-worker/register-same-scope-different-script-url.https.html
#https://web-platform.test:8443/service-workers/service-worker/register-wait-forever-in-install-worker.https.html
#https://web-platform.test:8443/service-workers/service-worker/registration-basic.https.html
#https://web-platform.test:8443/service-workers/service-worker/registration-end-to-end.https.html
#https://web-platform.test:8443/service-workers/service-worker/registration-events.https.html
#https://web-platform.test:8443/service-workers/service-worker/registration-iframe.https.html
#https://web-platform.test:8443/service-workers/service-worker/registration-mime-types.https.html
#https://web-platform.test:8443/service-workers/service-worker/registration-scope.https.html
#https://web-platform.test:8443/service-workers/service-worker/registration-script.https.html
#https://web-platform.test:8443/service-workers/service-worker/registration-script-url.https.html
#https://web-platform.test:8443/service-workers/service-worker/registration-security-error.https.html
#https://web-platform.test:8443/service-workers/service-worker/registration-service-worker-attributes.https.html
#https://web-platform.test:8443/service-workers/service-worker/registration-updateviacache.https.html
#
#
#https://web-platform.test:8443/service-workers/service-worker/rejections.https.html
#https://web-platform.test:8443/service-workers/service-worker/request-end-to-end.https.html
#https://web-platform.test:8443/service-workers/service-worker/resource-timing-cross-origin.https.html
#https://web-platform.test:8443/service-workers/service-worker/resource-timing.https.html
#https://web-platform.test:8443/service-workers/service-worker/respond-with-body-accessed-response.https.html
#https://web-platform.test:8443/service-workers/service-worker/sandboxed-iframe-fetch-event.https.html
#https://web-platform.test:8443/service-workers/service-worker/sandboxed-iframe-navigator-serviceworker.https.html
#https://web-platform.test:8443/service-workers/service-worker/Service-Worker-Allowed-header.https.html
#https://web-platform.test:8443/service-workers/service-worker/service-worker-csp-connect.https.html
#https://web-platform.test:8443/service-workers/service-worker/service-worker-csp-default.https.html
#https://web-platform.test:8443/service-workers/service-worker/service-worker-csp-script.https.html
#
#
#https://web-platform.test:8443/service-workers/service-worker/ServiceWorkerGlobalScope/close.https.html
#https://web-platform.test:8443/service-workers/service-worker/ServiceWorkerGlobalScope/extendable-message-event-constructor.https.html
#https://web-platform.test:8443/service-workers/service-worker/ServiceWorkerGlobalScope/extendable-message-event.https.html
#https://web-platform.test:8443/service-workers/service-worker/ServiceWorkerGlobalScope/postmessage.https.html
#https://web-platform.test:8443/service-workers/service-worker/ServiceWorkerGlobalScope/registration-attribute.https.html
#https://web-platform.test:8443/service-workers/service-worker/ServiceWorkerGlobalScope/service-worker-error-event.https.html
#https://web-platform.test:8443/service-workers/service-worker/ServiceWorkerGlobalScope/unregister.https.html
#https://web-platform.test:8443/service-workers/service-worker/ServiceWorkerGlobalScope/update.https.html
#
#
#https://web-platform.test:8443/service-workers/service-worker/service-worker-header.https.html
#https://web-platform.test:8443/service-workers/service-worker/serviceworker-message-event-historical.https.html
#https://web-platform.test:8443/service-workers/service-worker/serviceworkerobject-scripturl.https.html
#https://web-platform.test:8443/service-workers/service-worker/shared-worker-controlled.https.html
#https://web-platform.test:8443/service-workers/service-worker/skip-waiting.https.html
#https://web-platform.test:8443/service-workers/service-worker/skip-waiting-installed.https.html
#https://web-platform.test:8443/service-workers/service-worker/skip-waiting-using-registration.https.html
#https://web-platform.test:8443/service-workers/service-worker/skip-waiting-without-client.https.html
#https://web-platform.test:8443/service-workers/service-worker/skip-waiting-without-using-registration.https.html
#https://web-platform.test:8443/service-workers/service-worker/state.https.html
#https://web-platform.test:8443/service-workers/service-worker/svg-target-reftest.https.html
#https://web-platform.test:8443/service-workers/service-worker/synced-state.https.html
#https://web-platform.test:8443/service-workers/service-worker/uncontrolled-page.https.html
#https://web-platform.test:8443/service-workers/service-worker/unregister-controller.https.html
#https://web-platform.test:8443/service-workers/service-worker/unregister.https.html
#https://web-platform.test:8443/service-workers/service-worker/unregister-then-register.https.html
#https://web-platform.test:8443/service-workers/service-worker/unregister-then-register-new-script.https.html
#https://web-platform.test:8443/service-workers/service-worker/update-after-navigation-fetch-event.https.html
#https://web-platform.test:8443/service-workers/service-worker/update-after-oneday.https.html
#https://web-platform.test:8443/service-workers/service-worker/update-bytecheck.https.html
#https://web-platform.test:8443/service-workers/service-worker/update.https.html
#https://web-platform.test:8443/service-workers/service-worker/update-recovery.https.html
#https://web-platform.test:8443/service-workers/service-worker/update-result.https.html
#https://web-platform.test:8443/service-workers/service-worker/waiting.https.html
#https://web-platform.test:8443/service-workers/service-worker/websocket.https.html
#https://web-platform.test:8443/service-workers/service-worker/websocket-in-service-worker.https.html
#https://web-platform.test:8443/service-workers/service-worker/webvtt-cross-origin.https.html
#https://web-platform.test:8443/service-workers/service-worker/windowclient-navigate.https.html
#https://web-platform.test:8443/service-workers/service-worker/worker-client-id.https.html
#https://web-platform.test:8443/service-workers/service-worker/worker-in-sandboxed-iframe-by-csp-fetch-event.https.html
#https://web-platform.test:8443/service-workers/service-worker/worker-interception.https.html
#https://web-platform.test:8443/service-workers/service-worker/worker-interception-redirect.https.html
#
#
#https://web-platform.test:8443/service-workers/cache-storage/common.https.html
#https://web-platform.test:8443/service-workers/cache-storage/serviceworker/cache-abort.https.html
#https://web-platform.test:8443/service-workers/cache-storage/serviceworker/cache-add.https.html
#https://web-platform.test:8443/service-workers/cache-storage/serviceworker/cache-delete.https.html
#https://web-platform.test:8443/service-workers/cache-storage/serviceworker/cache-keys-attributes-for-service-worker.https.html
#https://web-platform.test:8443/service-workers/cache-storage/serviceworker/cache-keys.https.html
#https://web-platform.test:8443/service-workers/cache-storage/serviceworker/cache-matchAll.https.html
#https://web-platform.test:8443/service-workers/cache-storage/serviceworker/cache-match.https.html
#https://web-platform.test:8443/service-workers/cache-storage/serviceworker/cache-put.https.html
#https://web-platform.test:8443/service-workers/cache-storage/serviceworker/cache-storage.https.html
#https://web-platform.test:8443/service-workers/cache-storage/serviceworker/cache-storage-keys.https.html
#https://web-platform.test:8443/service-workers/cache-storage/serviceworker/cache-storage-match.https.html
#https://web-platform.test:8443/service-workers/cache-storage/serviceworker/credentials.https.html
#https://web-platform.test:8443/service-workers/cache-storage/window/cache-abort.https.html
#https://web-platform.test:8443/service-workers/cache-storage/window/cache-add.https.html
#https://web-platform.test:8443/service-workers/cache-storage/window/cache-delete.https.html
#https://web-platform.test:8443/service-workers/cache-storage/window/cache-keys.https.html
#https://web-platform.test:8443/service-workers/cache-storage/window/cache-matchAll.https.html
#https://web-platform.test:8443/service-workers/cache-storage/window/cache-match.https.html
#https://web-platform.test:8443/service-workers/cache-storage/window/cache-put.https.html
#https://web-platform.test:8443/service-workers/cache-storage/window/cache-storage.https.html
#https://web-platform.test:8443/service-workers/cache-storage/window/cache-storage-keys.https.html
#https://web-platform.test:8443/service-workers/cache-storage/window/cache-storage-match.https.html
#https://web-platform.test:8443/service-workers/cache-storage/window/sandboxed-iframes.https.html
#https://web-platform.test:8443/service-workers/cache-storage/worker/cache-abort.https.html
#https://web-platform.test:8443/service-workers/cache-storage/worker/cache-add.https.html
#https://web-platform.test:8443/service-workers/cache-storage/worker/cache-delete.https.html
#https://web-platform.test:8443/service-workers/cache-storage/worker/cache-keys.https.html
#https://web-platform.test:8443/service-workers/cache-storage/worker/cache-matchAll.https.html
#https://web-platform.test:8443/service-workers/cache-storage/worker/cache-match.https.html
#https://web-platform.test:8443/service-workers/cache-storage/worker/cache-put.https.html
#https://web-platform.test:8443/service-workers/cache-storage/worker/cache-storage.https.html
#https://web-platform.test:8443/service-workers/cache-storage/worker/cache-storage-keys.https.html
#https://web-platform.test:8443/service-workers/cache-storage/worker/cache-storage-match.https.html
#
#
#https://web-platform.test:8443/service-workers/stub-3.1.1-service-worker-scope.html
#https://web-platform.test:8443/service-workers/stub-3.1.2-service-worker-url.html
#https://web-platform.test:8443/service-workers/stub-3.1.3-service-worker-state.html
#https://web-platform.test:8443/service-workers/stub-3.1.4-service-worker-on-state-change.html
#https://web-platform.test:8443/service-workers/stub-3.1-service-worker-obj.html
#https://web-platform.test:8443/service-workers/stub-3.2.10-navigator-service-worker-oncontrollerchange.html
#https://web-platform.test:8443/service-workers/stub-3.2.11-navigator-service-worker-onreloadpage.html
#https://web-platform.test:8443/service-workers/stub-3.2.12-navigator-service-worker-onerror.html
#https://web-platform.test:8443/service-workers/stub-3.2.1-navigator-service-worker-installing.html
#https://web-platform.test:8443/service-workers/stub-3.2.2-navigator-service-worker-waiting.html
#https://web-platform.test:8443/service-workers/stub-3.2.3-navigator-service-worker-active.html
#https://web-platform.test:8443/service-workers/stub-3.2.4-navigator-service-worker-controller.html
#https://web-platform.test:8443/service-workers/stub-3.2.5-navigator-service-worker-ready.html
#https://web-platform.test:8443/service-workers/stub-3.2.6-navigator-service-worker-getAll.html
#https://web-platform.test:8443/service-workers/stub-3.2.7-navigator-service-worker-register.html
#https://web-platform.test:8443/service-workers/stub-3.2.8-navigator-service-worker-unregister.html
#https://web-platform.test:8443/service-workers/stub-3.2.9-navigator-service-worker-onupdatefound.html
#https://web-platform.test:8443/service-workers/stub-3.2-navigator-service-worker.html
#https://web-platform.test:8443/service-workers/stub-4.1.1-service-worker-global-scope-caches.html
#https://web-platform.test:8443/service-workers/stub-4.1.2-service-worker-global-scope-clients.html
#https://web-platform.test:8443/service-workers/stub-4.1.3-service-worker-global-scope-scope.html
#https://web-platform.test:8443/service-workers/stub-4.1.4-service-worker-global-scope-fetch.html
#https://web-platform.test:8443/service-workers/stub-4.1.5-service-worker-global-scope-update.html
#https://web-platform.test:8443/service-workers/stub-4.1.6-service-worker-global-scope-unregister.html
#https://web-platform.test:8443/service-workers/stub-4.1.7-service-worker-global-scope-onmessage.html
#https://web-platform.test:8443/service-workers/stub-4.1-service-worker-global-scope.html
#https://web-platform.test:8443/service-workers/stub-4.2-client.html
#https://web-platform.test:8443/service-workers/stub-4.3.1-get-serviced-method.html
#https://web-platform.test:8443/service-workers/stub-4.3.2-reloadall-method.html
#https://web-platform.test:8443/service-workers/stub-4.3-service-worker-clients.html
#https://web-platform.test:8443/service-workers/stub-4.4-request-objects.html
#https://web-platform.test:8443/service-workers/stub-4.5.2-response.html
#https://web-platform.test:8443/service-workers/stub-4.5.4-opaque-response.html
#https://web-platform.test:8443/service-workers/stub-4.5-response-objects.html
#https://web-platform.test:8443/service-workers/stub-4.6.1-cache-lifetimes.html
#https://web-platform.test:8443/service-workers/stub-4.6.2-cache.html
#https://web-platform.test:8443/service-workers/stub-4.6.3-cache-storage.html
#https://web-platform.test:8443/service-workers/stub-4.6-cache-objects.html
#https://web-platform.test:8443/service-workers/stub-4.7.1.1-wait-until-method.html
#https://web-platform.test:8443/service-workers/stub-4.7.1-install-phase-event.html
#https://web-platform.test:8443/service-workers/stub-4.7.2.1-install-event-section.html
#https://web-platform.test:8443/service-workers/stub-4.7.2.2-replace-method.html
#https://web-platform.test:8443/service-workers/stub-4.7.2-install-event.html
#https://web-platform.test:8443/service-workers/stub-4.7.3-activate-event.html
#https://web-platform.test:8443/service-workers/stub-4.7.4.1-fetch-event-section.html
#https://web-platform.test:8443/service-workers/stub-4.7.4.2-respond-with-method.html
#https://web-platform.test:8443/service-workers/stub-4.7.4.3-default-method.html
#https://web-platform.test:8443/service-workers/stub-4.7.4.4-is-reload-attribute.html
#https://web-platform.test:8443/service-workers/stub-5.1-origin-relativity.html
#https://web-platform.test:8443/service-workers/stub-5.2-cross-origin-resources.html
