#http://web-platform.test:8000/svg/path/bearing/absolute-ref.svg
#http://web-platform.test:8000/svg/path/bearing/absolute.svg
#http://web-platform.test:8000/svg/path/bearing/relative-ref.svg
#http://web-platform.test:8000/svg/path/bearing/relative.svg
#http://web-platform.test:8000/svg/path/bearing/zero-ref.svg
#http://web-platform.test:8000/svg/path/bearing/zero.svg
#http://web-platform.test:8000/svg/path/closepath/segment-completing-ref.svg
#http://web-platform.test:8000/svg/path/closepath/segment-completing.svg
#http://web-platform.test:8000/svg/path/distance/pathLength-positive-percentage.svg
#http://web-platform.test:8000/svg/path/distance/pathLength-positive-ref.svg
#http://web-platform.test:8000/svg/path/distance/pathLength-positive.svg
#http://web-platform.test:8000/svg/path/distance/pathLength-zero-percentage-ref.svg
#http://web-platform.test:8000/svg/path/distance/pathLength-zero-percentage.svg
#http://web-platform.test:8000/svg/path/distance/pathLength-zero-ref.svg
#http://web-platform.test:8000/svg/path/distance/pathLength-zero.svg
#http://web-platform.test:8000/svg/path/error-handling/bounding.svg
#http://web-platform.test:8000/svg/path/error-handling/render-until-error-ref.svg
#http://web-platform.test:8000/svg/path/error-handling/render-until-error.svg
#http://web-platform.test:8000/svg/path/interfaces/SVGAnimatedPathData-removed.svg
#http://web-platform.test:8000/svg/path/property/d-interpolation-discrete.svg
#http://web-platform.test:8000/svg/path/property/d-interpolation-relative-absolute.svg
#http://web-platform.test:8000/svg/path/property/d-interpolation-single.svg
#http://web-platform.test:8000/svg/path/property/getComputedStyle.svg
#http://web-platform.test:8000/svg/path/property/priority-ref.svg
#http://web-platform.test:8000/svg/path/property/priority.svg
