#http://web-platform.test:8000/svg/import/animate-dom-01-f-manual.svg
#http://web-platform.test:8000/svg/import/animate-dom-02-f-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-02-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-03-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-04-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-05-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-06-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-07-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-08-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-09-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-10-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-11-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-12-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-13-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-14-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-15-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-17-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-19-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-20-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-21-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-22-b-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-23-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-24-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-25-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-26-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-27-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-28-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-29-b-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-30-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-31-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-32-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-33-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-34-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-35-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-36-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-37-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-38-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-39-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-40-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-41-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-44-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-46-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-52-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-53-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-60-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-61-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-62-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-63-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-64-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-65-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-66-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-67-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-68-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-69-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-70-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-77-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-78-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-80-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-81-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-82-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-83-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-84-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-85-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-86-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-87-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-88-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-89-t-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-90-b-manual.svg
#http://web-platform.test:8000/svg/import/animate-elem-91-t-manual.svg
#http://web-platform.test:8001/svg/import/animate-elem-92-t-manual.svg
#http://web-platform.test:8002/svg/import/animate-interact-events-01-t-manual.svg
#http://web-platform.test:8003/svg/import/animate-interact-pevents-01-t-manual.svg
#http://web-platform.test:8004/svg/import/animate-interact-pevents-02-t-manual.svg
#http://web-platform.test:8005/svg/import/animate-interact-pevents-03-t-manual.svg
#http://web-platform.test:8006/svg/import/animate-interact-pevents-04-t-manual.svg
#http://web-platform.test:8007/svg/import/animate-pservers-grad-01-b-manual.svg
#http://web-platform.test:8008/svg/import/animate-script-elem-01-b-manual.svg
#http://web-platform.test:8009/svg/import/animate-struct-dom-01-b-manual.svg
#http://web-platform.test:8010/svg/import/color-prof-01-f-manual.svg
#http://web-platform.test:8011/svg/import/color-prop-01-b-manual.svg
#http://web-platform.test:8012/svg/import/color-prop-02-f-manual.svg
#http://web-platform.test:8013/svg/import/color-prop-03-t-manual.svg
#http://web-platform.test:8014/svg/import/color-prop-04-t-manual.svg
#http://web-platform.test:8015/svg/import/color-prop-05-t-manual.svg
#http://web-platform.test:8016/svg/import/conform-viewers-02-f-manual.svg
#http://web-platform.test:8017/svg/import/conform-viewers-03-f-manual.svg
#http://web-platform.test:8018/svg/import/coords-coord-01-t-manual.svg
#http://web-platform.test:8019/svg/import/coords-coord-02-t-manual.svg
#http://web-platform.test:8020/svg/import/coords-dom-01-f-manual.svg
#http://web-platform.test:8021/svg/import/coords-dom-02-f-manual.svg
#http://web-platform.test:8022/svg/import/coords-dom-03-f-manual.svg
#http://web-platform.test:8023/svg/import/coords-dom-04-f-manual.svg
#http://web-platform.test:8024/svg/import/coords-trans-01-b-manual.svg
#http://web-platform.test:8025/svg/import/coords-trans-02-t-manual.svg
#http://web-platform.test:8026/svg/import/coords-trans-03-t-manual.svg
#http://web-platform.test:8027/svg/import/coords-trans-04-t-manual.svg
#http://web-platform.test:8028/svg/import/coords-trans-05-t-manual.svg
#http://web-platform.test:8029/svg/import/coords-trans-06-t-manual.svg
#http://web-platform.test:8030/svg/import/coords-trans-07-t-manual.svg
#http://web-platform.test:8031/svg/import/coords-trans-08-t-manual.svg
#http://web-platform.test:8032/svg/import/coords-trans-09-t-manual.svg
#http://web-platform.test:8033/svg/import/coords-trans-10-f-manual.svg
#http://web-platform.test:8034/svg/import/coords-trans-11-f-manual.svg
#http://web-platform.test:8035/svg/import/coords-trans-12-f-manual.svg
#http://web-platform.test:8036/svg/import/coords-trans-13-f-manual.svg
#http://web-platform.test:8037/svg/import/coords-trans-14-f-manual.svg
#http://web-platform.test:8038/svg/import/coords-transformattr-01-f-manual.svg
#http://web-platform.test:8039/svg/import/coords-transformattr-02-f-manual.svg
#http://web-platform.test:8040/svg/import/coords-transformattr-03-f-manual.svg
#http://web-platform.test:8041/svg/import/coords-transformattr-04-f-manual.svg
#http://web-platform.test:8042/svg/import/coords-transformattr-05-f-manual.svg
#http://web-platform.test:8043/svg/import/coords-units-01-b-manual.svg
#http://web-platform.test:8044/svg/import/coords-units-02-b-manual.svg
#http://web-platform.test:8045/svg/import/coords-units-03-b-manual.svg
#http://web-platform.test:8046/svg/import/coords-viewattr-01-b-manual.svg
#http://web-platform.test:8047/svg/import/coords-viewattr-02-b-manual.svg
#http://web-platform.test:8048/svg/import/coords-viewattr-03-b-manual.svg
#http://web-platform.test:8049/svg/import/coords-viewattr-04-f-manual.svg
#http://web-platform.test:8050/svg/import/extend-namespace-01-f-manual.svg
#http://web-platform.test:8051/svg/import/filters-background-01-f-manual.svg
#http://web-platform.test:8052/svg/import/filters-blend-01-b-manual.svg
#http://web-platform.test:8053/svg/import/filters-color-01-b-manual.svg
#http://web-platform.test:8054/svg/import/filters-color-02-b-manual.svg
#http://web-platform.test:8055/svg/import/filters-composite-02-b-manual.svg
#http://web-platform.test:8056/svg/import/filters-composite-03-f-manual.svg
#http://web-platform.test:8057/svg/import/filters-composite-04-f-manual.svg
#http://web-platform.test:8058/svg/import/filters-composite-05-f-manual.svg
#http://web-platform.test:8059/svg/import/filters-comptran-01-b-manual.svg
#http://web-platform.test:8060/svg/import/filters-conv-01-f-manual.svg
#http://web-platform.test:8061/svg/import/filters-conv-02-f-manual.svg
#http://web-platform.test:8062/svg/import/filters-conv-03-f-manual.svg
#http://web-platform.test:8063/svg/import/filters-conv-04-f-manual.svg
#http://web-platform.test:8064/svg/import/filters-conv-05-f-manual.svg
#http://web-platform.test:8065/svg/import/filters-diffuse-01-f-manual.svg
#http://web-platform.test:8066/svg/import/filters-displace-01-f-manual.svg
#http://web-platform.test:8067/svg/import/filters-displace-02-f-manual.svg
#http://web-platform.test:8068/svg/import/filters-example-01-b-manual.svg
#http://web-platform.test:8069/svg/import/filters-felem-01-b-manual.svg
#http://web-platform.test:8070/svg/import/filters-felem-02-f-manual.svg
#http://web-platform.test:8071/svg/import/filters-gauss-01-b-manual.svg
#http://web-platform.test:8072/svg/import/filters-gauss-02-f-manual.svg
#http://web-platform.test:8073/svg/import/filters-gauss-03-f-manual.svg
#http://web-platform.test:8074/svg/import/filters-image-01-b-manual.svg
#http://web-platform.test:8075/svg/import/filters-image-02-b-manual.svg
#http://web-platform.test:8076/svg/import/filters-image-03-f-manual.svg
#http://web-platform.test:8077/svg/import/filters-image-04-f-manual.svg
#http://web-platform.test:8078/svg/import/filters-image-05-f-manual.svg
#http://web-platform.test:8079/svg/import/filters-light-01-f-manual.svg
#http://web-platform.test:8080/svg/import/filters-light-02-f-manual.svg
#http://web-platform.test:8081/svg/import/filters-light-03-f-manual.svg
#http://web-platform.test:8082/svg/import/filters-light-04-f-manual.svg
#http://web-platform.test:8083/svg/import/filters-light-05-f-manual.svg
#http://web-platform.test:8084/svg/import/filters-morph-01-f-manual.svg
#http://web-platform.test:8085/svg/import/filters-offset-01-b-manual.svg
#http://web-platform.test:8086/svg/import/filters-offset-02-b-manual.svg
#http://web-platform.test:8087/svg/import/filters-overview-01-b-manual.svg
#http://web-platform.test:8088/svg/import/filters-overview-02-b-manual.svg
#http://web-platform.test:8089/svg/import/filters-overview-03-b-manual.svg
#http://web-platform.test:8090/svg/import/filters-specular-01-f-manual.svg
#http://web-platform.test:8091/svg/import/filters-tile-01-b-manual.svg
#http://web-platform.test:8092/svg/import/filters-turb-01-f-manual.svg
#http://web-platform.test:8093/svg/import/filters-turb-02-f-manual.svg
#http://web-platform.test:8094/svg/import/fonts-desc-01-t-manual.svg
#http://web-platform.test:8095/svg/import/fonts-desc-02-t-manual.svg
#http://web-platform.test:8096/svg/import/fonts-desc-03-t-manual.svg
#http://web-platform.test:8097/svg/import/fonts-desc-04-t-manual.svg
#http://web-platform.test:8098/svg/import/fonts-desc-05-t-manual.svg
#http://web-platform.test:8099/svg/import/fonts-elem-01-t-manual.svg
#http://web-platform.test:8100/svg/import/fonts-elem-02-t-manual.svg
#http://web-platform.test:8101/svg/import/fonts-elem-03-b-manual.svg
#http://web-platform.test:8102/svg/import/fonts-elem-04-b-manual.svg
#http://web-platform.test:8103/svg/import/fonts-elem-05-t-manual.svg
#http://web-platform.test:8104/svg/import/fonts-elem-06-t-manual.svg
#http://web-platform.test:8105/svg/import/fonts-elem-07-b-manual.svg
#http://web-platform.test:8106/svg/import/fonts-glyph-02-t-manual.svg
#http://web-platform.test:8107/svg/import/fonts-glyph-03-t-manual.svg
#http://web-platform.test:8108/svg/import/fonts-glyph-04-t-manual.svg
#http://web-platform.test:8109/svg/import/fonts-kern-01-t-manual.svg
#http://web-platform.test:8110/svg/import/fonts-overview-201-t-manual.svg
#http://web-platform.test:8111/svg/import/imp-path-01-f-manual.svg
#http://web-platform.test:8112/svg/import/interact-cursor-01-f-manual.svg
#http://web-platform.test:8113/svg/import/interact-dom-01-b-manual.svg
#http://web-platform.test:8114/svg/import/interact-events-01-b-manual.svg
#http://web-platform.test:8115/svg/import/interact-events-02-b-manual.svg
#http://web-platform.test:8116/svg/import/interact-events-202-f-manual.svg
#http://web-platform.test:8117/svg/import/interact-events-203-t-manual.svg
#http://web-platform.test:8118/svg/import/interact-order-01-b-manual.svg
#http://web-platform.test:8119/svg/import/interact-order-02-b-manual.svg
#http://web-platform.test:8120/svg/import/interact-order-03-b-manual.svg
#http://web-platform.test:8121/svg/import/interact-pevents-01-b-manual.svg
#http://web-platform.test:8122/svg/import/interact-pevents-03-b-manual.svg
#http://web-platform.test:8123/svg/import/interact-pevents-04-t-manual.svg
#http://web-platform.test:8124/svg/import/interact-pevents-05-b-manual.svg
#http://web-platform.test:8125/svg/import/interact-pevents-07-t-manual.svg
#http://web-platform.test:8126/svg/import/interact-pevents-08-f-manual.svg
#http://web-platform.test:8127/svg/import/interact-pevents-09-f-manual.svg
#http://web-platform.test:8128/svg/import/interact-pevents-10-f-manual.svg
#http://web-platform.test:8129/svg/import/interact-pointer-01-t-manual.svg
#http://web-platform.test:8130/svg/import/interact-pointer-02-t-manual.svg
#http://web-platform.test:8131/svg/import/interact-pointer-03-t-manual.svg
#http://web-platform.test:8132/svg/import/interact-pointer-04-f-manual.svg
#http://web-platform.test:8133/svg/import/interact-zoom-01-t-manual.svg
#http://web-platform.test:8134/svg/import/interact-zoom-02-t-manual.svg
#http://web-platform.test:8135/svg/import/interact-zoom-03-t-manual.svg
#http://web-platform.test:8136/svg/import/linking-a-01-b-manual.svg
#http://web-platform.test:8137/svg/import/linking-a-03-b-manual.svg
#http://web-platform.test:8138/svg/import/linking-a-04-t-manual.svg
#http://web-platform.test:8139/svg/import/linking-a-05-t-manual.svg
#http://web-platform.test:8140/svg/import/linking-a-07-t-manual.svg
#http://web-platform.test:8141/svg/import/linking-a-08-t-manual.svg
#http://web-platform.test:8142/svg/import/linking-a-09-b-manual.svg
#http://web-platform.test:8143/svg/import/linking-a-10-f-manual.svg
#http://web-platform.test:8144/svg/import/linking-frag-01-f-manual.svg
#http://web-platform.test:8145/svg/import/linking-uri-01-b-manual.svg
#http://web-platform.test:8146/svg/import/linking-uri-02-b-manual.svg
#http://web-platform.test:8147/svg/import/linking-uri-03-t-manual.svg
#http://web-platform.test:8148/svg/import/masking-filter-01-f-manual.svg
#http://web-platform.test:8149/svg/import/masking-intro-01-f-manual.svg
#http://web-platform.test:8150/svg/import/masking-mask-01-b-manual.svg
#http://web-platform.test:8151/svg/import/masking-mask-02-f-manual.svg
#http://web-platform.test:8152/svg/import/masking-opacity-01-b-manual.svg
#http://web-platform.test:8153/svg/import/masking-path-01-b-manual.svg
#http://web-platform.test:8154/svg/import/masking-path-02-b-manual.svg
#http://web-platform.test:8155/svg/import/masking-path-03-b-manual.svg
#http://web-platform.test:8156/svg/import/masking-path-04-b-manual.svg
#http://web-platform.test:8157/svg/import/masking-path-05-f-manual.svg
#http://web-platform.test:8158/svg/import/masking-path-06-b-manual.svg
#http://web-platform.test:8159/svg/import/masking-path-07-b-manual.svg
#http://web-platform.test:8160/svg/import/masking-path-08-b-manual.svg
#http://web-platform.test:8161/svg/import/masking-path-09-b-manual.svg
#http://web-platform.test:8162/svg/import/masking-path-10-b-manual.svg
#http://web-platform.test:8163/svg/import/masking-path-11-b-manual.svg
#http://web-platform.test:8164/svg/import/masking-path-12-f-manual.svg
#http://web-platform.test:8165/svg/import/masking-path-13-f-manual.svg
#http://web-platform.test:8166/svg/import/masking-path-14-f-manual.svg
#http://web-platform.test:8167/svg/import/metadata-example-01-t-manual.svg
#http://web-platform.test:8168/svg/import/painting-control-01-f-manual.svg
#http://web-platform.test:8169/svg/import/painting-control-02-f-manual.svg
#http://web-platform.test:8170/svg/import/painting-control-03-f-manual.svg
#http://web-platform.test:8171/svg/import/painting-control-04-f-manual.svg
#http://web-platform.test:8172/svg/import/painting-control-05-f-manual.svg
#http://web-platform.test:8173/svg/import/painting-control-06-f-manual.svg
#http://web-platform.test:8174/svg/import/painting-fill-01-t-manual.svg
#http://web-platform.test:8175/svg/import/painting-fill-02-t-manual.svg
#http://web-platform.test:8176/svg/import/painting-fill-03-t-manual.svg
#http://web-platform.test:8177/svg/import/painting-fill-04-t-manual.svg
#http://web-platform.test:8178/svg/import/painting-fill-05-b-manual.svg
#http://web-platform.test:8179/svg/import/painting-marker-01-f-manual.svg
#http://web-platform.test:8180/svg/import/painting-marker-02-f-manual.svg
#http://web-platform.test:8181/svg/import/painting-marker-03-f-manual.svg
#http://web-platform.test:8182/svg/import/painting-marker-04-f-manual.svg
#http://web-platform.test:8183/svg/import/painting-marker-05-f-manual.svg
#http://web-platform.test:8184/svg/import/painting-marker-06-f-manual.svg
#http://web-platform.test:8185/svg/import/painting-marker-07-f-manual.svg
#http://web-platform.test:8186/svg/import/painting-marker-properties-01-f-manual.svg
#http://web-platform.test:8187/svg/import/painting-render-01-b-manual.svg
#http://web-platform.test:8188/svg/import/painting-render-02-b-manual.svg
#http://web-platform.test:8189/svg/import/painting-stroke-01-t-manual.svg
#http://web-platform.test:8190/svg/import/painting-stroke-02-t-manual.svg
#http://web-platform.test:8191/svg/import/painting-stroke-03-t-manual.svg
#http://web-platform.test:8192/svg/import/painting-stroke-04-t-manual.svg
#http://web-platform.test:8193/svg/import/painting-stroke-05-t-manual.svg
#http://web-platform.test:8194/svg/import/painting-stroke-06-t-manual.svg
#http://web-platform.test:8195/svg/import/painting-stroke-07-t-manual.svg
#http://web-platform.test:8196/svg/import/painting-stroke-08-t-manual.svg
#http://web-platform.test:8197/svg/import/painting-stroke-09-t-manual.svg
#http://web-platform.test:8198/svg/import/painting-stroke-10-t-manual.svg
#http://web-platform.test:8199/svg/import/paths-data-01-t-manual.svg
#http://web-platform.test:8200/svg/import/paths-data-02-t-manual.svg
#http://web-platform.test:8201/svg/import/paths-data-03-f-manual.svg
#http://web-platform.test:8202/svg/import/paths-data-04-t-manual.svg
#http://web-platform.test:8203/svg/import/paths-data-05-t-manual.svg
#http://web-platform.test:8204/svg/import/paths-data-06-t-manual.svg
#http://web-platform.test:8205/svg/import/paths-data-07-t-manual.svg
#http://web-platform.test:8206/svg/import/paths-data-08-t-manual.svg
#http://web-platform.test:8207/svg/import/paths-data-09-t-manual.svg
#http://web-platform.test:8208/svg/import/paths-data-10-t-manual.svg
#http://web-platform.test:8209/svg/import/paths-data-12-t-manual.svg
#http://web-platform.test:8210/svg/import/paths-data-13-t-manual.svg
#http://web-platform.test:8211/svg/import/paths-data-14-t-manual.svg
#http://web-platform.test:8212/svg/import/paths-data-15-t-manual.svg
#http://web-platform.test:8213/svg/import/paths-data-16-t-manual.svg
#http://web-platform.test:8214/svg/import/paths-data-17-f-manual.svg
#http://web-platform.test:8215/svg/import/paths-data-18-f-manual.svg
#http://web-platform.test:8216/svg/import/paths-data-19-f-manual.svg
#http://web-platform.test:8217/svg/import/paths-data-20-f-manual.svg
#http://web-platform.test:8218/svg/import/paths-dom-01-f-manual.svg
#http://web-platform.test:8219/svg/import/paths-dom-02-f-manual.svg
#http://web-platform.test:8220/svg/import/pservers-grad-01-b-manual.svg
#http://web-platform.test:8221/svg/import/pservers-grad-02-b-manual.svg
#http://web-platform.test:8222/svg/import/pservers-grad-03-b-manual.svg
#http://web-platform.test:8223/svg/import/pservers-grad-04-b-manual.svg
#http://web-platform.test:8224/svg/import/pservers-grad-05-b-manual.svg
#http://web-platform.test:8225/svg/import/pservers-grad-06-b-manual.svg
#http://web-platform.test:8226/svg/import/pservers-grad-07-b-manual.svg
#http://web-platform.test:8227/svg/import/pservers-grad-08-b-manual.svg
#http://web-platform.test:8228/svg/import/pservers-grad-09-b-manual.svg
#http://web-platform.test:8229/svg/import/pservers-grad-10-b-manual.svg
#http://web-platform.test:8230/svg/import/pservers-grad-11-b-manual.svg
#http://web-platform.test:8231/svg/import/pservers-grad-12-b-manual.svg
#http://web-platform.test:8232/svg/import/pservers-grad-13-b-manual.svg
#http://web-platform.test:8233/svg/import/pservers-grad-14-b-manual.svg
#http://web-platform.test:8234/svg/import/pservers-grad-15-b-manual.svg
#http://web-platform.test:8235/svg/import/pservers-grad-16-b-manual.svg
#http://web-platform.test:8236/svg/import/pservers-grad-17-b-manual.svg
#http://web-platform.test:8237/svg/import/pservers-grad-18-b-manual.svg
#http://web-platform.test:8238/svg/import/pservers-grad-20-b-manual.svg
#http://web-platform.test:8239/svg/import/pservers-grad-21-b-manual.svg
#http://web-platform.test:8240/svg/import/pservers-grad-22-b-manual.svg
#http://web-platform.test:8241/svg/import/pservers-grad-23-f-manual.svg
#http://web-platform.test:8242/svg/import/pservers-grad-24-f-manual.svg
#http://web-platform.test:8243/svg/import/pservers-grad-stops-01-f-manual.svg
#http://web-platform.test:8244/svg/import/pservers-pattern-01-b-manual.svg
#http://web-platform.test:8245/svg/import/pservers-pattern-02-f-manual.svg
#http://web-platform.test:8246/svg/import/pservers-pattern-03-f-manual.svg
#http://web-platform.test:8247/svg/import/pservers-pattern-04-f-manual.svg
#http://web-platform.test:8248/svg/import/pservers-pattern-05-f-manual.svg
#http://web-platform.test:8249/svg/import/pservers-pattern-06-f-manual.svg
#http://web-platform.test:8250/svg/import/pservers-pattern-07-f-manual.svg
#http://web-platform.test:8251/svg/import/pservers-pattern-08-f-manual.svg
#http://web-platform.test:8252/svg/import/pservers-pattern-09-f-manual.svg
#http://web-platform.test:8253/svg/import/render-elems-01-t-manual.svg
#http://web-platform.test:8254/svg/import/render-elems-02-t-manual.svg
#http://web-platform.test:8255/svg/import/render-elems-03-t-manual.svg
#http://web-platform.test:8256/svg/import/render-elems-06-t-manual.svg
#http://web-platform.test:8257/svg/import/render-elems-07-t-manual.svg
#http://web-platform.test:8258/svg/import/render-elems-08-t-manual.svg
#http://web-platform.test:8259/svg/import/render-groups-01-b-manual.svg
#http://web-platform.test:8260/svg/import/render-groups-03-t-manual.svg
#http://web-platform.test:8261/svg/import/script-handle-01-b-manual.svg
#http://web-platform.test:8262/svg/import/script-handle-02-b-manual.svg
#http://web-platform.test:8263/svg/import/script-handle-03-b-manual.svg
#http://web-platform.test:8264/svg/import/script-handle-04-b-manual.svg
#http://web-platform.test:8265/svg/import/script-specify-01-f-manual.svg
#http://web-platform.test:8266/svg/import/script-specify-02-f-manual.svg
#http://web-platform.test:8267/svg/import/shapes-circle-01-t-manual.svg
#http://web-platform.test:8268/svg/import/shapes-circle-02-t-manual.svg
#http://web-platform.test:8269/svg/import/shapes-ellipse-01-t-manual.svg
#http://web-platform.test:8270/svg/import/shapes-ellipse-02-t-manual.svg
#http://web-platform.test:8271/svg/import/shapes-ellipse-03-f-manual.svg
#http://web-platform.test:8272/svg/import/shapes-grammar-01-f-manual.svg
#http://web-platform.test:8273/svg/import/shapes-intro-01-t-manual.svg
#http://web-platform.test:8274/svg/import/shapes-intro-02-f-manual.svg
#http://web-platform.test:8275/svg/import/shapes-line-01-t-manual.svg
#http://web-platform.test:8276/svg/import/shapes-line-02-f-manual.svg
#http://web-platform.test:8277/svg/import/shapes-polygon-01-t-manual.svg
#http://web-platform.test:8278/svg/import/shapes-polygon-02-t-manual.svg
#http://web-platform.test:8279/svg/import/shapes-polygon-03-t-manual.svg
#http://web-platform.test:8280/svg/import/shapes-polyline-01-t-manual.svg
#http://web-platform.test:8281/svg/import/shapes-polyline-02-t-manual.svg
#http://web-platform.test:8282/svg/import/shapes-rect-02-t-manual.svg
#http://web-platform.test:8283/svg/import/shapes-rect-03-t-manual.svg
#http://web-platform.test:8284/svg/import/shapes-rect-04-f-manual.svg
#http://web-platform.test:8285/svg/import/shapes-rect-05-f-manual.svg
#http://web-platform.test:8286/svg/import/shapes-rect-06-f-manual.svg
#http://web-platform.test:8287/svg/import/shapes-rect-07-f-manual.svg
#http://web-platform.test:8288/svg/import/struct-cond-01-t-manual.svg
#http://web-platform.test:8289/svg/import/struct-cond-02-t-manual.svg
#http://web-platform.test:8290/svg/import/struct-cond-03-t-manual.svg
#http://web-platform.test:8291/svg/import/struct-cond-overview-02-f-manual.svg
#http://web-platform.test:8292/svg/import/struct-cond-overview-03-f-manual.svg
#http://web-platform.test:8293/svg/import/struct-cond-overview-04-f-manual.svg
#http://web-platform.test:8294/svg/import/struct-cond-overview-05-f-manual.svg
#http://web-platform.test:8295/svg/import/struct-defs-01-t-manual.svg
#http://web-platform.test:8296/svg/import/struct-dom-01-b-manual.svg
#http://web-platform.test:8297/svg/import/struct-dom-02-b-manual.svg
#http://web-platform.test:8298/svg/import/struct-dom-03-b-manual.svg
#http://web-platform.test:8299/svg/import/struct-dom-04-b-manual.svg
#http://web-platform.test:8300/svg/import/struct-dom-05-b-manual.svg
#http://web-platform.test:8301/svg/import/struct-dom-06-b-manual.svg
#http://web-platform.test:8302/svg/import/struct-dom-07-f-manual.svg
#http://web-platform.test:8303/svg/import/struct-dom-08-f-manual.svg
#http://web-platform.test:8304/svg/import/struct-dom-11-f-manual.svg
#http://web-platform.test:8305/svg/import/struct-dom-12-b-manual.svg
#http://web-platform.test:8306/svg/import/struct-dom-13-f-manual.svg
#http://web-platform.test:8307/svg/import/struct-dom-14-f-manual.svg
#http://web-platform.test:8308/svg/import/struct-dom-15-f-manual.svg
#http://web-platform.test:8309/svg/import/struct-dom-16-f-manual.svg
#http://web-platform.test:8310/svg/import/struct-dom-17-f-manual.svg
#http://web-platform.test:8311/svg/import/struct-dom-18-f-manual.svg
#http://web-platform.test:8312/svg/import/struct-dom-19-f-manual.svg
#http://web-platform.test:8313/svg/import/struct-dom-20-f-manual.svg
#http://web-platform.test:8314/svg/import/struct-frag-01-t-manual.svg
#http://web-platform.test:8315/svg/import/struct-frag-02-t-manual.svg
#http://web-platform.test:8316/svg/import/struct-frag-03-t-manual.svg
#http://web-platform.test:8317/svg/import/struct-frag-04-t-manual.svg
#http://web-platform.test:8318/svg/import/struct-frag-05-t-manual.svg
#http://web-platform.test:8319/svg/import/struct-frag-06-t-manual.svg
#http://web-platform.test:8320/svg/import/struct-group-01-t-manual.svg
#http://web-platform.test:8321/svg/import/struct-group-02-b-manual.svg
#http://web-platform.test:8322/svg/import/struct-group-03-t-manual.svg
#http://web-platform.test:8323/svg/import/struct-image-01-t-manual.svg
#http://web-platform.test:8324/svg/import/struct-image-02-b-manual.svg
#http://web-platform.test:8325/svg/import/struct-image-03-t-manual.svg
#http://web-platform.test:8326/svg/import/struct-image-04-t-manual.svg
#http://web-platform.test:8327/svg/import/struct-image-05-b-manual.svg
#http://web-platform.test:8328/svg/import/struct-image-06-t-manual.svg
#http://web-platform.test:8329/svg/import/struct-image-07-t-manual.svg
#http://web-platform.test:8330/svg/import/struct-image-08-t-manual.svg
#http://web-platform.test:8331/svg/import/struct-image-09-t-manual.svg
#http://web-platform.test:8332/svg/import/struct-image-10-t-manual.svg
#http://web-platform.test:8333/svg/import/struct-image-11-b-manual.svg
#http://web-platform.test:8334/svg/import/struct-image-12-b-manual.svg
#http://web-platform.test:8335/svg/import/struct-image-13-f-manual.svg
#http://web-platform.test:8336/svg/import/struct-image-14-f-manual.svg
#http://web-platform.test:8337/svg/import/struct-image-15-f-manual.svg
#http://web-platform.test:8338/svg/import/struct-image-16-f-manual.svg
#http://web-platform.test:8339/svg/import/struct-image-17-b-manual.svg
#http://web-platform.test:8340/svg/import/struct-image-18-f-manual.svg
#http://web-platform.test:8341/svg/import/struct-image-19-f-manual.svg
#http://web-platform.test:8342/svg/import/struct-svg-01-f-manual.svg
#http://web-platform.test:8343/svg/import/struct-svg-02-f-manual.svg
#http://web-platform.test:8344/svg/import/struct-svg-03-f-manual.svg
#http://web-platform.test:8345/svg/import/struct-symbol-01-b-manual.svg
#http://web-platform.test:8346/svg/import/struct-use-01-t-manual.svg
#http://web-platform.test:8347/svg/import/struct-use-03-t-manual.svg
#http://web-platform.test:8348/svg/import/struct-use-04-b-manual.svg
#http://web-platform.test:8349/svg/import/struct-use-05-b-manual.svg
#http://web-platform.test:8350/svg/import/struct-use-06-b-manual.svg
#http://web-platform.test:8351/svg/import/struct-use-07-b-manual.svg
#http://web-platform.test:8352/svg/import/struct-use-08-b-manual.svg
#http://web-platform.test:8353/svg/import/struct-use-09-b-manual.svg
#http://web-platform.test:8354/svg/import/struct-use-10-f-manual.svg
#http://web-platform.test:8355/svg/import/struct-use-11-f-manual.svg
#http://web-platform.test:8356/svg/import/struct-use-12-f-manual.svg
#http://web-platform.test:8357/svg/import/struct-use-13-f-manual.svg
#http://web-platform.test:8358/svg/import/struct-use-14-f-manual.svg
#http://web-platform.test:8359/svg/import/struct-use-15-f-manual.svg
#http://web-platform.test:8360/svg/import/styling-class-01-f-manual.svg
#http://web-platform.test:8361/svg/import/styling-css-01-b-manual.svg
#http://web-platform.test:8362/svg/import/styling-css-02-b-manual.svg
#http://web-platform.test:8363/svg/import/styling-css-03-b-manual.svg
#http://web-platform.test:8364/svg/import/styling-css-04-f-manual.svg
#http://web-platform.test:8365/svg/import/styling-css-05-b-manual.svg
#http://web-platform.test:8366/svg/import/styling-css-06-b-manual.svg
#http://web-platform.test:8367/svg/import/styling-css-07-f-manual.svg
#http://web-platform.test:8368/svg/import/styling-css-08-f-manual.svg
#http://web-platform.test:8369/svg/import/styling-css-09-f-manual.svg
#http://web-platform.test:8370/svg/import/styling-css-10-f-manual.svg
#http://web-platform.test:8371/svg/import/styling-elem-01-b-manual.svg
#http://web-platform.test:8372/svg/import/styling-inherit-01-b-manual.svg
#http://web-platform.test:8373/svg/import/styling-pres-01-t-manual.svg
#http://web-platform.test:8374/svg/import/styling-pres-02-f-manual.svg
#http://web-platform.test:8375/svg/import/styling-pres-03-f-manual.svg
#http://web-platform.test:8376/svg/import/styling-pres-04-f-manual.svg
#http://web-platform.test:8377/svg/import/styling-pres-05-f-manual.svg
#http://web-platform.test:8378/svg/import/svgdom-over-01-f-manual.svg
#http://web-platform.test:8379/svg/import/text-align-01-b-manual.svg
#http://web-platform.test:8380/svg/import/text-align-02-b-manual.svg
#http://web-platform.test:8381/svg/import/text-align-03-b-manual.svg
#http://web-platform.test:8382/svg/import/text-align-04-b-manual.svg
#http://web-platform.test:8383/svg/import/text-align-05-b-manual.svg
#http://web-platform.test:8384/svg/import/text-align-06-b-manual.svg
#http://web-platform.test:8385/svg/import/text-align-07-t-manual.svg
#http://web-platform.test:8386/svg/import/text-align-08-b-manual.svg
#http://web-platform.test:8387/svg/import/text-altglyph-01-b-manual.svg
#http://web-platform.test:8388/svg/import/text-altglyph-02-b-manual.svg
#http://web-platform.test:8389/svg/import/text-altglyph-03-b-manual.svg
#http://web-platform.test:8390/svg/import/text-bidi-01-t-manual.svg
#http://web-platform.test:8391/svg/import/text-deco-01-b-manual.svg
#http://web-platform.test:8392/svg/import/text-dom-01-f-manual.svg
#http://web-platform.test:8393/svg/import/text-dom-02-f-manual.svg
#http://web-platform.test:8394/svg/import/text-dom-03-f-manual.svg
#http://web-platform.test:8395/svg/import/text-dom-04-f-manual.svg
#http://web-platform.test:8396/svg/import/text-dom-05-f-manual.svg
#http://web-platform.test:8397/svg/import/text-fonts-01-t-manual.svg
#http://web-platform.test:8398/svg/import/text-fonts-02-t-manual.svg
#http://web-platform.test:8399/svg/import/text-fonts-03-t-manual.svg
#http://web-platform.test:8400/svg/import/text-fonts-04-t-manual.svg
#http://web-platform.test:8401/svg/import/text-fonts-05-f-manual.svg
#http://web-platform.test:8402/svg/import/text-fonts-202-t-manual.svg
#http://web-platform.test:8403/svg/import/text-fonts-203-t-manual.svg
#http://web-platform.test:8404/svg/import/text-fonts-204-t-manual.svg
#http://web-platform.test:8405/svg/import/text-intro-01-t-manual.svg
#http://web-platform.test:8406/svg/import/text-intro-02-b-manual.svg
#http://web-platform.test:8407/svg/import/text-intro-03-b-manual.svg
#http://web-platform.test:8408/svg/import/text-intro-04-t-manual.svg
#http://web-platform.test:8409/svg/import/text-intro-05-t-manual.svg
#http://web-platform.test:8410/svg/import/text-intro-06-t-manual.svg
#http://web-platform.test:8411/svg/import/text-intro-07-t-manual.svg
#http://web-platform.test:8412/svg/import/text-intro-09-b-manual.svg
#http://web-platform.test:8413/svg/import/text-intro-10-f-manual.svg
#http://web-platform.test:8414/svg/import/text-intro-11-t-manual.svg
#http://web-platform.test:8415/svg/import/text-intro-12-t-manual.svg
#http://web-platform.test:8416/svg/import/text-path-01-b-manual.svg
#http://web-platform.test:8417/svg/import/text-path-02-b-manual.svg
#http://web-platform.test:8418/svg/import/text-spacing-01-b-manual.svg
#http://web-platform.test:8419/svg/import/text-text-01-b-manual.svg
#http://web-platform.test:8420/svg/import/text-text-03-b-manual.svg
#http://web-platform.test:8421/svg/import/text-text-04-t-manual.svg
#http://web-platform.test:8422/svg/import/text-text-05-t-manual.svg
#http://web-platform.test:8423/svg/import/text-text-06-t-manual.svg
#http://web-platform.test:8424/svg/import/text-text-07-t-manual.svg
#http://web-platform.test:8425/svg/import/text-text-08-b-manual.svg
#http://web-platform.test:8426/svg/import/text-text-09-t-manual.svg
#http://web-platform.test:8427/svg/import/text-text-10-t-manual.svg
#http://web-platform.test:8428/svg/import/text-text-11-t-manual.svg
#http://web-platform.test:8429/svg/import/text-text-12-t-manual.svg
#http://web-platform.test:8430/svg/import/text-tref-01-b-manual.svg
#http://web-platform.test:8431/svg/import/text-tref-02-b-manual.svg
#http://web-platform.test:8432/svg/import/text-tref-03-b-manual.svg
#http://web-platform.test:8433/svg/import/text-tselect-01-b-manual.svg
#http://web-platform.test:8434/svg/import/text-tselect-02-f-manual.svg
#http://web-platform.test:8435/svg/import/text-tselect-03-f-manual.svg
#http://web-platform.test:8436/svg/import/text-tspan-01-b-manual.svg
#http://web-platform.test:8437/svg/import/text-tspan-02-b-manual.svg
#http://web-platform.test:8438/svg/import/types-basic-01-f-manual.svg
#http://web-platform.test:8439/svg/import/types-basic-02-f-manual.svg
#http://web-platform.test:8440/svg/import/types-dom-01-b-manual.svg
#http://web-platform.test:8441/svg/import/types-dom-02-f-manual.svg
#http://web-platform.test:8442/svg/import/types-dom-03-b-manual.svg
#http://web-platform.test:8443/svg/import/types-dom-04-b-manual.svg
#http://web-platform.test:8444/svg/import/types-dom-05-b-manual.svg
#http://web-platform.test:8445/svg/import/types-dom-06-f-manual.svg
#http://web-platform.test:8446/svg/import/types-dom-07-f-manual.svg
#http://web-platform.test:8447/svg/import/types-dom-08-f-manual.svg
#http://web-platform.test:8448/svg/import/types-dom-svgfittoviewbox-01-f-manual.svg
#http://web-platform.test:8449/svg/import/types-dom-svglengthlist-01-f-manual.svg
#http://web-platform.test:8450/svg/import/types-dom-svgnumberlist-01-f-manual.svg
#http://web-platform.test:8451/svg/import/types-dom-svgstringlist-01-f-manual.svg
#http://web-platform.test:8452/svg/import/types-dom-svgtransformable-01-f-manual.svg
