http://web-platform.test:8000/svg/types/scripted/SVGAnimatedAngle.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedBoolean.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedEnumeration-SVGClipPathElement.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedEnumeration-SVGComponentTransferFunctionElement.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedEnumeration-SVGFEBlendElement.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedEnumeration-SVGFEColorMatrixElement.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedEnumeration-SVGFECompositeElement.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedEnumeration-SVGFEConvolveMatrixElement.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedEnumeration-SVGFEDisplacementMapElement.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedEnumeration-SVGFEMorphologyElement.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedEnumeration-SVGFETurbulenceElement.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedEnumeration-SVGFilterElement.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedEnumeration-SVGGradientElement.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedEnumeration-SVGMarkerElement.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedEnumeration-SVGMaskElement.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedEnumeration-SVGPatternElement.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedEnumeration-SVGTextContentElement.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedEnumeration-SVGTextPathElement.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedEnumeration.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedInteger.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedLength.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedLengthList.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedNumber.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedNumberList.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedPreserveAspectRatio.html
#http://web-platform.test:8000/svg/types/scripted/SVGAnimatedRect.html
#http://web-platform.test:8000/svg/types/scripted/SVGGeometryElement.getPointAtLength-01.svg
#http://web-platform.test:8000/svg/types/scripted/SVGLength-px-with-context.html
#http://web-platform.test:8000/svg/types/scripted/SVGLength-px.html
http://web-platform.test:8000/svg/types/scripted/SVGLength.html
http://web-platform.test:8000/svg/types/scripted/SVGLengthList-appendItem.html
http://web-platform.test:8000/svg/types/scripted/SVGLengthList-appendItemFromClearedList.html
http://web-platform.test:8000/svg/types/scripted/SVGLengthList-basics.html
http://web-platform.test:8000/svg/types/scripted/SVGLengthList-getItem.html
#http://web-platform.test:8000/svg/types/elements/SVGGeometryElement-rect.svg
