#http://web-platform.test:8000/webstorage/event_session_removeitem.html
http://web-platform.test:8000/webstorage/storage_in.html
http://web-platform.test:8000/webstorage/storage_removeitem.html
#http://web-platform.test:8000/webstorage/storage_session_window_noopener.html
#http://web-platform.test:8000/webstorage/event_local_key.html
#http://web-platform.test:8000/webstorage/event_session_oldvalue.html
http://web-platform.test:8000/webstorage/storage_functions_not_overwritten.html
#http://web-platform.test:8000/webstorage/event_local_newvalue.html
http://web-platform.test:8000/webstorage/storage_getitem.html
http://web-platform.test:8000/webstorage/storage_builtins.html
#http://web-platform.test:8000/webstorage/storage_setitem.html
#http://web-platform.test:8000/webstorage/event_local_removeitem.html
#http://web-platform.test:8000/webstorage/event_setattribute.html
#http://web-platform.test:8000/webstorage/storage_local-manual.html
http://web-platform.test:8000/webstorage/storage_indexing.html
http://web-platform.test:8000/webstorage/storage_set_value_enumerate.html
#http://web-platform.test:8000/webstorage/resources/local_change_item_iframe.html
#http://web-platform.test:8000/webstorage/resources/local_set_item_iframe.html
#http://web-platform.test:8000/webstorage/resources/storage_session_window_noopener_second.html
#http://web-platform.test:8000/webstorage/resources/local_set_item_remove_iframe.html
#http://web-platform.test:8000/webstorage/resources/session_set_item_iframe.html
#http://web-platform.test:8000/webstorage/resources/session_set_item_remove_iframe.html
#http://web-platform.test:8000/webstorage/resources/session_set_item_clear_iframe.html
#http://web-platform.test:8000/webstorage/resources/event_setattribute_handler.html
#http://web-platform.test:8000/webstorage/resources/session_change_item_iframe.html
#http://web-platform.test:8000/webstorage/resources/storage_local_window_open_second.html
#http://web-platform.test:8000/webstorage/resources/local_set_item_clear_iframe.html
#http://web-platform.test:8000/webstorage/resources/storage_session_window_open_second.html
#http://web-platform.test:8000/webstorage/resources/event_body_handler.html
http://web-platform.test:8000/webstorage/storage_length.html
#http://web-platform.test:8000/webstorage/event_local_url.html
#http://web-platform.test:8000/webstorage/event_session_key.html
#http://web-platform.test:8000/webstorage/event_local_storagearea.html
#http://web-platform.test:8000/webstorage/event_constructor.html
http://web-platform.test:8000/webstorage/storage_clear.html
#http://web-platform.test:8000/webstorage/storage_session_window_open.html
#http://web-platform.test:8000/webstorage/storage_session-manual.html
#http://web-platform.test:8000/webstorage/storage_key.html
#http://web-platform.test:8000/webstorage/idlharness.html
#http://web-platform.test:8000/webstorage/storage_enumerate.html
#http://web-platform.test:8000/webstorage/event_body_attribute.html
#http://web-platform.test:8000/webstorage/storage_local_window_open.html
#http://web-platform.test:8000/webstorage/missing_arguments.html
#http://web-platform.test:8000/webstorage/storage_string_conversion.html
#http://web-platform.test:8000/webstorage/storage_session_setitem_quotaexceedederr.html
#http://web-platform.test:8000/webstorage/document-domain.html
#http://web-platform.test:8000/webstorage/event_session_url.html
#http://web-platform.test:8000/webstorage/storage_local_setitem_quotaexceedederr.html
http://web-platform.test:8000/webstorage/storage_supported_property_names.html
#http://web-platform.test:8000/webstorage/event_case_sensitive.html
#http://web-platform.test:8000/webstorage/event_local_oldvalue.html
http://web-platform.test:8000/webstorage/storage_key_empty_string.html
#http://web-platform.test:8000/webstorage/event_no_duplicates.html
#http://web-platform.test:8000/webstorage/event_basic.html
#http://web-platform.test:8000/webstorage/event_constructor_eventinit.html
#http://web-platform.test:8000/webstorage/event_session_newvalue.html
#http://web-platform.test:8000/webstorage/event_local_storageeventinit.html
#http://web-platform.test:8000/webstorage/event_session_storageeventinit.html
#http://web-platform.test:8000/webstorage/event_session_storagearea.html

