http://web-platform.test:8000/websockets/extended-payload-length.html
#binary
http://web-platform.test:8000/websockets/binary/001.html
http://web-platform.test:8000/websockets/binary/002.html
http://web-platform.test:8000/websockets/binary/004.html
http://web-platform.test:8000/websockets/binary/005.html
#
#http://web-platform.test:8000/websockets/interfaces/WebSocket/url/001.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/url/002.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/url/003.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/url/004.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/url/005.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/url/006.html
#http://web-platform.test:8000/websockets/interfaces/WebSocket/url/resolve.html
#
http://web-platform.test:8000/websockets/interfaces/WebSocket/send/001.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/send/002.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/send/003.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/send/004.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/send/005.html
#http://web-platform.test:8000/websockets/interfaces/WebSocket/send/006.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/send/007.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/send/008.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/send/009.html
#http://web-platform.test:8000/websockets/interfaces/WebSocket/send/010.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/send/011.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/send/012.html
#
http://web-platform.test:8000/websockets/interfaces/WebSocket/readyState/001.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/readyState/002.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/readyState/003.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/readyState/004.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/readyState/005.html
#http://web-platform.test:8000/websockets/interfaces/WebSocket/readyState/006.html
#http://web-platform.test:8000/websockets/interfaces/WebSocket/readyState/007.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/readyState/008.html
#
http://web-platform.test:8000/websockets/interfaces/WebSocket/protocol/protocol-initial.html
#
http://web-platform.test:8000/websockets/interfaces/WebSocket/extensions/001.html
#
http://web-platform.test:8000/websockets/interfaces/WebSocket/events/001.html
#http://web-platform.test:8000/websockets/interfaces/WebSocket/events/002.html
#http://web-platform.test:8000/websockets/interfaces/WebSocket/events/003.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/events/004.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/events/006.html
#http://web-platform.test:8000/websockets/interfaces/WebSocket/events/007.html
#http://web-platform.test:8000/websockets/interfaces/WebSocket/events/008.html
#http://web-platform.test:8000/websockets/interfaces/WebSocket/events/009.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/events/010.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/events/011.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/events/012.html
#http://web-platform.test:8000/websockets/interfaces/WebSocket/events/013.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/events/014.html
#http://web-platform.test:8000/websockets/interfaces/WebSocket/events/015.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/events/016.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/events/017.html
#http://web-platform.test:8000/websockets/interfaces/WebSocket/events/018.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/events/019.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/events/020.html
#
http://web-platform.test:8000/websockets/interfaces/WebSocket/constants/001.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/constants/002.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/constants/003.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/constants/004.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/constants/005.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/constants/006.html
#
#http://web-platform.test:8000/websockets/interfaces/WebSocket/close/close-basic.html
#http://web-platform.test:8000/websockets/interfaces/WebSocket/close/close-connecting.html // chrome fail
#http://web-platform.test:8000/websockets/interfaces/WebSocket/close/close-multiple.html
#http://web-platform.test:8000/websockets/interfaces/WebSocket/close/close-nested.html //chrome fail
http://web-platform.test:8000/websockets/interfaces/WebSocket/close/close-replace.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/close/close-return.html
#
#http://web-platform.test:8000/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-arraybuffer.html
#http://web-platform.test:8000/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-blob.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-defineProperty-getter.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-defineProperty-setter.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-deleting.html
#http://web-platform.test:8000/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-getting.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-initial.html
#http://web-platform.test:8000/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-large.html
http://web-platform.test:8000/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-readonly.html
#http://web-platform.test:8000/websockets/interfaces/WebSocket/bufferedAmount/bufferedAmount-unicode.html
#
#http://web-platform.test:8000/websockets/interfaces/CloseEvent/clean-close.html //chrome fail
#http://web-platform.test:8000/websockets/interfaces/CloseEvent/constructor.html
#http://web-platform.test:8000/websockets/interfaces/CloseEvent/historical.html
#
#http://web-platform.test:8000/websockets/unload-a-document/001.html
#http://web-platform.test:8000/websockets/unload-a-document/002.html
#http://web-platform.test:8000/websockets/unload-a-document/003.html
#http://web-platform.test:8000/websockets/unload-a-document/004.html
#http://web-platform.test:8000/websockets/unload-a-document/005.html
#
http://web-platform.test:8000/websockets/multi-globals/message-received.html
#
#http://web-platform.test:8000/websockets/security/001.html
http://web-platform.test:8000/websockets/security/002.html
#
#http://web-platform.test:8000/websockets/opening-handshake/001.html
#http://web-platform.test:8000/websockets/opening-handshake/002.html
#http://web-platform.test:8000/websockets/opening-handshake/003.html
#http://web-platform.test:8000/websockets/opening-handshake/005.html
#
#http://web-platform.test:8000/websockets/keeping-connection-open/001.html
#
#http://web-platform.test:8000/websockets/cookies/001.html
#http://web-platform.test:8000/websockets/cookies/002.html
#http://web-platform.test:8000/websockets/cookies/003.html
#http://web-platform.test:8000/websockets/cookies/004.html
#http://web-platform.test:8000/websockets/cookies/005.html
#http://web-platform.test:8000/websockets/cookies/006.html
#
#http://web-platform.test:8000/websockets/closing-handshake/002.html //chrome fail
#http://web-platform.test:8000/websockets/closing-handshake/003.html //chrome fail
#http://web-platform.test:8000/websockets/closing-handshake/004.html //chrome fail
#
http://web-platform.test:8000/websockets/constructor/001.html
#http://web-platform.test:8000/websockets/constructor/002.html
#http://web-platform.test:8000/websockets/constructor/004.html
http://web-platform.test:8000/websockets/constructor/005.html
#http://web-platform.test:8000/websockets/constructor/006.html
#http://web-platform.test:8000/websockets/constructor/007.html
http://web-platform.test:8000/websockets/constructor/008.html
#http://web-platform.test:8000/websockets/constructor/009.html
#http://web-platform.test:8000/websockets/constructor/010.html
#http://web-platform.test:8000/websockets/constructor/011.html
http://web-platform.test:8000/websockets/constructor/012.html
http://web-platform.test:8000/websockets/constructor/013.html
#http://web-platform.test:8000/websockets/constructor/014.html
#http://web-platform.test:8000/websockets/constructor/016.html
#http://web-platform.test:8000/websockets/constructor/017.html
#http://web-platform.test:8000/websockets/constructor/018.html
#http://web-platform.test:8000/websockets/constructor/019.html
#http://web-platform.test:8000/websockets/constructor/020.html
#http://web-platform.test:8000/websockets/constructor/021.html
#http://web-platform.test:8000/websockets/constructor/022.html
