#http://web-platform.test:8000/workers/baseurl/alpha/importScripts.html
#http://web-platform.test:8000/workers/baseurl/alpha/sharedworker.html
#http://web-platform.test:8000/workers/baseurl/alpha/worker.html
#http://web-platform.test:8000/workers/baseurl/alpha/xhr.html
#http://web-platform.test:8000/workers/constructors/SharedWorker/connect-event.html
#http://web-platform.test:8000/workers/constructors/SharedWorker/dummy-name.html
#http://web-platform.test:8000/workers/constructors/SharedWorker/dummy-shared-worker.html
#http://web-platform.test:8000/workers/constructors/SharedWorker/empty-name.html
#http://web-platform.test:8000/workers/constructors/SharedWorker/global-members.html
#http://web-platform.test:8000/workers/constructors/SharedWorker/interface-objects.html
#http://web-platform.test:8000/workers/constructors/SharedWorker/name.html
#http://web-platform.test:8000/workers/constructors/SharedWorker/no-arguments-ctor.html
#http://web-platform.test:8000/workers/constructors/SharedWorker/null-arguments.html
#http://web-platform.test:8000/workers/constructors/SharedWorker/number-arguments.html
#http://web-platform.test:8000/workers/constructors/SharedWorker/port-onmessage.html
#http://web-platform.test:8000/workers/constructors/SharedWorker/port-properties.html
#http://web-platform.test:8000/workers/constructors/SharedWorker/port-readonly.html
#http://web-platform.test:8000/workers/constructors/SharedWorker/same-origin.html
#http://web-platform.test:8000/workers/constructors/SharedWorker/setting-port-members.html
#http://web-platform.test:8000/workers/constructors/SharedWorker/undefined-arguments.html
#http://web-platform.test:8000/workers/constructors/SharedWorker/unexpected-global-properties.html
#http://web-platform.test:8000/workers/constructors/SharedWorker/unresolvable-url.html
#http://web-platform.test:8000/workers/constructors/SharedWorker/URLMismatchError.htm
#http://web-platform.test:8000/workers/constructors/Worker/AbstractWorker.onerror.html
#http://web-platform.test:8000/workers/constructors/Worker/Blob-url.html
#http://web-platform.test:8000/workers/constructors/Worker/ctor-1.html
#http://web-platform.test:8000/workers/constructors/Worker/ctor-null.html
#http://web-platform.test:8000/workers/constructors/Worker/ctor-undefined.html
#http://web-platform.test:8000/workers/constructors/Worker/no-arguments-ctor.html
#http://web-platform.test:8000/workers/constructors/Worker/resolve-empty-string.html
#http://web-platform.test:8000/workers/constructors/Worker/same-origin.html
#http://web-platform.test:8000/workers/constructors/Worker/terminate.html
#http://web-platform.test:8000/workers/constructors/Worker/unresolvable-url.html
http://web-platform.test:8000/workers/constructors/Worker/use-base-url.html
http://web-platform.test:8000/workers/interfaces/DedicatedWorkerGlobalScope/postMessage/event-ports-dedicated.html
#http://web-platform.test:8000/workers/interfaces/DedicatedWorkerGlobalScope/postMessage/imagedata-cloned-canvas-in-array.html
http://web-platform.test:8000/workers/interfaces/DedicatedWorkerGlobalScope/postMessage/message-event.html
http://web-platform.test:8000/workers/interfaces/DedicatedWorkerGlobalScope/postMessage/second-argument-null-in-array.html
http://web-platform.test:8000/workers/interfaces/DedicatedWorkerGlobalScope/postMessage/second-argument-null.html
http://web-platform.test:8000/workers/interfaces/DedicatedWorkerGlobalScope/postMessage/second-argument-undefined.html
http://web-platform.test:8000/workers/interfaces/DedicatedWorkerGlobalScope/postMessage/setting-postMessage.html
#http://web-platform.test:8000/workers/interfaces/DedicatedWorkerGlobalScope/postMessage/structured-clone-imagedata.html
#http://web-platform.test:8000/workers/interfaces/DedicatedWorkerGlobalScope/postMessage/structured-clone-message.html
#http://web-platform.test:8000/workers/interfaces/SharedWorkerGlobalScope/name/getting.html
#http://web-platform.test:8000/workers/interfaces/SharedWorkerGlobalScope/name/setting.html
#http://web-platform.test:8000/workers/interfaces/SharedWorkerGlobalScope/onconnect.html
#http://web-platform.test:8000/workers/interfaces/WorkerGlobalScope/close/incoming-message.html
#http://web-platform.test:8000/workers/interfaces/WorkerGlobalScope/close/sending-messages.html
#http://web-platform.test:8000/workers/interfaces/WorkerGlobalScope/close/setInterval.html
#http://web-platform.test:8000/workers/interfaces/WorkerGlobalScope/close/setTimeout.html
#http://web-platform.test:8000/workers/interfaces/WorkerGlobalScope/location/members.html
#http://web-platform.test:8000/workers/interfaces/WorkerGlobalScope/location/redirect.html
http://web-platform.test:8000/workers/interfaces/WorkerGlobalScope/location/returns-same-object.html
#http://web-platform.test:8000/workers/interfaces/WorkerGlobalScope/location/setting-members.html
http://web-platform.test:8000/workers/interfaces/WorkerGlobalScope/location/worker-separate-file.html
#http://web-platform.test:8000/workers/interfaces/WorkerGlobalScope/onerror/exception-in-onerror.html
#http://web-platform.test:8000/workers/interfaces/WorkerGlobalScope/onerror/handled.html
#http://web-platform.test:8000/workers/interfaces/WorkerGlobalScope/onerror/not-handled.html
#http://web-platform.test:8000/workers/interfaces/WorkerGlobalScope/onerror/propagate-to-window-onerror.html
#http://web-platform.test:8000/workers/interfaces/WorkerGlobalScope/self.html
http://web-platform.test:8000/workers/interfaces/WorkerUtils/importScripts/003.html
#http://web-platform.test:8000/workers/interfaces/WorkerUtils/importScripts/004.html
http://web-platform.test:8000/workers/interfaces/WorkerUtils/importScripts/005.html
#http://web-platform.test:8000/workers/interfaces/WorkerUtils/importScripts/006.html
http://web-platform.test:8000/workers/interfaces/WorkerUtils/importScripts/007.html
http://web-platform.test:8000/workers/interfaces/WorkerUtils/importScripts/008.html
http://web-platform.test:8000/workers/interfaces/WorkerUtils/importScripts/009.html
http://web-platform.test:8000/workers/interfaces/WorkerUtils/importScripts/010.html
http://web-platform.test:8000/workers/interfaces/WorkerUtils/importScripts/011.html
http://web-platform.test:8000/workers/interfaces/WorkerUtils/importScripts/012.html
http://web-platform.test:8000/workers/interfaces/WorkerUtils/navigator/002.html
http://web-platform.test:8000/workers/interfaces/WorkerUtils/navigator/003.html
http://web-platform.test:8000/workers/interfaces/WorkerUtils/navigator/004.html
http://web-platform.test:8000/workers/interfaces/WorkerUtils/navigator/005.html
http://web-platform.test:8000/workers/interfaces/WorkerUtils/navigator/006.html
http://web-platform.test:8000/workers/interfaces/WorkerUtils/navigator/007.html
http://web-platform.test:8000/workers/interfaces/WorkerUtils/navigator/language.html
http://web-platform.test:8000/workers/interfaces/WorkerUtils/WindowTimers/001.html
http://web-platform.test:8000/workers/interfaces/WorkerUtils/WindowTimers/002.html
http://web-platform.test:8000/workers/interfaces/WorkerUtils/WindowTimers/003.html
http://web-platform.test:8000/workers/interfaces/WorkerUtils/WindowTimers/004.html
#http://web-platform.test:8000/workers/interfaces/WorkerUtils/WindowTimers/005.html
#http://web-platform.test:8000/workers/modules/dedicated-worker-import-csp.html
#http://web-platform.test:8000/workers/modules/dedicated-worker-import-failure.html
#http://web-platform.test:8000/workers/modules/dedicated-worker-import-meta.html
#http://web-platform.test:8000/workers/modules/dedicated-worker-import-referrer.html
#http://web-platform.test:8000/workers/modules/dedicated-worker-import.html
#http://web-platform.test:8000/workers/modules/dedicated-worker-options-credentials.html
#http://web-platform.test:8000/workers/modules/dedicated-worker-options-credentials.html.headers
#http://web-platform.test:8000/workers/modules/dedicated-worker-options-type.html
#http://web-platform.test:8000/workers/modules/resources/new-worker-window.html
#http://web-platform.test:8000/workers/data-url-shared-window.html
#http://web-platform.test:8000/workers/data-url-shared.html
#http://web-platform.test:8000/workers/data-url.html
#http://web-platform.test:8000/workers/name-property.html
#http://web-platform.test:8000/workers/non-automated/application-cache-dedicated.html
#http://web-platform.test:8000/workers/non-automated/infinite-nested.html
#http://web-platform.test:8000/workers/non-automated/infinite-sibling-and-nested.html
#http://web-platform.test:8000/workers/non-automated/infinite-sibling.html
#http://web-platform.test:8000/workers/non-automated/navigator-onLine.html
#http://web-platform.test:8000/workers/opaque-origin.html
#http://web-platform.test:8000/workers/postMessage_clone_port_error.htm
#http://web-platform.test:8000/workers/postMessage_clone_port.htm
#http://web-platform.test:8000/workers/postMessage_DataCloneErr.htm
#http://web-platform.test:8000/workers/postMessage_event_properties.htm
#http://web-platform.test:8000/workers/postMessage_ports_readonly_array.htm
#http://web-platform.test:8000/workers/postMessage_target_source.htm
#http://web-platform.test:8000/workers/semantics/encodings/001.html
#http://web-platform.test:8000/workers/semantics/encodings/001.html.headers
#http://web-platform.test:8000/workers/semantics/encodings/002.html
#http://web-platform.test:8000/workers/semantics/encodings/002.html.headers
#http://web-platform.test:8000/workers/semantics/encodings/003.html
#http://web-platform.test:8000/workers/semantics/encodings/004.html
#http://web-platform.test:8000/workers/semantics/interface-objects/003.html
#http://web-platform.test:8000/workers/semantics/interface-objects/004.html
#http://web-platform.test:8000/workers/semantics/multiple-workers/001.html
#http://web-platform.test:8000/workers/semantics/multiple-workers/002.html
#http://web-platform.test:8000/workers/semantics/multiple-workers/003.html
#http://web-platform.test:8000/workers/semantics/multiple-workers/004-1.html
#http://web-platform.test:8000/workers/semantics/multiple-workers/004.html
#http://web-platform.test:8000/workers/semantics/multiple-workers/005.html
#http://web-platform.test:8000/workers/semantics/multiple-workers/006.html
#http://web-platform.test:8000/workers/semantics/multiple-workers/007.html
#http://web-platform.test:8000/workers/semantics/multiple-workers/008-1.html
#http://web-platform.test:8000/workers/semantics/multiple-workers/008.html
#http://web-platform.test:8000/workers/semantics/navigation/001.html
#http://web-platform.test:8000/workers/semantics/navigation/002.html
#http://web-platform.test:8000/workers/semantics/reporting-errors/001.html
#http://web-platform.test:8000/workers/semantics/reporting-errors/002.html
#http://web-platform.test:8000/workers/semantics/reporting-errors/003.html
#http://web-platform.test:8000/workers/semantics/reporting-errors/004-1.html
#http://web-platform.test:8000/workers/semantics/reporting-errors/004.html
http://web-platform.test:8000/workers/semantics/run-a-worker/001.html
#http://web-platform.test:8000/workers/semantics/run-a-worker/002.html
#http://web-platform.test:8000/workers/semantics/run-a-worker/003.html
#http://web-platform.test:8000/workers/semantics/structured-clone/dedicated.html
#http://web-platform.test:8000/workers/semantics/structured-clone/shared.html
#http://web-platform.test:8000/workers/semantics/xhr/001.html
#http://web-platform.test:8000/workers/semantics/xhr/002.html
#http://web-platform.test:8000/workers/semantics/xhr/003.html
#http://web-platform.test:8000/workers/semantics/xhr/004.html
#http://web-platform.test:8000/workers/semantics/xhr/005.html
#http://web-platform.test:8000/workers/semantics/xhr/006.html
#http://web-platform.test:8000/workers/shared-worker-name-via-options.html
#http://web-platform.test:8000/workers/SharedWorker_blobUrl.html
#http://web-platform.test:8000/workers/SharedWorker_dataUrl.html
#http://web-platform.test:8000/workers/SharedWorkerPerformanceNow.html
http://web-platform.test:8000/workers/Worker_basic.htm
#http://web-platform.test:8000/workers/Worker_cross_origin_security_err.htm
http://web-platform.test:8000/workers/Worker_dispatchEvent_ErrorEvent.htm
#http://web-platform.test:8000/workers/Worker_ErrorEvent_bubbles_cancelable.htm
#http://web-platform.test:8000/workers/Worker_ErrorEvent_error.htm
#http://web-platform.test:8000/workers/Worker_ErrorEvent_filename.htm
#http://web-platform.test:8000/workers/Worker_ErrorEvent_lineno.htm
#http://web-platform.test:8000/workers/Worker_ErrorEvent_message.htm
#http://web-platform.test:8000/workers/Worker_ErrorEvent_type.htm
#http://web-platform.test:8000/workers/Worker_NosniffErr.htm
#http://web-platform.test:8000/workers/Worker_script_mimetype.htm
#http://web-platform.test:8000/workers/Worker_terminate_event_queue.htm
#http://web-platform.test:8000/workers/WorkerGlobalScope_close.htm
#http://web-platform.test:8000/workers/WorkerGlobalScope_ErrorEvent_colno.htm
#http://web-platform.test:8000/workers/WorkerGlobalScope_ErrorEvent_filename.htm
#http://web-platform.test:8000/workers/WorkerGlobalScope_ErrorEvent_lineno.htm
#http://web-platform.test:8000/workers/WorkerGlobalScope_ErrorEvent_message.htm
#http://web-platform.test:8000/workers/WorkerGlobalScope_importScripts_NetworkErr.htm
#http://web-platform.test:8000/workers/WorkerGlobalScope_importScripts_NosniffErr.htm
http://web-platform.test:8000/workers/WorkerGlobalScope_importScripts.htm
#http://web-platform.test:8000/workers/WorkerGlobalScope_requestAnimationFrame.htm
http://web-platform.test:8000/workers/WorkerGlobalScope_setInterval.htm
http://web-platform.test:8000/workers/WorkerGlobalScope_setTimeout.htm
#http://web-platform.test:8000/workers/WorkerLocation_hash_encoding.htm
#http://web-platform.test:8000/workers/WorkerLocation_hash_nonexist.htm
#http://web-platform.test:8000/workers/WorkerLocation_hash.htm
#http://web-platform.test:8000/workers/WorkerLocation_host.htm
#http://web-platform.test:8000/workers/WorkerLocation_hostname.htm
#http://web-platform.test:8000/workers/WorkerLocation_href.htm
#http://web-platform.test:8000/workers/WorkerLocation_pathname.htm
#http://web-platform.test:8000/workers/WorkerLocation_port.htm
#http://web-platform.test:8000/workers/WorkerLocation_protocol.htm
#http://web-platform.test:8000/workers/WorkerLocation_search_empty.htm
#http://web-platform.test:8000/workers/WorkerLocation_search_fragment.htm
#http://web-platform.test:8000/workers/WorkerLocation_search_nonexist.htm
#http://web-platform.test:8000/workers/WorkerLocation_search.htm
#http://web-platform.test:8000/workers/WorkerLocation.htm
#http://web-platform.test:8000/workers/WorkerNavigator_appName.htm
#http://web-platform.test:8000/workers/WorkerNavigator_appVersion.htm
#http://web-platform.test:8000/workers/WorkerNavigator_onLine.htm
#http://web-platform.test:8000/workers/WorkerNavigator_platform.htm
#http://web-platform.test:8000/workers/WorkerNavigator_userAgent.htm
#http://web-platform.test:8000/workers/WorkerPerformanceNow.html
