http://web-platform.test:8000/xhr/access-control-preflight-sync-method-denied.babel.html
http://web-platform.test:8000/xhr/access-control-preflight-async-method-denied.babel.html
http://web-platform.test:8000/xhr/access-control-preflight-sync-not-supported.babel.html
http://web-platform.test:8000/xhr/access-control-preflight-async-not-supported.babel.html
http://web-platform.test:8000/xhr/access-control-preflight-async-header-denied.babel.html
http://web-platform.test:8000/xhr/access-control-preflight-sync-header-denied.babel.html
http://web-platform.test:8000/xhr/access-control-preflight-headers-async.babel.html
http://web-platform.test:8000/xhr/access-control-preflight-headers-sync.babel.html
#http://web-platform.test:8000/xhr/access-control-preflight-sync-method-denied.htm
#http://web-platform.test:8000/xhr/access-control-preflight-async-method-denied.htm
#http://web-platform.test:8000/xhr/access-control-preflight-sync-not-supported.htm
#http://web-platform.test:8000/xhr/access-control-preflight-async-not-supported.htm
#http://web-platform.test:8000/xhr/access-control-preflight-async-header-denied.htm
#http://web-platform.test:8000/xhr/access-control-preflight-sync-header-denied.htm
#http://web-platform.test:8000/xhr/access-control-preflight-headers-async.htm
#http://web-platform.test:8000/xhr/access-control-preflight-headers-sync.htm
