http://web-platform.test:8000/xhr/open-url-javascript-window.htm
http://web-platform.test:8000/xhr/send-sync-no-response-event-load.htm
http://web-platform.test:8000/xhr/access-control-basic-allow-access-control-origin-header.htm
#http://web-platform.test:8000/xhr/access-control-and-redirects-async-same-origin.htm
#http://web-platform.test:8000/xhr/access-control-basic-allow-preflight-cache-invalidation-by-method.htm
http://web-platform.test:8000/xhr/open-url-base.htm
#http://web-platform.test:8000/xhr/no-utf16-json.htm
#http://web-platform.test:8000/xhr/xmlhttprequest-timeout-worker-overrides.html
#http://web-platform.test:8000/xhr/xmlhttprequest-network-error.htm
http://web-platform.test:8000/xhr/send-redirect-infinite.htm
#http://web-platform.test:8000/xhr/responsexml-basic.htm
#http://web-platform.test:8000/xhr/access-control-sandboxed-iframe-allow.htm
http://web-platform.test:8000/xhr/access-control-basic-cors-safelisted-response-headers.htm
http://web-platform.test:8000/xhr/open-referer.htm
#http://web-platform.test:8000/xhr/event-upload-progress.htm
http://web-platform.test:8000/xhr/access-control-response-with-exposed-headers.htm
#http://web-platform.test:8000/xhr/abort-after-send.htm
#http://web-platform.test:8000/xhr/getallresponseheaders.htm
http://web-platform.test:8000/xhr/access-control-basic-preflight-denied.htm
http://web-platform.test:8000/xhr/response-method.htm
http://web-platform.test:8000/xhr/send-sync-no-response-event-loadend.htm
#http://web-platform.test:8000/xhr/access-control-basic-allow-preflight-cache-timeout.htm
#http://web-platform.test:8000/xhr/send-entity-body-empty.htm
http://web-platform.test:8000/xhr/xmlhttprequest-unsent.htm
http://web-platform.test:8000/xhr/getresponseheader-error-state.htm
#http://web-platform.test:8000/xhr/open-url-multi-window-6.htm
#http://web-platform.test:8000/xhr/send-content-type-string.htm
http://web-platform.test:8000/xhr/open-user-password-non-same-origin.htm
#http://web-platform.test:8000/xhr/responseXML-unavailable-in-worker.html
#http://web-platform.test:8000/xhr/setrequestheader-bogus-value.htm
http://web-platform.test:8000/xhr/getresponseheader-case-insensitive.htm
#http://web-platform.test:8000/xhr/send-data-unexpected-tostring.htm
#http://web-platform.test:8000/xhr/status-async.htm
#http://web-platform.test:8000/xhr/xmlhttprequest-timeout-worker-aborted.html
http://web-platform.test:8000/xhr/abort-event-listeners.htm
#http://web-platform.test:8000/xhr/send-redirect-post-upload.htm
#http://web-platform.test:8000/xhr/close-worker-with-xhr-in-progress.html
#http://web-platform.test:8000/xhr/open-after-setrequestheader.htm
http://web-platform.test:8000/xhr/response-data-arraybuffer.htm
#http://web-platform.test:8000/xhr/send-non-same-origin.htm
#http://web-platform.test:8000/xhr/setrequestheader-bogus-name.htm
http://web-platform.test:8000/xhr/send-redirect.htm
#http://web-platform.test:8000/xhr/send-redirect-bogus.htm
#http://web-platform.test:8000/xhr/send-receive-utf16.htm
#http://web-platform.test:8000/xhr/open-method-responsetype-set-sync.htm
#http://web-platform.test:8000/xhr/open-url-encoding.htm
#http://web-platform.test:8000/xhr/open-during-abort.htm
http://web-platform.test:8000/xhr/send-response-upload-event-progress.htm
#http://web-platform.test:8000/xhr/setrequestheader-allow-empty-value.htm
#http://web-platform.test:8000/xhr/responsedocument-decoding.htm
#http://web-platform.test:8000/xhr/responsetype.html
#http://web-platform.test:8000/xhr/send-data-arraybuffer.htm
#http://web-platform.test:8000/xhr/header-user-agent-async.htm
#http://web-platform.test:8000/xhr/responsexml-non-well-formed.htm // Replace modified test because rapidxml has some bugs
http://web-platform.test:8000/xhr/responsexml-non-well-formed.modified.htm
#http://web-platform.test:8000/xhr/responsexml-document-properties.htm
#http://web-platform.test:8000/xhr/send-network-error-sync-events.sub.htm
http://web-platform.test:8000/xhr/xmlhttprequest-sync-block-defer-scripts.html
#http://web-platform.test:8000/xhr/open-url-javascript-window-2.htm
#http://web-platform.test:8000/xhr/open-url-multi-window-2.htm
http://web-platform.test:8000/xhr/access-control-preflight-request-header-sorted.htm
http://web-platform.test:8000/xhr/overridemimetype-open-state-force-utf-8.htm
#http://web-platform.test:8000/xhr/response-json.htm
#http://web-platform.test:8000/xhr/send-response-event-order.htm
#http://web-platform.test:8000/xhr/responsetext-decoding.htm
#http://web-platform.test:8000/xhr/send-sync-response-event-order.htm
#http://web-platform.test:8000/xhr/overridemimetype-blob.html
http://web-platform.test:8000/xhr/open-url-about-blank-window.htm
#http://web-platform.test:8000/xhr/overridemimetype-done-state.htm
#http://web-platform.test:8000/xhr/open-url-redirected-worker-origin.htm
#http://web-platform.test:8000/xhr/loadstart-and-state.html
http://web-platform.test:8000/xhr/access-control-basic-allow-star.htm
http://web-platform.test:8000/xhr/xmlhttprequest-timeout-simple.html
#http://web-platform.test:8000/xhr/send-sync-timeout.htm
http://web-platform.test:8000/xhr/send-no-response-event-loadstart.htm
http://web-platform.test:8000/xhr/abort-upload-event-abort.htm
http://web-platform.test:8000/xhr/abort-upload-event-loadend.htm
#http://web-platform.test:8000/xhr/interfaces.html
http://web-platform.test:8000/xhr/getresponseheader-cookies-and-more.htm
http://web-platform.test:8000/xhr/xmlhttprequest-timeout-aborted.html
#http://web-platform.test:8000/xhr/template-element.html
http://web-platform.test:8000/xhr/access-control-preflight-request-header-lowercase.htm
http://web-platform.test:8000/xhr/access-control-basic-allow.htm
#http://web-platform.test:8000/xhr/access-control-sandboxed-iframe-denied.htm
#http://web-platform.test:8000/xhr/xmlhttprequest-sync-default-feature-policy.sub.html
http://web-platform.test:8000/xhr/send-accept-language.htm
http://web-platform.test:8000/xhr/xmlhttprequest-eventtarget.htm
#http://web-platform.test:8000/xhr/header-user-agent-sync.htm
#http://web-platform.test:8000/xhr/send-blob-with-no-mime-type.html
http://web-platform.test:8000/xhr/access-control-basic-post-with-non-cors-safelisted-content-type.htm
http://web-platform.test:8000/xhr/responseText-status.html
#http://web-platform.test:8000/xhr/setrequestheader-open-setrequestheader.htm
http://web-platform.test:8000/xhr/access-control-basic-allow-non-cors-safelisted-method-async.htm
http://web-platform.test:8000/xhr/send-data-es-object.htm
http://web-platform.test:8000/xhr/access-control-preflight-request-invalid-status-301.htm
#http://web-platform.test:8000/xhr/abort-during-loading.htm
#http://web-platform.test:8000/xhr/send-network-error-async-events.sub.htm
#http://web-platform.test:8000/xhr/abort-event-order.htm
#http://web-platform.test:8000/xhr/open-parameters-toString.htm
#http://web-platform.test:8000/xhr/send-redirect-no-location.htm
http://web-platform.test:8000/xhr/access-control-preflight-credential-async.htm
http://web-platform.test:8000/xhr/xmlhttprequest-timeout-abortedonmain.html
http://web-platform.test:8000/xhr/xmlhttprequest-basic.htm
http://web-platform.test:8000/xhr/access-control-basic-allow-access-control-origin-header-data-url.htm
http://web-platform.test:8000/xhr/send-accept.htm
http://web-platform.test:8000/xhr/send-no-response-event-loadend.htm
#http://web-platform.test:8000/xhr/send-content-type-charset.htm
http://web-platform.test:8000/xhr/open-url-fragment.htm
http://web-platform.test:8000/xhr/xmlhttprequest-timeout-synconmain.html
#http://web-platform.test:8000/xhr/access-control-sandboxed-iframe-denied-without-wildcard.htm
#http://web-platform.test:8000/xhr/open-send-open.htm
http://web-platform.test:8000/xhr/send-response-upload-event-loadstart.htm
#http://web-platform.test:8000/xhr/send-authentication-prompt-2-manual.htm
#http://web-platform.test:8000/xhr/send-data-blob.htm
http://web-platform.test:8000/xhr/access-control-preflight-request-invalid-status-501.htm
http://web-platform.test:8000/xhr/setrequestheader-header-forbidden.htm
#http://web-platform.test:8000/xhr/abort-after-timeout.htm
#http://web-platform.test:8000/xhr/event-readystatechange-loaded.htm
http://web-platform.test:8000/xhr/getresponseheader-server-date.htm
#http://web-platform.test:8000/xhr/open-url-multi-window-4.htm
#http://web-platform.test:8000/xhr/xmlhttprequest-sync-not-hang-scriptloader-subframe.html
#http://web-platform.test:8000/xhr/response-data-progress.htm
http://web-platform.test:8000/xhr/getallresponseheaders-status.htm
#http://web-platform.test:8000/xhr/open-during-abort-processing.htm
#http://web-platform.test:8000/xhr/xmlhttprequest-timeout-worker-overridesexpires.html
#http://web-platform.test:8000/xhr/timeout-multiple-fetches.html
http://web-platform.test:8000/xhr/open-url-base-inserted.htm
http://web-platform.test:8000/xhr/response-data-gzip.htm
#http://web-platform.test:8000/xhr/setrequestheader-header-allowed.htm
http://web-platform.test:8000/xhr/access-control-preflight-request-headers-origin.htm
http://web-platform.test:8000/xhr/access-control-basic-get-fail-non-simple.htm
#http://web-platform.test:8000/xhr/abort-event-abort.htm
#http://web-platform.test:8000/xhr/send-entity-body-document-bogus.htm
http://web-platform.test:8000/xhr/open-method-bogus.htm
#http://web-platform.test:8000/xhr/setrequestheader-content-type.htm
#http://web-platform.test:8000/xhr/open-url-worker-origin.htm
#http://web-platform.test:8000/xhr/open-send-during-abort.htm
#http://web-platform.test:8000/xhr/send-entity-body-none.htm
#http://web-platform.test:8000/xhr/event-upload-progress-crossorigin.htm
#http://web-platform.test:8000/xhr/send-authentication-existing-session-manual.htm
#http://web-platform.test:8000/xhr/xmlhttprequest-timeout-worker-simple.html
#http://web-platform.test:8000/xhr/data-uri.htm
#http://web-platform.test:8000/xhr/xmlhttprequest-sync-block-defer-scripts-subframe.html
http://web-platform.test:8000/xhr/access-control-basic-non-cors-safelisted-content-type.htm
#http://web-platform.test:8000/xhr/send-timeout-events.htm
#http://web-platform.test:8000/xhr/send-authentication-basic.htm
#http://web-platform.test:8000/xhr/access-control-and-redirects.htm
http://web-platform.test:8000/xhr/access-control-preflight-request-must-not-contain-cookie.htm
#http://web-platform.test:8000/xhr/status-basic.htm
#http://web-platform.test:8000/xhr/anonymous-mode-unsupported.htm
http://web-platform.test:8000/xhr/setrequestheader-after-send.htm
#http://web-platform.test:8000/xhr/access-control-basic-allow-preflight-cache.htm
#http://web-platform.test:8000/xhr/xmlhttprequest-timeout-worker-synconworker.html
#http://web-platform.test:8000/xhr/send-redirect-bogus-sync.htm
#http://web-platform.test:8000/xhr/send-authentication-prompt-manual.htm
#http://web-platform.test:8000/xhr/setrequestheader-case-insensitive.htm
#http://web-platform.test:8000/xhr/abort-after-stop.htm
#http://web-platform.test:8000/xhr/send-conditional-cors.htm
#http://web-platform.test:8000/xhr/access-control-and-redirects-async.htm
http://web-platform.test:8000/xhr/access-control-response-with-body-sync.htm
http://web-platform.test:8000/xhr/event-error.sub.html
http://web-platform.test:8000/xhr/response-invalid-responsetype.htm
#http://web-platform.test:8000/xhr/send-no-response-event-order.htm
http://web-platform.test:8000/xhr/response-data-deflate.htm
http://web-platform.test:8000/xhr/xmlhttprequest-timeout-reused.html
http://web-platform.test:8000/xhr/access-control-response-with-body.htm
http://web-platform.test:8000/xhr/send-entity-body-basic.htm
#http://web-platform.test:8000/xhr/send-after-setting-document-domain.htm
http://web-platform.test:8000/xhr/send-authentication-basic-cors.htm
#http://web-platform.test:8000/xhr/allow-lists-starting-with-comma.htm
http://web-platform.test:8000/xhr/xmlhttprequest-sync-block-scripts.html
#http://web-platform.test:8000/xhr/send-sync-blocks-async.htm
#http://web-platform.test:8000/xhr/send-authentication-cors-setrequestheader-no-cred.htm
#http://web-platform.test:8000/xhr/open-method-case-sensitive.htm
http://web-platform.test:8000/xhr/getresponseheader-unsent-opened-state.htm
http://web-platform.test:8000/xhr/access-control-preflight-credential-sync.htm
#http://web-platform.test:8000/xhr/send-data-arraybufferview.htm
http://web-platform.test:8000/xhr/send-redirect-infinite-sync.htm
#http://web-platform.test:8000/xhr/send-entity-body-document.htm
http://web-platform.test:8000/xhr/xmlhttprequest-timeout-twice.html
#http://web-platform.test:8000/xhr/responsexml-non-document-types.htm
#http://web-platform.test:8000/xhr/status-error.htm
http://web-platform.test:8000/xhr/responsexml-get-twice.htm
http://web-platform.test:8000/xhr/open-url-base-inserted-after-open.htm
#http://web-platform.test:8000/xhr/getresponseheader-chunked-trailer.htm
#http://web-platform.test:8000/xhr/timeout-cors-async.htm
http://web-platform.test:8000/xhr/access-control-basic-allow-async.htm
http://web-platform.test:8000/xhr/event-loadstart.htm
http://web-platform.test:8000/xhr/abort-during-unsent.htm
#http://web-platform.test:8000/xhr/send-authentication-competing-names-passwords.htm
#http://web-platform.test:8000/xhr/event-abort.htm
http://web-platform.test:8000/xhr/access-control-basic-cors-safelisted-request-headers.htm
http://web-platform.test:8000/xhr/progressevent-interface.html
#http://web-platform.test:8000/xhr/abort-during-upload.htm
http://web-platform.test:8000/xhr/send-entity-body-get-head.htm
#http://web-platform.test:8000/xhr/access-control-basic-allow-preflight-cache-invalidation-by-header.htm
#http://web-platform.test:8000/xhr/headers-normalize-response.htm
#http://web-platform.test:8000/xhr/open-during-abort-event.htm
http://web-platform.test:8000/xhr/abort-after-receive.htm
#http://web-platform.test:8000/xhr/xmlhttprequest-timeout-worker-twice.html
#http://web-platform.test:8000/xhr/event-timeout-order.htm
#http://web-platform.test:8000/xhr/open-url-worker-simple.htm
#http://web-platform.test:8000/xhr/setrequestheader-allow-whitespace-in-value.htm
#http://web-platform.test:8000/xhr/send-redirect-to-cors.htm
#http://web-platform.test:8000/xhr/progress-events-response-data-gzip.htm
#http://web-platform.test:8000/xhr/responseurl.html
#http://web-platform.test:8000/xhr/send-authentication-basic-setrequestheader-and-arguments.htm
#http://web-platform.test:8000/xhr/open-url-multi-window-5.htm
#http://web-platform.test:8000/xhr/send-conditional.htm
#http://web-platform.test:8000/xhr/abort-during-headers-received.htm
#http://web-platform.test:8000/xhr/access-control-sandboxed-iframe-allow-origin-null.htm
#http://web-platform.test:8000/xhr/preserve-ua-header-on-redirect.htm
http://web-platform.test:8000/xhr/event-readystate-sync-open.htm
http://web-platform.test:8000/xhr/access-control-basic-denied.htm
#http://web-platform.test:8000/xhr/send-authentication-basic-repeat-no-args.htm
http://web-platform.test:8000/xhr/access-control-basic-allow-non-cors-safelisted-method.htm
#http://web-platform.test:8000/xhr/event-loadstart-upload.htm
#http://web-platform.test:8000/xhr/access-control-recursive-failed-request.htm
http://web-platform.test:8000/xhr/open-after-abort.htm
http://web-platform.test:8000/xhr/open-method-insecure.htm
#http://web-platform.test:8000/xhr/abort-during-done.htm
http://web-platform.test:8000/xhr/overridemimetype-open-state-force-xml.htm
#http://web-platform.test:8000/xhr/send-authentication-cors-basic-setrequestheader.htm
#http://web-platform.test:8000/xhr/xmlhttprequest-network-error-sync.htm
#http://web-platform.test:8000/xhr/event-load.htm
#http://web-platform.test:8000/xhr/event-timeout.htm
http://web-platform.test:8000/xhr/send-response-upload-event-loadend.htm
#http://web-platform.test:8000/xhr/open-open-sync-send.htm
#http://web-platform.test:8000/xhr/responsexml-media-type.htm
http://web-platform.test:8000/xhr/xmlhttprequest-timeout-overrides.html
#http://web-platform.test:8000/xhr/open-sync-open-send.htm
#http://web-platform.test:8000/xhr/response-data-blob.htm
http://web-platform.test:8000/xhr/send-authentication-basic-cors-not-enabled.htm
http://web-platform.test:8000/xhr/setrequestheader-before-open.htm
#http://web-platform.test:8000/xhr/responseType-document-in-worker.html
http://web-platform.test:8000/xhr/event-progress.htm
http://web-platform.test:8000/xhr/abort-event-loadend.htm
#http://web-platform.test:8000/xhr/security-consideration.sub.html
#http://web-platform.test:8000/xhr/event-error-order.sub.html
http://web-platform.test:8000/xhr/xmlhttprequest-timeout-overridesexpires.html
#http://web-platform.test:8000/xhr/open-url-multi-window-3.htm
#http://web-platform.test:8000/xhr/send-authentication-basic-setrequestheader-existing-session.htm
http://web-platform.test:8000/xhr/xmlhttprequest-sync-not-hang-scriptloader.html
http://web-platform.test:8000/xhr/overridemimetype-headers-received-state-force-shiftjis.htm
http://web-platform.test:8000/xhr/access-control-basic-post-success-no-content-type.htm
#http://web-platform.test:8000/xhr/event-loadend.htm
#http://web-platform.test:8000/xhr/firing-events-http-content-length.html
#http://web-platform.test:8000/xhr/send-sync-no-response-event-order.htm
http://web-platform.test:8000/xhr/getresponseheader-special-characters.htm
#http://web-platform.test:8000/xhr/firing-events-http-no-content-length.html
http://web-platform.test:8000/xhr/timeout-sync.htm
http://web-platform.test:8000/xhr/send-redirect-to-non-cors.htm
#http://web-platform.test:8000/xhr/open-open-send.htm
#http://web-platform.test:8000/xhr/overridemimetype-loading-state.htm
http://web-platform.test:8000/xhr/open-method-case-insensitive.htm
http://web-platform.test:8000/xhr/progressevent-constructor.html
#http://web-platform.test:8000/xhr/send-authentication-basic-setrequestheader.htm
http://web-platform.test:8000/xhr/historical.html
http://web-platform.test:8000/xhr/getallresponseheaders-cookies.htm
http://web-platform.test:8000/xhr/overridemimetype-unsent-state-force-shiftjis.htm
http://web-platform.test:8000/xhr/access-control-preflight-request-invalid-status-400.htm
#http://web-platform.test:8000/xhr/overridemimetype-invalid-mime-type.htm
#http://web-platform.test:8000/xhr/send-entity-body-get-head-async.htm
http://web-platform.test:8000/xhr/open-url-multi-window.htm
#formdata
http://web-platform.test:8000/xhr/formdata-get.htm
http://web-platform.test:8000/xhr/formdata-has.htm
http://web-platform.test:8000/xhr/formdata-delete.htm
#http://web-platform.test:8000/xhr/formdata-foreach.html
#http://web-platform.test:8000/xhr/send-data-formdata.htm
#http://web-platform.test:8000/xhr/formdata-set.htm
#http://web-platform.test:8000/xhr/FormData-append.html
#http://web-platform.test:8000/xhr/formdata-blob.htm
#http://web-platform.test:8000/xhr/formdata.htm
