/*
 * Copyright (c) 2019-present Samsung Electronics Co., Ltd
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
 *  USA
 */

// https://webaudio.github.io/web-audio-api/#dictdef-audiobuffersourceoptions
[ STARFISH_ENABLE_WEBAUDIO ]
dictionary AudioBufferSourceOptions {
  AudioBuffer? buffer;
//  float detune = 0;
//  boolean loop = false;
//  double loopEnd = 0;
//  double loopStart = 0;
//  float playbackRate = 1;
};

// https://webaudio.github.io/web-audio-api/#AudioBufferSourceNode
[ STARFISH_ENABLE_WEBAUDIO,
  Constructor (BaseAudioContext context, optional AudioBufferSourceOptions options),
  ConstructorCallWith=ExecutionContext,
  Exposed=Window ]
interface AudioBufferSourceNode : AudioScheduledSourceNode {
  attribute AudioBuffer? buffer;
  //readonly attribute AudioParam playbackRate;
  //readonly attribute AudioParam detune;
  //attribute boolean loop;
  //attribute double loopStart;
  //attribute double loopEnd;
  //void start (optional double when = 0, optional double offset, optional double duration);
};
