/*
 * Copyright (c) 2019-present Samsung Electronics Co., Ltd
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
 *  USA
 */

// https://webaudio.github.io/web-audio-api/#audionode
[ STARFISH_ENABLE_WEBAUDIO,
  ConstructorCallWith=ExecutionContext,
  Exposed=Window ]
interface AudioNode : EventTarget {
  //AudioNode connect (AudioNode destinationNode, optional unsigned long output = 0, optional unsigned long input = 0);
  //void connect (AudioParam destinationParam, optional unsigned long output = 0);
  //void disconnect ();
  //void disconnect (unsigned long output);
  //void disconnect (AudioNode destinationNode);
  //void disconnect (AudioNode destinationNode, unsigned long output);
  //void disconnect (AudioNode destinationNode, unsigned long output, unsigned long input);
  //void disconnect (AudioParam destinationParam);
  //void disconnect (AudioParam destinationParam, unsigned long output);
  //readonly attribute BaseAudioContext context;
  //readonly attribute unsigned long numberOfInputs;
  //readonly attribute unsigned long numberOfOutputs;
  //attribute unsigned long channelCount;
  //attribute ChannelCountMode channelCountMode;
  //attribute ChannelInterpretation channelInterpretation;
};
