// https://webaudio.github.io/web-audio-api/#enumdef-automationrate
[ STARFISH_ENABLE_WEBAUDIO ]
enum AutomationRate { "a-rate", "k-rate" };

// https://webaudio.github.io/web-audio-api/#AudioParam
[ STARFISH_ENABLE_WEBAUDIO, Exposed=Window ]
interface AudioParam {
  [RaisesException] attribute float value;
  [Rename=automationRateStr, RaisesException] attribute AutomationRate automationRate;
  readonly attribute float defaultValue;
  readonly attribute float minValue;
  readonly attribute float maxValue;
  [RaisesException] AudioParam setValueAtTime(float value, double startTime);
  [RaisesException] AudioParam linearRampToValueAtTime(float value, double endTime);
  [RaisesException] AudioParam exponentialRampToValueAtTime(float value, double endTime);
  [RaisesException] AudioParam setTargetAtTime(float target, double startTime, float timeConstant);
  [RaisesException] AudioParam setValueCurveAtTime(sequence<float> values, double startTime, double duration);
  [RaisesException] AudioParam cancelScheduledValues(double cancelTime);
  [RaisesException] AudioParam cancelAndHoldAtTime(double cancelTime);
};
