// https://webaudio.github.io/web-audio-api/#dictdef-gainoptions
[ STARFISH_ENABLE_WEBAUDIO ]
dictionary GainOptions : AudioNodeOptions {
  float gain = 1.0;
};

// https://webaudio.github.io/web-audio-api/#GainNode
[ STARFISH_ENABLE_WEBAUDIO,
  Constructor(BaseAudioContext context, optional GainOptions options),
  ConstructorCallWith=ExecutionContext,
  RaisesException=Constructor,
  Exposed=Window ]
interface GainNode : AudioNode {
  readonly attribute AudioParam gain;
};
