// https://w3c.github.io/speech-api/#tts-section

[STARFISH_ENABLE_TTS, Exposed=Window]
interface SpeechSynthesis : EventTarget {
    readonly attribute boolean pending;
    readonly attribute boolean speaking;
    readonly attribute boolean paused;

    void speak(SpeechSynthesisUtterance utterance);
    void cancel();
    void pause();
    void resume();
    sequence<SpeechSynthesisVoice> getVoices();

    attribute EventHandler onvoiceschanged;
};

partial interface Window {
    [STARFISH_ENABLE_TTS, SameObject] readonly attribute SpeechSynthesis speechSynthesis;
};

[STARFISH_ENABLE_TTS, Constructor(optional DOMString text),
 ConstructorCallWith=Document]
interface SpeechSynthesisUtterance : EventTarget {
    attribute DOMString text;
    attribute DOMString lang;
    attribute SpeechSynthesisVoice? voice;
    [Unimplemented] attribute float volume;
    attribute float rate;
    [Unimplemented] attribute float pitch;

    attribute EventHandler onstart;
    attribute EventHandler onend;
    attribute EventHandler onerror;
    attribute EventHandler onpause;
    attribute EventHandler onresume;
    [Unimplemented] attribute EventHandler onmark;
    [Unimplemented] attribute EventHandler onboundary;
};

[STARFISH_ENABLE_TTS, Exposed=Window]
interface SpeechSynthesisVoice {
    readonly attribute DOMString voiceURI;
    readonly attribute DOMString name;
    readonly attribute DOMString lang;
    readonly attribute boolean localService;
    [Rename=isDefault] readonly attribute boolean default;
};
