# Require expected PNG
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-composite-alpha.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/downsample-quality.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/gradient-add-second-start-end-stop.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/pixelated.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/pixelated-canvas.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/pixelated-resize.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/toDataURL-alpha-stability.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/webgl/pixelated.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/webgl/webgl-composite-modes.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/webgl/webgl-composite-modes-repaint.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/yuv-video-on-accelerated-canvas.html
#test/cairo/reftest/vendor/blink_original/fast/canvas-arc-circumference.html
#test/cairo/reftest/vendor/blink_original/fast/canvas-arc-circumference-fill.html
#test/cairo/reftest/vendor/blink_original/fast/canvas-composite-transformclip.html
#test/cairo/reftest/vendor/blink_original/fast/canvas-createImageBitmap-drawImage-video.html
#test/cairo/reftest/vendor/blink_original/fast/canvas-ellipse-circumference.html
#test/cairo/reftest/vendor/blink_original/fast/canvas-ellipse-circumference-fill.html
#test/cairo/reftest/vendor/blink_original/fast/canvas-ellipse-connecting-line.html
#test/cairo/reftest/vendor/blink_original/fast/canvas-hidpi-blurry.html
#test/cairo/reftest/vendor/blink_original/fast/canvas-pattern-video.html
#test/cairo/reftest/vendor/blink_original/fast/canvas-toDataURL-webp.html
#
#
# Require expected html
#test/cairo/reftest/vendor/blink_original/fast/canvas/bidi-multi-run.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/bug382588.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/bug412718.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/bug445162.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/bug532148.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-before-css.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-clip-stack-persistence.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-createImageBitmap-colorClamping.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-createImageBitmap-immutable.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-createImageBitmap-out-of-bounds-src.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-css-clip-path.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-drawImage-out-of-bounds-src.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvasDrawingIntoSelf.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-default-color.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-drop-shadow.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-drop-shadow-transformed.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-fill-liveness.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-fill-paint-color.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-fill-paint-gradient.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-fill-paint-pattern.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-global-alpha.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-global-composite-operation.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-liveness.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-modified.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-modified-save-restore.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-multiple-drop-shadows.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-removed.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-shadow-copy.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-shadow-destination-in.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-shadow.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-stroke-liveness.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-stroke-paint-color.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-stroke-paint-gradient.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-stroke-paint-pattern.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-svg-bbox.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-svg-inline.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-svg-liveness.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-svg-off-screen.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-undefined.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-undefined-then-defined.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-units-em.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-units-em-liveness.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-units-ex.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-units.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-units-off-screen.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-width-height.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-width-height-hidpi.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-width-height-hidpi-scale.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-width-height-off-screen.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-filter-width-height-scale.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-incremental-repaint-3.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-measure-text-rtl.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-overflow-hidden-animation.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-partial-invalidation-zoomed.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-resize-reset.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-size-change-after-layout.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-state-persistence-no-dirty.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-state-stack-simple.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-transform-identity.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-transform-infinity.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-transform-multiply.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-transform-nan.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-transform-non-invertible.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-transform-skewed.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-unbalanced-save.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/canvas-zoom.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/check-stale-putImageData.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/drawImage.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/fillrect-gradient-zero-stops.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/font-update.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/OffscreenCanvas-clearRect-in-worker.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/OffscreenCanvas-fillRect-in-worker.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/OffscreenCanvas-paths-in-worker.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/OffscreenCanvas-strokeRect-in-worker.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/patternfill-repeat.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/pixelated-off-screen.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/imagebitmap/transferImageBitmap-alpha.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/imagebitmap/transferImageBitmap-no-alpha.html
#test/cairo/reftest/vendor/blink_original/fast/canvas/imagebitmap/transferImageBitmap.html
