#test/cairo/reftest/vendor/blink_original/svg/animations/accumulate-use-count.html
#test/cairo/reftest/vendor/blink_original/svg/animations/add-after-load-use-counter.html
#test/cairo/reftest/vendor/blink_original/svg/animations/additive-use-count.html
#test/cairo/reftest/vendor/blink_original/svg/animations/animate-values-whitespace.html
#test/cairo/reftest/vendor/blink_original/svg/animations/animation-begin-change-js.html
#test/cairo/reftest/vendor/blink_original/svg/animations/animationElementTiming-use-counter.html
#test/cairo/reftest/vendor/blink_original/svg/animations/animation-events.html
#test/cairo/reftest/vendor/blink_original/svg/animations/animation-started-use-counter.html
#test/cairo/reftest/vendor/blink_original/svg/animations/animval-web-animations-flush-crash.html
#test/cairo/reftest/vendor/blink_original/svg/animations/beginEndAnimationElement-use-counter.html
#test/cairo/reftest/vendor/blink_original/svg/animations/begin-use-counters.html
#test/cairo/reftest/vendor/blink_original/svg/animations/calcMode-use-counters.html
#test/cairo/reftest/vendor/blink_original/svg/animations/currentTime-use-counter.html
#test/cairo/reftest/vendor/blink_original/svg/animations/end-use-counters.html
#test/cairo/reftest/vendor/blink_original/svg/animations/getCurrentTime-pause-unpause.html
#test/cairo/reftest/vendor/blink_original/svg/animations/getCurrentTime-pause-unpause-setCurrentTime.html
test/cairo/reftest/vendor/blink_original/svg/animations/img-tag-css-length-animation-crash.html
#test/cairo/reftest/vendor/blink_original/svg/animations/pause-setcurrenttime-unpause-before-timeline-start.html
#test/cairo/reftest/vendor/blink_original/svg/animations/pausing-use-counter.html
#test/cairo/reftest/vendor/blink_original/svg/animations/reinserting-svg-into-document.html
test/cairo/reftest/vendor/blink_original/svg/animations/script-href-no-animate.html
test/cairo/reftest/vendor/blink_original/svg/animations/svg-animation-parseValues.html
#test/cairo/reftest/vendor/blink_original/svg/as-iframe/svg-in-iframe.html
#test/cairo/reftest/vendor/blink_original/svg/as-image/adopt-while-async-svg-load-is-in-progress-crash.html
#test/cairo/reftest/vendor/blink_original/svg/as-image/animated-svg-as-image-visited-link.html
#test/cairo/reftest/vendor/blink_original/svg/as-image/data-font-in-css-crash.html
#test/cairo/reftest/vendor/blink_original/svg/as-image/data-font-in-css-invalid-data-url-crash.html
#test/cairo/reftest/vendor/blink_original/svg/as-image/data-font-in-css-invalid-font-crash.html
test/cairo/reftest/vendor/blink_original/svg/as-image/invalid-svg-image-with-data-uri.html
#test/cairo/reftest/vendor/blink_original/svg/as-image/svg-as-image-intrinsic-size.html
test/cairo/reftest/vendor/blink_original/svg/as-image/zero-size-svg-image-with-data-uri.html
test/cairo/reftest/vendor/blink_original/svg/as-list-image/svg-list-image-intrinsic-size-zoom.html
#test/cairo/reftest/vendor/blink_original/svg/as-object/sizing/svg-in-object-placeholder-auto-auto-intrinsic-ratio.html
#test/cairo/reftest/vendor/blink_original/svg/as-object/sizing/svg-in-object-placeholder-auto-auto-no-intrinsic-ratio.html
#test/cairo/reftest/vendor/blink_original/svg/as-object/sizing/svg-in-object-placeholder-auto-fixed-intrinsic-ratio.html
#test/cairo/reftest/vendor/blink_original/svg/as-object/sizing/svg-in-object-placeholder-auto-fixed-no-intrinsic-ratio.html
#test/cairo/reftest/vendor/blink_original/svg/as-object/sizing/svg-in-object-placeholder-auto-percentage-intrinsic-ratio.html
#test/cairo/reftest/vendor/blink_original/svg/as-object/sizing/svg-in-object-placeholder-auto-percentage-no-intrinsic-ratio.html
#test/cairo/reftest/vendor/blink_original/svg/as-object/sizing/svg-in-object-placeholder-fixed-auto-intrinsic-ratio.html
#test/cairo/reftest/vendor/blink_original/svg/as-object/sizing/svg-in-object-placeholder-fixed-auto-no-intrinsic-ratio.html
#test/cairo/reftest/vendor/blink_original/svg/as-object/sizing/svg-in-object-placeholder-fixed-fixed-intrinsic-ratio.html
#test/cairo/reftest/vendor/blink_original/svg/as-object/sizing/svg-in-object-placeholder-fixed-fixed-no-intrinsic-ratio.html
#test/cairo/reftest/vendor/blink_original/svg/as-object/sizing/svg-in-object-placeholder-fixed-percentage-intrinsic-ratio.html
#test/cairo/reftest/vendor/blink_original/svg/as-object/sizing/svg-in-object-placeholder-fixed-percentage-no-intrinsic-ratio.html
#test/cairo/reftest/vendor/blink_original/svg/as-object/sizing/svg-in-object-placeholder-percentage-auto-intrinsic-ratio.html
#test/cairo/reftest/vendor/blink_original/svg/as-object/sizing/svg-in-object-placeholder-percentage-auto-no-intrinsic-ratio.html
#test/cairo/reftest/vendor/blink_original/svg/as-object/sizing/svg-in-object-placeholder-percentage-fixed-intrinsic-ratio.html
#test/cairo/reftest/vendor/blink_original/svg/as-object/sizing/svg-in-object-placeholder-percentage-fixed-no-intrinsic-ratio.html
#test/cairo/reftest/vendor/blink_original/svg/as-object/sizing/svg-in-object-placeholder-percentage-percentage-intrinsic-ratio.html
#test/cairo/reftest/vendor/blink_original/svg/as-object/sizing/svg-in-object-placeholder-percentage-percentage-no-intrinsic-ratio.html
test/cairo/reftest/vendor/blink_original/svg/clip-path/clip-path-foreign-object-crash.html
#test/cairo/reftest/vendor/blink_original/svg/css/baseline-shift-inherit.html
#test/cairo/reftest/vendor/blink_original/svg/css/css-keyword-properties.html
#test/cairo/reftest/vendor/blink_original/svg/css/display-computed.html
#test/cairo/reftest/vendor/blink_original/svg/css/getcomputedstyle-width-height.html
#test/cairo/reftest/vendor/blink_original/svg/css/path-element.html
#test/cairo/reftest/vendor/blink_original/svg/css/url-serialization-resource-references.html
#test/cairo/reftest/vendor/blink_original/svg/css/viewBox-attribute-selector.html
#test/cairo/reftest/vendor/blink_original/svg/custom/animate-initial-pause-unpause.html
#test/cairo/reftest/vendor/blink_original/svg/custom/animate-svgsvgelement.html
#test/cairo/reftest/vendor/blink_original/svg/custom/disallow-non-lengths-in-attrs.html
#test/cairo/reftest/vendor/blink_original/svg/custom/display-none-a-does-not-stop-focus-navigation.html
#test/cairo/reftest/vendor/blink_original/svg/custom/getBBox-circle-has-one-zero-value.html
#test/cairo/reftest/vendor/blink_original/svg/custom/getBBox-ellipse-has-one-zero-value.html
#test/cairo/reftest/vendor/blink_original/svg/custom/getBBox-rect-has-one-zero-value.html
#test/cairo/reftest/vendor/blink_original/svg/custom/getBBox-use.html
test/cairo/reftest/vendor/blink_original/svg/custom/getClientRects.html
#test/cairo/reftest/vendor/blink_original/svg/custom/image-svgload-after-docload.html
test/cairo/reftest/vendor/blink_original/svg/custom/inline-svg-use-available-width.html
#test/cairo/reftest/vendor/blink_original/svg/custom/inline-svg-use-available-width-in-stf.html
#test/cairo/reftest/vendor/blink_original/svg/custom/invalid-length-units.html
#test/cairo/reftest/vendor/blink_original/svg/custom/load-image-removed-in-onload.html
#test/cairo/reftest/vendor/blink_original/svg/custom/load-image-reparented-in-onload.html
#test/cairo/reftest/vendor/blink_original/svg/custom/load-svgfragments-inserted-after-docload.html
#test/cairo/reftest/vendor/blink_original/svg/custom/object-sizing-zero-intrinsic-width-height.html
#test/cairo/reftest/vendor/blink_original/svg/custom/size-follows-container-size.html
#test/cairo/reftest/vendor/blink_original/svg/custom/stf-container-with-intrinsic-ratio-svg.html
#test/cairo/reftest/vendor/blink_original/svg/custom/svg-image-intrinsic-size-with-cssstyle-auto-dynamic-image-change.html
#test/cairo/reftest/vendor/blink_original/svg/custom/svg-image-intrinsic-size-with-cssstyle-auto.html
#test/cairo/reftest/vendor/blink_original/svg/custom/svg-length-empty-string.html
#test/cairo/reftest/vendor/blink_original/svg/custom/zoomed-alignment-baseline.html
#test/cairo/reftest/vendor/blink_original/svg/custom/zoomed-baseline-shift.html
#test/cairo/reftest/vendor/blink_original/svg/custom/zoomed-ex-em-font-sizes.html
#test/cairo/reftest/vendor/blink_original/svg/custom/zoomed-mixed-scripts.html
#test/cairo/reftest/vendor/blink_original/svg/dom/getbbox.html
#test/cairo/reftest/vendor/blink_original/svg/dom/getScreenCTM-ancestor-transform.html
#test/cairo/reftest/vendor/blink_original/svg/dom/getScreenCTM.html
#test/cairo/reftest/vendor/blink_original/svg/dom/getscreenctm-use-with-additional-translation.html
#test/cairo/reftest/vendor/blink_original/svg/dom/href-baseval-animval.html
#test/cairo/reftest/vendor/blink_original/svg/dom/href-semantics.html
#test/cairo/reftest/vendor/blink_original/svg/dom/image-detached-load.html
#test/cairo/reftest/vendor/blink_original/svg/dom/image-moved-to-new-document.html
#test/cairo/reftest/vendor/blink_original/svg/dom/integer-optional-integer-value-range.html
#test/cairo/reftest/vendor/blink_original/svg/dom/linear-gradient-default-length.html
#test/cairo/reftest/vendor/blink_original/svg/dom/no-value-synching-after-attr-removal.html
#test/cairo/reftest/vendor/blink_original/svg/dom/no-value-synching-after-property-get.html
#test/cairo/reftest/vendor/blink_original/svg/dom/no-value-synching-after-setattr.html
#test/cairo/reftest/vendor/blink_original/svg/dom/path-queries-pathLength.html
test/cairo/reftest/vendor/blink_original/svg/dom/set-title-element-on-inner-svg-document.html
test/cairo/reftest/vendor/blink_original/svg/dom/set-title-html-namespace-on-SVG.html
test/cairo/reftest/vendor/blink_original/svg/dom/SVGAngle.html
#test/cairo/reftest/vendor/blink_original/svg/dom/svgangle-units.html
#test/cairo/reftest/vendor/blink_original/svg/dom/svganimatedangle-initial-values.html
#test/cairo/reftest/vendor/blink_original/svg/dom/svganimatedenumeration-initial-values.html
#test/cairo/reftest/vendor/blink_original/svg/dom/svganimatedinteger-initial-values.html
#test/cairo/reftest/vendor/blink_original/svg/dom/svganimatedlength-initial-values.html
#test/cairo/reftest/vendor/blink_original/svg/dom/svganimatednumber-initial-values.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGAnimationElement-exceptions.html
#test/cairo/reftest/vendor/blink_original/svg/dom/svg-document-set-title-mutations.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGFESpecularLightingElement-svgdom-kernelUnitLength.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGGeometryElement-getPointAtLength-attached.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGGeometryElement-getPointAtLength-detached.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGGeometryElement-getTotalLength-attached.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGGeometryElement-getTotalLength-detached.html
test/cairo/reftest/vendor/blink_original/svg/dom/SVGGeometryElement-valid-arguments.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGLength-absolute-length-units.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGLength-calc-in-attr.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGLengthList-dom-modifications.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGLengthList-initialize.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGLengthList-insertItemBefore.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGLengthList-removeItem.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGLengthList-replaceItem.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGLengthList-setEmptyString.html
#test/cairo/reftest/vendor/blink_original/svg/dom/svglength-units.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGLength-viewport-units.html
#test/cairo/reftest/vendor/blink_original/svg/dom/svglist-basic-interface.html
#test/cairo/reftest/vendor/blink_original/svg/dom/svglist-immutable.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGMarkerElement-orientType-synchronization.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGMatrix.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGNumber.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGPoint.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGStyleElement.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGSVGElement-no-op-methods.html
test/cairo/reftest/vendor/blink_original/svg/dom/SVGTransform.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGTransformList-basics.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGTransformList-createSVGTransformFromMatrix-argument-type.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGTransformList-empty-list-consolidation.html
#test/cairo/reftest/vendor/blink_original/svg/dom/SVGTransformList-with-existing-item.html
#test/cairo/reftest/vendor/blink_original/svg/dom/systemLanguage-case-insensitive.html
#test/cairo/reftest/vendor/blink_original/svg/dom/systemLanguage-comma-separated.html
#test/cairo/reftest/vendor/blink_original/svg/dom/systemLanguage-langtag-match-prefix.html
#test/cairo/reftest/vendor/blink_original/svg/dom/systemLanguage-reflect-user-language.html
#test/cairo/reftest/vendor/blink_original/svg/dom/tabindex-focus.html
#test/cairo/reftest/vendor/blink_original/svg/dom/tooltip-title-external-svg.html
#test/cairo/reftest/vendor/blink_original/svg/dom/tooltip-title-inline-svg.html
#test/cairo/reftest/vendor/blink_original/svg/dom/tooltip-title-with-use.html
test/cairo/reftest/vendor/blink_original/svg/foreignObject/foreignObject-position-crash.html
#test/cairo/reftest/vendor/blink_original/svg/foreignObject/viewport-foreignobject-crash.html
test/cairo/reftest/vendor/blink_original/svg/foreignObject/z-index-crash.html
#test/cairo/reftest/vendor/blink_original/svg/hittest/clip-path-shape.html
test/cairo/reftest/vendor/blink_original/svg/hittest/empty-container.html
#test/cairo/reftest/vendor/blink_original/svg/hittest/foreign-object-with-transform.html
#test/cairo/reftest/vendor/blink_original/svg/hittest/text-fill-none-with-nested-tspan.html
#test/cairo/reftest/vendor/blink_original/svg/hittest/text-overlapped.html
#test/cairo/reftest/vendor/blink_original/svg/hittest/text-small-font-size-and-viewbox.html
#test/cairo/reftest/vendor/blink_original/svg/hittest/text-small-font-size.html
#test/cairo/reftest/vendor/blink_original/svg/hittest/text-vertical.html
#test/cairo/reftest/vendor/blink_original/svg/hittest/text-visibility-hidden-with-nested-tspan.html
#test/cairo/reftest/vendor/blink_original/svg/hittest/zero-stroke-width.html
#test/cairo/reftest/vendor/blink_original/svg/in-html/sizing/svg-inline.html
#test/cairo/reftest/vendor/blink_original/svg/in-html/sizing/svg-inline-vertical.html
#test/cairo/reftest/vendor/blink_original/svg/markers/marker-orientation-set.html
test/cairo/reftest/vendor/blink_original/svg/masking/mask-within-feimage-filter-on-root-crash.html
#test/cairo/reftest/vendor/blink_original/svg/parser/whitespace-angle-1.html
#test/cairo/reftest/vendor/blink_original/svg/parser/whitespace-angle-2.html
#test/cairo/reftest/vendor/blink_original/svg/parser/whitespace-angle-invalid-1.html
#test/cairo/reftest/vendor/blink_original/svg/parser/whitespace-angle-invalid-2.html
#test/cairo/reftest/vendor/blink_original/svg/parser/whitespace-integer.html
#test/cairo/reftest/vendor/blink_original/svg/parser/whitespace-length.html
test/cairo/reftest/vendor/blink_original/svg/parser/whitespace-length-invalid-1.html
test/cairo/reftest/vendor/blink_original/svg/parser/whitespace-length-invalid-2.html
#test/cairo/reftest/vendor/blink_original/svg/parser/whitespace-length-invalid-3.html
#test/cairo/reftest/vendor/blink_original/svg/parser/whitespace-length-invalid-4.html
#test/cairo/reftest/vendor/blink_original/svg/parser/whitespace-number.html
#test/cairo/reftest/vendor/blink_original/svg/stroke/isPointInStroke-non-scaling-stroke-empty-ellipse-crash.html
#test/cairo/reftest/vendor/blink_original/svg/stroke/isPointInStroke-non-scaling-stroke-invalid-shape-crash.html
#test/cairo/reftest/vendor/blink_original/svg/svg-in-html.html
#test/cairo/reftest/vendor/blink_original/svg/text/bidi-getcharnumatpos.html
#test/cairo/reftest/vendor/blink_original/svg/text/bidi-getcomputedtextlength.html
#test/cairo/reftest/vendor/blink_original/svg/text/bidi-getsubstringlength.html
#test/cairo/reftest/vendor/blink_original/svg/text/empty-text-node-crash.html
#test/cairo/reftest/vendor/blink_original/svg/text/getcharnumatposition-multiple-fragments.html
#test/cairo/reftest/vendor/blink_original/svg/text/getextentofchar-nonbmp.html
#test/cairo/reftest/vendor/blink_original/svg/text/invalid-non-bmp-characters.html
#test/cairo/reftest/vendor/blink_original/svg/text/selection-dragging-outside-1.html
#test/cairo/reftest/vendor/blink_original/svg/text/selection-dragging-outside-2.html
#test/cairo/reftest/vendor/blink_original/svg/text/selection-dragging-outside-3.html
#test/cairo/reftest/vendor/blink_original/svg/text/selection-pseudo-resource-invalidation-crash.html
#test/cairo/reftest/vendor/blink_original/svg/text/select-svg-text-with-collapsed-whitespace.html
#test/cairo/reftest/vendor/blink_original/svg/text/select-text-vertical.html
#test/cairo/reftest/vendor/blink_original/svg/text/svgtextcontentelement-glyphqueries-rtl.html
#test/cairo/reftest/vendor/blink_original/svg/text/svgtextcontentelement-methods-parameters.html
#test/cairo/reftest/vendor/blink_original/svg/text/text-bbox-empty.html
#test/cairo/reftest/vendor/blink_original/svg/text/text-bbox-of-empty-after-change.html
#test/cairo/reftest/vendor/blink_original/svg/text/text-getSubStringLength.html
#test/cairo/reftest/vendor/blink_original/svg/text/textquery-collapsed-whitespace.html
test/cairo/reftest/vendor/blink_original/svg/text/text-rect-precision.html
#test/cairo/reftest/vendor/blink_original/svg/transforms/transform-boxsize-usecounter-1.html
#test/cairo/reftest/vendor/blink_original/svg/transforms/transform-boxsize-usecounter-2.html
#test/cairo/reftest/vendor/blink_original/svg/transforms/transform-boxsize-usecounter-3.html
#test/cairo/reftest/vendor/blink_original/svg/transforms/transform-boxsize-usecounter-4.html
#test/cairo/reftest/vendor/blink_original/svg/transforms/transform-boxsize-usecounter-no-trigger-1.html
#test/cairo/reftest/vendor/blink_original/svg/transforms/transform-boxsize-usecounter-no-trigger-2.html
#test/cairo/reftest/vendor/blink_original/svg/zoom/page/zoom-get-screen-ctm.html
#test/cairo/reftest/vendor/blink_original/svg/zoom/xy-getcomputedstyle.html
