test/cairo/reftest/web-platform-tests/html/browsers/the-window-object/Document-defaultView.html
test/cairo/reftest/web-platform-tests/html/browsers/the-window-object/window-aliases.html
test/cairo/reftest/web-platform-tests/html/browsers/the-window-object/window-indexed-properties.html
test/cairo/reftest/web-platform-tests/html/browsers/the-window-object/window-indexed-properties-strict.html
test/cairo/reftest/web-platform-tests/html/browsers/the-window-object/window-properties.html
test/cairo/reftest/web-platform-tests/html/browsers/the-window-object/window-prototype-chain.html
test/cairo/reftest/web-platform-tests/html/dom/documents/dom-tree-accessors/document.body-setter-01.html
test/cairo/reftest/web-platform-tests/html/dom/documents/dom-tree-accessors/Document.getElementsByClassName-null-undef.html
test/cairo/reftest/web-platform-tests/html/dom/documents/dom-tree-accessors/document.getElementsByClassName-same.html
test/cairo/reftest/web-platform-tests/html/dom/documents/dom-tree-accessors/document.head-01.html
test/cairo/reftest/web-platform-tests/html/dom/documents/dom-tree-accessors/document.head-02.html
test/cairo/reftest/web-platform-tests/html/dom/documents/dom-tree-accessors/Element.getElementsByClassName-null-undef.html
test/cairo/reftest/web-platform-tests/html/dom/documents/resource-metadata-management/document-compatmode-01.html
test/cairo/reftest/web-platform-tests/html/dom/documents/resource-metadata-management/document-compatmode-02.html
test/cairo/reftest/web-platform-tests/html/dom/documents/resource-metadata-management/document-cookie.html
test/cairo/reftest/web-platform-tests/html/dom/elements/elements-in-the-dom/unknown-element.html
test/cairo/reftest/web-platform-tests/html/dom/elements/global-attributes/classlist-nonstring.html
test/cairo/reftest/web-platform-tests/html/dom/elements/global-attributes/id-attribute.html
test/cairo/reftest/web-platform-tests/html/editing/activation/click.html
test/cairo/reftest/web-platform-tests/html/infrastructure/conformance-requirements/extensibility/foreign.html
test/cairo/reftest/web-platform-tests/html/semantics/grouping-content/the-div-element/grouping-div.html
test/cairo/reftest/web-platform-tests/html/semantics/grouping-content/the-p-element/grouping-p.html
test/cairo/reftest/web-platform-tests/html/semantics/scripting-1/the-script-element/script-languages-01.html
test/cairo/reftest/web-platform-tests/html/semantics/scripting-1/the-script-element/script-onload-string.html
test/cairo/reftest/web-platform-tests/html/semantics/document-metadata/the-base-element/base_href_empty.html
test/cairo/reftest/web-platform-tests/html/semantics/document-metadata/the-base-element/base_href_unspecified.html
test/cairo/reftest/web-platform-tests/html/semantics/scripting-1/the-script-element/fetch-src/alpha/base.html
test/cairo/reftest/web-platform-tests/html/webappapis/animation-frames/callback-invoked.html
test/cairo/reftest/web-platform-tests/html/webappapis/animation-frames/callback-multicalls.html
test/cairo/reftest/web-platform-tests/html/webappapis/animation-frames/cancel-invoked.html
test/cairo/reftest/web-platform-tests/html/webappapis/animation-frames/same-dispatch-time.html
test/cairo/reftest/web-platform-tests/html/webappapis/scripting/events/body-onload.html
test/cairo/reftest/web-platform-tests/html/webappapis/scripting/events/event-handler-javascript.html
# test/cairo/reftest/web-platform-tests/html/webappapis/scripting/processing-model-2/addEventListener.html # Other browsers also failed
