http://web-platform.test:7000/XMLHttpRequest/abort-after-receive.htm
http://web-platform.test:7000/XMLHttpRequest/abort-during-unsent.htm
http://web-platform.test:7000/XMLHttpRequest/abort-event-abort.htm
http://web-platform.test:7000/XMLHttpRequest/abort-event-listeners.htm
http://web-platform.test:7000/XMLHttpRequest/abort-event-loadend.htm
http://web-platform.test:7000/XMLHttpRequest/event-abort.htm
http://web-platform.test:7000/XMLHttpRequest/event-loadend.htm
http://web-platform.test:7000/XMLHttpRequest/event-load.htm
http://web-platform.test:7000/XMLHttpRequest/event-loadstart.htm
http://web-platform.test:7000/XMLHttpRequest/event-timeout.htm
http://web-platform.test:7000/XMLHttpRequest/event-progress.htm
http://web-platform.test:7000/XMLHttpRequest/event-readystatechange-loaded.htm
http://web-platform.test:7000/XMLHttpRequest/event-readystate-sync-open.htm
http://web-platform.test:7000/XMLHttpRequest/open-after-abort.htm
http://web-platform.test:7000/XMLHttpRequest/open-during-abort.htm
http://web-platform.test:7000/XMLHttpRequest/open-user-password-non-same-origin.htm
http://web-platform.test:7000/XMLHttpRequest/responseText-status.html
http://web-platform.test:7000/XMLHttpRequest/timeout-sync.htm
http://web-platform.test:7000/XMLHttpRequest/xmlhttprequest-basic.htm
http://web-platform.test:7000/XMLHttpRequest/getallresponseheaders-status.htm
http://web-platform.test:7000/XMLHttpRequest/getresponseheader-error-state.htm
http://web-platform.test:7000/XMLHttpRequest/open-url-base-inserted-after-open.htm
http://web-platform.test:7000/XMLHttpRequest/setrequestheader-after-send.htm
http://web-platform.test:7000/XMLHttpRequest/setrequestheader-before-open.htm
http://web-platform.test:7000/XMLHttpRequest/open-method-bogus.htm
http://web-platform.test:7000/XMLHttpRequest/getresponseheader-server-date.htm
http://web-platform.test:7000/XMLHttpRequest/send-no-response-event-loadstart.htm
http://web-platform.test:7000/XMLHttpRequest/xmlhttprequest-eventtarget.htm
http://web-platform.test:7000/XMLHttpRequest/send-authentication-basic-cors.htm
http://web-platform.test:7000/XMLHttpRequest/getresponseheader-unsent-opened-state.htm
http://web-platform.test:7000/XMLHttpRequest/getresponseheader-case-insensitive.htm
http://web-platform.test:7000/XMLHttpRequest/getresponseheader-chunked-trailer.htm
http://web-platform.test:7000/XMLHttpRequest/getresponseheader-cookies-and-more.htm
http://web-platform.test:7000/XMLHttpRequest/getresponseheader-special-characters.htm
http://web-platform.test:7000/XMLHttpRequest/getallresponseheaders-cookies.htm
