[general]
profile = profile.da_sac_ehsc_m64_armv7l_dev
work_dir=~/da/gbs-configuration/sac/ehsc

#dvmai
[profile.da_sac_ehsc_m64_armv7l_dev]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_sac_ehsc_m64_dev, repo.da_base, repo.da_platform_y25_dev_meson64
buildconf=${work_dir}/TIZEN_7.0_DA_SAC_MESON64_BUILD.conf
buildroot=~/gbs-root/tizen-7.0/da-sac-ehsc/meson64/armv7l/dev/

[profile.da_sac_ehsc_m64_armv7l_stg]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_sac_ehsc_m64_stg, repo.da_base, repo.da_platform_y25_dev_meson64
buildconf=${work_dir}/TIZEN_7.0_DA_SAC_MESON64_BUILD.conf
buildroot=~/gbs-root/tizen-7.0/da-sac-ehsc/meson64/armv7l/stg/

[repo.da_sac_ehsc_m64_dev]
url = http://10.91.252.21/snapshots/DA/Tizen-7.0/Prod-MP-Tizen-7.0-DA-SAC-EHSC-25-Dev/reference/repos/MESON64/packages/

[repo.da_sac_ehsc_m64_stg]
url = http://10.91.252.21/snapshots/DA/Tizen-7.0/Prod-MP-Tizen-7.0-DA-SAC-EHSC-25-Stg/reference/repos/MESON64/packages/

#DA Base
[repo.da_base]
url=http://10.113.138.205/snapshots/DA/Tizen-7.0/Tizen-7.0-DA-Base/reference/repos/standard/packages/

#DA Platform Y25 Dev MESON64
[repo.da_platform_y25_dev_meson64]
url = http://10.91.252.21/snapshots/DA/Tizen-7.0/Prod-MP-Tizen-7.0-DA-Platform-Y25-Dev/reference/repos/MESON64/packages/

#DA Platform Y25 Stg MESON64
[repo.da_platform_y25_stg_meson64]
url = http://10.91.252.21/snapshots/DA/Tizen-7.0/Prod-MP-Tizen-7.0-DA-Platform-Y25-Stg/reference/repos/MESON64/packages/