[general]
profile = profile.tv
upstream_branch = origin

[profile.tv]
repos = repo.tv_pontus,repo.tv_base

[repo.tv_base]
url = http://repos.vd.sec.samsung.net/base/tizen-7.0-base/standard/latest

[repo.tv_pontus]
#url = http://repos.vd.sec.samsung.net/products/tv/official/2023/TRUNK2023/PontusML_WW/latest
url = http://repos.vd.sec.samsung.net/products/b2b/sie/2023/SecureDowngrade/PontusML_WW/PontusML_0000_tizen_20231004.10545856
