[general]
profile = profile.RoseW

############################################################################################

[repo.base]
url=http://repos.vd.sec.samsung.net/base/tizen-10.0-base/standard/latest/

[repo.product]
url=http://repos.vd.sec.samsung.net/priv/168.219.246.197:81/PRV/builds/b055/15733055/artifacts/TIZEN-25-Native-CoBA-PontusM-RELEASE_20250808.1/

############################################################################################

[profile.RoseW]
repos = repo.product, repo.base

