[general]
profile = profile.OneMain_NikeM

[profile.OneMain_NikeM]
repos = repo.product_Trunk2020_NikeM, repo.base_Main2020_standard

[repo.base_Main2020_standard]
url = http://168.219.244.109/tizen-rsa/tizen-6.0-base/standard/latest/

[repo.product_OneMain_NikeM]
url = http://168.219.244.109/products/tv/archive/2020/ONEMAIN/NikeM_DVB/latest
