[general]
profile = profile.T55
#profile = profile.T50

############################################################################################

[repo.base_T55]
url=http://168.219.245.245/base/tizen-5.5-base-main/standard/tizen-5.5-main-stan_20200113.1/

[repo.local_T55]
url=~/GBS-ROOT/local/repos/T55/armv7l/RPMS

[repo.base_T50]
url=http://168.219.245.245/base/tizen-5.0-base-main2019/standard/tizen-5.0-main2019-stan_20190116.1/

[repo.local_T50]
url=~/GBS-ROOT/local/repos/T50/armv7l/RPMS

############################################################################################
# For Tizen 5.5
############################################################################################

[profile.T55]
repos = repo.local_T55, repo.product_T55, repo.base_T55
          
[repo.product_T55]
url=http://168.219.245.245/products/tv/official/current/ONEMAIN/NikeM/latest/

############################################################################################
# For Tizen 5.5
############################################################################################

[profile.T50]
repos = repo.local_T50, repo.product_T50, repo.base_T50

[repo.product_T50]
url=http://168.219.245.245/products/tv/official/2019/TRUNK2019/MuseM/latest/
