[general]
profile = profile.t90robotc8
profile = profile.t90robotc8_qb

[obs.tizen]
url = https://api.tizen.org

[profile.t90robotc8]
obs = obs.tizen
repos = repo.90base, repo.90robot_latest
buildroot = ~/GBS-ROOT/t90robotc8

[profile.t90robotc8_qb]
obs = obs.tizen
repos = repo.90base_onemain, repo.90robot_onemain
buildroot = ~/GBS-ROOT/t90robotc8

[repo.90base]
url=http://repos.vd.sec.samsung.net/base/tizen-base-x/standard/latest/repos/base/aarch64/packages/

[repo.90base_onemain]
url=http://repos.vd.sec.samsung.net/obs220/tizen-rsa/tizen-base-x/standard/latest/repos/base/aarch64/packages/

[repo.90robot_latest]
url=http://repos.vd.sec.samsung.net/products/tv/official/2025/Ballie-2025-MP/QCS8550/latest/repos/product/aarch64/packages/

[repo.90robot_onemain]
url=http://repos.vd.sec.samsung.net/products/tv/official/2025/ONEMAIN/QCS8550/latest/repos/product/aarch64/packages/
