[general]
profile = profile.da_rvc_y25_stg_meson64_aarch64
work_dir=~/da/gbs-configuration/rvc

[profile.da_rvc_y25_stg_qrb4210_aarch64]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_rvc_y25_stg_qrb4210, repo.da_platform_y25_stg_qrb4210, repo.da_base
buildconf=${work_dir}/TIZEN_7.0_DA_RVC_Y25_BUILD_QRB4210.conf
buildroot=~/gbs-root/tizen-7.0/da-rvc-y25/stg/qrb4210/aarch64/

[profile.da_rvc_y25_stg_meson64_aarch64]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_rvc_y25_stg_meson64, repo.da_platform_y25_stg_meson64, repo.da_base
buildconf=${work_dir}/TIZEN_7.0_DA_RVC_Y25_BUILD_MESON64.conf
buildroot=~/gbs-root/tizen-7.0/da-rvc-y25/stg/meson64/aarch64/

[profile.da_rvc_y25_prd_qrb4210_aarch64]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_rvc_y25_prd_qrb4210, repo.da_platform_y25_prd_qrb4210, repo.da_base
buildconf=${work_dir}/TIZEN_7.0_DA_RVC_Y25_BUILD_QRB4210.conf
buildroot=~/gbs-root/tizen-7.0/da-rvc-y25/prd/qrb4210/aarch64/

[profile.da_rvc_y25_prd_meson64_aarch64]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_rvc_y25_prd_meson64, repo.da_platform_y25_prd_meson64, repo.da_base
buildconf=${work_dir}/TIZEN_7.0_DA_RVC_Y25_BUILD_MESON64.conf
buildroot=~/gbs-root/tizen-7.0/da-rvc-y25/prd/meson64/aarch64/

#DA RVC Y25 Stg QRB4210
[repo.da_rvc_y25_stg_qrb4210]
url = http://10.91.252.21/snapshots/DA/Tizen-7.0/Prod-MP-Tizen-7.0-DA-VCR-VR90F-25-Stg/reference/repos/QRB4210/packages/

#DA RVC Y25 Stg MESON64
[repo.da_rvc_y25_stg_meson64]
url = http://10.91.252.21/snapshots/DA/Tizen-7.0/Prod-MP-Tizen-7.0-DA-VCR-VR70F-25-Stg/reference/repos/MESON64/packages/

#DA RVC Y25 Prd QRB4210
[repo.da_rvc_y25_prd_qrb4210]
url = http://10.91.252.21/snapshots/DA/Tizen-7.0/Prod-MP-Tizen-7.0-DA-VCR-VR90F-25-Prd/reference/repos/QRB4210/packages/

#DA RVC Y25 Prd MESON64
[repo.da_rvc_y25_prd_meson64]
url = http://10.91.252.21/snapshots/DA/Tizen-7.0/Prod-MP-Tizen-7.0-DA-VCR-VR70F-25-Prd/reference/repos/MESON64/packages/

#DA Platform Y25 Stg QRB4210
[repo.da_platform_y25_stg_qrb4210]
url = http://10.91.252.21/snapshots/DA/Tizen-7.0/Prod-MP-Tizen-7.0-DA-Platform-Y25-Stg/reference/repos/QRB4210/packages/

#DA Platform Y25 Stg MESON64
[repo.da_platform_y25_stg_meson64]
url = http://10.91.252.21/snapshots/DA/Tizen-7.0/Prod-MP-Tizen-7.0-DA-Platform-Y25-Stg/reference/repos/MESON64/packages/

#DA Platform Y25 Prd QRB4210
[repo.da_platform_y25_prd_qrb4210]
url = http://10.91.252.21/snapshots/DA/Tizen-7.0/Prod-MP-Tizen-7.0-DA-Platform-Y25-Prd/reference/repos/QRB4210/packages/

#DA Platform Y25 Prd MESON64
[repo.da_platform_y25_prd_meson64]
url = http://10.91.252.21/snapshots/DA/Tizen-7.0/Prod-MP-Tizen-7.0-DA-Platform-Y25-Prd/reference/repos/MESON64/packages/

#DA Base
[repo.da_base]
url=http://10.113.138.205/snapshots/DA/Tizen-7.0/Tizen-7.0-DA-Base/reference/repos/standard/packages/
