// https://www.w3.org/TR/webstorage/#the-storage-interface

interface StorageImpl {
    [RaisesException] readonly attribute unsigned long length;
    [RaisesException] DOMString? key(unsigned long index);
    // NOTE Remove `getter` keyword from getItem temporarily
    [RaisesException] DOMString? getItem(DOMString key);
    [RaisesException] void setItem(DOMString key, DOMString data);
    [RaisesException] void removeItem(DOMString key);
    [RaisesException] void clear();
};
