#!/bin/sh
RED='\033[0;31m'
RESET='\033[0m'
echo "checking... make tidy"
make tidy
if cat error_report | grep 'ERROR'; then
 echo "$RED[FAIL] make tidy error$RESET"
 exit 1
fi

run_test() {
    echo "checking... make" $1
    stdbuf -oL make $1 | tee prepush_test_result
    if cat prepush_test_result |grep 'FAIL'; then
        echo "$RED[FAIL] make" $1"$RESET"
        exit 1
    fi
}

# Internal test
run_test internal_test

# Vendor Tests
run_test vendor_test_blink_fast_dom
run_test vendor_test_blink_fast_html
run_test vendor_test_blink_fast_css
run_test vendor_test_blink_fast_etc
run_test vendor_test_webkit_fast_dom
run_test vendor_test_webkit_fast_html
run_test vendor_test_webkit_fast_css
run_test vendor_test_webkit_fast_etc

# Web Platform Tests
run_test web_platform_test_dom
run_test web_platform_test_html
run_test web_platform_test_dom_events
run_test web_platform_test_progress_events
run_test web_platform_test_page_visibility
run_test web_platform_test_xhr
run_test web_platform_test_page_visibility

# Dom Conformance Tests
run_test dom_conformance_test
run_test dom_conformance_test_webkit
run_test dom_conformance_test_blink
run_test dom_conformance_test_gecko

# CSSWG Tests
run_test csswg_test_all

#disable tct while to fix tct error
#echo "checking... make tct"
#make tct > prepush_test_result 2>&1
#if cat prepush_test_result |grep 'FAIL'; then
# echo "$RED[FAIL] make tct$RESET"
# exit 1
#fi

rm prepush_test_result
