// https://w3c.github.io/IndexedDB/#keyrange

[
  STARFISH_ENABLE_IDB,
  ConstructorCallWith=ExecutionContext,
  Exposed=(Window,Worker)
]
interface IDBKeyRange {
  [Unimplemented] readonly attribute any lower;
  [Unimplemented] readonly attribute any upper;
  [Unimplemented] readonly attribute boolean lowerOpen;
  [Unimplemented] readonly attribute boolean upperOpen;

  // Static construction methods:
  [Unimplemented, NewObject] static IDBKeyRange only(any value);
  [Unimplemented, NewObject] static IDBKeyRange lowerBound(any lower, optional boolean open = false);
  [Unimplemented, NewObject] static IDBKeyRange upperBound(any upper, optional boolean open = false);
  [Unimplemented, NewObject] static IDBKeyRange bound(any lower,
                                       any upper,
                                       optional boolean lowerOpen = false,
                                       optional boolean upperOpen = false);

  [Unimplemented] boolean includes(any key);
};
