// https://w3c.github.io/IndexedDB/#request-api

[
  STARFISH_ENABLE_IDB,
  ConstructorCallWith=ExecutionContext,
  Exposed=(Window,Worker),
]
interface IDBOpenDBRequest : IDBRequest {
  // Event handlers:
  [Unimplemented] attribute EventHandler onblocked;
  [Unimplemented] attribute EventHandler onupgradeneeded;
};
