/*
 * Copyright (c) 2018-present Samsung Electronics Co., Ltd
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
 *  USA
 */

#include "StarFishConfig.h"
#include "core/style/Style.h"
#include "core/style/CSSProperty.h"

namespace StarFish {
bool CSSPropertyHelper::isAnimatable(CSSStyleValuePair::KeyKind property)
{
    switch (property) {
    case CSSStyleValuePair::All:
    case CSSStyleValuePair::Background:
    case CSSStyleValuePair::BackgroundColor:
    case CSSStyleValuePair::BackgroundPosition:
    case CSSStyleValuePair::BackgroundPositionX:
    case CSSStyleValuePair::BackgroundPositionY:
    case CSSStyleValuePair::BackgroundSize:
    case CSSStyleValuePair::BorderBottom:
    case CSSStyleValuePair::BorderBottomColor:
    case CSSStyleValuePair::BorderBottomLeftRadius:
    case CSSStyleValuePair::BorderBottomRightRadius:
    case CSSStyleValuePair::BorderBottomWidth:
    case CSSStyleValuePair::BorderColor:
    case CSSStyleValuePair::BorderImageOutset:
    case CSSStyleValuePair::BorderImageSlice:
    case CSSStyleValuePair::BorderImageSource:
    case CSSStyleValuePair::BorderImageWidth:
    case CSSStyleValuePair::BorderLeft:
    case CSSStyleValuePair::BorderLeftColor:
    case CSSStyleValuePair::BorderLeftWidth:
    case CSSStyleValuePair::BorderRight:
    case CSSStyleValuePair::BorderRightColor:
    case CSSStyleValuePair::BorderRightWidth:
    case CSSStyleValuePair::BorderTop:
    case CSSStyleValuePair::BorderTopColor:
    case CSSStyleValuePair::BorderTopLeftRadius:
    case CSSStyleValuePair::BorderTopRightRadius:
    case CSSStyleValuePair::BorderTopWidth:
    case CSSStyleValuePair::Bottom:
    case CSSStyleValuePair::BoxShadow:
    case CSSStyleValuePair::CaretColor:
    case CSSStyleValuePair::Clip:
    case CSSStyleValuePair::Color:
    case CSSStyleValuePair::CX:
    case CSSStyleValuePair::CY:
    case CSSStyleValuePair::D:
    case CSSStyleValuePair::Fill:
    case CSSStyleValuePair::FillOpacity:
    case CSSStyleValuePair::FlexBasis:
    case CSSStyleValuePair::FlexGrow:
    case CSSStyleValuePair::FlexShrink:
    case CSSStyleValuePair::FontSize:
    case CSSStyleValuePair::FontWeight:
    case CSSStyleValuePair::Height:
    case CSSStyleValuePair::Left:
    case CSSStyleValuePair::LetterSpacing:
    case CSSStyleValuePair::LineHeight:
    case CSSStyleValuePair::ListStyleImage:
    case CSSStyleValuePair::MarginBottom:
    case CSSStyleValuePair::MarginLeft:
    case CSSStyleValuePair::MarginRight:
    case CSSStyleValuePair::MarginTop:
    case CSSStyleValuePair::MaxHeight:
    case CSSStyleValuePair::MaxWidth:
    case CSSStyleValuePair::MinHeight:
    case CSSStyleValuePair::MinWidth:
    case CSSStyleValuePair::ObjectPosition:
    case CSSStyleValuePair::Opacity:
    case CSSStyleValuePair::Order:
    case CSSStyleValuePair::OutlineColor:
    case CSSStyleValuePair::OutlineOffset:
    case CSSStyleValuePair::OutlineWidth:
    case CSSStyleValuePair::PaddingBottom:
    case CSSStyleValuePair::PaddingLeft:
    case CSSStyleValuePair::PaddingRight:
    case CSSStyleValuePair::PaddingTop:
    case CSSStyleValuePair::R:
    case CSSStyleValuePair::Right:
    case CSSStyleValuePair::RX:
    case CSSStyleValuePair::RY:
    case CSSStyleValuePair::Stroke:
    case CSSStyleValuePair::StrokeWidth:
    case CSSStyleValuePair::TextDecoration:
    case CSSStyleValuePair::TextDecorationColor:
    case CSSStyleValuePair::TextIndent:
    case CSSStyleValuePair::TextShadow:
    case CSSStyleValuePair::Top:
    case CSSStyleValuePair::Transform:
    case CSSStyleValuePair::TransformOrigin:
    case CSSStyleValuePair::VerticalAlign:
    case CSSStyleValuePair::Visibility:
    case CSSStyleValuePair::Width:
    case CSSStyleValuePair::WordSpacing:
    case CSSStyleValuePair::X:
    case CSSStyleValuePair::Y:
    case CSSStyleValuePair::ZIndex:
        return true;
    default:
        break;
    }
    return false;
}

String* CSSPropertyHelper::toGCString(CSSStyleValuePair::KeyKind property)
{
    return String::createASCIIString(toString(property));
}

const char* CSSPropertyHelper::toString(CSSStyleValuePair::KeyKind property)
{
    switch (property) {
    case CSSStyleValuePair::AlignContent:
        return "align-content";
    case CSSStyleValuePair::AlignItems:
        return "align-items";
    case CSSStyleValuePair::AlignSelf:
        return "align-self";
    case CSSStyleValuePair::All:
        return "all";
    case CSSStyleValuePair::Background:
        return "background";
    case CSSStyleValuePair::BackgroundAttachment:
        return "background-attachment";
    case CSSStyleValuePair::BackgroundClip:
        return "background-clip";
    case CSSStyleValuePair::BackgroundColor:
        return "background-color";
    case CSSStyleValuePair::BackgroundImage:
        return "background-image";
    case CSSStyleValuePair::BackgroundOrigin:
        return "background-origin";
    case CSSStyleValuePair::BackgroundPosition:
        return "background-position";
    case CSSStyleValuePair::BackgroundPositionX:
        return "background-position-x";
    case CSSStyleValuePair::BackgroundPositionY:
        return "background-position-y";
    case CSSStyleValuePair::BackgroundRepeat:
        return "background-repeat";
    case CSSStyleValuePair::BackgroundRepeatX:
        return "background-repeat-x";
    case CSSStyleValuePair::BackgroundRepeatY:
        return "background-repeat-y";
    case CSSStyleValuePair::BackgroundSize:
        return "background-size";
    case CSSStyleValuePair::Border:
        return "border";
    case CSSStyleValuePair::BorderBottom:
        return "border-bottom";
    case CSSStyleValuePair::BorderBottomColor:
        return "border-bottom-color";
    case CSSStyleValuePair::BorderBottomLeftRadius:
        return "border-bottom-left-radius";
    case CSSStyleValuePair::BorderBottomRightRadius:
        return "border-bottom-right-radius";
    case CSSStyleValuePair::BorderBottomStyle:
        return "border-bottom-style";
    case CSSStyleValuePair::BorderBottomWidth:
        return "border-bottom-width";
    case CSSStyleValuePair::BorderCollapse:
        return "border-collapse";
    case CSSStyleValuePair::BorderColor:
        return "border-color";
    case CSSStyleValuePair::BorderImage:
        return "border-image";
    case CSSStyleValuePair::BorderImageOutset:
        return "border-image-outset";
    case CSSStyleValuePair::BorderImageRepeat:
        return "border-image-repeat";
    case CSSStyleValuePair::BorderImageSlice:
        return "border-image-slice";
    case CSSStyleValuePair::BorderImageSource:
        return "border-image-source";
    case CSSStyleValuePair::BorderImageWidth:
        return "border-image-width";
    case CSSStyleValuePair::BorderLeft:
        return "border-left";
    case CSSStyleValuePair::BorderLeftColor:
        return "border-left-color";
    case CSSStyleValuePair::BorderLeftStyle:
        return "border-left-style";
    case CSSStyleValuePair::BorderLeftWidth:
        return "border-left-width";
    case CSSStyleValuePair::BorderRadius:
        return "border-radius";
    case CSSStyleValuePair::BorderRight:
        return "border-right";
    case CSSStyleValuePair::BorderRightColor:
        return "border-right-color";
    case CSSStyleValuePair::BorderRightStyle:
        return "border-right-style";
    case CSSStyleValuePair::BorderRightWidth:
        return "border-right-width";
    case CSSStyleValuePair::BorderSpacing:
        return "border-spacing";
    case CSSStyleValuePair::BorderStyle:
        return "border-style";
    case CSSStyleValuePair::BorderTop:
        return "border-top";
    case CSSStyleValuePair::BorderTopColor:
        return "border-top-color";
    case CSSStyleValuePair::BorderTopLeftRadius:
        return "border-top-left-radius";
    case CSSStyleValuePair::BorderTopRightRadius:
        return "border-top-right-radius";
    case CSSStyleValuePair::BorderTopStyle:
        return "border-top-style";
    case CSSStyleValuePair::BorderTopWidth:
        return "border-top-width";
    case CSSStyleValuePair::BorderWidth:
        return "border-width";
    case CSSStyleValuePair::Bottom:
        return "bottom";
    case CSSStyleValuePair::BoxDecorationBreak:
        return "box-decoration-break";
    case CSSStyleValuePair::BoxShadow:
        return "box-shadow";
    case CSSStyleValuePair::BoxSizing:
        return "box-sizing";
    case CSSStyleValuePair::CaptionSide:
        return "caption-side";
    case CSSStyleValuePair::CaretColor:
        return "caret-color";
    case CSSStyleValuePair::Clear:
        return "clear";
    case CSSStyleValuePair::Clip:
        return "clip";
    case CSSStyleValuePair::Color:
        return "color";
    case CSSStyleValuePair::Content:
        return "content";
    case CSSStyleValuePair::CounterIncrement:
        return "counter-increment";
    case CSSStyleValuePair::CounterReset:
        return "counter-reset";
    case CSSStyleValuePair::Cursor:
        return "cursor";
    case CSSStyleValuePair::CX:
        return "cx";
    case CSSStyleValuePair::CY:
        return "cy";
    case CSSStyleValuePair::D:
        return "d";
    case CSSStyleValuePair::Direction:
        return "direction";
    case CSSStyleValuePair::Display:
        return "display";
    case CSSStyleValuePair::EmptyCells:
        return "empty-cells";
    case CSSStyleValuePair::Fill:
        return "fill";
    case CSSStyleValuePair::FillOpacity:
        return "fill-opacity";
    case CSSStyleValuePair::FillRule:
        return "fill-rule";
    case CSSStyleValuePair::Flex:
        return "flex";
    case CSSStyleValuePair::FlexBasis:
        return "flex-basis";
    case CSSStyleValuePair::FlexDirection:
        return "flex-direction";
    case CSSStyleValuePair::FlexFlow:
        return "flex-flow";
    case CSSStyleValuePair::FlexGrow:
        return "flex-grow";
    case CSSStyleValuePair::FlexShrink:
        return "flex-shrink";
    case CSSStyleValuePair::FlexWrap:
        return "flex-wrap";
    case CSSStyleValuePair::Float:
        return "float";
    case CSSStyleValuePair::Font:
        return "font";
    case CSSStyleValuePair::FontFamily:
        return "font-family";
    case CSSStyleValuePair::FontKerning:
        return "font-kerning";
    case CSSStyleValuePair::FontSize:
        return "font-size";
    case CSSStyleValuePair::FontStyle:
        return "font-style";
    case CSSStyleValuePair::FontWeight:
        return "font-weight";
    case CSSStyleValuePair::GridArea:
        return "grid-area";
    case CSSStyleValuePair::GridColumnEnd:
        return "grid-column-end";
    case CSSStyleValuePair::GridColumnGap:
        return "grid-column-gap";
    case CSSStyleValuePair::GridColumnStart:
        return "grid-column-start";
    case CSSStyleValuePair::GridGap:
        return "grid-gap";
    case CSSStyleValuePair::GridRowEnd:
        return "grid-row-end";
    case CSSStyleValuePair::GridRowGap:
        return "grid-row-gap";
    case CSSStyleValuePair::GridRowStart:
        return "grid-row-start";
    case CSSStyleValuePair::GridTemplateAreas:
        return "grid-template-areas";
    case CSSStyleValuePair::GridTemplateColumns:
        return "grid-template-columns";
    case CSSStyleValuePair::GridTemplateRows:
        return "grid-template-rows";
    case CSSStyleValuePair::GridRow:
        return "grid-row";
    case CSSStyleValuePair::GridColumn:
        return "grid-column";
    case CSSStyleValuePair::Height:
        return "height";
    case CSSStyleValuePair::Hyphens:
        return "hyphens";
    case CSSStyleValuePair::ImageRendering:
        return "image-rendering";
    case CSSStyleValuePair::JustifyContent:
        return "justify-content";
    case CSSStyleValuePair::Left:
        return "left";
    case CSSStyleValuePair::LetterSpacing:
        return "letter-spacing";
    case CSSStyleValuePair::LineBreak:
        return "line-break";
    case CSSStyleValuePair::LineHeight:
        return "line-height";
    case CSSStyleValuePair::ListStyle:
        return "list-style";
    case CSSStyleValuePair::ListStyleImage:
        return "list-style-image";
    case CSSStyleValuePair::ListStylePosition:
        return "list-style-position";
    case CSSStyleValuePair::ListStyleType:
        return "list-style-type";
    case CSSStyleValuePair::Margin:
        return "margin";
    case CSSStyleValuePair::MarginBottom:
        return "margin-bottom";
    case CSSStyleValuePair::MarginLeft:
        return "margin-left";
    case CSSStyleValuePair::MarginRight:
        return "margin-right";
    case CSSStyleValuePair::MarginTop:
        return "margin-top";
    case CSSStyleValuePair::MaskImage:
        return "mask-image";
    case CSSStyleValuePair::MaskSize:
        return "mask-size";
    case CSSStyleValuePair::MaxHeight:
        return "max-height";
    case CSSStyleValuePair::MaxWidth:
        return "max-width";
    case CSSStyleValuePair::MinHeight:
        return "min-height";
    case CSSStyleValuePair::MinWidth:
        return "min-width";
    case CSSStyleValuePair::ObjectFit:
        return "object-fit";
    case CSSStyleValuePair::ObjectPosition:
        return "object-position";
    case CSSStyleValuePair::Opacity:
        return "opacity";
    case CSSStyleValuePair::Order:
        return "order";
    case CSSStyleValuePair::Outline:
        return "outline";
    case CSSStyleValuePair::OutlineColor:
        return "outline-color";
    case CSSStyleValuePair::OutlineOffset:
        return "outline-offset";
    case CSSStyleValuePair::OutlineStyle:
        return "outline-style";
    case CSSStyleValuePair::OutlineWidth:
        return "outline-width";
    case CSSStyleValuePair::Overflow:
        return "overflow";
    case CSSStyleValuePair::OverflowWrap:
        return "overflow-wrap";
    case CSSStyleValuePair::OverflowX:
        return "overflow-x";
    case CSSStyleValuePair::OverflowY:
        return "overflow-y";
    case CSSStyleValuePair::Padding:
        return "padding";
    case CSSStyleValuePair::PaddingBottom:
        return "padding-bottom";
    case CSSStyleValuePair::PaddingLeft:
        return "padding-left";
    case CSSStyleValuePair::PaddingRight:
        return "padding-right";
    case CSSStyleValuePair::PaddingTop:
        return "padding-top";
    case CSSStyleValuePair::PointerEvents:
        return "pointer-events";
    case CSSStyleValuePair::Position:
        return "position";
    case CSSStyleValuePair::R:
        return "r";
    case CSSStyleValuePair::Resize:
        return "resize";
    case CSSStyleValuePair::Right:
        return "right";
    case CSSStyleValuePair::RX:
        return "rx";
    case CSSStyleValuePair::RY:
        return "ry";
    case CSSStyleValuePair::Src:
        return "src";
    case CSSStyleValuePair::Stroke:
        return "stroke";
    case CSSStyleValuePair::StrokeWidth:
        return "stroke-width";
    case CSSStyleValuePair::TableLayout:
        return "table-layout";
    case CSSStyleValuePair::TextAlign:
        return "text-align";
    case CSSStyleValuePair::TextDecoration:
        return "text-decoration";
    case CSSStyleValuePair::TextDecorationColor:
        return "text-decoration-color";
    case CSSStyleValuePair::TextDecorationLine:
        return "text-decoration-line";
    case CSSStyleValuePair::TextDecorationStyle:
        return "text-decoration-style";
    case CSSStyleValuePair::TextIndent:
        return "text-indent";
    case CSSStyleValuePair::TextOverflow:
        return "text-overflow";
    case CSSStyleValuePair::TextShadow:
        return "text-shadow";
    case CSSStyleValuePair::TextTransform:
        return "text-transform";
    case CSSStyleValuePair::TextUnderlinePosition:
        return "text-underline-position";
    case CSSStyleValuePair::Top:
        return "top";
    case CSSStyleValuePair::Transform:
        return "transform";
    case CSSStyleValuePair::TransformOrigin:
        return "transform-origin";
    case CSSStyleValuePair::Transition:
        return "transition";
    case CSSStyleValuePair::TransitionDelay:
        return "transition-delay";
    case CSSStyleValuePair::TransitionDuration:
        return "transition-duration";
    case CSSStyleValuePair::TransitionProperty:
        return "transition-property";
    case CSSStyleValuePair::TransitionTimingFunction:
        return "transition-timing-function";
    case CSSStyleValuePair::UnicodeBidi:
        return "unicode-bidi";
    case CSSStyleValuePair::UserSelect:
        return "user-select";
    case CSSStyleValuePair::VerticalAlign:
        return "vertical-align";
    case CSSStyleValuePair::Visibility:
        return "visibility";
    case CSSStyleValuePair::WhiteSpace:
        return "white-space";
    case CSSStyleValuePair::Width:
        return "width";
    case CSSStyleValuePair::WillChange:
        return "will-change";
    case CSSStyleValuePair::WordBreak:
        return "word-break";
    case CSSStyleValuePair::WordSpacing:
        return "word-spacing";
    case CSSStyleValuePair::WordWrap:
        return "word-wrap";
    case CSSStyleValuePair::X:
        return "x";
    case CSSStyleValuePair::Y:
        return "y";
    case CSSStyleValuePair::ZIndex:
        return "z-index";
    // Non CSS property
    case CSSStyleValuePair::CustomProperty:
    case CSSStyleValuePair::KeyKindSize:
    case CSSStyleValuePair::Unknown:
    case CSSStyleValuePair::VarValue:
        break;
    }
    return "";
}

String* CSSPropertyHelper::toCamelCaseGCString(
    CSSStyleValuePair::KeyKind property)
{
    return String::createASCIIString(toCamelCaseString(property));
}

const char* CSSPropertyHelper::toCamelCaseString(
    CSSStyleValuePair::KeyKind property)
{
    switch (property) {
    case CSSStyleValuePair::AlignContent:
        return "alignContent";
    case CSSStyleValuePair::AlignItems:
        return "alignItems";
    case CSSStyleValuePair::AlignSelf:
        return "alignSelf";
    case CSSStyleValuePair::All:
        return "all";
    case CSSStyleValuePair::Background:
        return "background";
    case CSSStyleValuePair::BackgroundAttachment:
        return "backgroundAttachment";
    case CSSStyleValuePair::BackgroundClip:
        return "backgroundClip";
    case CSSStyleValuePair::BackgroundColor:
        return "backgroundColor";
    case CSSStyleValuePair::BackgroundImage:
        return "backgroundImage";
    case CSSStyleValuePair::BackgroundOrigin:
        return "backgroundOrigin";
    case CSSStyleValuePair::BackgroundPosition:
        return "backgroundPosition";
    case CSSStyleValuePair::BackgroundPositionX:
        return "backgroundPositionX";
    case CSSStyleValuePair::BackgroundPositionY:
        return "backgroundPositionY";
    case CSSStyleValuePair::BackgroundRepeat:
        return "backgroundRepeat";
    case CSSStyleValuePair::BackgroundRepeatX:
        return "backgroundRepeatX";
    case CSSStyleValuePair::BackgroundRepeatY:
        return "backgroundRepeatY";
    case CSSStyleValuePair::BackgroundSize:
        return "backgroundSize";
    case CSSStyleValuePair::Border:
        return "border";
    case CSSStyleValuePair::BorderBottom:
        return "borderBottom";
    case CSSStyleValuePair::BorderBottomColor:
        return "borderBottomColor";
    case CSSStyleValuePair::BorderBottomLeftRadius:
        return "borderBottomLeftRadius";
    case CSSStyleValuePair::BorderBottomRightRadius:
        return "borderBottomRightRadius";
    case CSSStyleValuePair::BorderBottomStyle:
        return "borderBottomStyle";
    case CSSStyleValuePair::BorderBottomWidth:
        return "borderBottomWidth";
    case CSSStyleValuePair::BorderCollapse:
        return "borderCollapse";
    case CSSStyleValuePair::BorderColor:
        return "borderColor";
    case CSSStyleValuePair::BorderImage:
        return "borderImage";
    case CSSStyleValuePair::BorderImageOutset:
        return "borderImageOutset";
    case CSSStyleValuePair::BorderImageRepeat:
        return "borderImageRepeat";
    case CSSStyleValuePair::BorderImageSlice:
        return "borderImageSlice";
    case CSSStyleValuePair::BorderImageSource:
        return "borderImageSource";
    case CSSStyleValuePair::BorderImageWidth:
        return "borderImageWidth";
    case CSSStyleValuePair::BorderLeft:
        return "borderLeft";
    case CSSStyleValuePair::BorderLeftColor:
        return "borderLeftColor";
    case CSSStyleValuePair::BorderLeftStyle:
        return "borderLeftStyle";
    case CSSStyleValuePair::BorderLeftWidth:
        return "borderLeftWidth";
    case CSSStyleValuePair::BorderRadius:
        return "borderRadius";
    case CSSStyleValuePair::BorderRight:
        return "borderRight";
    case CSSStyleValuePair::BorderRightColor:
        return "borderRightColor";
    case CSSStyleValuePair::BorderRightStyle:
        return "borderRightStyle";
    case CSSStyleValuePair::BorderRightWidth:
        return "borderRightWidth";
    case CSSStyleValuePair::BorderSpacing:
        return "borderSpacing";
    case CSSStyleValuePair::BorderStyle:
        return "borderStyle";
    case CSSStyleValuePair::BorderTop:
        return "borderTop";
    case CSSStyleValuePair::BorderTopColor:
        return "borderTopColor";
    case CSSStyleValuePair::BorderTopLeftRadius:
        return "borderTopLeftRadius";
    case CSSStyleValuePair::BorderTopRightRadius:
        return "borderTopRightRadius";
    case CSSStyleValuePair::BorderTopStyle:
        return "borderTopStyle";
    case CSSStyleValuePair::BorderTopWidth:
        return "borderTopWidth";
    case CSSStyleValuePair::BorderWidth:
        return "borderWidth";
    case CSSStyleValuePair::Bottom:
        return "bottom";
    case CSSStyleValuePair::BoxDecorationBreak:
        return "boxDecorationBreak";
    case CSSStyleValuePair::BoxShadow:
        return "boxShadow";
    case CSSStyleValuePair::BoxSizing:
        return "boxSizing";
    case CSSStyleValuePair::CaptionSide:
        return "captionSide";
    case CSSStyleValuePair::CaretColor:
        return "caretColor";
    case CSSStyleValuePair::Clear:
        return "clear";
    case CSSStyleValuePair::Clip:
        return "clip";
    case CSSStyleValuePair::Color:
        return "color";
    case CSSStyleValuePair::Content:
        return "content";
    case CSSStyleValuePair::CounterIncrement:
        return "counterIncrement";
    case CSSStyleValuePair::CounterReset:
        return "counterReset";
    case CSSStyleValuePair::Cursor:
        return "cursor";
    case CSSStyleValuePair::CX:
        return "cx";
    case CSSStyleValuePair::CY:
        return "cy";
    case CSSStyleValuePair::D:
        return "d";
    case CSSStyleValuePair::Direction:
        return "direction";
    case CSSStyleValuePair::Display:
        return "display";
    case CSSStyleValuePair::EmptyCells:
        return "emptyCells";
    case CSSStyleValuePair::Fill:
        return "fill";
    case CSSStyleValuePair::FillOpacity:
        return "fillOpacity";
    case CSSStyleValuePair::FillRule:
        return "fillRule";
    case CSSStyleValuePair::Flex:
        return "flex";
    case CSSStyleValuePair::FlexBasis:
        return "flexBasis";
    case CSSStyleValuePair::FlexDirection:
        return "flexDirection";
    case CSSStyleValuePair::FlexFlow:
        return "flexFlow";
    case CSSStyleValuePair::FlexGrow:
        return "flexGrow";
    case CSSStyleValuePair::FlexShrink:
        return "flexShrink";
    case CSSStyleValuePair::FlexWrap:
        return "flexWrap";
    case CSSStyleValuePair::Float:
        return "float";
    case CSSStyleValuePair::Font:
        return "font";
    case CSSStyleValuePair::FontFamily:
        return "fontFamily";
    case CSSStyleValuePair::FontKerning:
        return "fontKerning";
    case CSSStyleValuePair::FontSize:
        return "fontSize";
    case CSSStyleValuePair::FontStyle:
        return "fontStyle";
    case CSSStyleValuePair::FontWeight:
        return "fontWeight";
    case CSSStyleValuePair::GridArea:
        return "gridArea";
    case CSSStyleValuePair::GridColumnEnd:
        return "gridColumnEnd";
    case CSSStyleValuePair::GridColumnGap:
        return "gridColumnGap";
    case CSSStyleValuePair::GridColumnStart:
        return "gridColumnStart";
    case CSSStyleValuePair::GridGap:
        return "gridGap";
    case CSSStyleValuePair::GridRow:
        return "gridRow";
    case CSSStyleValuePair::GridColumn:
        return "gridColumn";
    case CSSStyleValuePair::GridRowEnd:
        return "gridRowEnd";
    case CSSStyleValuePair::GridRowGap:
        return "gridRowGap";
    case CSSStyleValuePair::GridRowStart:
        return "gridRowStart";
    case CSSStyleValuePair::GridTemplateAreas:
        return "gridTemplateAreas";
    case CSSStyleValuePair::GridTemplateColumns:
        return "gridTemplateColumns";
    case CSSStyleValuePair::GridTemplateRows:
        return "gridTemplateRows";
    case CSSStyleValuePair::Height:
        return "height";
    case CSSStyleValuePair::Hyphens:
        return "hyphens";
    case CSSStyleValuePair::ImageRendering:
        return "imageRendering";
    case CSSStyleValuePair::JustifyContent:
        return "justifyContent";
    case CSSStyleValuePair::Left:
        return "left";
    case CSSStyleValuePair::LetterSpacing:
        return "letterSpacing";
    case CSSStyleValuePair::LineBreak:
        return "lineBreak";
    case CSSStyleValuePair::LineHeight:
        return "lineHeight";
    case CSSStyleValuePair::ListStyle:
        return "listStyle";
    case CSSStyleValuePair::ListStyleImage:
        return "listStyleImage";
    case CSSStyleValuePair::ListStylePosition:
        return "listStylePosition";
    case CSSStyleValuePair::ListStyleType:
        return "listStyleType";
    case CSSStyleValuePair::Margin:
        return "margin";
    case CSSStyleValuePair::MarginBottom:
        return "marginBottom";
    case CSSStyleValuePair::MarginLeft:
        return "marginLeft";
    case CSSStyleValuePair::MarginRight:
        return "marginRight";
    case CSSStyleValuePair::MarginTop:
        return "marginTop";
    case CSSStyleValuePair::MaskImage:
        return "maskImage";
    case CSSStyleValuePair::MaskSize:
        return "maskSize";
    case CSSStyleValuePair::MaxHeight:
        return "maxHeight";
    case CSSStyleValuePair::MaxWidth:
        return "maxWidth";
    case CSSStyleValuePair::MinHeight:
        return "minHeight";
    case CSSStyleValuePair::MinWidth:
        return "minWidth";
    case CSSStyleValuePair::ObjectFit:
        return "objectFit";
    case CSSStyleValuePair::ObjectPosition:
        return "objectPosition";
    case CSSStyleValuePair::Opacity:
        return "opacity";
    case CSSStyleValuePair::Order:
        return "order";
    case CSSStyleValuePair::Outline:
        return "outline";
    case CSSStyleValuePair::OutlineColor:
        return "outlineColor";
    case CSSStyleValuePair::OutlineOffset:
        return "outlineOffset";
    case CSSStyleValuePair::OutlineStyle:
        return "outlineStyle";
    case CSSStyleValuePair::OutlineWidth:
        return "outlineWidth";
    case CSSStyleValuePair::Overflow:
        return "overflow";
    case CSSStyleValuePair::OverflowWrap:
        return "overflowWrap";
    case CSSStyleValuePair::OverflowX:
        return "overflowX";
    case CSSStyleValuePair::OverflowY:
        return "overflowY";
    case CSSStyleValuePair::Padding:
        return "padding";
    case CSSStyleValuePair::PaddingBottom:
        return "paddingBottom";
    case CSSStyleValuePair::PaddingLeft:
        return "paddingLeft";
    case CSSStyleValuePair::PaddingRight:
        return "paddingRight";
    case CSSStyleValuePair::PaddingTop:
        return "paddingTop";
    case CSSStyleValuePair::PointerEvents:
        return "pointerEvents";
    case CSSStyleValuePair::Position:
        return "position";
    case CSSStyleValuePair::R:
        return "r";
    case CSSStyleValuePair::Resize:
        return "resize";
    case CSSStyleValuePair::Right:
        return "right";
    case CSSStyleValuePair::RX:
        return "rx";
    case CSSStyleValuePair::RY:
        return "ry";
    case CSSStyleValuePair::Src:
        return "src";
    case CSSStyleValuePair::Stroke:
        return "stroke";
    case CSSStyleValuePair::StrokeWidth:
        return "strokeWidth";
    case CSSStyleValuePair::TableLayout:
        return "tableLayout";
    case CSSStyleValuePair::TextAlign:
        return "textAlign";
    case CSSStyleValuePair::TextDecoration:
        return "textDecoration";
    case CSSStyleValuePair::TextDecorationColor:
        return "textDecorationColor";
    case CSSStyleValuePair::TextDecorationLine:
        return "textDecorationLine";
    case CSSStyleValuePair::TextDecorationStyle:
        return "textDecorationStyle";
    case CSSStyleValuePair::TextIndent:
        return "textIndent";
    case CSSStyleValuePair::TextOverflow:
        return "textOverflow";
    case CSSStyleValuePair::TextShadow:
        return "textShadow";
    case CSSStyleValuePair::TextTransform:
        return "textTransform";
    case CSSStyleValuePair::TextUnderlinePosition:
        return "textUnderlinePosition";
    case CSSStyleValuePair::Top:
        return "top";
    case CSSStyleValuePair::Transform:
        return "transform";
    case CSSStyleValuePair::TransformOrigin:
        return "transformOrigin";
    case CSSStyleValuePair::Transition:
        return "transition";
    case CSSStyleValuePair::TransitionDelay:
        return "transitionDelay";
    case CSSStyleValuePair::TransitionDuration:
        return "transitionDuration";
    case CSSStyleValuePair::TransitionProperty:
        return "transitionProperty";
    case CSSStyleValuePair::TransitionTimingFunction:
        return "transitionTimingFunction";
    case CSSStyleValuePair::UnicodeBidi:
        return "unicodeBidi";
    case CSSStyleValuePair::UserSelect:
        return "userSelect";
    case CSSStyleValuePair::VerticalAlign:
        return "verticalAlign";
    case CSSStyleValuePair::Visibility:
        return "visibility";
    case CSSStyleValuePair::WhiteSpace:
        return "whiteSpace";
    case CSSStyleValuePair::Width:
        return "width";
    case CSSStyleValuePair::WillChange:
        return "willChange";
    case CSSStyleValuePair::WordBreak:
        return "wordBreak";
    case CSSStyleValuePair::WordSpacing:
        return "wordSpacing";
    case CSSStyleValuePair::WordWrap:
        return "wordWrap";
    case CSSStyleValuePair::X:
        return "x";
    case CSSStyleValuePair::Y:
        return "y";
    case CSSStyleValuePair::ZIndex:
        return "zIndex";
    // Non CSS property
    case CSSStyleValuePair::CustomProperty:
    case CSSStyleValuePair::KeyKindSize:
    case CSSStyleValuePair::Unknown:
    case CSSStyleValuePair::VarValue:
        break;
    }
    return "";
}
}
