// https://drafts.csswg.org/cssom/#the-cssstylesheet-interface

[ Exposed=Window,
  Constructor(optional CSSStyleSheetInit options),
  ConstructorCallWith=ExecutionContext ]
interface CSSStyleSheet : StyleSheet {
    // constructor(optional CSSStyleSheetInit options = {});

    readonly attribute CSSRule? ownerRule;
    [SameObject] readonly attribute CSSRuleList cssRules;
    [SameObject] readonly attribute CSSRuleList rules;
    [RaisesException] unsigned long insertRule(CSSOMString rule, optional unsigned long index = 0);
    [RaisesException] void deleteRule(unsigned long index);

    [Unimplemented] Promise<CSSStyleSheet> replace(USVString text);
    [Unimplemented] undefined replaceSync(USVString text);
};

dictionary CSSStyleSheetInit {
  DOMString? baseURL = null;
  (MediaList or DOMString) media = "";
  boolean disabled = false;
};
