// https://drafts.css-houdini.org/css-typed-om/#cssunitvalue
[
 Constructor(double value, CSSOMString unit),
 ConstructorCallWith=ExecutionContext,
 RaisesException=Constructor,
 Exposed=(Window, Worker, PaintWorklet, LayoutWorklet)
] interface CSSUnitValue : CSSNumericValue {
  attribute double value;
  readonly attribute CSSOMString unit;
};

