// https://drafts.csswg.org/css-font-loading/#fontfaceset-interface

enum FontFaceSetLoadStatus { "loading", "loaded" };

[Exposed=Window]
interface FontFaceSet : EventTarget {
  readonly attribute FontFaceSetLoadStatus status;
  readonly attribute Promise<FontFaceSet> ready;

  [RaisesException] boolean check(DOMString font, optional DOMString text = " ");

  attribute EventHandler onloading;
  attribute EventHandler onloadingdone;
  attribute EventHandler onloadingerror;
};
