// https://html.spec.whatwg.org/multipage/browsers.html#location
// NOTE Using DOMString instead of USVString

interface Location {

  [Unforgeable, CrossOrigin=Getter] stringifier attribute DOMString href;
  [Unforgeable, CrossOrigin] readonly attribute DOMString origin;
  [Unforgeable, CrossOrigin] attribute DOMString protocol;
  [Unforgeable, CrossOrigin] attribute DOMString host;
  [Unforgeable, CrossOrigin] attribute DOMString hostname;
  [Unforgeable, CrossOrigin] attribute DOMString port;
  [Unforgeable, CrossOrigin] attribute DOMString pathname;
  [Unforgeable, CrossOrigin] attribute DOMString search;
  [Unforgeable, CrossOrigin] attribute DOMString hash;

  [Unforgeable, CrossOrigin] void assign(DOMString url);
  [Unforgeable] void replace(DOMString url);
  [Unforgeable, CrossOrigin] void reload();

  [Unimplemented, Unforgeable, SameObject] readonly attribute DOMStringList ancestorOrigins;
};
