// https://html.spec.whatwg.org/#the-navigator-object

[
  PartialInterface,
  NoInterfaceObject
] interface NavigatorCookies {
  readonly attribute boolean cookieEnabled;
};

[
  PartialInterface,
  NoInterfaceObject,
  Exposed=(Window,Worker),
] interface NavigatorLanguage {
  readonly attribute DOMString language;
  [Unimplemented] readonly attribute DOMString[] languages;
};

[
  PartialInterface
] interface NavigatorOnLine {
  readonly attribute boolean onLine;
};

interface Navigator {
  // Partial
  // https://dev.w3.org/geo/api/spec-source.html#navi-geo
  readonly attribute Geolocation geolocation;
};

Navigator implements NavigatorID;
Navigator implements NavigatorLanguage;
Navigator implements NavigatorOnLine;
Navigator implements NavigatorContentUtils;
Navigator implements NavigatorCookies;
Navigator implements NavigatorPlugins;
Navigator implements NavigatorConcurrentHardware;
