// https://html.spec.whatwg.org/#windoworworkerglobalscope

typedef (DOMString or Function) TimerHandler;

[STARFISH_ENABLE_CANVAS]
typedef (CanvasImageSource or
         Blob or
         ImageData) ImageBitmapSource;

[PartialInterface,
 NoInterfaceObject,
 Exposed=(Window,Worker)]
interface WindowOrWorkerGlobalScope {
  [Unimplemented, Replaceable] readonly attribute USVString origin;

  // base64 utility methods
  [CallWith=ExecutionContext,RaisesException] DOMString btoa(DOMString data);
  [CallWith=ExecutionContext,RaisesException] DOMString atob(DOMString data);

  // timers
  [Custom] long setTimeout(TimerHandler handler, optional long timeout = 0, any... arguments);
  void clearTimeout(optional long handle = 0);
  [Custom] long setInterval(TimerHandler handler, optional long timeout = 0, any... arguments);
  void clearInterval(optional long handle = 0);

  // microtask queuing
  // Original: undefined queueMicrotask(VoidFunction callback);
  [CallWith=ExecutionContext,RaisesException] void queueMicrotask(Function callback);

  // ImageBitmap
  [STARFISH_ENABLE_CANVAS, CallWith=ExecutionContext, RaisesException] Promise<ImageBitmap> createImageBitmap(ImageBitmapSource image, optional ImageBitmapOptions options);
  [STARFISH_ENABLE_CANVAS, CallWith=ExecutionContext, RaisesException] Promise<ImageBitmap> createImageBitmap(ImageBitmapSource image, long sx, long sy, long sw, long sh, optional ImageBitmapOptions options);
};
