// https://html.spec.whatwg.org/#the-window-object
// NOTE Using DOMString instead of USVString

enum ScrollBehavior { "auto", "instant", "smooth" };

dictionary ScrollOptions {
    ScrollBehavior behavior = "auto";
};
dictionary ScrollToOptions : ScrollOptions {
    unrestricted double left;
    unrestricted double top;
};

[PrimaryGlobal, LegacyUnenumerableNamedProperties, CustomDescriptor, Exposed=Window]
interface Window : EventTarget {
  // the current browsing context
  // NOTE WindowProxy -> Window
  [Unforgeable, CrossOrigin] readonly attribute Window window;
  // `self` is Implemented in virtual id
  // [Replaceable] readonly attribute WindowProxy self;
  [Unforgeable, CrossOrigin] readonly attribute Document document;
  [CrossOrigin] attribute DOMString name;
  [PutForwards=href, Unforgeable] readonly attribute Location location;
  [CrossOrigin] readonly attribute History history;
  [Unimplemented] readonly attribute CustomElementRegistry customElements;
  [Unimplemented, Replaceable] readonly attribute BarProp locationbar;
  [Unimplemented, Replaceable] readonly attribute BarProp menubar;
  [Unimplemented, Replaceable] readonly attribute BarProp personalbar;
  [Unimplemented, Replaceable] readonly attribute BarProp scrollbars;
  [Unimplemented, Replaceable] readonly attribute BarProp statusbar;
  [Unimplemented, Replaceable] readonly attribute BarProp toolbar;
  [Unimplemented] attribute DOMString status;
  [Unimplemented] void close();
  [Unimplemented] readonly attribute boolean closed;
  [Unimplemented] void stop();
  void focus();
  void blur();
  // `event` is Implemented in virtual id
  // [STARFISH_ENABLE_OBSOLETE_SPEC, Replaceable] readonly attribute Event? event;

  // other browsing contexts
  // NOTE WindowProxy -> Window
  [Replaceable, CrossOrigin=Setter] readonly attribute Window frames;
  [Replaceable, CrossOrigin=Setter] readonly attribute unsigned long length;

  // NOTE WindowProxy -> Window
  [Unforgeable, CrossOrigin=Setter] readonly attribute Window? top;
  [Unimplemented] attribute any opener;
  // NOTE WindowProxy -> Window
  [Replaceable, CrossOrigin=Setter] readonly attribute Window? parent;
  readonly attribute Element? frameElement;
  [Unimplemented] WindowProxy? open(optional DOMString url = "about:blank", optional DOMString target = "_blank", [TreatNullAs=EmptyString] optional DOMString features = "");
  [Unimplemented, NotEnumerable] getter object (DOMString name);
  [Unimplemented, NotEnumerable] getter Window (unsigned long index);

  // the user agent
  [CrossOrigin] readonly attribute Navigator navigator;
  [Unimplemented] readonly attribute ApplicationCache applicationCache;

  // user prompts
  [CrossOrigin] void alert();
  [CrossOrigin] void alert(DOMString message);
  [Unimplemented] boolean confirm(optional DOMString message = "");
  [Unimplemented] DOMString? prompt(optional DOMString message = "", optional DOMString default = "");
  [Unimplemented] void print();

  [Custom] unsigned long requestAnimationFrame(FrameRequestCallback callback);
  [CrossOrigin] void cancelAnimationFrame(unsigned long handle);

  // NOTE transfer: sequence<object> -> sequence<any>
  [Custom, RaisesException] void postMessage(any message, DOMString targetOrigin, optional sequence<any> transfer);

  // https://html.spec.whatwg.org/#Window-partial
  [Unimplemented] void captureEvents();
  [Unimplemented] void releaseEvents();

  [Unimplemented, Replaceable, SameObject] readonly attribute External external;

  // https://drafts.csswg.org/cssom/#extensions-to-the-window-interface
  [NewObject, CrossOrigin] CSSStyleDeclaration getComputedStyle(Element elt, optional CSSOMString? pseudoElt);

  // https://drafts.csswg.org/cssom-view/#extensions-to-the-window-interface
  [NewObject, CrossOrigin] MediaQueryList matchMedia(CSSOMString query);
  [SameObject, Replaceable, CrossOrigin] readonly attribute Screen screen;

  // browsing context
  [Unimplemented] void moveTo(long x, long y);
  [Unimplemented] void moveBy(long x, long y);
  [Unimplemented] void resizeTo(long x, long y);
  [Unimplemented] void resizeBy(long x, long y);

  // viewport
  [Replaceable, CrossOrigin] readonly attribute long innerWidth;
  [Replaceable, CrossOrigin] readonly attribute long innerHeight;

  // viewport scrolling
  [Replaceable, CrossOrigin] readonly attribute double scrollX;
  [Replaceable, CrossOrigin] readonly attribute double pageXOffset;
  [Replaceable, CrossOrigin] readonly attribute double scrollY;
  [Replaceable, CrossOrigin] readonly attribute double pageYOffset;
  [CrossOrigin] void scroll(optional ScrollToOptions options);
  [CrossOrigin] void scroll(unrestricted double x, unrestricted double y);
  [CrossOrigin] void scrollTo(optional ScrollToOptions options);
  [CrossOrigin] void scrollTo(unrestricted double x, unrestricted double y);
  [Unimplemented] void scrollBy(optional ScrollToOptions options);
  [Unimplemented] void scrollBy(unrestricted double x, unrestricted double y);

  // client
  [Unimplemented, Replaceable] readonly attribute long screenX;
  [Unimplemented, Replaceable] readonly attribute long screenY;
  [Unimplemented, Replaceable] readonly attribute long outerWidth;
  [Unimplemented, Replaceable] readonly attribute long outerHeight;
  [Replaceable, CrossOrigin] readonly attribute double devicePixelRatio;
};

Window implements GlobalEventHandlers;
Window implements WindowEventHandlers;

callback FrameRequestCallback = void (DOMHighResTimeStamp time);

Window implements WindowOrWorkerGlobalScope;

// https://html.spec.whatwg.org/#windowlocalstorage
[PartialInterface,
 NoInterfaceObject]
interface WindowLocalStorage {
  readonly attribute Storage localStorage;
};
Window implements WindowLocalStorage;

// https://html.spec.whatwg.org/#windowsessionstorage
[PartialInterface,
 NoInterfaceObject]
interface WindowSessionStorage {
  readonly attribute Storage sessionStorage;
};
Window implements WindowSessionStorage;


