[Exposed=Window,STARFISH_ENABLE_TEST]
interface testRunner {
  static void dumpAsText();
  static void waitUntilDone();
  static void notifyDone();

  [Unimplemented] static void abortModal();
  [Unimplemented] static void addDisallowedURL();
  [Unimplemented] static void setMockCredentialManagerError();
  [Unimplemented] static void setMockCredentialManagerResponse();
  [Unimplemented] static void clearMockCredentialManagerResponse();
  [Unimplemented] static void addMockSpeechRecognitionResult();
  [Unimplemented] static void addOriginAccessWhitelistEntry();
  [Unimplemented] static void addWebPageOverlay();
  [Unimplemented] static void callShouldCloseOnWebView();
  [Unimplemented] static void capturePixelsAsyncThen();
  [Unimplemented] static void clearAllDatabases();
  [Unimplemented] static void clearBackForwardList();
  [Unimplemented] static void clearPrinting();
  [Unimplemented] static void closeWebInspector();
  [Unimplemented] static void copyImageAtAndCapturePixelsAsyncThen();
  [Unimplemented] static void didAcquirePointerLock();
  [Unimplemented] static void didLosePointerLock();
  [Unimplemented] static void didNotAcquirePointerLock();
  [Unimplemented] static void disableAutoResizeMode();
  [Unimplemented] static void disableMockScreenOrientation();
  [Unimplemented] static void setDisallowedSubresourcePathSuffixes();
  [Unimplemented] static void dispatchBeforeInstallPromptEvent();
  [Unimplemented] static void dumpAsMarkup();
  [Unimplemented] static void dumpAsText();
  [Unimplemented] static void dumpAsTextWithPixelResults();
  [Unimplemented] static void dumpBackForwardList();
  [Unimplemented] static void dumpChildFrameScrollPositions();
  [Unimplemented] static void dumpChildFramesAsMarkup();
  [Unimplemented] static void dumpChildFramesAsText();
  [Unimplemented] static void dumpCreateView();
  [Unimplemented] static void dumpDatabaseCallbacks();
  [Unimplemented] static void dumpDragImage();
  [Unimplemented] static void dumpEditingCallbacks();
  [Unimplemented] static void dumpFrameLoadCallbacks();
  [Unimplemented] static void dumpIconChanges();
  [Unimplemented] static void dumpNavigationPolicy();
  [Unimplemented] static void dumpPageImportanceSignals();
  [Unimplemented] static void dumpPermissionClientCallbacks();
  [Unimplemented] static void dumpPingLoaderCallbacks();
  [Unimplemented] static void dumpResourceLoadCallbacks();
  [Unimplemented] static void dumpResourceResponseMIMETypes();
  [Unimplemented] static void dumpSelectionRect();
  [Unimplemented] static void dumpSpellCheckCallbacks();
  [Unimplemented] static void dumpStatusCallbacks();
  [Unimplemented] static void dumpTitleChanges();
  [Unimplemented] static void dumpUserGestureInFrameLoadCallbacks();
  [Unimplemented] static void enableAutoResizeMode();
  [Unimplemented] static void enableUseZoomForDSF();
  [Unimplemented] static void evaluateInWebInspector();
  [Unimplemented] static void evaluateInWebInspectorOverlay();
  [Unimplemented] static void evaluateScriptInIsolatedWorld();
  [Unimplemented] static void execCommand();
  [Unimplemented] static void findString();
  [Unimplemented] static void forceNextDrawingBufferCreationToFail();
  [Unimplemented] static void forceNextWebGLContextCreationToFail();
  [Unimplemented] static void forceRedSelectionColors();
  [Unimplemented] static void getBluetoothManualChooserEvents();
  [Unimplemented] static void getManifestThen();
  [Unimplemented] static void hasCustomPageSizeStyle();
  [Unimplemented] static void insertStyleSheet();
  [Unimplemented] static void isChooserShown();
  [Unimplemented] static void isCommandEnabled();
  [Unimplemented] static void keepWebHistory();
  [Unimplemented] static void layoutAndPaintAsync();
  [Unimplemented] static void layoutAndPaintAsyncThen();
  [Unimplemented] static void logToStderr();
  [Unimplemented] static void overridePreference();
  [Unimplemented] static void pathToLocalResource();
  [Unimplemented] static void platformName();
  [Unimplemented] static void queueBackNavigation();
  [Unimplemented] static void queueForwardNavigation();
  [Unimplemented] static void queueLoad();
  [Unimplemented] static void queueLoadingScript();
  [Unimplemented] static void queueNonLoadingScript();
  [Unimplemented] static void queueReload();
  [Unimplemented] static void removeOriginAccessWhitelistEntry();
  [Unimplemented] static void removeSpellCheckResolvedCallback();
  [Unimplemented] static void removeWebPageOverlay();
  [Unimplemented] static void resetDeviceLight();
  [Unimplemented] static void resetTestHelperControllers();
  [Unimplemented] static void resolveBeforeInstallPromptPromise();
  [Unimplemented] static void runIdleTasks();
  [Unimplemented] static void selectionAsMarkup();
  [Unimplemented] static void sendBluetoothManualChooserEvent();
  [Unimplemented] static void setAcceptLanguages();
  [Unimplemented] static void setAllowFileAccessFromFileURLs();
  [Unimplemented] static void setAllowRunningOfInsecureContent();
  [Unimplemented] static void setAutoplayAllowed();
  [Unimplemented] static void setAllowUniversalAccessFromFileURLs();
  [Unimplemented] static void setBlockThirdPartyCookies();
  [Unimplemented] static void setAudioData();
  [Unimplemented] static void setBackingScaleFactor();
  [Unimplemented] static void setBluetoothFakeAdapter();
  [Unimplemented] static void setBluetoothManualChooser();
  [Unimplemented] static void setCallCloseOnWebViews();
  [Unimplemented] static void setCanOpenWindows();
  [Unimplemented] static void setCloseRemainingWindowsWhenComplete();
  [Unimplemented] static void setColorProfile();
  [Unimplemented] static void setCustomPolicyDelegate();
  [Unimplemented] static void setCustomTextOutput();
  [Unimplemented] static void setDatabaseQuota();
  [Unimplemented] static void setDomainRelaxationForbiddenForURLScheme();
  [Unimplemented] static void setDumpConsoleMessages();
  [Unimplemented] static void setDumpJavaScriptDialogs();
  [Unimplemented] static void setEffectiveConnectionType();
  [Unimplemented] static void setMockSpellCheckerEnabled();
  [Unimplemented] static void setIconDatabaseEnabled();
  [Unimplemented] static void setImagesAllowed();
  [Unimplemented] static void setIsolatedWorldContentSecurityPolicy();
  [Unimplemented] static void setIsolatedWorldSecurityOrigin();
  [Unimplemented] static void setJavaScriptCanAccessClipboard();
  [Unimplemented] static void setMIDIAccessorResult();
  [Unimplemented] static void setMainFrameIsFirstResponder();
  [Unimplemented] static void setMockDeviceLight();
  [Unimplemented] static void setMockDeviceMotion();
  [Unimplemented] static void setMockDeviceOrientation();
  [Unimplemented] static void setMockScreenOrientation();
  [Unimplemented] static void setMockSpeechRecognitionError();
  [Unimplemented] static void setPOSIXLocale();
  [Unimplemented] static void setPageVisibility();
  [Unimplemented] static void setPermission();
  [Unimplemented] static void setPluginsAllowed();
  [Unimplemented] static void setPluginsEnabled();
  [Unimplemented] static void setPointerLockWillFailSynchronously();
  [Unimplemented] static void setPointerLockWillRespondAsynchronously();
  [Unimplemented] static void setPopupBlockingEnabled();
  [Unimplemented] static void setPrinting();
  [Unimplemented] static void setScriptsAllowed();
  [Unimplemented] static void setScrollbarPolicy();
  [Unimplemented] static void setSpellCheckResolvedCallback();
  [Unimplemented] static void setStorageAllowed();
  [Unimplemented] static void setTabKeyCyclesThroughElements();
  [Unimplemented] static void setTextDirection();
  [Unimplemented] static void setTextSubpixelPositioning();
  [Unimplemented] static void setUseDashboardCompatibilityMode();
  [Unimplemented] static void setUseMockTheme();
  [Unimplemented] static void setViewSourceForFrame();
  [Unimplemented] static void setWillSendRequestClearHeader();
  [Unimplemented] static void setWindowIsKey();
  [Unimplemented] static void setXSSAuditorEnabled();
  [Unimplemented] static void showWebInspector();
  [Unimplemented] static void simulateWebNotificationClick();
  [Unimplemented] static void simulateWebNotificationClickWithReply();
  [Unimplemented] static void simulateWebNotificationClose();
  [Unimplemented] static void tooltipText();
  [Unimplemented] static void useUnfortunateSynchronousResizeMode();
  [Unimplemented] static void waitForPolicyDelegate();
  [Unimplemented] static void waitUntilExternalURLLoad();
  [Unimplemented] static void webHistoryItemCount();
  [Unimplemented] static void windowCount(); 
};



