// https://svgwg.org/svg2-draft/types.html#InterfaceSVGElement
interface SVGElement : Element {
  [CEReactions, RaisesException] attribute DOMString id;
  [CEReactions, RaisesException] attribute DOMString xmlbase;
  readonly attribute SVGElement? ownerSVGElement;
  readonly attribute SVGElement? viewportElement;

  attribute long tabIndex;
};

SVGElement implements ElementCSSInlineStyle;
