// https://drafts.fxtf.org/filter-effects/#ref-for-svgfemergeelement

[Exposed=Window]
interface SVGFEMergeElement : SVGElement {
};

// includes -> implements
SVGFEMergeElement implements SVGFilterPrimitiveStandardAttributes;
