//https://www.w3.org/TR/SVG/painting.html#InterfaceSVGMarkerElement
interface SVGMarkerElement : SVGElement {

    // Marker Unit Types
    const unsigned short SVG_MARKERUNITS_UNKNOWN = 0;
    const unsigned short SVG_MARKERUNITS_USERSPACEONUSE = 1;
    const unsigned short SVG_MARKERUNITS_STROKENWIDTH = 2;

    // Marker Orientation Types
    const unsigned short SVG_MARKER_ORIENT_UNKNOWN = 0;
    const unsigned short SVG_MARKER_ORIENT_AUTO = 1;
    const unsigned short SVG_MARKER_ORIENT_ANGLE = 2;

    [Unimplemented, SameObject] readonly attribute SVGAnimatedLength refX;
    [Unimplemented, SameObject] readonly attribute SVGAnimatedLength refY;
    [Unimplemented, SameObject] readonly attribute SVGAnimatedEnumeration markerUnits;
    [Unimplemented, SameObject] readonly attribute SVGAnimatedLength markerWidth;
    [Unimplemented, SameObject] readonly attribute SVGAnimatedLength markerHeight;
    [Unimplemented, SameObject] readonly attribute SVGAnimatedEnumeration orientType;
    [SameObject] readonly attribute SVGAnimatedAngle orientAngle;
    [Unimplemented] attribute DOMString orient;

    [Unimplemented] void setOrientToAuto();
    [Unimplemented] void setOrientToAngle(SVGAngle angle);
};

// SVGMarkerElement implements SVGFitToViewBox;
