// https://www.w3.org/TR/SVG11/shapes.html#InterfaceSVGRectElement
// TODO implement SVGTests, SVGLangSpace, SVGExternalResourcesRequired, SVGStylable, SVGTransformable 
interface SVGRectElement : SVGElement {
  readonly attribute SVGAnimatedLength x;
  readonly attribute SVGAnimatedLength y;
  readonly attribute SVGAnimatedLength width;
  readonly attribute SVGAnimatedLength height;
  readonly attribute SVGAnimatedLength rx;
  readonly attribute SVGAnimatedLength ry;
};