// https://svgwg.org/svg2-draft/interact.html#InterfaceSVGScriptElement    

interface SVGScriptElement : SVGElement {
  [Unimplemented] attribute DOMString type;
  [Unimplemented] attribute DOMString? crossOrigin;
};

SVGScriptElement implements SVGURIReference;