// https://html.spec.whatwg.org/multipage/canvas.html#canvasdrawimage

[STARFISH_ENABLE_CANVAS]
typedef (HTMLImageElement or
         SVGImageElement) HTMLOrSVGImageElement;

[STARFISH_ENABLE_CANVAS]
// NOTE: We expand
// HTMLOrSVGImageElement -> HTMLImageElement or SVGImageElement
// to overcome some bugs in the binding generator
typedef (HTMLImageElement or
         SVGImageElement or
         HTMLVideoElement or
         HTMLCanvasElement or
         ImageBitmap /*or
         OffscreenCanvas*/) CanvasImageSource;

// mixin
[STARFISH_ENABLE_CANVAS,
 PartialInterface,
 NoInterfaceObject]
interface CanvasDrawImage {
  // drawing images
  [RaisesException] void drawImage(CanvasImageSource image, unrestricted double dx, unrestricted double dy);
  [RaisesException] void drawImage(CanvasImageSource image, unrestricted double dx, unrestricted double dy, unrestricted double dw, unrestricted double dh);
  [RaisesException] void drawImage(CanvasImageSource image, unrestricted double sx, unrestricted double sy, unrestricted double sw, unrestricted double sh, unrestricted double dx, unrestricted double dy, unrestricted double dw, unrestricted double dh);
};
