// https://html.spec.whatwg.org/multipage/canvas.html#canvasgradient
[STARFISH_ENABLE_CANVAS, Exposed=(Window,Worker)]
interface CanvasGradient {
  // opaque object
  void addColorStop(double offset, DOMString color);
};
