// https://html.spec.whatwg.org/multipage/canvas.html#canvaspattern

// Exposed=(Window,Worker) -> Exposed=(Window)
[Exposed=(Window)]
interface CanvasPattern {
  // opaque object
  [RaisesException] void setTransform(optional DOMMatrix2DInit transform);
};