// https://html.spec.whatwg.org/multipage/canvas.html#canvasfillstrokestyles

// Declare a typedef to apply the flag
typedef (DOMString or CanvasGradient or CanvasPattern) CanvasFillStrokeStylesType;

// mixin
[STARFISH_ENABLE_CANVAS, 
 PartialInterface,
 NoInterfaceObject]
interface CanvasFillStrokeStyles {
  // colors and styles (see also the CanvasPathDrawingStyles and CanvasTextDrawingStyles interfaces)
  // (DOMString or CanvasGradient or CanvasPattern) -> CanvasFillStrokeStylesType
  attribute CanvasFillStrokeStylesType strokeStyle; // (default black)
  attribute CanvasFillStrokeStylesType fillStyle; // (default black)
  [RaisesException] CanvasGradient createLinearGradient(double x0, double y0, double x1, double y1);
  [RaisesException] CanvasGradient createRadialGradient(double x0, double y0, double r0, double x1, double y1, double r1);
  [RaisesException] CanvasPattern? createPattern(CanvasImageSource image, [TreatNullAs=EmptyString] DOMString repetition);
};
