// https://html.spec.whatwg.org/multipage/canvas.html#canvasgradient
[Exposed=(Window,Worker)]
interface CanvasGradient {
  // opaque object
  [RaisesException] void addColorStop(double offset, DOMString color);
};
