// https://html.spec.whatwg.org/multipage/canvas.html#canvaspattern

[STARFISH_ENABLE_CANVAS, Exposed=(Window,Worker)]
interface CanvasPattern {
  // opaque object
  [Unimplemented] void setTransform(optional DOMMatrix2DInit transform);
};