// https://html.spec.whatwg.org/multipage/canvas.html#path2d

// Declare a typedef to apply the flag
[STARFISH_ENABLE_CANVAS]
typedef (Path2D or DOMString) Path2DConstructorType;

// (Path2D or DOMString) -> Path2DConstructorType
[STARFISH_ENABLE_CANVAS,
 Constructor(optional Path2DConstructorType path),
 ConstructorCallWith=ExecutionContext,
 Exposed=(Window,Worker)]
interface Path2D {
  [Unimplemented] void addPath(Path2D path, optional DOMMatrix2DInit transform);

};
// includes -> implements
Path2D implements CanvasPath;
