[general]
profile = profile.da_nl_wad_r18_arm32
work_dir=~/tizen/spin/product/da/scm/meta/gbs-build-config

[profile.da_nl_wad_r18_arm32]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_nl_wad_r18, repo.da_base_arm32
buildconf=${work_dir}/TIZEN_4.0_DA_WAD_BUILD_R18.conf
buildroot=~/gbs-root/tizen_4.0_spin/da-nl-wad/r18/arm32/ad/

[profile.da_nl_wad_r18_arm64]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_nl_wad_r18, repo.da_base_arm64
buildconf=${work_dir}/TIZEN_4.0_DA_WAD_BUILD_R18.conf
buildroot=~/gbs-root/tizen_4.0_spin/da-nl-wad/r18/arm64/ad/

[profile.da_nl_wad_i586]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_nl_wad_r18, repo.da_base_i586
buildconf=${work_dir}/TIZEN_4.0_DA_WAD_BUILD_R18.conf
buildroot=~/gbs-root/tizen_4.0_spin/da-nl-wad/r18/i586/ad/

[profile.da_nl_wad_x86_64]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.da_nl_wad_r18, repo.da_base_x86_64
buildconf=${work_dir}/TIZEN_4.0_DA_WAD_BUILD_R18.conf
buildroot=~/gbs-root/tizen_4.0_spin/da-nl-wad/r18/x86_64/ad/

#DA KS MD1S R18
[repo.da_nl_wad_r18]
url = http://165.213.149.200/download/snapshots/tizen/4.0-da-nl-wad/latest/repos/R18/packages/

#Tizen 4.0 Base ARM 32-bit
[repo.da_base_arm32]
url=http://165.213.149.200/download/public_mirror/tizen/4.0-base/latest/repos/arm/packages/

#Tizen 4.0 Base ARM 64-bit
[repo.da_base_arm64]
url=http://165.213.149.200/download/public_mirror/tizen/4.0-base/latest/repos/arm64/packages/

#Tizen 4.0 Base i568 (32-bit)
[repo.da_base_i586]
url=http://165.213.149.200/download/public_mirror/tizen/4.0-base/latest/repos/ia32/packages/

#Tizen 4.0 Base x86_64 (64-bit)
[repo.da_base_x86_64]
url=http://165.213.149.200/download/public_mirror/tizen/4.0-base/latest/repos/x86_64/packages/

