[general]
profile = profile.fhub3.0_kantm_ad
work_dir=~/tizen/spin/product/da/scm/meta/gbs-build-config

[profile.fhub3.0_kantm_ad]
user =
passwd =
repos = repo.fhub3.0_kantm_main_ad, repo.fhub3.0_kantm_base_ad
buildconf=${work_dir}/TIZEN_3.0_FHUB3.0_KANTM_BUILD.conf
buildroot=~/gbs-root/tizen_3.0_spin/KANTM/ad/

[profile.fhub3.0_kantm_dv]
user =
passwd =
repos = repo.fhub3.0_kantm_main_dv, repo.fhub3.0_kantm_base_dv
buildconf=${work_dir}/TIZEN_3.0_FHUB3.0_KANTM_BUILD.conf
buildroot=~/gbs-root/tizen_3.0_spin/KANTM/dv/

[profile.fhub3.0_kantm2_ad]
user =
passwd =
repos = repo.fhub3.0_kantm2_main_ad, repo.fhub3.0_kantm_base_ad
buildconf=${work_dir}/TIZEN_3.0_FHUB3.0_KANTM2_BUILD.conf
buildroot=~/gbs-root/tizen_3.0_spin/KANTM2/ad/

[profile.fhub3.0_emulator32_ad]
user =
passwd =
repos = repo.fhub3.0_emulator32_ad, repo.fhub3.0_emulator32_base_ad
buildconf=${work_dir}/TIZEN_3.0_FHUB3.0_EMULATOR_BUILD.conf
buildroot=~/gbs-root/tizen_3.0_spin/EMULATOR/ad/

[profile.fhub3.0_emulator32_dv]
user =
passwd =
repos = repo.fhub3.0_emulator32_main_dv, repo.fhub3.0_emulator32_base_dv
buildconf=${work_dir}/TIZEN_3.0_FHUB3.0_EMULATOR_BUILD.conf
buildroot=~/gbs-root/tizen_3.0_spin/EMULATOR/dv/

#Family Hub 3.0 KANT-M Main DV
[repo.fhub3.0_kantm_main_dv]
url = http://165.213.149.200/download/snapshots/product/da/3.0/product-dv-tizen-3.0-fhub3.0-main/latest/repos/KANTM/packages/

#Family Hub 3.0 KANT-M Base DV
[repo.fhub3.0_kantm_base_dv]
url = http://165.213.149.200/download/snapshots/product/da/3.0/product-dv-tizen-3.0-fhub3.0-base/latest/repos/arm/packages/

#Family Hub 3.0 KANT-M AD
[repo.fhub3.0_kantm_main_ad]
url = http://165.213.149.200/download/snapshots/tizen/3.0-fhub3.0/latest/repos/KANTM/packages/

#Family Hub 3.0 KANT-M2 AD
[repo.fhub3.0_kantm2_main_ad]
url = http://165.213.149.200/download/snapshots/tizen/3.0-fhub3.0/latest/repos/KANTM2/packages/

#Tizen 3.0 Base ARM
[repo.fhub3.0_kantm_base_ad]
url=http://165.213.149.200/download/public_mirror/tizen/3.0-base/latest/repos/arm/packages/

#Family Hub 3.0 Emulator32 Main DV
[repo.fhub3.0_emulator32_main_dv]
url = http://165.213.149.200/download/snapshots/product/da/3.0/product-dv-tizen-3.0-fhub3.0-main/latest/repos/emulator32/packages/

#Family Hub 3.0 Emulator Base DV
[repo.fhub3.0_emulator32_base_dv]
url = http://165.213.149.200/download/snapshots/product/da/3.0/product-dv-tizen-3.0-fhub3.0-base/latest/repos/emulator32/packages/

#Family Hub 3.0 Emulator AD
[repo.fhub3.0_emulator32_main_ad]
url=http://165.213.149.200/download/snapshots/tizen/3.0-fhub3.0/latest/repos/emulator32/packages/

#Tizen 3.0 Base Emulator AD
[repo.fhub3.0_emulator32_base_ad]
url=http://165.213.149.200/download/public_mirror/tizen/3.0-base/latest/repos/emulator32/packages/

