[general]
profile = profile.fhub5_kantm
work_dir=~/tizen/spin/product/da/scm/meta/gbs-build-config

[profile.fhub5_kantm]
user= juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos=repo.fhub5_kantm, repo.base_arm
buildconf=${work_dir}/TIZEN_4.0_DA_FHUB4_BUILD_KANTM.conf
buildroot=~/gbs-root/tizen_4.0_spin/da-fhub/kantm/ad/

[profile.fhub5_kantm_asan]
user = juhak.jeong
passwdx = QlpoOTFBWSZTWawX5/wAAAIJgCqAJQAIACAAIgaaehDAj81cBBdyRThQkKwX5/w=
repos = repo.fhub5_kantm_asan, repo.base_arm
buildconf=${work_dir}/TIZEN_4.0_DA_FHUB4_BUILD_KANTM_ASAN.conf
buildroot=~/gbs-root/tizen_4.0_spin/da-fhub/kantm/ad/

#Family Hub 5 KANT-M
[repo.fhub5_kantm]
url = http://10.91.255.30/download/snapshots/product/da/4.0/product-dv-tizen-4.0-da-fhub5/latest/repos/KANTM/packages/

#Family Hub 5 KANT-M ASAN
[repo.fhub5_kantm_asan]
url = http://10.91.255.30/download/snapshots/product/da/4.0/product-dv-tizen-4.0-da-fhub5/latest/repos/KANTM/packages/

#Family Hub 5 Emulator
[repo.fhub5_emulator]
url= http://10.91.255.30/download/snapshots/product/da/4.0/product-dv-tizen-4.0-da-fhub5/latest/repos/emulator/packages/

#Tizen 4.0 Base ARM
[repo.base_arm]
url=http://10.91.255.30/download/snapshots/product/da/4.0/product-mp-tizen-4.0-da-base/latest/repos/arm/packages/

