name: Build Starfish

on:
  push:

jobs:
  build_x64:
    runs-on: [ self-hosted,code-2xlarge ]
    container:
      image: art.sec.samsung.net/lws_docker/health_sdk/health-sdk:latest
      options: --user root
    strategy:
      matrix:
        mode: [x64_glfw_debug, x64_glfw_debug_wasm, x64_glfw_release, x64_efl_headless]

    # Set reasonable timeout value.
    timeout-minutes: 30

    steps:
      - name: Checkout source..
        uses: CODE-Actions/checkout@v2
        with:
          submodules: true

      - name: Reset Submodule
        run: git submodule foreach --recursive git reset --hard

      - name: Build Starfish
        run: /root/workspace/build.sh ${{ matrix.mode }}
