name: Build Starfish

on:
  push:

jobs:
  build_x64:
    runs-on: [ self-hosted,code-2xlarge ]
    container:
      image: lws-docker-local.bart.sec.samsung.net/starfish-build:20.04
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      options: --user root
    strategy:
      matrix:
        mode: [x64_glfw_debug, x64_glfw_debug_wasm, x64_glfw_release, x64_efl_headless]

    # Set reasonable timeout value.
    timeout-minutes: 30

    steps:
      - name: Checkout source..
        uses: CODE-Actions/checkout@v2
        with:
          submodules: true

      - name: Add safe directory
        run: git config --global --add safe.directory /__w/starfish/starfish

      - name: Reset Submodule
        run: git submodule foreach --recursive git reset --hard

      - name: Build Starfish
        run: /root/workspace/build.sh ${{ matrix.mode }}
