name: Build Starfish

on: [pull_request_target]

jobs:
  build_x64_serivce_worker:
    runs-on: [code-2xlarge]
    container:
      image: lws-docker-local.bart.sec.samsung.net/starfish-build:20.04
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      options: --user root
    strategy:
      fail-fast: false
      matrix:
        mode: [release, debug]
        backend: [glfw_cairo_gl]
        target: [executable, webworker]
        exclude:
          - mode: debug
            target: executable
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: CODE-Actions/checkout@v3
        with:
          submodules: true
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Add safe directory
        run: git config --global --add safe.directory /__w/starfish/starfish
      - name: Reset Submodule
        run: git submodule foreach --recursive git reset --hard
      - name: Configuration
        run: |
          cmake CMakeLists.txt -G Ninja -DTARGETNAME=Starfish \
            -DHOST=linux -DARCH=x64 -DDOCKER=1 \
            -DMODE=${{ matrix.mode }} -DBACKEND=${{ matrix.backend }} \
            -DENABLE_SERVICE_WORKER=1
      - name: Build
        run: ninja starfish.${{ matrix.target }}
