name: Build Starfish (gl backend)

on:
  workflow_call:
    inputs:
      pr_number:
        description: 'PR Number'
        default: 'master'
        required: true
        type: string


jobs:
  build_x64:
    runs-on:  [ code-linux, code-2xlarge ]
    container:
      image: lws-docker-local.bart.sec.samsung.net/starfish-build:20.04
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      options: --user root
    strategy:
      fail-fast: false
      matrix:
        mode: [debug]
        backend: [efl_cairo_gl,x11_cairo_gl]
        target: [executable]
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: CODE-Actions/checkout@v2
        with:
          submodules: false
          repository: mh-byun/starfish_window_build
          ref: ${{ inputs.pr_number }}
      - name: Clean workspace
        run: |
            git clean -xdf
      - name: Configuration
        run: |
          cmake CMakeLists.txt -G Ninja -DTARGETNAME=Starfish \
            -DHOST=linux -DARCH=x64 -DDOCKER=1 \
            -DMODE=${{ matrix.mode }} -DBACKEND=${{ matrix.backend }}
      - name: Build
        run: ninja starfish.${{ matrix.target }}
