name: Build Starfish (minor port)

on:
  workflow_call:
    inputs:
      pr_number:
        description: 'PR Number'
        default: 'master'
        required: true
        type: string


jobs:
  build_x64_glfw_debug_wasm:
    runs-on:  [ code-linux, code-2xlarge ]
    container:
      image: lws-docker-local.bart.sec.samsung.net/starfish-build:20.04
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      options: --user root
    # Set reasonable timeout value.
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: CODE-Actions/checkout@v2
        with:
          submodules: false
          repository: mh-byun/starfish_window_build
          ref: ${{ inputs.pr_number }}
      - name: Clean workspace
        run: |
            git clean -xdf
      - name: Build Starfish
        run: |
            cmake CMakeLists.txt -DMODE=debug -DBACKEND=uv_cairo_gl -DSHELL=glfw -DDOCKER=1 -DENABLE_WASM=1 -G Ninja
            ninja starfish.executable

  build_x64_glfw_release:
    runs-on:  [ code-linux, code-2xlarge ]
    container:
      image: lws-docker-local.bart.sec.samsung.net/starfish-build:20.04
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      options: --user root
    # Set reasonable timeout value.
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: CODE-Actions/checkout@v2
        with:
          submodules: false
          repository: mh-byun/starfish_window_build
          ref: ${{ inputs.pr_number }}
      - name: Clean workspace
        run: |
            git clean -xdf
      - name: Build Starfish
        run: |
            cmake CMakeLists.txt -DMODE=release -DBACKEND=uv_cairo_gl -DSHELL=glfw -DDOCKER=1 -G Ninja
            ninja starfish.executable
      - name: Run crash test
        run: |
            xvfb-run -s '-screen 0 1920x1080x24' -a ./Starfish https://github.com/Samsung/escargot --crash-test --disable-console 1>/dev/null || exit 1
            xvfb-run -s '-screen 0 1920x1080x24' -a ./Starfish https://github.com/Samsung/escargot --crash-test --disable-console 1>/dev/null || exit 1
            xvfb-run -s '-screen 0 1920x1080x24' -a ./Starfish https://github.com/Samsung/escargot --crash-test --disable-console 1>/dev/null || exit 1

  x64_efl_headless:
    runs-on:  [ code-linux, code-2xlarge ]
    container:
      image: lws-docker-local.bart.sec.samsung.net/starfish-build:20.04
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      options: --user root

    # Set reasonable timeout value.
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: CODE-Actions/checkout@v2
        with:
          submodules: false
          repository: mh-byun/starfish_window_build
          ref: ${{ inputs.pr_number }}
      - name: Clean workspace
        run: |
            git clean -xdf
      - name: Build Starfish
        run: |
            cmake CMakeLists.txt -DMODE=debug -DBACKEND=efl_headless -DSHELL=efl_headless -DDOCKER=1 -G Ninja
            ninja starfish.executable
