name: Build Starfish (worker)

on:
  workflow_call:
    inputs:
      pr_number:
        description: 'PR Number'
        default: 'master'
        required: true
        type: string

jobs:
  build_x64_workers:
    # After the firewall registraion is done, a code runner should also be added to test work.
    runs-on:  [ code-linux, code-2xlarge ]
    container:
      image: lws-docker-local.bart.sec.samsung.net/starfish-build:24.04
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      options: --user root
    strategy:
        fail-fast: false
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: CODE-Actions/checkout@v2
        with:
          submodules: false
          repository: mh-byun/starfish_window_build
          ref: ${{ inputs.pr_number }}

      - name: Add safe directory
        run: git config --global --add safe.directory /__w/starfish/starfish

      - name: Clean workspace
        run: |
            git clean -xdf
      - name: Configuration
        run: |
            cmake CMakeLists.txt -Buv_cairo_gl/debug -G Ninja -DTARGETNAME=Starfish \
            -DHOST=linux -DARCH=x64 -DDOCKER=1 \
            -DMODE=debug -DBACKEND=uv_cairo_gl -DSHELL=x11 \
            -DWORKER=1 -DSHARED_WORKER=1 -DSERVICE_WORKER=1
      - name: Build Starfish
        run: ninja -C uv_cairo_gl/debug starfish.executable
      - name: Build SharedWorker
        run: ninja -C uv_cairo_gl/debug starfish.sharedworker.executable
      - name: Build ServiceWorker
        run: ninja -C uv_cairo_gl/debug starfish.serviceworker.executable

      - uses: CODE-Actions/upload-artifact@v2
        with:
          name: starfish-x64_x11_worker
          path: |
            ./uv_cairo_gl/debug/bin/*
            ./uv_cairo_gl/debug/lib/*
            ./build.ninja
            ./rules.ninja

  test:
    needs: build_x64_workers
    timeout-minutes: 60
    # After the firewall registraion is done, a code runner should also be added to test work.
    runs-on:  [ code-linux, code-2xlarge ]
    container:
      image: lws-docker-local.bart.sec.samsung.net/starfish-build:24.04
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      options: --user root

    steps:
      - name: Checkout source..
        uses: CODE-Actions/checkout@v2
        with:
          submodules: false
          allow-unsafe-pr-checkout: true
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Add safe directory
        run: git config --global --add safe.directory /__w/starfish/starfish

      - name: Checkout Testcase..
        run: |
          git submodule init
          git submodule update third_party/wpt

      - uses: CODE-Actions/download-artifact@v2
        with:
          name: starfish-x64_x11_worker

      - name: Prepare Test
        run: |
            chmod a+x $PWD/uv_cairo_gl/debug/bin/Starfish
            chmod a+x $PWD/uv_cairo_gl/debug/bin/Starfish-sharedworker
            chmod a+x $PWD/uv_cairo_gl/debug/bin/Starfish-serviceworker
            ln -s -f $PWD/uv_cairo_gl/debug/bin/Starfish Starfish
            ln -s -f $PWD/uv_cairo_gl/debug/bin/Starfish-sharedworker Starfish-sharedworker
            ln -s -f $PWD/uv_cairo_gl/debug/bin/Starfish-serviceworker Starfish-serviceworker
            python3 third_party/wpt/wpt make-hosts-file | tee -a /etc/hosts

      - name: Run SharedWorker WPT
        run: |
            xvfb-run -s '-screen 0 1920x1080x24' -a python3 ./tool/test_runner.py wpt_serve_testharness_worker || exit 1

      - name: Run ServiceWorker WPT
        run: |
            xvfb-run -s '-screen 0 1920x1080x24' -a python3 ./tool/test_runner.py wpt_serve_testharness_serviceworker || exit 1
